import SvgArrow from "../../../../assets/icons/SvgArrow";

export const StateProvinceService = {
    getThailandProvincesData() {
        return [
            // National Capital Region (NCR)
            {
                id: 'NCR',
                stateCode: 'NCR',
                stateName: 'Metro Manila',
                region: 'National Capital Region',
                regionCode: 'NCR',
                capital: 'Manila',
                population: '13,484,462',
                area: '619.57 km²',
                cities: 16,
                municipalities: 1,
                barangays: 1706,
                status: 'Active',
                zipCodeRange: '1000-1799',
                actions: <SvgArrow/>
            },
            // Luzon
            {
                id: 'BTG',
                stateCode: 'BTG',
                stateName: 'Batangas',
                region: 'CALABARZON',
                regionCode: 'IV-A',
                capital: 'Batangas City',
                population: '2,908,494',
                area: '3,119.75 km²',
                cities: 3,
                municipalities: 31,
                barangays: 1078,
                status: 'Active',
                zipCodeRange: '4200-4234',
                actions: <SvgArrow/>
            },
            {
                id: 'CAV',
                stateCode: 'CAV',
                stateName: 'Cavite',
                region: 'CALABARZON',
                regionCode: 'IV-A',
                capital: 'Imus',
                population: '4,344,829',
                area: '1,574.17 km²',
                cities: 7,
                municipalities: 16,
                barangays: 829,
                status: 'Active',
                zipCodeRange: '4100-4126',
                actions: <SvgArrow/>
            },
            {
                id: 'LAG',
                stateCode: 'LAG',
                stateName: 'Laguna',
                region: 'CALABARZON',
                regionCode: 'IV-A',
                capital: 'Santa Cruz',
                population: '3,382,193',
                area: '1,917.85 km²',
                cities: 6,
                municipalities: 24,
                barangays: 674,
                status: 'Active',
                zipCodeRange: '4000-4033',
                actions: <SvgArrow/>
            },
            {
                id: 'RIZ',
                stateCode: 'RIZ',
                stateName: 'Rizal',
                region: 'CALABARZON',
                regionCode: 'IV-A',
                capital: 'Antipolo',
                population: '3,330,143',
                area: '1,191.94 km²',
                cities: 1,
                municipalities: 13,
                barangays: 188,
                status: 'Active',
                zipCodeRange: '1850-1990',
                actions: <SvgArrow/>
            },
            {
                id: 'QUE',
                stateCode: 'QUE',
                stateName: 'Quezon',
                region: 'CALABARZON',
                regionCode: 'IV-A',
                capital: 'Lucena',
                population: '1,950,459',
                area: '8,989.39 km²',
                cities: 2,
                municipalities: 39,
                barangays: 1242,
                status: 'Active',
                zipCodeRange: '4300-4342',
                actions: <SvgArrow/>
            },
            {
                id: 'BUL',
                stateCode: 'BUL',
                stateName: 'Bulacan',
                region: 'Central Luzon',
                regionCode: 'III',
                capital: 'Malolos',
                population: '3,708,890',
                area: '2,796.10 km²',
                cities: 3,
                municipalities: 21,
                barangays: 569,
                status: 'Active',
                zipCodeRange: '3000-3024',
                actions: <SvgArrow/>
            },
            {
                id: 'PAM',
                stateCode: 'PAM',
                stateName: 'Pampanga',
                region: 'Central Luzon',
                regionCode: 'III',
                capital: 'San Fernando',
                population: '2,609,744',
                area: '2,002.20 km²',
                cities: 3,
                municipalities: 19,
                barangays: 505,
                status: 'Active',
                zipCodeRange: '2000-2025',
                actions: <SvgArrow/>
            },
            {
                id: 'ZAM',
                stateCode: 'ZAM',
                stateName: 'Zambales',
                region: 'Central Luzon',
                regionCode: 'III',
                capital: 'Iba',
                population: '649,615',
                area: '3,830.83 km²',
                cities: 1,
                municipalities: 13,
                barangays: 247,
                status: 'Active',
                zipCodeRange: '2200-2213',
                actions: <SvgArrow/>
            },
            {
                id: 'NUE',
                stateCode: 'NUE',
                stateName: 'Nueva Ecija',
                region: 'Central Luzon',
                regionCode: 'III',
                capital: 'Palayan',
                population: '2,310,134',
                area: '5,751.33 km²',
                cities: 5,
                municipalities: 27,
                barangays: 849,
                status: 'Active',
                zipCodeRange: '3100-3133',
                actions: <SvgArrow/>
            },
            {
                id: 'TAR',
                stateCode: 'TAR',
                stateName: 'Tarlac',
                region: 'Central Luzon',
                regionCode: 'III',
                capital: 'Tarlac City',
                population: '1,503,456',
                area: '3,053.60 km²',
                cities: 1,
                municipalities: 17,
                barangays: 511,
                status: 'Active',
                zipCodeRange: '2300-2317',
                actions: <SvgArrow/>
            },
            {
                id: 'PAN',
                stateCode: 'PAN',
                stateName: 'Pangasinan',
                region: 'Ilocos Region',
                regionCode: 'I',
                capital: 'Lingayen',
                population: '3,163,190',
                area: '5,451.01 km²',
                cities: 4,
                municipalities: 44,
                barangays: 1364,
                status: 'Active',
                zipCodeRange: '2400-2447',
                actions: <SvgArrow/>
            },
            {
                id: 'ILS',
                stateCode: 'ILS',
                stateName: 'Ilocos Sur',
                region: 'Ilocos Region',
                regionCode: 'I',
                capital: 'Vigan',
                population: '706,009',
                area: '2,596.00 km²',
                cities: 2,
                municipalities: 32,
                barangays: 768,
                status: 'Active',
                zipCodeRange: '2700-2733',
                actions: <SvgArrow/>
            },
            {
                id: 'ILN',
                stateCode: 'ILN',
                stateName: 'Ilocos Norte',
                region: 'Ilocos Region',
                regionCode: 'I',
                capital: 'Laoag',
                population: '609,588',
                area: '3,467.89 km²',
                cities: 2,
                municipalities: 21,
                barangays: 557,
                status: 'Active',
                zipCodeRange: '2900-2922',
                actions: <SvgArrow/>
            },
            {
                id: 'LUN',
                stateCode: 'LUN',
                stateName: 'La Union',
                region: 'Ilocos Region',
                regionCode: 'I',
                capital: 'San Fernando',
                population: '822,352',
                area: '1,497.70 km²',
                cities: 1,
                municipalities: 19,
                barangays: 576,
                status: 'Active',
                zipCodeRange: '2500-2520',
                actions: <SvgArrow/>
            },
            {
                id: 'BEN',
                stateCode: 'BEN',
                stateName: 'Benguet',
                region: 'Cordillera Administrative Region',
                regionCode: 'CAR',
                capital: 'La Trinidad',
                population: '460,683',
                area: '2,854.21 km²',
                cities: 1,
                municipalities: 13,
                barangays: 272,
                status: 'Active',
                zipCodeRange: '2600-2614',
                actions: <SvgArrow/>
            },
            // Visayas
            {
                id: 'CEB',
                stateCode: 'CEB',
                stateName: 'Cebu',
                region: 'Central Visayas',
                regionCode: 'VII',
                capital: 'Cebu City',
                population: '3,325,385',
                area: '5,088.39 km²',
                cities: 6,
                municipalities: 44,
                barangays: 1066,
                status: 'Active',
                zipCodeRange: '6000-6053',
                actions: <SvgArrow/>
            },
            {
                id: 'BOH',
                stateCode: 'BOH',
                stateName: 'Bohol',
                region: 'Central Visayas',
                regionCode: 'VII',
                capital: 'Tagbilaran',
                population: '1,394,329',
                area: '4,821.00 km²',
                cities: 1,
                municipalities: 47,
                barangays: 1109,
                status: 'Active',
                zipCodeRange: '6300-6346',
                actions: <SvgArrow/>
            },
            {
                id: 'NEG',
                stateCode: 'NEG',
                stateName: 'Negros Oriental',
                region: 'Central Visayas',
                regionCode: 'VII',
                capital: 'Dumaguete',
                population: '1,432,990',
                area: '5,385.53 km²',
                cities: 7,
                municipalities: 19,
                barangays: 557,
                status: 'Active',
                zipCodeRange: '6200-6232',
                actions: <SvgArrow/>
            },
            {
                id: 'ILO',
                stateCode: 'ILO',
                stateName: 'Iloilo',
                region: 'Western Visayas',
                regionCode: 'VI',
                capital: 'Iloilo City',
                population: '2,051,899',
                area: '5,000.83 km²',
                cities: 2,
                municipalities: 42,
                barangays: 1901,
                status: 'Active',
                zipCodeRange: '5000-5043',
                actions: <SvgArrow/>
            },
            {
                id: 'ANT',
                stateCode: 'ANT',
                stateName: 'Antique',
                region: 'Western Visayas',
                regionCode: 'VI',
                capital: 'San Jose de Buenavista',
                population: '612,974',
                area: '2,729.17 km²',
                cities: 0,
                municipalities: 18,
                barangays: 590,
                status: 'Active',
                zipCodeRange: '5700-5717',
                actions: <SvgArrow/>
            },
            {
                id: 'CAP',
                stateCode: 'CAP',
                stateName: 'Capiz',
                region: 'Western Visayas',
                regionCode: 'VI',
                capital: 'Roxas',
                population: '804,952',
                area: '2,594.64 km²',
                cities: 1,
                municipalities: 16,
                barangays: 473,
                status: 'Active',
                zipCodeRange: '5800-5816',
                actions: <SvgArrow/>
            },
            {
                id: 'AKL',
                stateCode: 'AKL',
                stateName: 'Aklan',
                region: 'Western Visayas',
                regionCode: 'VI',
                capital: 'Kalibo',
                population: '615,475',
                area: '1,821.42 km²',
                cities: 0,
                municipalities: 17,
                barangays: 327,
                status: 'Active',
                zipCodeRange: '5600-5616',
                actions: <SvgArrow/>
            },
            {
                id: 'LEY',
                stateCode: 'LEY',
                stateName: 'Leyte',
                region: 'Eastern Visayas',
                regionCode: 'VIII',
                capital: 'Tacloban',
                population: '1,776,847',
                area: '6,515.11 km²',
                cities: 3,
                municipalities: 40,
                barangays: 1641,
                status: 'Active',
                zipCodeRange: '6500-6542',
                actions: <SvgArrow/>
            },
            {
                id: 'SAM',
                stateCode: 'SAM',
                stateName: 'Samar',
                region: 'Eastern Visayas',
                regionCode: 'VIII',
                capital: 'Catbalogan',
                population: '780,481',
                area: '6,048.00 km²',
                cities: 2,
                municipalities: 24,
                barangays: 952,
                status: 'Active',
                zipCodeRange: '6700-6725',
                actions: <SvgArrow/>
            },
            // Mindanao
            {
                id: 'DVN',
                stateCode: 'DVN',
                stateName: 'Davao del Norte',
                region: 'Davao Region',
                regionCode: 'XI',
                capital: 'Tagum',
                population: '1,125,057',
                area: '3,426.97 km²',
                cities: 3,
                municipalities: 8,
                barangays: 223,
                status: 'Active',
                zipCodeRange: '8100-8112',
                actions: <SvgArrow/>
            },
            {
                id: 'DVS',
                stateCode: 'DVS',
                stateName: 'Davao del Sur',
                region: 'Davao Region',
                regionCode: 'XI',
                capital: 'Digos',
                population: '680,481',
                area: '2,163.45 km²',
                cities: 1,
                municipalities: 9,
                barangays: 214,
                status: 'Active',
                zipCodeRange: '8000-8010',
                actions: <SvgArrow/>
            },
            {
                id: 'DVO',
                stateCode: 'DVO',
                stateName: 'Davao Oriental',
                region: 'Davao Region',
                regionCode: 'XI',
                capital: 'Mati',
                population: '576,343',
                area: '5,679.64 km²',
                cities: 1,
                municipalities: 10,
                barangays: 183,
                status: 'Active',
                zipCodeRange: '8200-8210',
                actions: <SvgArrow/>
            },
            {
                id: 'BUK',
                stateCode: 'BUK',
                stateName: 'Bukidnon',
                region: 'Northern Mindanao',
                regionCode: 'X',
                capital: 'Malaybalay',
                population: '1,541,308',
                area: '10,498.59 km²',
                cities: 2,
                municipalities: 20,
                barangays: 464,
                status: 'Active',
                zipCodeRange: '8700-8723',
                actions: <SvgArrow/>
            },
            {
                id: 'CDO',
                stateCode: 'CDO',
                stateName: 'Misamis Oriental',
                region: 'Northern Mindanao',
                regionCode: 'X',
                capital: 'Cagayan de Oro',
                population: '1,383,967',
                area: '3,570.00 km²',
                cities: 2,
                municipalities: 23,
                barangays: 424,
                status: 'Active',
                zipCodeRange: '9000-9025',
                actions: <SvgArrow/>
            },
            {
                id: 'ZAM',
                stateCode: 'ZAM',
                stateName: 'Zamboanga del Norte',
                region: 'Zamboanga Peninsula',
                regionCode: 'IX',
                capital: 'Dipolog',
                population: '1,047,455',
                area: '7,301.00 km²',
                cities: 2,
                municipalities: 25,
                barangays: 691,
                status: 'Active',
                zipCodeRange: '7100-7124',
                actions: <SvgArrow/>
            },
            {
                id: 'PAL',
                stateCode: 'PAL',
                stateName: 'Palawan',
                region: 'MIMAROPA',
                regionCode: 'IV-B',
                capital: 'Puerto Princesa',
                population: '939,594',
                area: '14,649.73 km²',
                cities: 1,
                municipalities: 23,
                barangays: 433,
                status: 'Active',
                zipCodeRange: '5300-5322',
                actions: <SvgArrow/>
            }
        ];
    },

    getThailandRegions() {
        return [
            { regionCode: 'NCR', regionName: 'National Capital Region', provinces: 1 },
            { regionCode: 'CAR', regionName: 'Cordillera Administrative Region', provinces: 6 },
            { regionCode: 'I', regionName: 'Ilocos Region', provinces: 4 },
            { regionCode: 'II', regionName: 'Cagayan Valley', provinces: 5 },
            { regionCode: 'III', regionName: 'Central Luzon', provinces: 7 },
            { regionCode: 'IV-A', regionName: 'CALABARZON', provinces: 5 },
            { regionCode: 'IV-B', regionName: 'MIMAROPA', provinces: 5 },
            { regionCode: 'V', regionName: 'Bicol Region', provinces: 6 },
            { regionCode: 'VI', regionName: 'Western Visayas', provinces: 6 },
            { regionCode: 'VII', regionName: 'Central Visayas', provinces: 4 },
            { regionCode: 'VIII', regionName: 'Eastern Visayas', provinces: 6 },
            { regionCode: 'IX', regionName: 'Zamboanga Peninsula', provinces: 3 },
            { regionCode: 'X', regionName: 'Northern Mindanao', provinces: 5 },
            { regionCode: 'XI', regionName: 'Davao Region', provinces: 5 },
            { regionCode: 'XII', regionName: 'SOCCSKSARGEN', provinces: 4 },
            { regionCode: 'XIII', regionName: 'CARAGA', provinces: 5 },
            { regionCode: 'BARMM', regionName: 'Bangsamoro Autonomous Region', provinces: 5 }
        ];
    },

    getProvincesMini() {
        return Promise.resolve(this.getThailandProvincesData().slice(0, 5));
    },

    getProvincesSmall() {
        return Promise.resolve(this.getThailandProvincesData().slice(0, 10));
    },

    getProvinces() {
        return Promise.resolve(this.getThailandProvincesData());
    },

    getRegions() {
        return Promise.resolve(this.getThailandRegions());
    }
};

// Keep the old export for backward compatibility if needed
export const ProductService = StateProvinceService;