/*
 * Builds the in-app help from the user manual of one edition:
 *
 *   public/help/user-manual.html   the manual as one HTML page in the colours and font of the edition's brand
 *   public/help/sections.json      the edition (title, version and its label, date, status, files, brand pack, the
 *                                  chapter of each role) and the headings (id, title, level, chapter): the Help panel
 *                                  links a screen to one and a user to the chapter of his or her role
 *   public/help/manual.js          the contents list script of the page
 *   public/help/images/            the screenshots the manual shows
 *   public/help/<pdf>, <docx>      the manual as PDF and Word: the product PDF is copied in; the files of a client
 *                                  edition are written here by npm run help:word and kept by the build (one copy only)
 *
 * Editions (help.config.json names the one this branch ships):
 *   base    the product manual: docs/package/source/user-manual.md, the product default theme
 *   tisph   Toyota Insurance Services Philippines: docs/TISPH/manual/manual.json (chapter files in order, the role
 *           facts generated by the backend's npm run manual:role-facts, the Toyota Insurance Services brand pack);
 *           it also writes docs/TISPH/manual/generated/TISPH_User_Manual.md, the source of the Word and PDF files
 *           (npm run help:word)
 *
 *   npm run help:build                                 the configured edition into public/help; commit public/help
 *   npm run help:build -- --edition base --out <dir>   another edition into a folder, for review
 *   npm run help:build -- --check                      checks only: fails when the edition breaks a rule
 *
 * The manual covers the features of the delivered edition only: Phase 1 and platform functions (scripts/help/features.js).
 *
 * The build stops when a chapter names a generic role, a withdrawn screen, a code or a forbidden term of the
 * manifest, when a role has no chapter, when a screen of a role's menu has no section, or when the role facts no
 * longer match the menus. helpRoutes.test.js fails when a heading the Help panel links to is missing.
 */
const fs = require("fs");
const path = require("path");
const { headingIds, parseFrontMatter, render, toc } = require("./help/render");
const { page } = require("./help/page");
const { assemble, controlRows, effectiveStatus, loadManifest, wordSource } = require("./help/edition");
const { deliveredEdition } = require("./help/features");

const ROOT = path.resolve(__dirname, "..");
const REPO = path.resolve(ROOT, "..");
const PUBLISHED = path.join(ROOT, "public", "help");
const CONFIG = path.join(ROOT, "help.config.json");
const BRAND_PACKS = path.join(REPO, "backend", "assets", "brand-packs");
// the font files of the page, served with it: the help opens where Google Fonts is blocked
const FONT_FILES = { inter: { dir: path.join(ROOT, "node_modules", "primereact", "resources", "themes", "mira", "fonts"), family: "Inter",
  files: { 400: "Inter-Regular.woff2", 500: "Inter-Medium.woff2", 600: "Inter-SemiBold.woff2", 700: "Inter-Bold.woff2" } } };

const EDITIONS = {
  base: { manifest: null, source: path.join(REPO, "docs", "package", "source", "user-manual.md"), images: path.join(REPO, "docs", "package", "source", "manual-images"),
    files: { pdf: path.join(REPO, "docs", "package", "05_Delivery", "BrokerVerse_User_Manual.pdf") } },
  tisph: { manifest: path.join(REPO, "docs", "TISPH", "manual", "manual.json") },
};

const arg = (name) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? process.argv[i + 1] : null;
};
const fail = (problems) => {
  console.error(`help: the manual breaks ${problems.length} rule(s):\n  ${problems.join("\n  ")}`);
  process.exit(1);
};

const load = (file) => import(path.join(ROOT, "src", file));

/**
 * The features of the edition (the delivered state: Phase 1 and platform functions) applied to the menus, and the
 * screens of the features left out (their sections and links leave the manual).
 */
async function featureEdition() {
  const edition = await deliveredEdition(REPO);
  const [{ menuList }, { flattenLeaves }, { setFeatureState, hiddenMenus }] = await Promise.all([
    load("components/SideBar/list.js"), load("components/SideBar/menuTree.js"), load("features/entitlements.js"),
  ]);
  setFeatureState(edition.off);
  const hidden = hiddenMenus(edition.off);
  const screens = new Set(flattenLeaves(menuList).filter((l) => l.item.path && hidden.has([...l.ancestors.map((a) => a.name), l.item.name].join(" > ")))
    .map((l) => l.item.path));
  return { ...edition, screens };
}

/** The screens of every role's menu, and the Help section each one opens. */
async function menuChecks(facts) {
  const [{ menuList }, { filterMenuForRoles }, { flattenLeaves }, { helpSectionFor }] = await Promise.all([
    load("components/SideBar/list.js"), load("utils/menuPermissions.js"), load("components/SideBar/menuTree.js"), load("components/HelpPanel/helpRoutes.js"),
  ]);
  const problems = [];
  const paths = new Set();
  for (const role of facts.roles) {
    const live = flattenLeaves(filterMenuForRoles(menuList, [role.code])).map((l) => l.item.path).filter(Boolean);
    const written = role.menus.map((m) => m.path);
    if (live.join("\n") !== written.join("\n")) problems.push(`the role facts of ${role.name} no longer match the menus: run npm run manual:role-facts in backend/`);
    live.forEach((p) => paths.add(p));
  }
  return { problems, sectionOf: (p, known) => helpSectionFor(p, known).id, paths: [...paths] };
}

async function theme(packId) {
  const { themeToCssVars } = await import(path.join(ROOT, "src", "theme", "runtime", "themeEngine.js"));
  if (!packId) return { vars: themeToCssVars({}), pack: null };
  const dir = path.join(BRAND_PACKS, packId);
  const pack = JSON.parse(fs.readFileSync(path.join(dir, "theme.json"), "utf8"));
  const manifest = JSON.parse(fs.readFileSync(path.join(dir, "manifest.json"), "utf8"));
  const { FONTS, googleFontUrl } = await import(path.join(REPO, "backend", "src", "modules", "branding", "presets.js"));
  const font = FONTS[pack.theme.font];
  const local = FONT_FILES[pack.theme.font];
  const fonts = local && Object.values(local.files).every((f) => fs.existsSync(path.join(local.dir, f)))
    ? { family: local.family, files: Object.entries(local.files).map(([weight, file]) => ({ weight, from: path.join(local.dir, file), to: `fonts/${file}` })) }
    : null;
  return {
    vars: themeToCssVars(pack.theme, { fontStack: font?.stack }),
    pack: { id: manifest.id, name: manifest.name, logo: path.join(dir, pack.assets?.logo || "logo.png"), fonts, fontUrl: fonts ? null : googleFontUrl(pack.theme.font) },
  };
}

/** Writes the help into `out`, emptied first except for the files named in `keep` (the edition's Word and PDF). */
function write(out, { html, sections, images, copies, script, keep = [] }) {
  if (fs.existsSync(out)) {
    for (const entry of fs.readdirSync(out)) if (!keep.includes(entry)) fs.rmSync(path.join(out, entry), { recursive: true, force: true });
  }
  fs.mkdirSync(path.join(out, "images"), { recursive: true });
  fs.writeFileSync(path.join(out, "user-manual.html"), html);
  fs.writeFileSync(path.join(out, "sections.json"), `${JSON.stringify(sections, null, 1)}\n`);
  fs.copyFileSync(script, path.join(out, "manual.js"));
  for (const { from, to } of [...images, ...copies]) {
    fs.mkdirSync(path.dirname(path.join(out, to)), { recursive: true });
    fs.copyFileSync(from, path.join(out, to));
  }
}

const headingList = (heads) => heads.map((h) => ({ id: h.id, ...(h.number ? { number: h.number } : {}), title: h.title, level: h.level,
  chapter: h.chapter ? h.chapter.title : null }));

async function buildBase(out, check) {
  const ed = EDITIONS.base;
  const { meta, body } = parseFrontMatter(fs.readFileSync(ed.source, "utf8").replace(/\r\n/g, "\n"));
  const heads = headingIds(body.split("\n"));
  const images = [];
  const missing = [];
  const content = render(body, heads, (src) => {
    const file = path.basename(src);
    const from = path.join(ed.images, file);
    if (fs.existsSync(from)) images.push({ from, to: `images/${file}` });
    else missing.push(file);
    return `images/${encodeURIComponent(file)}`;
  });
  if (check) return;
  const { vars } = await theme(null);
  const pdf = path.basename(ed.files.pdf);
  const edition = { title: `BrokerVerse ${meta.title || "User Manual"}`, version: meta.version || "", date: meta.date || "", status: "", files: { pdf } };
  const copies = fs.existsSync(ed.files.pdf) ? [{ from: ed.files.pdf, to: pdf }] : [];
  write(out, {
    html: page({ edition, vars, toc: toc(heads), content }),
    sections: { edition: "base", title: edition.title, version: edition.version, date: edition.date, status: "", brandPack: null, files: { pdf: copies.length ? pdf : null, word: null },
      roles: {}, sections: headingList(heads) },
    images, copies, script: path.join(__dirname, "help", "manual.js"),
  });
  missing.forEach((f) => console.warn(`image not found: ${f}`));
  console.log(`help (base): ${heads.length} sections, ${images.length} images, PDF ${copies.length ? "copied" : "missing"} -> ${path.relative(ROOT, out)}`);
}

async function buildManifest(name, out, check) {
  const manifest = loadManifest(EDITIONS[name].manifest);
  const factsFile = path.join(manifest.dir, manifest.roleFacts);
  if (!fs.existsSync(factsFile)) fail([`${path.relative(REPO, factsFile)} is missing: run npm run manual:role-facts in backend/`]);
  const facts = JSON.parse(fs.readFileSync(factsFile, "utf8"));
  const result = assemble(manifest, facts, await featureEdition());
  const menu = await menuChecks(facts);
  const problems = [...result.problems, ...menu.problems];

  const { status, reason } = effectiveStatus(manifest, result);
  if (reason) console.warn(`help (${name}): shown as Draft: ${reason}`);
  const docControl = [
    "# Document control {#document-control}", "",
    "| Item | Value |", "|---|---|",
    ...controlRows(manifest, status).map(([k, v]) => `| ${k} | ${v} |`),
    "", "**Change log**", "", "| Version | Date | Author | Change |", "|---|---|---|---|",
    ...(manifest.changes || []).map((c) => `| ${c.version} | ${c.date} | ${c.author} | ${c.change} |`),
  ].join("\n");
  const markdown = `${docControl}\n\n${result.markdown}`;
  let heads;
  try {
    heads = headingIds(markdown.split("\n"));
  } catch (e) {
    problems.push(e.message);
  }
  if (heads) {
    // section numbers as in the Word and PDF files: the chapters from 1, the document control without a number
    const counters = [0, 0, 0];
    for (const h of heads) {
      if (h.id === "document-control" || h.chapter?.id === "document-control") continue;
      counters[h.level - 1] += 1;
      for (let k = h.level; k < 3; k += 1) counters[k] = 0;
      h.number = counters.slice(0, h.level).join(".");
    }
  }
  if (heads) {
    const ids = new Set(heads.map((h) => h.id));
    const uncovered = menu.paths.filter((p) => !ids.has(menu.sectionOf(p, ids)));
    for (const p of uncovered) problems.push(`the screen ${facts.screens[p]?.menu || p} has no section (helpRoutes.js gives "${menu.sectionOf(p, ids)}")`);
    for (const [, id] of markdown.matchAll(/\]\(#([a-z0-9-]+)\)/g)) if (!ids.has(id)) problems.push(`a link leads to no heading: #${id}`);
  }
  if (problems.length) fail(problems);
  if (check) {
    console.log(`help (${name}): ${heads.length} sections, ${result.drafts} in preparation, no rule broken`);
    return;
  }

  const { vars, pack } = await theme(manifest.brandPack);
  // the Word and PDF are published in public/help only (npm run help:word writes them there); a build into another
  // folder copies them from there
  const files = {};
  const copies = [];
  const keep = [];
  for (const [kind, file] of Object.entries(manifest.files || {})) {
    const from = path.join(PUBLISHED, file);
    if (!fs.existsSync(from)) {
      console.warn(`help (${name}): ${kind} not found: ${path.relative(REPO, from)} (npm run help:word)`);
      continue;
    }
    files[kind] = file;
    if (path.resolve(out) === PUBLISHED) keep.push(file);
    else copies.push({ from, to: file });
  }
  if (pack) copies.push({ from: pack.logo, to: `logo${path.extname(pack.logo)}` });
  for (const f of pack?.fonts?.files || []) copies.push({ from: f.from, to: f.to });
  const edition = { title: manifest.title, version: manifest.version, versionLabel: manifest.versionLabel, date: manifest.date, status, files, brandName: pack?.name,
    logo: pack ? `logo${path.extname(pack.logo)}` : null, fontUrl: pack?.fontUrl,
    fonts: pack?.fonts ? { family: pack.fonts.family, files: pack.fonts.files.map(({ weight, to }) => ({ weight, src: to })) } : null };
  const content = render(markdown, heads, (src) => src.split("/").map(encodeURIComponent).join("/"));
  const roles = Object.fromEntries(facts.roles.map((r) => [r.code, { id: r.chapterId, title: r.name }]));
  write(out, {
    html: page({ edition, vars, toc: toc(heads), content }),
    sections: { edition: manifest.id, title: manifest.title, version: manifest.version, versionLabel: manifest.versionLabel || null, date: manifest.date, status, brandPack: pack?.id || null,
      files: { pdf: files.pdf || null, word: files.word || null }, sourceHash: result.hash, roles, sections: headingList(heads) },
    images: result.images, copies, keep, script: path.join(__dirname, "help", "manual.js"),
  });
  if (manifest.wordSource) {
    fs.mkdirSync(path.dirname(path.join(manifest.dir, manifest.wordSource)), { recursive: true });
    fs.writeFileSync(path.join(manifest.dir, manifest.wordSource), wordSource(manifest, result, status));
  }
  console.log(`help (${name}): ${heads.length} sections, ${result.drafts} in preparation, ${result.images.length} images, ${Object.keys(files).join(" and ") || "no"} downloads`
    + ` -> ${path.relative(ROOT, out)}`);
}

async function main() {
  const configured = JSON.parse(fs.readFileSync(CONFIG, "utf8")).edition;
  const name = arg("edition") || configured;
  if (!EDITIONS[name]) fail([`unknown edition "${name}" (${Object.keys(EDITIONS).join(", ")})`]);
  const out = arg("out") ? path.resolve(arg("out")) : PUBLISHED;
  if (!arg("out") && name !== configured) fail([`help.config.json ships the ${configured} edition: write the ${name} edition with --out <folder>`]);
  const check = process.argv.includes("--check");
  if (EDITIONS[name].manifest) await buildManifest(name, out, check);
  else await buildBase(out, check);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
