#!/bin/sh
# Write the runtime configuration of one environment: /env-config.js, read by the app before its bundle
# (src/config/runtimeConfig.js). The same build is deployed everywhere; only this file differs.
#
#   scripts/env-config.sh build/env-config.js        write the file
#   scripts/env-config.sh                            print it
#
# Environment variables (all optional):
#   API_BASE_URL        API address seen by the browser. Leave empty when the web server proxies /api to the
#                       backend (same origin, the recommended set-up); else e.g. https://api.example.ph/api
#   ENVIRONMENT_NAME    DEV, SIT, UAT, PREPROD, TRAINING... shown as a label next to the logo.
#                       Empty or PRODUCTION shows no label.
#   ENVIRONMENT_COLOR   label colour as #rgb or #rrggbb (a default per environment name otherwise)
#   ANALYTICS_ENABLED   true to allow analytics (default false)
#
# Values are checked against a strict character set, so nothing can break out of the generated script.
# POSIX sh: runs in the nginx Alpine image, on the EC2 host and on the GitHub runner.
set -eu

fail() { echo "env-config: $*" >&2; exit 1; }

api="${API_BASE_URL:-}"
name="${ENVIRONMENT_NAME:-}"
color="${ENVIRONMENT_COLOR:-}"
analytics="${ANALYTICS_ENABLED:-false}"

if [ -n "$api" ]; then
  case "$api" in
    /*|http://*|https://*) ;;
    *) fail "API_BASE_URL must start with / or http(s):// (got '$api')" ;;
  esac
  printf '%s' "$api" | grep -Eq '^[A-Za-z0-9._~:/?#@!$&()*+,;=%-]+$' \
    || fail "API_BASE_URL holds characters that are not allowed in a URL"
fi
if [ -n "$name" ]; then
  printf '%s' "$name" | grep -Eq '^[A-Za-z0-9 _-]{1,24}$' \
    || fail "ENVIRONMENT_NAME may hold letters, digits, space, - and _ (at most 24)"
fi
if [ -n "$color" ]; then
  printf '%s' "$color" | grep -Eq '^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$' \
    || fail "ENVIRONMENT_COLOR must be #rgb or #rrggbb"
fi
case "$analytics" in
  1|true|TRUE|True|yes|on) analytics=true ;;
  *) analytics=false ;;
esac

content="// Generated by scripts/env-config.sh at deployment; do not edit by hand.
window.__BROKERVERSE_CONFIG__ = {
  \"API_BASE_URL\": \"$api\",
  \"ENVIRONMENT_NAME\": \"$name\",
  \"ENVIRONMENT_COLOR\": \"$color\",
  \"ANALYTICS_ENABLED\": $analytics
};"

if [ $# -ge 1 ] && [ -n "$1" ]; then
  tmp="$1.tmp.$$"
  printf '%s\n' "$content" > "$tmp"
  chmod 644 "$tmp"
  mv "$tmp" "$1"
  echo "env-config: wrote $1 (environment '${name:-production}', API '${api:-same origin /api}')"
else
  printf '%s\n' "$content"
fi
