#!/bin/sh
# Write the nginx snippets of the web server for this environment, into the directory given as argument
# (default /etc/nginx/brokerverse):
#   headers.conf    security headers and the Content-Security-Policy (connect-src adds the API origin when
#                   API_BASE_URL, or else REACT_APP_BASE_URL, points at another origin)
#   api-proxy.conf  location /api/ proxied to API_UPSTREAM (e.g. http://api:8000 in Docker Compose,
#                   http://api.railway.internal:8000 on Railway, http://127.0.0.1:8001 on EC2, the internal
#                   https://<api>.internal.<environment domain> on Azure Container Apps); empty when API_UPSTREAM is
#                   not set (the API is then reached on API_BASE_URL). The upstream's own host name is sent as Host
#                   (Container Apps routes on it), the browser's in X-Forwarded-Host.
#   origin.conf     with FRONT_DOOR_ID (Azure): requests that did not come through that Front Door profile (header
#                   X-Azure-FDID) are refused with 403, so its WAF cannot be bypassed; empty otherwise
# Used by the web container at start (docker-entrypoint.d) and by deploy/ec2/release.sh. POSIX sh.
set -eu

dir="${1:-/etc/nginx/brokerverse}"
mkdir -p "$dir"

# API_BASE_URL, or the build-time REACT_APP_BASE_URL of a service set up before runtime configuration existed
# (Railway passes a service's variables to the running container too): the app calls that address, so the
# policy must allow it, or the browser blocks every API call ("Failed to fetch").
api="${API_BASE_URL:-${REACT_APP_BASE_URL:-}}"
upstream="${API_UPSTREAM:-}"
extra_connect="${CSP_CONNECT_EXTRA:-}"
front_door="${FRONT_DOOR_ID:-}"

api_origin=""
case "$api" in
  http://*|https://*) api_origin="$(printf '%s' "$api" | sed -E 's#^(https?://[^/]+).*#\1#')" ;;
esac
for v in "$api_origin" "$extra_connect"; do
  if [ -n "$v" ] && ! printf '%s' "$v" | grep -Eq '^[A-Za-z0-9._:/ *-]+$'; then
    echo "nginx-snippets: refusing CSP source '$v'" >&2
    exit 1
  fi
done

connect="'self'"
[ -n "$api_origin" ] && connect="$connect $api_origin"
[ -n "$extra_connect" ] && connect="$connect $extra_connect"
frames="'self' blob:"
[ -n "$api_origin" ] && frames="$frames $api_origin"

csp="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src $connect; frame-src $frames; worker-src 'self' blob:; manifest-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'"

cat > "$dir/headers.conf" <<EOF
# Generated by scripts/nginx-snippets.sh. Included in every location: nginx drops server-level add_header
# lines in a location that has its own.
add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options SAMEORIGIN always;
add_header Referrer-Policy strict-origin-when-cross-origin always;
add_header Content-Security-Policy "$csp" always;
EOF

if [ -n "$upstream" ]; then
  printf '%s' "$upstream" | grep -Eq '^https?://[]A-Za-z0-9.:[_-]+/?$' \
    || { echo "nginx-snippets: API_UPSTREAM must be scheme://host:port (got '$upstream')" >&2; exit 1; }
  upstream="${upstream%/}"
  # resolve the API's name at request time (it may change address on a restart); first resolver of the host
  ns="$(awk '/^nameserver/ { print $2; exit }' /etc/resolv.conf 2>/dev/null || true)"
  resolver=""
  if [ -n "$ns" ]; then
    case "$ns" in *:*) ns="[$ns]" ;; esac
    resolver="resolver $ns valid=30s;"
  fi
  cat > "$dir/api-proxy.conf" <<EOF
# Generated by scripts/nginx-snippets.sh: same-origin API, /api/ forwarded to $upstream
location /api/ {
  $resolver
  set \$brokerverse_api "$upstream";
  proxy_pass \$brokerverse_api;
  proxy_http_version 1.1;
  proxy_ssl_server_name on;
  proxy_set_header Host \$proxy_host;
  proxy_set_header X-Forwarded-Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto \$scheme;
  proxy_read_timeout 120s;
  client_max_body_size 25m;
}
EOF
else
  printf '%s\n' "# Generated by scripts/nginx-snippets.sh: API_UPSTREAM not set, the browser calls API_BASE_URL directly." > "$dir/api-proxy.conf"
fi
if [ -n "$front_door" ]; then
  printf '%s' "$front_door" | grep -Eq '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$' \
    || { echo "nginx-snippets: FRONT_DOOR_ID must be the ID of the Front Door profile (a GUID)" >&2; exit 1; }
  cat > "$dir/origin.conf" <<EOF
# Generated by scripts/nginx-snippets.sh: only requests through Azure Front Door $front_door
if (\$http_x_azure_fdid != "$front_door") {
  return 403;
}
EOF
else
  printf '%s\n' "# Generated by scripts/nginx-snippets.sh: FRONT_DOOR_ID not set, no origin check." > "$dir/origin.conf"
fi
echo "nginx-snippets: wrote $dir/headers.conf, $dir/api-proxy.conf and $dir/origin.conf (API upstream '${upstream:-none}', Front Door '${front_door:-none}')"
