// Audit Trail Action Types
export const GET_QUOTATION_AUDIT_TRAIL_REQUEST =
  "GET_QUOTATION_AUDIT_TRAIL_REQUEST";
export const GET_QUOTATION_AUDIT_TRAIL_SUCCESS =
  "GET_QUOTATION_AUDIT_TRAIL_SUCCESS";
export const GET_QUOTATION_AUDIT_TRAIL_FAILURE =
  "GET_QUOTATION_AUDIT_TRAIL_FAILURE";

// Quotation Details Action Types
export const GET_QUOTATION_DETAILS_REQUEST = "GET_QUOTATION_DETAILS_REQUEST";
export const GET_QUOTATION_DETAILS_SUCCESS = "GET_QUOTATION_DETAILS_SUCCESS";
export const GET_QUOTATION_DETAILS_FAILURE = "GET_QUOTATION_DETAILS_FAILURE";
