/**
 * The application menu. Conventions (components/SideBar renders it):
 *  - at most three levels: group > item, or group > sub-group > item;
 *  - only top-level entries carry an icon (a PrimeIcons class, all the same size and colour);
 *  - `section: true` turns a sub-group into a plain heading inside its group instead of a collapsible level (Master);
 *  - `name` is the key of the role grants (utils/menuPermissions.js) and of the label (sidebar.<name> in en.json):
 *    shorten a label in en.json, not here, so that grants and links keep working.
 */
export const menuList = [
  {
    // the working home page of a user (open items, upcoming events): a top-level entry, not part of Operations
    name: "Home",
    icon: "pi pi-home",
    // not taken as the landing page of a role that also has a dashboard (firstAllowedPath)
    landing: false,
    path: "/agent/home",
    // the notifications page and the user's own profile are open to every signed-in role (not part of Home)
    includes: [
      "/agent/home",
      "/agent/openitems",
      "/agent/openitems/upcomingevents",
    ],
    permissions: ["read:home"],
  },
  {
    name: "Dashboard",
    icon: "pi pi-chart-bar",
    submenu: [
      {
        id: 1,
        name: "Executive Dashboard",
        path: "/executive/dashboard",
        includes: ["/executive/dashboard", "/"],
        permissions: ["read:executive-dashboard"],
      },
      {
        id: 2,
        name: "Claims Dashboard",
        path: "/claims/dashboard",
        includes: ["/claims/dashboard"],
        permissions: ["read:claims-dashboard"],
      },
      {
        id: 3,
        name: "Processing Dashboard",
        path: "/processing/dashboard",
        includes: ["/processing/dashboard"],
        permissions: ["read:processing-dashboard"],
      },
      {
        id: 4,
        name: "Sales Dashboard",
        path: "/sales/dashboard",
        includes: ["/sales/dashboard", "/agent/home"],
        permissions: ["read:agent-dashboard"],
      },
    ],
  },
  {
    name: "Operations",
    icon: "pi pi-briefcase",
    submenu: [
      {
        // Sales & Marketing: prospects, quick quotes for package products, requests for quotation (broker slips) and
        // quotations for non-package risks, and the placement slips that bind them with the insurers
        id: 29,
        name: "Sales & Marketing",
        submenu: [
          {
            id: 30,
            // the prospect (lead) list and the motor quote and policy conversion screens opened from it
            name: "Prospects",
            path: "/agent/leadlisting",
            includes: [
              "/agent/createlead/employee-benefit",
              "/agent/createlead/fire-allied-perils",
              "/agent/leadlisting",
              "/agent/createlead",
              "/createquote/policydetails/createquote/",
              "/createquote/coveragedetails/coveragecreate/",
              "/createquote/accessories/accessoriescreate/",
              "/agent/createquote/ordersummary",
              "/agent/quotedetailview",
              "/agent/convertpolicy/customerinfo/view/",
              "/agent/convertpolicy/customerinfo/fire/new/",
              "/agent/convertpolicy/uploadvehiclephotos",
              "/agent/coveragedetailedview",
              "/agent/policyapproval",
              "/agent/uploadpolicy",
              "/agent/createquote/policydetails/createquote/",
              "/agent/createquote/coveragedetails/coveragecreate/",
              "/agent/leadedit",
              "/agent/createquote/accessories/accessoriescreate/",
              "/agent/quotelisting",
              "/agent/convertpolicy/customerinfo/edit/",
              "/agent/editquote/policydetails/quotedetails/",
              "/agent/quotedetailedit",
            ],
            permissions: ["read:leads"],
          },
          {
            id: 31,
            name: "Quick Quote",
            path: "/sales/quick-quote",
            includes: ["/sales/quick-quote"],
            permissions: ["write:quotations"],
          },
          {
            // package products: premiums of several insurers side by side from their rate tables
            id: 35,
            name: "Compare Insurers",
            path: "/sales/compare-insurers",
            includes: ["/sales/compare-insurers"],
            permissions: ["write:quotations"],
          },
          {
            // the broker slip is the request for quotation sent to several insurers
            id: 32,
            name: "Request for Quotation",
            path: "/placement/broker-slips",
            includes: ["/placement/broker-slips"],
            permissions: ["read:quotations"],
          },
          {
            id: 33,
            name: "Quotations",
            path: "/agent/Quotation",
            includes: [
              "/agent/Quotation",
              "/agent/employee-benefit/create-quote",
              "/agent/employee-benefit/create-quote-employeebulkupload",
              "/agent/employee-benefit/create-quote-Coverage-details",
              "/agent/employee-benefit/create-quote-order-summary",
              "/agent/employee-benefit/create-quote-quote-details",
            ],
            permissions: ["read:quotations"],
          },
          {
            // firm orders to the insurers, binding and policy issuance; direct policy entry
            id: 34,
            name: "Placement Slips",
            path: "/placement/placement-slips",
            includes: ["/placement/placement-slips", "/placement/record-issued-policy"],
            permissions: ["read:quotations"],
          },
        ],
      },
      {
        name: "Clients",
        path: "/agent/clientlisting",
        includes: [
          "/agent/clientlisting",
          "/agent/clientedit",
          "/agent/clientview/",
          "/agent/policydetailedview",
          "/agent/policydetailedview/accountview",
          "/agent/policydetailedviewonly",
          "/agent/claimrequest/claimdetails",
          "/agent/claimrequest/sendmail",
          "/agent/claimrequest/requestapproval/",
          "/agent/claimrequest/adjustersubmission",
          "/agent/claimrequest/settlementapproval",
          "/agent/claimrequest/settlementdetails/",
          "/agent/claimdetailedview/",
          "/agent/renewalquote/coveragedetails/coveragedetail/",
          "/agent/createquote/accessories/accessorirsdetails/",
          "/agent/createquote/ordersummaryquote",
          "/agent/endorsement/paymentconfirmation",
          "/agent/policy/paymentoptions",
          "/agent/endorsement/paymenterror/",
          "/agent/uploadendorsement",
          "/agent/endorsementdetailedview/123",
          "/agent/endorsement/paymentconfirmation",
          "/agent/endorsement/personaldetails",
          "/agent/uploadendorsement",
          "/agent/endorsementdetailedview/123",
          "/agent/endorsement/paymentconfirmation",
          "/agent/policy/paymentapproval",
          "/agent/renewal/waiting/",
          "/agent/renewalquote/accessories/accessorirsdetails/",
          "/agent/renewalquote/ordersummary",
          "/agent/endorsementdetailedview/",
          "/agent/endorsement/rejected/",
          "/agent/createquote/coveragedetails/coveragedetail/",
          "/agent/claimrejected",
          "/agent/claimdocumentupload",
          "/agent/endorsementdetailedviewonly/",
          "/agent/employee-benefit/client-policy-details",
        ],
        permissions: ["read:clients"],
      },
      {
        name: "Policy",
        path: "/agent/policy",
        includes: [
          "/agent/policy",
          "/agent/employee-benefit/policy-waiting-for-policy",
          "/agent/employee-benefit/policy-upload-policy",
        ],
        permissions: ["read:policies"],
      },

      {
        name: "Claims",
        path: "/agent/claim",
        includes: ["/agent/claim"],
        permissions: ["read:claims"],
      },
      {
        id: 9,
        name: "Renewals",
        submenu: [
          {
            id: 18,
            name: "Renewal Policy",
            path: "/agent/expired-policies",
            includes: ["/agent/expired-policies"],
          },
          {
            id: 19,
            name: "Renewal Batch",
            path: "/agent/renewal-batch",
            includes: ["/agent/renewal-batch"],
          },
          {
            id: 1,
            name: "Renewal Queue",
            path: "/renewal/queue",
            includes: ["/renewal/queue", "/renewal/generate-quote"],
          },
          {
            id: 2,
            name: "Retention Analytics",
            path: "/renewal/analytics",
            includes: ["/renewal/analytics"],
          },
          {
            id: 3,
            name: "At-Risk Policies",
            path: "/renewal/at-risk",
            includes: ["/renewal/at-risk"],
          },
          {
            id: 4,
            name: "Negotiations",
            path: "/renewal/negotiations",
            includes: ["/renewal/negotiations"],
          },
          {
            id: 5,
            name: "Lapse Management",
            path: "/renewal/lapse-management",
            includes: ["/renewal/lapse-management"],
          },
          {
            id: 6,
            name: "Performance",
            path: "/renewal/performance",
            includes: ["/renewal/performance"],
          },
        ],
      },
      {
        name: "Open Items",
        path: "/agent/openitemslistdata",
        includes: [
          "/agent/openitemslistdata",
          "/agent/openitemslistdata",
          "/agent/openitems/expiringpolicy",
          "/agent/openitems/quotepending",

          "/agent/openitems/renewalrequest",
        ],
        permissions: ["read:openitems"],
      },
      {
        name: "Payments",
        path: "/agent/payments",
        includes: ["/agent/payments"],
        permissions: ["read:payments"],
      },
    ],
  },
  {
    name: "Accounts",
    icon: "pi pi-wallet",
    submenu: [
      {
        id: 1,
        name: "Receipts",
        path: "/accounts/receipts",
        includes: [
          "/accounts/receipts/addreceipts",
          "/accounts/receipts/receiptdetailview",
          "/accounts/receipts/addreceiptedit",
          "/accounts/receipts/paymentdetails",
          "/accounts/receipts",
          // finance verifies payments captured on a policy (linked from the "Premium payment to verify" notification)
          "/agent/policy/paymentoptions",
          "/agent/policy/paymentconfirmation",
        ],
        permissions: ["read:receipts"],
      },
  {
        id: 12,
        name: "Collections",
        path: "/agent/collections",
        includes: ["/agent/collections", "/agent/collections/aging-report"],
        permissions: ["read:collections"],
      },
  {
        id: 24,
        name: "Credit Control",
        submenu: [
          { id: 1, name: "Instalment Plans", path: "/accounts/credit-control/instalments", includes: ["/accounts/credit-control/instalments"] },
          { id: 2, name: "Premium Warranty Monitor", path: "/accounts/credit-control/warranty", includes: ["/accounts/credit-control/warranty"] },
          { id: 3, name: "Client Credit Limits", path: "/accounts/credit-control/limits", includes: ["/accounts/credit-control/limits"] },
          { id: 4, name: "Remittance Ageing", path: "/accounts/credit-control/remittance-ageing", includes: ["/accounts/credit-control/remittance-ageing"] },
        ],
      },
  {
        id: 2,
        name: "Disbursement",
        path: "/accounts/paymentvoucher",
        includes: [
          "/accounts/paymentvoucher",
          "/accounts/paymentvoucher/createvoucher",
          "/accounts/paymentvoucher/bulk-disburse",
          "/accounts/paymentvoucher/invoicelist/",
          "/accounts/paymentvoucher/detailview/",
          "/accounts/paymentvoucher/SpecificVoucher",
          "/accounts/paymentvoucher/bankdetailselection",
        ],
        permissions: ["read:disbursements"],
      },
  {
        id: 7,
        name: "Remittance",
        submenu: [
          {
            id: 1,
            name: "Automated Processing",
            path: "/finance/remittance/automated/execute",
            includes: [
              "/finance/remittance/automated/execute",
              "/finance/remittance/automated/history",
            ],
          },
          {
            id: 2,
            name: "Tracking",
            path: "/finance/remittance/tracking/status",
            includes: [
              "/finance/remittance/tracking/status",
              "/finance/remittance/tracking/history",
            ],
          },
          {
            id: 3,
            name: "Statements",
            path: "/finance/remittance/statements/generate",
            includes: [
              "/finance/remittance/statements/generate",
              "/finance/remittance/statements/history",
            ],
          },
          {
            id: 4,
            name: "Settlement",
            path: "/finance/remittance/settlement/process",
            includes: [
              "/finance/remittance/settlement/process",
              "/finance/remittance/settlement/history",
            ],
          },
          {
            id: 5,
            name: "Reconciliation",
            path: "/finance/remittance/reconciliation",
            includes: [
              "/finance/remittance/reconciliation",
              "/finance/remittance/reconciliation/process",
              "/finance/remittance/reconciliation/exceptions",
            ],
          },
          {
            id: 6,
            name: "Bulk Processing",
            path: "/finance/remittance/bulkprocessing",
            includes: [
              "/finance/remittance/bulkprocessing",
              "/finance/remittance/bulkprocessing/upload",
              "/finance/remittance/bulkprocessing/history",
            ],
          },
          {
            id: 7,
            name: "Scheduling",
            path: "/finance/remittance/scheduling",
            includes: [
              "/finance/remittance/scheduling",
              "/finance/remittance/scheduling/calendar",
              "/finance/remittance/scheduling/jobs",
            ],
          },
          {
            id: 8,
            name: "Electronic Transfer",
            path: "/finance/remittance/electronictransfer",
            includes: [
              "/finance/remittance/electronictransfer",
              "/finance/remittance/electronictransfer/create",
              "/finance/remittance/electronictransfer/history",
            ],
          },
          {
            id: 9,
            name: "Approval Workflow",
            path: "/finance/remittance/approval",
            includes: [
              "/finance/remittance/approval",
              "/finance/remittance/approval/pending",
              "/finance/remittance/approval/history",
              "/finance/remittance/approval/delegation",
            ],
          },
          {
            id: 10,
            name: "Exception Management",
            path: "/finance/remittance/exceptions",
            includes: [
              "/finance/remittance/exceptions",
              "/finance/remittance/exceptions/resolve",
              "/finance/remittance/exceptions/history",
            ],
          },
          {
            id: 12,
            name: "Agency Bill Processing",
            path: "/finance/remittance/agencybill",
            includes: [
              "/finance/remittance/agencybill",
              "/finance/remittance/agencybill/process",
              "/finance/remittance/agencybill/history",
            ],
          },
          {
            id: 13,
            name: "Direct Bill Processing",
            path: "/finance/remittance/directbill",
            includes: [
              "/finance/remittance/directbill",
              "/finance/remittance/directbill/process",
              "/finance/remittance/directbill/history",
            ],
          },
          {
            id: 14,
            name: "Adjustments",
            path: "/finance/remittance/adjustments",
            includes: [
              "/finance/remittance/adjustments",
              "/finance/remittance/adjustments/process",
              "/finance/remittance/adjustments/history",
            ],
          },
          {
            id: 15,
            name: "Notifications",
            path: "/finance/remittance/notifications",
            includes: [
              "/finance/remittance/notifications",
              "/finance/remittance/notifications/manage",
              "/finance/remittance/notifications/history",
            ],
          },
          {
            id: 16,
            name: "History",
            path: "/finance/remittance/history",
            includes: [
              "/finance/remittance/history",
              "/finance/remittance/history/view",
              "/finance/remittance/history/reports",
            ],
          },
          {
            id: 17,
            name: "Analytics",
            path: "/finance/remittance/analytics",
            includes: [
              "/finance/remittance/analytics",
              "/finance/remittance/analytics/dashboard",
              "/finance/remittance/analytics/reports",
            ],
          },
        ],
      },
  {
        id: 4,
        name: "Journal Voucher",
        path: "/accounts/journalvoucher",
        includes: [
          "/accounts/journalvoucher",
          "/accounts/journalvoucher/addjournalvoucture",
          "/accounts/journalvoucher/detailsjournalvocture/",
        ],
        permissions: ["read:journalvoucher"],
      },
  {
        id: 5,
        name: "Correction JV",
        path: "/accounts/correctionsjv/correctionsjvdetails",
        includes: ["/accounts/correctionsjv/correctionsjvdetails"],
        permissions: ["read:correctionjv"],
      },
  {
        id: 6,
        name: "Reversal JV",
        path: "/accounts/reversaljv/reversaljvdetails",
        includes: ["/accounts/reversaljv/reversaljvdetails"],
        permissions: ["read:reversaljv"],
      },
  {
        id: 15,
        name: "Open Entry Matching",
        path: "/accounts/open-entry-matching",
        includes: ["/accounts/open-entry-matching"],
        permissions: ["read:accounting"],
      },
  {
        id: 16,
        name: "Open Entry Unmatching",
        path: "/accounts/open-entry-unmatching",
        includes: ["/accounts/open-entry-unmatching"],
        permissions: ["read:accounting"],
      },
  {
        id: 13,
        name: "Accounting Query",
        path: "/agent/accounting/query",
        includes: ["/agent/accounting/query"],
        permissions: ["read:accounting"],
      },
  {
        id: 14,
        name: "All Clients Accounting",
        path: "/agent/accounting/all-clients-details",
        includes: ["/agent/accounting/all-clients-details"],
        permissions: ["read:accounting"],
      },
  {
        id: 3,
        name: "Petty Cash",
        permissions: ["read:pettycash"],
        submenu: [
          {
            id: 1,
            name: "Initiate",
            path: "/accounts/pettycash/pettycashcodeinitiate",
            includes: [
              "/accounts/pettycash/pettycashcodeinitiate",
              "/accounts/pettycash/pettycashcodeinitiate/initiate",
              "/accounts/pettycash/PettyCashCodeDetails",
            ],
          },
          {
            id: 2,
            name: "Request",
            path: "/accounts/pettycash/pettycashrequest",
            includes: [
              "/accounts/pettycash/pettycashrequest",
              "/accounts/pettycash/addrequest/add/",
              "/accounts/pettycash/addrequesttable",
              "/accounts/pettycash/request",
              "/accounts/pettycash/editrequestform/edit/",
              "/accounts/pettycash/editrequestform/view/",
            ],
          },
          {
            id: 3,
            name: "Disbursement",
            path: "/accounts/pettycash/disbursement",
            includes: [
              "/accounts/pettycash/disbursement",
              "/accounts/pettycash/adddisbursement",
              "/accounts/pettycash/adddisbursementtable",
              "/accounts/pettycash/disbursementdetailview",
            ],
          },
          {
            id: 4,
            name: "Receipts",
            path: "/accounts/pettycash/receipts",
            includes: [
              "/accounts/pettycash/receipts",
              "/accounts/pettycash/addreceipts",
              "/accounts/pettycash/receiptlist",
              "/accounts/pettycash/addreceiptstable",
            ],
          },
          {
            id: 5,
            name: "Replenish",
            path: "/accounts/pettycash/replenish",
            includes: [
              "/accounts/pettycash/replenish",
              "/accounts/pettycash/addreplenish",
              "/accounts/pettycash/addreplenishtable",
              "/accounts/pettycash/replenishtdetailview",
            ],
          },
        ],
      },
  {
        id: 22,
        name: "Bank Reconciliation",
        submenu: [
          { id: 1, name: "Reconciliation Workspace", path: "/accounts/bank-reconciliation", includes: ["/accounts/bank-reconciliation"] },
          { id: 2, name: "Reconciliations", path: "/accounts/bank-reconciliation/reconciliations", includes: ["/accounts/bank-reconciliation/reconciliations"] },
          { id: 3, name: "Reconciliation Statement Report", path: "/accounts/bank-reconciliation/reports/bank-reconciliation-statement", includes: ["/accounts/bank-reconciliation/reports/bank-reconciliation-statement"] },
          { id: 4, name: "Outstanding Cheques", path: "/accounts/bank-reconciliation/reports/bank-outstanding-cheques", includes: ["/accounts/bank-reconciliation/reports/bank-outstanding-cheques"] },
          { id: 5, name: "Deposits in Transit", path: "/accounts/bank-reconciliation/reports/bank-deposits-in-transit", includes: ["/accounts/bank-reconciliation/reports/bank-deposits-in-transit"] },
          { id: 6, name: "Unmatched Bank Lines", path: "/accounts/bank-reconciliation/reports/bank-unmatched-lines", includes: ["/accounts/bank-reconciliation/reports/bank-unmatched-lines"] },
          { id: 7, name: "Bank Book", path: "/accounts/bank-reconciliation/reports/bank-book", includes: ["/accounts/bank-reconciliation/reports/bank-book"] },
        ],
      },
  {
        id: 23,
        name: "Insurer Reconciliation",
        submenu: [
          {
            id: 1,
            name: "Insurer Statements",
            path: "/accounts/insurer-reconciliation/statements",
            includes: ["/accounts/insurer-reconciliation/statements"],
          },
        ],
      },
  {
        id: 21,
        name: "Tax",
        submenu: [
          { id: 1, name: "BIR Form 2307", path: "/accounts/tax/2307", includes: ["/accounts/tax/2307"] },
          { id: 2, name: "VAT Summary", path: "/accounts/tax/reports/bir-vat-summary", includes: ["/accounts/tax/reports/bir-vat-summary"] },
          { id: 3, name: "SAWT", path: "/accounts/tax/reports/bir-sawt", includes: ["/accounts/tax/reports/bir-sawt"] },
          { id: 4, name: "QAP", path: "/accounts/tax/reports/bir-qap", includes: ["/accounts/tax/reports/bir-qap"] },
          { id: 5, name: "SLSP Sales", path: "/accounts/tax/reports/bir-slsp-sales", includes: ["/accounts/tax/reports/bir-slsp-sales"] },
          { id: 6, name: "SLSP Purchases", path: "/accounts/tax/reports/bir-slsp-purchases", includes: ["/accounts/tax/reports/bir-slsp-purchases"] },
        ],
      },
  {
        id: 20,
        name: "Period End",
        submenu: [
          { id: 1, name: "Period Management", path: "/accounts/period-end/periods", includes: ["/accounts/period-end/periods"] },
          { id: 2, name: "Month-End Close", path: "/accounts/period-end/close", includes: ["/accounts/period-end/close"] },
          { id: 3, name: "Year-End Close", path: "/accounts/period-end/year-end", includes: ["/accounts/period-end/year-end"] },
          { id: 4, name: "Recurring Journals", path: "/accounts/period-end/recurring", includes: ["/accounts/period-end/recurring"] },
          { id: 5, name: "Financial Statements", path: "/accounts/period-end/statements", includes: ["/accounts/period-end/statements"] },
        ],
      },
  {
        id: 8,
        name: "Incentive",
        submenu: [
          {
            id: 1,
            name: "My Programs",
            path: "/incentive/my-programs",
            includes: ["/incentive/my-programs"],
          },
          {
            id: 2,
            name: "Calculations",
            path: "/incentive/calculations",
            includes: ["/incentive/calculations"],
          },
          {
            id: 3,
            name: "Approvals",
            path: "/incentive/approvals",
            includes: ["/incentive/approvals"],
          },
          {
            id: 4,
            name: "Statement",
            path: "/incentive/statement",
            includes: ["/incentive/statement"],
          },
        ],
      },
    ],
  },
  {
    name: "Commission",
    icon: "pi pi-percentage",
    submenu: [
      {
        id: 1,
        name: "Commission Dashboard",
        path: "/commission/dashboard",
        includes: ["/commission/dashboard"],
      },
      {
        id: 2,
        name: "Agents/Referrer Accounts",
        path: "/commission/referrer-accounts",
        includes: [
          "/commission/referrer-accounts",
          "/commission/referrer-accounts/",
        ],
      },
    ],
  },
  {
    name: "Reinsurance",
    icon: "pi pi-shield",
    submenu: [
      {
        id: 1,
        name: "Treaty Dashboard",
        path: "/reinsurance/treaties",
        includes: ["/reinsurance/treaties", "/reinsurance/treaty"],
      },
      {
        id: 2,
        name: "Cession Tracking",
        path: "/reinsurance/cessions",
        includes: ["/reinsurance/cessions", "/reinsurance/cession"],
      },
      {
        id: 3,
        name: "Claims Recovery",
        path: "/reinsurance/claims",
        includes: ["/reinsurance/claims", "/reinsurance/claims/recovery"],
      },
      {
        id: 4,
        name: "Reconciliation",
        path: "/reinsurance/reconciliation",
        includes: [
          "/reinsurance/reconciliation",
          "/reinsurance/reconciliation/accounts",
        ],
      },
      {
        id: 5,
        name: "Analytics",
        path: "/reinsurance/analytics",
        includes: [
          "/reinsurance/analytics",
          "/reinsurance/analytics/performance",
        ],
      },
    ],
  },
  {
    name: "Reports",
    icon: "pi pi-file",
    submenu: [
      {
        id: 0,
        name: "All Reports",
        path: "/reports/catalogue",
        includes: ["/reports/catalogue", "/reports/run/"],
      },
      {
        id: 1,
        name: "Operational Reports",
        // path: "/reports/operationalreports",
        submenu: [
          {
            id: 1,
            name: "Production",
            path: "/reports/operationalreports/production",
            includes: ["/reports/operationalreports/production"],
            permissions: ["read:production-reports"],
          },
          {
            id: 2,
            name: "Claims",
            path: "/reports/operationalreports/claims",
            includes: ["/reports/operationalreports/claims"],
            permissions: ["read:claims-reports"],
          },
          {
            id: 3,
            name: "Renewal",
            path: "/reports/operationalreports/renewal",
            includes: ["/reports/operationalreports/renewal"],
            permissions: ["read:renewal-reports"],
          },
          {
            id: 4,
            name: "Remittance",
            path: "/reports/operationalreports/remittance",
            includes: ["/reports/operationalreports/remittance"],
            permissions: ["read:remittance-reports"],
          },
          {
            id: 5,
            name: "Broker Commission",
            path: "/reports/operationalreports/brokercommision",
            includes: ["/reports/operationalreports/brokercommision"],
            permissions: ["read:commission-reports"],
          },
        ],
      },
      {
        id: 2,
        name: "Financial Reports",
        // path: "/reports/operationalreports",
        submenu: [
          {
            id: 1,
            name: "SOA/Premium Receivable",
            path: "/reports/financialreports/soapremiumreceivable",
            includes: ["/reports/financialreports/soapremiumreceivable"],
            permissions: ["read:financial-reports"],
          },
          {
            id: 2,
            name: "Collection Report",
            path: "/reports/financialreports/collectionreport",
            includes: ["/reports/financialreports/collectionreport"],
            permissions: ["read:financial-reports"],
          },
          {
            id: 3,
            name: "Payables",
            path: "/reports/financialreports/Payables",
            includes: ["/reports/financialreports/Payables"],
            permissions: ["read:financial-reports"],
          },
          {
            id: 4,
            name: "Journal",
            path: "/reports/financialreports/journal",
            includes: ["/reports/financialreports/journal"],
            permissions: ["read:financial-reports"],
          },
          {
            id: 5,
            name: "Trial Balance",
            path: "/reports/financialreports/trailbalance",
            includes: ["/reports/financialreports/trailbalance"],
          },
          { id: 6, name: "Income Statement", path: "/reports/financialreports/pe/income-statement", includes: ["/reports/financialreports/pe/income-statement"] },
          { id: 7, name: "Balance Sheet", path: "/reports/financialreports/pe/balance-sheet", includes: ["/reports/financialreports/pe/balance-sheet"] },
          { id: 8, name: "Trial Balance Movement", path: "/reports/financialreports/pe/trial-balance-ocm", includes: ["/reports/financialreports/pe/trial-balance-ocm"] },
          { id: 9, name: "General Ledger Detail", path: "/reports/financialreports/pe/gl-detail", includes: ["/reports/financialreports/pe/gl-detail"] },
          { id: 10, name: "Aged Payables to Insurers", path: "/reports/financialreports/pe/aged-payables-insurers", includes: ["/reports/financialreports/pe/aged-payables-insurers"] },
          { id: 11, name: "Month-End Close Status", path: "/reports/financialreports/pe/month-end-close-status", includes: ["/reports/financialreports/pe/month-end-close-status"] },
          {
            id: 12,
            name: "Co-insurance Register",
            path: "/reports/financialreports/coinsuranceregister",
            includes: ["/reports/financialreports/coinsuranceregister"],
            permissions: ["read:financial-reports"],
          },
          {
            id: 13,
            name: "Due to Insurers by Co-insurer",
            path: "/reports/financialreports/duetoinsurers",
            includes: ["/reports/financialreports/duetoinsurers"],
            permissions: ["read:financial-reports"],
          },
        ],
      },
    ],
  },
  {
    name: "Master",
    icon: "pi pi-database",
    submenu: [
      // Master is two levels deep: each entry below is a section heading inside Master (not a collapsible group),
      // so every master screen is one click from the Master group. Section names are the grant keys of menuPermissions.
      {
        id: 1,
        name: "Organization",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Company",
            path: "/master/generals/organization/companymaster",
            includes: [
              "/master/generals/organization/companymaster",
              "/master/generals/organization/companymaster/add/",
              "/master/generals/organization/companymaster/edit/",
              "/master/generals/organization/companymaster/view/",
            ],
          },

          {
            id: 2,
            name: "Branch",
            path: "/master/generals/organization/branchmaster",
            includes: [
              "/master/generals/organization/branchmaster",
              "/master/generals/organization/branchmaster/add/",
              "/master/generals/organization/branchmaster/edit/",
              "/master/generals/organization/branchmaster/view/",
            ],
          },
        ],
      },
      {
        id: 2,
        name: "Insurance Management",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Insurance Company",
            path: "/master/generals/insurancemanagement/insurancecompany",
            includes: [
              "/master/generals/insurancemanagement/insurancecompany",
              "/master/generals/insurancemanagement/insurancecompany/add/",
              "/master/generals/insurancemanagement/insurancecompany/edit/",
              "/master/generals/insurancemanagement/insurancecompany/view/",
            ],
          },
          {
            id: 2,
            name: "Line of Business",
            path: "/master/generals/insurancemanagement/lineofbusiness",
            includes: [
              "/master/generals/insurancemanagement/lineofbusiness",
              "/master/generals/insurancemanagement/lineofbusiness/add/",
              "/master/generals/insurancemanagement/lineofbusiness/edit/",
              "/master/generals/insurancemanagement/lineofbusiness/view/",
            ],
          },
          {
            id: 3,
            name: "Product",
            path: "/master/generals/insurancemanagement/productmaster",
            includes: [
              "/master/generals/insurancemanagement/productmaster",
              "/master/generals/insurancemanagement/productmaster/add/",
              "/master/generals/insurancemanagement/productmaster/edit/",
              "/master/generals/insurancemanagement/productmaster/view/",
            ],
          },
          {
            id: 5,
            name: "Cover",
            path: "/master/generals/insurancemanagement/cover",
            includes: [
              "/master/generals/insurancemanagement/cover",
              "/master/generals/insurancemanagement/cover/add/",
              "/master/generals/insurancemanagement/cover/view/",
              "/master/generals/insurancemanagement/cover/edit/",
            ],
          },
          {
            id: 6,
            name: "Signatories",
            path: "/master/generals/insurancemanagement/signatories",
            includes: [
              "/master/generals/insurancemanagement/signatories",
              "/master/generals/insurancemanagement/signatories/add/",
              "/master/generals/insurancemanagement/signatories/edit/",
              "/master/generals/insurancemanagement/signatories/view/",
            ],
          },
          {
            id: 7,
            name: "Vehicle",
            path: "/master/generals/insurancemanagement/vehicle",
            includes: [
              "/master/generals/insurancemanagement/vehicle",
              "/master/generals/insurancemanagement/vehicle/add/",
              "/master/generals/insurancemanagement/vehicle/edit/",
              "/master/generals/insurancemanagement/vehicle/view/",
            ],
          },
          {
            id: 12,
            name: "Reinsurance Treaty",
            path: "/master/reinsurance/treaty",
            includes: [
              "/master/reinsurance/treaty",
              "/master/reinsurance/treaty/add",
              "/master/reinsurance/treaty/edit",
              "/master/reinsurance/treaty/view",
            ],
          },
        ],
      },
      {
        id: 3,
        name: "Location",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Country",
            path: "/master/generals/location/country",
            includes: [
              "/master/generals/location/country",
              "/master/generals/location/country/add",
              "/master/generals/location/country/edit",
              "/master/generals/location/country/view",
            ],
          },
          {
            id: 2,
            name: "State",
            path: "/master/generals/location/state",
            includes: [
              "/master/generals/location/state",
              "/master/generals/location/state/add",
              "/master/generals/location/state/edit",
              "/master/generals/location/state/view",
            ],
          },
          {
            id: 3,
            name: "City",
            path: "/master/generals/location/city",
            includes: [
              "/master/generals/location/city",
              "/master/generals/location/city/add",
              "/master/generals/location/city/edit",
              "/master/generals/location/city/view",
            ],
          },
        ],
      },
      {
        id: 5,
        name: "Employee Management",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Hierarchy",
            path: "/master/generals/employeemanagement/hierarchy",
            includes: [
              "/master/generals/employeemanagement/hierarchy",
              "/master/generals/employeemanagement/hierarchy/add",
              "/master/generals/employeemanagement/hierarchy/edit/",
              "/master/generals/employeemanagement/hierarchy/view/",
            ],
          },
          {
            id: 2,
            name: "Designation",
            path: "/master/generals/employeemanagement/designation",
            includes: [
              "/master/generals/employeemanagement/designation",
              "/master/generals/employeemanagement/designation/add/",
              "/master/generals/employeemanagement/designation/edit/",
              "/master/generals/employeemanagement/designation/view/",
            ],
          },
        ],
      },
      {
        id: 6,
        name: "User Management",
        section: true,
        submenu: [
          {
            id: 1,
            name: "User",
            path: "/master/generals/usermanagement/user",
            includes: [
              "/master/generals/usermanagement/user",
              "/master/generals/usermanagement/user/add",
              "/master/generals/usermanagement/user/edit/",
              "/master/generals/usermanagement/user/view/",
            ],
          },
          {
            id: 2,
            name: "Role",
            path: "/master/generals/usermanagement/role",
            includes: [
              "/master/generals/usermanagement/role",
              "/master/generals/usermanagement/role/add/",
              "/master/generals/usermanagement/role/edit/",
              "/master/generals/usermanagement/role/view/",
            ],
          },
          {
            id: 3,
            name: "User Access Matrix",
            path: "/master/generals/usermanagement/access-matrix",
            includes: ["/master/generals/usermanagement/access-matrix"],
          },
          {
            id: 4,
            name: "Role Permissions",
            path: "/master/generals/usermanagement/role-permissions",
            includes: ["/master/generals/usermanagement/role-permissions"],
          },
          {
            id: 5,
            name: "Authority Matrix",
            path: "/master/generals/usermanagement/authority-matrix",
            includes: ["/master/generals/usermanagement/authority-matrix"],
          },
          {
            id: 6,
            name: "Delegations",
            path: "/master/generals/usermanagement/delegations",
            includes: ["/master/generals/usermanagement/delegations"],
          },
          {
            id: 7,
            name: "Segregation of Duties",
            path: "/master/generals/usermanagement/segregation-of-duties",
            includes: ["/master/generals/usermanagement/segregation-of-duties"],
          },
          {
            id: 8,
            name: "Access Reviews",
            path: "/master/generals/usermanagement/access-reviews",
            includes: ["/master/generals/usermanagement/access-reviews"],
          },
        ],
      },
      {
        id: 2,
        name: "Finance",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Account Determination",
            path: "/master/finance/account-determination",
            includes: [
              "/master/finance/account-determination",
              "/master/finance/premium-account-setup",
              "/master/finance/miscellaneous-account-setup",
              "/master/finance/customer-account-setup",
              "/master/finance/ri-claim-account-setup",
            ],
          },
          {
            id: 2,
            name: "Posting Rules",
            path: "/master/finance/posting-rules",
            includes: ["/master/finance/posting-rules"],
          },
          {
            id: 3,
            name: "Configuration Approvals",
            path: "/master/finance/configuration-approvals",
            includes: ["/master/finance/configuration-approvals"],
          },
          {
            id: 4,
            name: "Accounting Flow",
            path: "/master/finance/accounting-flow",
            includes: ["/master/finance/accounting-flow"],
          },
          {
            // packaged products: bundles sold under one master policy, and each insurer's rates for comparisons
            id: 41,
            name: "Package Bundles",
            path: "/master/finance/package-bundles",
            includes: ["/master/finance/package-bundles"],
          },
          {
            id: 42,
            name: "Insurer Rate Tables",
            path: "/master/finance/insurer-rate-tables",
            includes: ["/master/finance/insurer-rate-tables"],
          },
          {
            // premium tax and charge engine: VAT or premium tax, DST, FST and the local government tax per city
            id: 43,
            name: "Premium Taxes & LGU Rates",
            path: "/master/finance/premium-taxes",
            includes: ["/master/finance/premium-taxes"],
          },
          {
            id: 44,
            name: "Payment Gateways",
            path: "/master/finance/payment-gateways",
            includes: ["/master/finance/payment-gateways"],
          },
          {
            id: 40,
            name: "Commission Rate Matrix",
            path: "/master/finance/commission-rate-matrix",
            includes: ["/master/finance/commission-rate-matrix"],
          },
          {
            id: 13,
            name: "Transaction Code",
            path: "/master/finance/transactioncode",
            includes: [
              "/master/finance/transactioncode",
              "/master/finance/transactioncode/addtransactioncode",
              "/master/finance/transactioncode/transactioncodeedit",
              "/master/finance/transactioncode/transactioncodedetails",
            ],
          },
          {
            id: 14,
            name: "Currency",
            path: "/master/finance/currency",
            includes: [
              "/master/finance/currency",
              "/master/finance/currency/addcurrency",
              "/master/finance/currency/editcurrency",
              "/master/finance/currency/viewcurrency",
            ],
          },
          {
            id: 15,
            name: "Exchange Rate",
            path: "/master/finance/exchangerate",
            includes: [
              "/master/finance/exchangerate",
              "/master/finance/exchangerate/addexchange",
              "/master/finance/exchangerate/saveandeditexchange",
              "/master/finance/exchangerate/viewexchange",
            ],
          },
          {
            id: 16,
            name: "Bank",
            path: "/master/finance/bank",
            includes: [
              "/master/finance/bank",
              "/master/finance/bank/addbankmaster",
              "/master/finance/bank/accountdataview",
              "/master/finance/bank/accountdataview/addaccountdetail",
              "/master/finance/bank/accountdataview/viewaccountdetail",
              "/master/finance/bank/accountdataview/editaccountdetail",
            ],
          },
          {
            id: 5,
            name: "Account Category",
            path: "/master/finance/accountcategory",
            includes: ["/master/finance/accountcategory"],
          },
          {
            id: 6,
            name: "Main Account",
            path: "/master/finance/mainaccount",
            includes: [
              "/master/finance/mainaccount",
              "/master/finance/mainaccount/addmainaccount",
              "/master/finance/mainaccount/editmainaccount",
              "/master/finance/mainaccount/viewmainaccount",
            ],
          },
          {
            id: 7,
            name: "Sub Account",
            path: "/master/finance/subaccount",
            includes: [
              "/master/finance/subaccount",
              "/master/finance/subaccount/subaccountedit",
              "/master/finance/subaccount/subaccountdetails",
            ],
          },
          {
            id: 8,
            name: "Taxation",
            path: "/master/finance/taxation",
            includes: ["/master/finance/taxation"],
          },
          {
            id: 20,
            name: "Close Checklist",
            path: "/master/finance/close-checklist",
            includes: ["/master/finance/close-checklist"],
          },
          {
            id: 21,
            name: "Bank Statement Formats",
            path: "/master/finance/bank-statement-formats",
            includes: ["/master/finance/bank-statement-formats"],
          },
          {
            id: 22,
            name: "Bank Transaction Types",
            path: "/master/finance/bank-transaction-types",
            includes: ["/master/finance/bank-transaction-types"],
          },
          {
            id: 23,
            name: "Insurer Statement Formats",
            path: "/master/finance/insurer-statement-formats",
            includes: ["/master/finance/insurer-statement-formats"],
          },
          {
            id: 10,
            name: "Remittance Master",
            path: "/master/finance/remittance",
            includes: [
              "/master/finance/remittance",
              "/master/finance/remittance/automatedremittance/add",
              "/master/finance/remittance/automatedremittance/edit",
              "/master/finance/remittance/automatedremittance/view",
              "/master/finance/remittance/statementtemplate/add",
              "/master/finance/remittance/statementtemplate/edit",
              "/master/finance/remittance/statementtemplate/view",
              "/master/finance/remittance/settlementparameter/add",
              "/master/finance/remittance/settlementparameter/edit",
              "/master/finance/remittance/settlementparameter/view",
              "/master/finance/remittance/bulkprocessingmaster/add",
              "/master/finance/remittance/bulkprocessingmaster/edit",
              "/master/finance/remittance/bulkprocessingmaster/view",
              "/master/finance/remittance/exceptionmaster/add",
              "/master/finance/remittance/exceptionmaster/edit",
              "/master/finance/remittance/exceptionmaster/view",
              "/master/finance/remittance/agencybillmaster/add",
              "/master/finance/remittance/agencybillmaster/edit",
              "/master/finance/remittance/agencybillmaster/view",
              "/master/finance/remittance/adjustmentmaster/add",
              "/master/finance/remittance/adjustmentmaster/edit",
              "/master/finance/remittance/adjustmentmaster/view",
              "/master/finance/remittance/notificationmaster/add",
              "/master/finance/remittance/notificationmaster/edit",
              "/master/finance/remittance/notificationmaster/view",
            ],
          },
          {
            id: 11,
            name: "Incentive Programs",
            path: "/master/incentive/programs/view",
            includes: [
              "/master/incentive/programs/add",
              "/master/incentive/programs/edit",
              "/master/incentive/programs/view",
            ],
          },
        ],
      },
      {
        // system parameters, numbering, schedules, audit trail and the e-mail outbox
        name: "System Configuration",
        section: true,
        submenu: [
          {
            id: 0,
            name: "System Settings",
            path: "/master/configuration/system-settings",
            includes: ["/master/configuration/system-settings"],
          },
          {
            id: 20,
            name: "Configuration",
            path: "/master/configuration/settings",
            includes: ["/master/configuration/settings"],
          },
          {
            id: 23,
            name: "Document Numbering",
            path: "/master/configuration/document-numbering",
            includes: ["/master/configuration/document-numbering"],
          },
          {
            id: 21,
            name: "Schedules",
            path: "/master/configuration/schedules",
            includes: ["/master/configuration/schedules"],
          },
          {
            id: 22,
            name: "Audit Trail",
            path: "/master/configuration/audit-trail",
            includes: ["/master/configuration/audit-trail"],
          },
          {
            id: 24,
            name: "E-mail Outbox",
            path: "/master/configuration/email-outbox",
            includes: ["/master/configuration/email-outbox"],
          },
        ],
      },
      {
        id: 25,
        name: "Data Privacy",
        section: true,
        submenu: [
          {
            id: 1,
            name: "Data Subject Requests",
            path: "/master/data-privacy/requests",
            includes: ["/master/data-privacy/requests"],
          },
          {
            id: 2,
            name: "Consent Register",
            path: "/master/data-privacy/consents",
            includes: ["/master/data-privacy/consents"],
          },
        ],
      },
      {
        // configuration and migration workbooks loaded before go-live
        name: "Go-Live and Data",
        section: true,
        submenu: [
          {
            id: 26,
            name: "Go-Live Data Load",
            path: "/master/go-live-data-load",
            includes: ["/master/go-live-data-load"],
          },
        ],
      },
    ],
  },
  {
    name: "Product Configurator",
    icon: "pi pi-sliders-h",
    submenu: [
      {
        id: 1,
        name: "Dashboard",
        path: "/product-configurator/dashboard",
        includes: ["/product-configurator/dashboard"],
        permissions: ["read:product-configurator-dashboard"],
      },
      {
        id: 2,
        name: "Product Templates",
        path: "/product-configurator/templates",
        includes: [
          "/product-configurator/templates",
          "/product-configurator/template/",
          "/product-configurator/create",
        ],
        permissions: ["read:product-templates"],
      },
      {
        id: 3,
        name: "Coverage Builder",
        path: "/product-configurator/coverages",
        includes: ["/product-configurator/coverages"],
        permissions: ["read:product-coverages"],
      },
      {
        id: 4,
        name: "Rating Engine",
        path: "/product-configurator/rating",
        includes: ["/product-configurator/rating"],
        permissions: ["read:product-rating"],
      },
      {
        id: 5,
        name: "Acceptance Rules",
        path: "/product-configurator/underwriting",
        includes: ["/product-configurator/underwriting"],
        permissions: ["read:product-underwriting"],
      },
      {
        id: 6,
        name: "Document Manager",
        path: "/product-configurator/documents",
        includes: ["/product-configurator/documents"],
        permissions: ["read:product-documents"],
      },
      {
        id: 8,
        name: "Market Mapping",
        path: "/product-configurator/market-mapping",
        includes: ["/product-configurator/market-mapping"],
        permissions: ["read:product-market-mapping"],
      },
      {
        id: 10,
        name: "Risk Mapping",
        path: "/product-configurator/risk-mapping",
        includes: [
          "/product-configurator/risk-mapping",
          "/product-configurator/risk-mapping/",
        ],
        permissions: [
          "read:product-risk-mapping",
          "read:product-templates",
        ],
      },
      {
        id: 9,
        name: "Product Analytics",
        path: "/product-configurator/analytics",
        includes: ["/product-configurator/analytics"],
        permissions: ["read:product-analytics"],
      },
    ],
  },
];
