/**
 * Upload templates: one workbook per upload the platform accepts, built from the importer's own column list (the
 * *_UPLOAD_COLUMNS specifications, the master type definitions, the GENERIC bank statement format and the remittance
 * bulk-processing configuration), so a template changes when the importer does.
 *
 * Workbook: "Data" (header row; required columns have dark red headers; sample rows), "Columns" (required, format,
 * allowed values, example, other accepted headers) and "Instructions" (screen, file types, row limit, errors).
 * Used by scripts/build-upload-templates.js (docs/templates) and the template download routes.
 */
import { writeXlsx } from '../../lib/xlsx.js';
import { csvCell } from '../../lib/csv.js';
import { LEAD_UPLOAD_COLUMNS } from '../leads/service.js';
import { QUOTE_UPLOAD_COLUMNS } from '../quotations/service.js';
import { POLICY_UPLOAD_COLUMNS } from '../policies/service.js';
import { RECEIPT_UPLOAD_COLUMNS } from '../receipts/service.js';
import { OPEN_ITEM_COLUMNS } from '../receipts/opening.js';
import { DISBURSEMENT_UPLOAD_COLUMNS } from '../disbursements/service.js';
import { ACCOUNT_UPLOAD_COLUMNS } from '../accounting/service.js';
import { OPENING_BALANCE_COLUMNS } from '../period-end/opening.js';
import { uploadColumns } from '../masters/service.js';
import { masterTemplateInfo } from '../masters/uploadSamples.js';
import { COLUMN_KEYS } from '../bank-reconciliation/statements.js';

const XLSX_OR_CSV = 'XLSX (the first sheet, Data, is read) or CSV saved as UTF-8. The first row must be the column headers.';
const IMPORT_ROWS = 'Up to 20,000 data rows per file (IMPORT_MAX_ROWS) and 10 MB (IMPORT_MAX_MB).';
const BULK_ROWS = 'Up to 1,000 data rows per file (Configuration setting limits.bulk_upload_max_rows) and 10 MB.';
const ROW_BY_ROW = 'Each row is checked and saved on its own. The result lists the rows that failed with their row number (as in the spreadsheet) and the reason; the other rows are saved. Fix the failed rows and upload only those rows again, otherwise the saved rows are created a second time.';
const ALL_OR_NOTHING = 'The whole file is checked first. If any row has an error, nothing is saved and every error is listed with its row number. Fix the file and upload it again.';

/** "Yes" / "No" / "Conditional: ..." for the Columns sheet. */
export const requiredText = (c) => (c.required === true ? 'Yes' : c.required ? `Conditional: ${c.required}` : 'No');

/** Build the three-sheet workbook of one upload definition. */
export function templateWorkbook(def) {
  const cols = def.columns;
  const data = {
    name: 'Data', autoFilter: false,
    columns: cols.map((c) => ({ header: c.header, required: c.required === true, width: Math.max(14, Math.min(42, String(c.header).length + 6)), type: 'text' })),
    rows: (def.samples || []).map((s) => cols.map((c) => (s[c.key] === undefined || s[c.key] === null ? '' : String(s[c.key])))),
  };
  const columns = {
    name: 'Columns', autoFilter: false,
    columns: [{ header: 'Column', width: 28 }, { header: 'Required', width: 28, type: 'wrap' }, { header: 'Format', width: 60, type: 'wrap' },
      { header: 'Allowed values', width: 40, type: 'wrap' }, { header: 'Example', width: 28 }, { header: 'Other accepted headers', width: 36, type: 'wrap' }],
    rows: cols.map((c) => [c.header, requiredText(c), c.format || 'Text', (c.allowed || []).join(', '), c.example ?? (def.samples?.[0]?.[c.key] || ''),
      [...new Set([c.key, ...(c.aliases || [])].filter((a) => a && a !== c.header))].join(', ')]),
  };
  const required = cols.filter((c) => c.required === true).map((c) => c.header);
  const conditional = cols.filter((c) => c.required && c.required !== true).map((c) => `${c.header} (${c.required})`);
  const rows = [
    ['Template', def.title],
    ['Upload on', def.menu],
    ['API route', def.route],
    ['File types', def.fileTypes || XLSX_OR_CSV],
    ['Row limit', def.maxRows || IMPORT_ROWS],
    ['Required columns', `${required.length ? `${required.join(', ')} (dark red headers on the Data sheet).` : 'None always required.'}${conditional.length ? ` Conditional: ${conditional.join('; ')}.` : ''} Other columns may be left empty or removed.`],
    ['Header row', 'Keep row 1 of the Data sheet. Column order does not matter; headers are matched without regard to case, spaces or punctuation. The Columns sheet lists other header names that are also accepted.'],
    ['Sample rows', 'The rows under the header on the Data sheet are samples. Delete them before you upload your own data.'],
    ['Dates and amounts', 'Enter dates as YYYY-MM-DD and amounts as plain numbers (no peso sign, no thousands separator). The Data sheet cells are formatted as text so that Excel keeps what you type.'],
    ['What happens on errors', def.onError || ROW_BY_ROW],
    ...(def.notes || []).map((n, i) => [i ? '' : 'Notes', n]),
    ['Source', 'Generated by backend/scripts/build-upload-templates.js from the column list the importer itself uses. Do not rename the headers.'],
  ];
  const instructions = { name: 'Instructions', autoFilter: false, freeze: false, columns: [{ header: 'Item', width: 24 }, { header: 'Detail', width: 120, type: 'wrap' }], rows };
  return writeXlsx({ sheets: [data, columns, instructions], title: def.title, creator: 'BrokerVerse' });
}

/** CSV of the Data sheet (header and samples) for uploads that read CSV only. */
export const templateCsv = (def) => [def.columns.map((c) => c.header), ...(def.samples || []).map((s) => def.columns.map((c) => s[c.key] ?? ''))]
  .map((r) => r.map((v) => csvCell(String(v))).join(',')).join('\r\n');

const fileBase = (label) => String(label).replace(/&/g, 'and').replace(/[^A-Za-z0-9]+/g, '_').replace(/^_|_$/g, '');

// ---------- definitions that need no database ----------

/** Uploads whose columns are fixed in code. */
export function staticUploads() {
  return [
    {
      id: 'leads', file: 'Leads_Upload_Template.xlsx', title: 'Leads upload', menu: 'Operations > Leads/Prospects > Bulk Upload', route: 'POST /api/leads/bulk-upload (multipart field "file")',
      columns: LEAD_UPLOAD_COLUMNS, maxRows: IMPORT_ROWS,
      samples: [
        { firstName: 'Maria', lastName: 'Santos', DOB: '1988-04-12', gender: 'Female', emailId: 'maria.santos@example.ph', contactNumber: '09171234567', houseNo: '12 Mabini St.', barangay: 'San Antonio',
          city: 'Pasig City', province: 'Metro Manila', country: 'Philippines', zipCode: '1600', leadCategory: 'Retail', taxInformationNumber: '123-456-789-000', lob: 'MOTOR', source: 'Referral' },
        { companyName: 'Luzon Agri Ventures Corp.', emailId: 'admin@luzonagri.example.ph', contactNumber: '+63 45 961 2233', houseNo: 'Km 78 MacArthur Highway', barangay: 'Dolores',
          city: 'San Fernando', province: 'Pampanga', country: 'Philippines', zipCode: '2000', leadCategory: 'Corporate', taxInformationNumber: '009-876-543-000', lob: 'FIRE', source: 'Walk-in' },
      ],
      notes: ['A lead needs a First Name (individual) or a Company Name (corporate).'],
    },
    {
      id: 'quotations', file: 'Quotations_Upload_Template.xlsx', title: 'Quotations upload', menu: 'Operations > Quotation > Bulk Upload', route: 'POST /api/quotations/bulk-upload (multipart field "file")',
      columns: QUOTE_UPLOAD_COLUMNS, maxRows: IMPORT_ROWS,
      samples: [
        { firstName: 'Jose', lastName: 'Reyes', emailId: 'jose.reyes@example.ph', contactNumber: '09189876543', productType: 'Motor', insurancePolicyType: 'PC', insuranceCompanyName: 'Malayan Insurance Co., Inc.',
          totalSumInsured: '980000', lossAndDamageCoverage: '980000', lossAndDamageCoverageRate: '1.5', discount: '0', remarks: 'Moving from another broker' },
      ],
      notes: ['With a Lead Id the quotation is added to that lead; without it a new lead is created from the name columns. Premiums are recalculated by BrokerVerse from the rate and the tariff.'],
    },
    {
      id: 'policies', file: 'Policies_Upload_Template.xlsx', title: 'Policies upload', menu: 'Operations > Policy > Bulk Upload', route: 'POST /api/policies/bulk-upload (multipart field "file"; mode=go-live for in-force policies of the old system)',
      columns: POLICY_UPLOAD_COLUMNS, maxRows: IMPORT_ROWS,
      samples: [
        { policyNumber: 'PC-MLY-2026-000101', insuredName: 'Maria Santos', firstName: 'Maria', lastName: 'Santos', emailId: 'maria.santos@example.ph', contactNumber: '09171234567', productType: 'Motor',
          insuranceCompanyName: 'Malayan Insurance Co., Inc.', inception: '2026-10-01', expiry: '2027-10-01', issuedDate: '2026-09-28', sumInsured: '1250000', netPremium: '28750', grossPremium: '35946.88',
          plateNumber: 'NCA 4521', paymentStatus: 'Pending' },
        { policyNumber: 'FPG-FI-2026-004417', insuredName: 'Visayas Cold Storage Inc.', companyName: 'Visayas Cold Storage Inc.', emailId: 'finance@visayascold.example.ph', contactNumber: '+63 32 238 7700',
          productType: 'Fire', insuranceCompanyName: 'FPG Insurance Co., Inc.', inception: '2026-08-15', expiry: '2027-08-15', issuedDate: '2026-08-10', sumInsured: '25000000', netPremium: '62500',
          grossPremium: '78437.50', paymentStatus: 'Partial' },
      ],
      notes: [
        'New business: each row creates the client, the policy with its insurer at 100%, the premium bill and its booking journal, and accrues the commission.',
        'Go-live migration of in-force policies: tick "Existing policies (go-live)" on the upload screen (API: mode=go-live). The client and policy are created without a bill, journal or commission; load the unpaid premiums with the Open Items template and the GL balances with the Opening Balances template.',
        'Each row creates a new client, even if the same client appears on several rows. Co-insured policies (several insurers) cannot be uploaded; enter them on the screen.',
      ],
    },
    {
      id: 'receipts', file: 'Receipts_Upload_Template.xlsx', title: 'Official receipts upload', menu: 'Accounts > Receipts > Bulk upload', route: 'POST /api/receipts/bulk-upload (multipart field "file")',
      columns: RECEIPT_UPLOAD_COLUMNS, maxRows: BULK_ROWS,
      samples: [{ policyNumber: 'PC-MLY-2026-000101', amount: '35946.88', receiptDate: '2026-10-05', paymentMode: 'bank-transfer', referenceNo: 'BDO-778812', remarks: 'Full payment' }],
      notes: ['Each row issues an official receipt, applies it to the oldest open bills of the policy and posts the collection journal. The receipt date must fall in an open accounting period.'],
    },
    {
      id: 'disbursements', file: 'Disbursements_Upload_Template.xlsx', title: 'Payment vouchers upload', menu: 'Accounts > Disbursement > Bulk upload', route: 'POST /api/disbursements/bulk-upload (multipart field "file")',
      columns: DISBURSEMENT_UPLOAD_COLUMNS, maxRows: BULK_ROWS,
      samples: [{ voucherDate: '2026-10-06', payeeType: 'Insurer', insurerName: 'Malayan Insurance Co., Inc.', policyNumber: 'PC-MLY-2026-000101', amount: '28120.50', paymentMode: 'check',
        transactionDescription: 'Premium remittance October 2026', remarks: 'Net of commission' }],
      notes: ['Each row creates a draft payment voucher. Vouchers are then approved and paid on the Disbursement screen (maker-checker).'],
    },
    {
      id: 'chart-of-accounts', file: 'Chart_of_Accounts_Upload_Template.xlsx', title: 'Chart of accounts upload (add or update accounts)', menu: 'Master > Finance > Main Account > Upload',
      route: 'POST /api/accounting/accounts/upload (multipart field "file")', columns: ACCOUNT_UPLOAD_COLUMNS, maxRows: BULK_ROWS,
      samples: [
        { code: '4401030', name: 'Training and Seminars', accountType: 'expense', fsGroup: 'Operating Expenses', category: 'Operating Expenses', normalBalance: 'debit', isOpenItem: 'No', allowManual: 'Yes', status: 'active', description: 'Staff training, including Insurance Commission seminars' },
        { code: '4401030001', name: 'Training – Compliance Seminars', accountType: 'expense', parentCode: '4401030', fsGroup: 'Operating Expenses', category: 'Operating Expenses', normalBalance: 'debit', isOpenItem: 'No', allowManual: 'Yes', status: 'active', description: 'Seminars required by the Insurance Commission' },
      ],
      notes: ['BrokerVerse ships a Philippine broker chart of accounts. Use this upload to add your own accounts or rename existing ones; an existing Account Code updates that account. Put a main account before its sub accounts. Accounts used by the system settings cannot be deactivated here.'],
    },
    {
      id: 'opening-balances', file: 'Opening_Balances_Upload_Template.xlsx', title: 'GL opening balances (go-live trial balance)', menu: 'Accounts > Period End > Period Management > Import opening balances',
      route: 'POST /api/period-end/opening-balances/import (multipart field "file" and field goLiveDate YYYY-MM-DD)', columns: OPENING_BALANCE_COLUMNS, maxRows: IMPORT_ROWS, onError: `${ALL_OR_NOTHING} Debits must equal credits.`,
      samples: [
        { accountCode: '1102001', accountName: 'Cash in Bank – Operating Account', debit: '1250000.00' },
        { accountCode: '1102003', accountName: "Cash in Bank – Premium Trust Account (Clients' Money)", debit: '812400.00' },
        { accountCode: '1202001', accountName: 'Premiums Receivable – Direct Clients', debit: '40000.00' },
        { accountCode: '2201001', accountName: 'Premiums Payable to Insurers', credit: '652400.00' },
        { accountCode: '2204001', accountName: 'Expanded Withholding Tax Payable (BIR 1601-EQ)', credit: '18500.00' },
        { accountCode: '5100001', accountName: 'Capital Stock – Common', credit: '1000000.00' },
        { accountCode: '5101001', accountName: 'Retained Earnings', credit: '431500.00' },
      ],
      notes: [
        'Enter the trial balance of the old system at the close of the day before the go-live date, one row per account with a balance.',
        'The balances are loaded into the fiscal year that contains the go-live date and are read by the financial statements, trial balance, GL detail and bank reconciliation of Accounts > Period End. No journal is posted. The year-end close carries them forward.',
        'Loading again with the same go-live date replaces the earlier load. A fiscal year with journals posted before the go-live date, or with balances carried forward by a year-end close, is refused.',
        'The Premiums Receivable balance should equal the total Open Balance of the Open Items upload.',
      ],
    },
    {
      id: 'open-items', file: 'Open_Items_Upload_Template.xlsx', title: 'Open premium receivables (go-live open items)', menu: 'Accounts > Collections > Import open items',
      route: 'POST /api/receipts/opening-items/import (multipart field "file" and field goLiveDate YYYY-MM-DD)', columns: OPEN_ITEM_COLUMNS, maxRows: BULK_ROWS,
      onError: `${ROW_BY_ROW.replace(' Fix the failed rows and upload only those rows again, otherwise the saved rows are created a second time.', '')} Rows already loaded for the same go-live date are skipped, so the corrected file can be uploaded again as a whole.`,
      samples: [{ policyNumber: 'FPG-FI-2026-004417', billReference: 'DN-2026-08812', dueDate: '2026-10-31', originalAmount: '78437.50', openBalance: '40000.00' }],
      notes: [
        'Load the in-force policies first (Policies template, go-live mode). Each row becomes an open bill of the policy: it ages, appears in Collections and is paid with an official receipt like any other bill.',
        'No journal is posted: the GL carries these bills in the opening balance of the premiums receivable account.',
      ],
    },
    {
      id: 'remittance-bank-transactions', file: 'Remittance_Bank_Transactions_Template.xlsx', csv: 'Remittance_Bank_Transactions_Template.csv', title: 'Remittance reconciliation: bank transactions',
      menu: 'Accounts > Remittance > Reconciliation > Import', route: 'The screen reads the CSV in the browser and sends POST /api/remittance/reconciliation/bank-transactions',
      fileTypes: 'CSV only (use the .csv file). Plain values: no commas inside a value, no quotes.', maxRows: 'No fixed limit; keep one bank statement period per file.',
      onError: 'The whole file is refused if a row has no date, reference or amount. Lines whose reference is already on file are skipped.',
      columns: [
        { key: 'transDate', header: 'TransDate', aliases: ['date', 'transaction date'], required: true, format: 'Date YYYY-MM-DD', example: '2026-10-07' },
        { key: 'reference', header: 'Reference', aliases: ['ref'], required: true, format: 'Bank reference of the credit', example: 'PSN-889201' },
        { key: 'amount', header: 'Amount', required: true, format: 'Amount in PHP; negative for a debit', example: '38250' },
        { key: 'description', header: 'Description', aliases: ['narration'], format: 'Text without commas', example: 'PESONet credit Malayan Insurance' },
      ],
      samples: [{ transDate: '2026-10-07', reference: 'PSN-889201', amount: '38250', description: 'PESONet credit Malayan Insurance' }],
      notes: ['These lines are matched to approved remittances on the same screen (Auto Match or Match).'],
    },
    {
      id: 'users', file: 'Users_Provisioning_Template.xlsx', csv: 'Users_Provisioning_Template.csv', title: 'Users (named users and their roles)',
      menu: 'Not a screen upload: run by the System Administrator on the server with backend/scripts/provision-users.js (dry run first, then CONFIRM_PROVISION=yes). Single users are added in Master > Generals > User Management > User.',
      route: 'node scripts/provision-users.js /secure/path/users.csv', fileTypes: 'CSV only. Keep the file outside the repository and delete it after use: it holds initial passwords.',
      maxRows: 'No fixed limit.', onError: 'The script runs in one transaction: an unknown role stops it and nothing is changed.',
      columns: [
        { key: 'name', header: 'name', required: true, format: 'Display name', example: 'Andrea Lim' },
        { key: 'username', header: 'username', required: true, format: 'Sign-in name; stored in lower case', example: 'alim' },
        { key: 'password', header: 'password', required: true, format: 'Initial password (8+ characters with upper case, lower case, digit and symbol); the user must change it at the first sign-in', example: '' },
        { key: 'role', header: 'role', required: true, format: 'Role code', allowed: ['system-admin', 'sales', 'processing', 'operations', 'claims', 'accounting', 'accounting-manager'], example: 'accounting' },
        { key: 'email', header: 'email', format: 'E-mail address (password reset codes are sent here)', example: 'andrea.lim@example.ph' },
      ],
      samples: [{ name: 'Andrea Lim', username: 'alim', password: '', role: 'accounting', email: 'andrea.lim@example.ph' }],
      notes: ['The password column is left empty in the template on purpose. Fill it in only in the copy kept outside the repository, and hand each password to its user privately.', 'An existing username is updated: its role is replaced and the password reset.'],
    },
  ];
}

// ---------- definitions read from the database (master types, statement format, remittance configuration) ----------

/** Upload definition of a master type (raw master_types row). */
export function masterUpload(t, { maxRows = BULK_ROWS, withSamples = true } = {}) {
  const info = masterTemplateInfo(t.code) || {};
  const columns = uploadColumns(t).map((c) => ({ ...c, ...(info.formats?.[c.key] ? { format: info.formats[c.key] } : {}), example: info.samples?.[0]?.[c.key] ?? '' }));
  return {
    id: `master:${t.code}`, file: `${fileBase(t.label)}_Upload_Template.xlsx`, title: `${t.label} master upload`, menu: `${info.menu || `Master > ${t.label}`} > Upload`,
    route: `POST /api/masters/${t.code}/upload (multipart field "file")`, columns, maxRows: typeof maxRows === 'number' ? `Up to ${maxRows.toLocaleString('en-US')} data rows per file and 10 MB.` : maxRows,
    samples: withSamples ? info.samples || [] : [],
    notes: [
      'Each row creates a new record, checked exactly like Add on the screen. A row whose code already exists is refused (edit existing records on the screen).',
      ...(uploadColumns(t).some((c) => /existing .* record/.test(c.format)) ? ['Linked columns take the name (or code) of a record that already exists in the linked master; upload the linked master first.'] : []),
      ...(info.notes || []),
    ],
  };
}

/** Workbook of one master type (template download on the master screens). */
export function masterTemplate(t, opts = {}) {
  const def = masterUpload(t, { maxRows: opts.maxRows, withSamples: opts.withSamples !== false });
  return { fileName: def.file, buffer: templateWorkbook(def) };
}

const titleCase = (s) => String(s).replace(/\b[a-z]/g, (ch) => ch.toUpperCase());

/** Bank statement upload from a statement format row (GENERIC): first alternative of each mapped column. */
export function statementUpload(format) {
  const map = format.columns || {};
  const REQ = { date: true, description: 'Description or Reference', reference: 'Description or Reference', debit: 'Debit or Credit on each line', credit: 'Debit or Credit on each line' };
  const FORMAT = { date: `Date ${format.date_format}`, valueDate: `Date ${format.date_format}`, description: 'Text as printed on the statement', reference: 'Cheque number or bank reference',
    debit: 'Money out of the account (withdrawal, cheque, charge), no sign', credit: 'Money into the account (deposit, transfer in), no sign', balance: 'Running balance after the line; lets the import check the statement' };
  const columns = COLUMN_KEYS.filter((k) => map[k] && !['amount', 'drCr'].includes(k)).map((k) => {
    const [first, ...rest] = String(map[k]).split('|');
    return { key: k, header: titleCase(first), aliases: rest, required: REQ[k] || false, format: FORMAT[k] || 'Text' };
  });
  return {
    id: 'bank-statement', file: 'Bank_Statement_Generic_Upload_Template.xlsx', title: `Bank statement (${format.name})`,
    menu: 'Accounts > Bank Reconciliation > Reconciliation Workspace > Import statement (format GENERIC)',
    route: 'POST /api/bank-reconciliation/statements/import (multipart field "file" and fields bankAccount, format=GENERIC; optional statementRef, openingBalance, closingBalance)', columns, maxRows: IMPORT_ROWS,
    onError: 'Preview first: the screen shows the lines, totals, the balance check and duplicates. The import is refused as a whole when a row cannot be read, when the statement does not balance (opening + credits - debits = closing) or when the same file was already imported for the account.',
    samples: [
      { date: '2026-10-01', valueDate: '2026-10-01', description: 'CASH DEPOSIT - COLLECTIONS', reference: 'DS-100201', credit: '35946.88', balance: '1285946.88' },
      { date: '2026-10-02', valueDate: '2026-10-02', description: 'CHECK PAYMENT MALAYAN INSURANCE', reference: 'CHK 000123', debit: '28120.50', balance: '1257826.38' },
      { date: '2026-10-03', valueDate: '2026-10-03', description: 'SERVICE CHARGE', reference: 'SC-OCT', debit: '250.00', balance: '1257576.38' },
    ],
    notes: [
      `A single signed Amount column (${map.amount || 'amount'}) may replace Debit and Credit (withdrawals negative).`,
      `Rows whose text starts with ${String(format.skip_pattern || '').replace(/^\^\(|\)$/g, '').split('|').join(', ')} are ignored (totals and balance lines).`,
      'For the BDO, BPI and Metrobank exports use the bank\'s own file with its format (BDO-SAMPLE, BPI-SAMPLE, MBT-SAMPLE) instead of this template.',
      'The opening balance is taken from the first line (balance minus amount) when not entered.',
    ],
  };
}

/** Remittance bulk upload from the bulk-processing configuration (fieldMappings). */
export function remittanceUpload(maps, configCode) {
  const FORMAT = { policy_number: 'Policy number in BrokerVerse', premium_amount: 'Premium in PHP, greater than zero', commission_amount: 'Commission in PHP, between 0 and the premium',
    tax_amount: 'Taxes in PHP', insured_name: 'Text' };
  const EXAMPLE = { policy_number: 'PC-MLY-2026-000101', premium_amount: '35946.88', commission_amount: '5750.00', tax_amount: '0', insured_name: 'Maria Santos' };
  const columns = maps.filter((m) => m.sourceField).map((m) => ({ key: m.targetField, header: m.sourceField, required: !!m.required, format: FORMAT[m.targetField] || 'Text', example: EXAMPLE[m.targetField] || '' }));
  return {
    id: 'remittance-bulk', file: 'Remittance_Bulk_Upload_Template.xlsx', title: `Remittance bulk processing (configuration ${configCode || 'default'})`,
    menu: 'Accounts > Remittance > Bulk Processing > Upload / Validate, then Process', route: `POST /api/remittance/bulk/upload (multipart field "file", configCode=${configCode || ''})`,
    columns, maxRows: 'As set on the configuration (Max Records) and 10 MB.', fileTypes: 'CSV (comma separated) or XLSX (first sheet). Headers must match exactly (case is ignored).',
    onError: 'Validation lists every row error (policy not found, premium not positive, commission above premium, duplicate policy). Process then creates draft remittances from the valid rows only.',
    samples: [Object.fromEntries(columns.map((c) => [c.key, c.example]))],
    notes: ['The columns come from the Bulk Processing master (Master > Finance > Remittance Master > Bulk Processing). Change the field mappings there and regenerate this template if your file differs.'],
  };
}

// ---------- download from the screens ----------

/** Send the workbook of a static upload definition (by id) as an attachment. */
export function sendTemplate(res, id) {
  const def = staticUploads().find((d) => d.id === id);
  if (!def) throw new Error(`Unknown template ${id}`);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="${def.file}"`);
  res.send(templateWorkbook(def));
}
