// Thailand Employee Master Mock Data

const Productdata = [
  {
    id: 1,
    employeeCode: "EMP-2025-001",
    employeeType: "Senior Agent",
    name: "Juan Dela Cruz",
    designation: "Senior Insurance Agent",
    reportingTo: "Roberto Reyes",
    modifiedBy: "Admin",
    modifiedOn: "03/28/2025",
    branch: "Makati",
    department: "Sales",
    email: "juan.delacruz@company.ph",
    contact: "+63 917 123 4567"
  },
  {
    id: 2,
    employeeCode: "EMP-2025-002",
    employeeType: "Agent",
    name: "Maria Santos",
    designation: "Insurance Agent",
    reportingTo: "Juan Dela Cruz",
    modifiedBy: "Admin",
    modifiedOn: "03/27/2025",
    branch: "Quezon City",
    department: "Sales",
    email: "maria.santos@company.ph",
    contact: "+63 918 234 5678"
  },
  {
    id: 3,
    employeeCode: "EMP-2025-003",
    employeeType: "Manager",
    name: "Roberto Reyes",
    designation: "Branch Manager",
    reportingTo: "Miguel Torres",
    modifiedBy: "Admin",
    modifiedOn: "03/26/2025",
    branch: "Makati",
    department: "Management",
    email: "roberto.reyes@company.ph",
    contact: "+63 919 345 6789"
  },
  {
    id: 4,
    employeeCode: "EMP-2025-004",
    employeeType: "Agent",
    name: "Ana Garcia",
    designation: "Junior Insurance Agent",
    reportingTo: "Maria Santos",
    modifiedBy: "Roberto Reyes",
    modifiedOn: "03/25/2025",
    branch: "Cebu",
    department: "Sales",
    email: "ana.garcia@company.ph",
    contact: "+63 920 456 7890"
  },
  {
    id: 5,
    employeeCode: "EMP-2025-005",
    employeeType: "Underwriter",
    name: "Pedro Gonzales",
    designation: "Senior Underwriter",
    reportingTo: "Carmen Bautista",
    modifiedBy: "Admin",
    modifiedOn: "03/24/2025",
    branch: "Makati",
    department: "Underwriting",
    email: "pedro.gonzales@company.ph",
    contact: "+63 921 567 8901"
  },
  {
    id: 6,
    employeeCode: "EMP-2025-006",
    employeeType: "Claims Officer",
    name: "Rosa Fernandez",
    designation: "Claims Processing Officer",
    reportingTo: "Pedro Gonzales",
    modifiedBy: "Roberto Reyes",
    modifiedOn: "03/23/2025",
    branch: "Davao",
    department: "Claims",
    email: "rosa.fernandez@company.ph",
    contact: "+63 922 678 9012"
  },
  {
    id: 7,
    employeeCode: "EMP-2025-007",
    employeeType: "Director",
    name: "Miguel Torres",
    designation: "Regional Director",
    reportingTo: "CEO",
    modifiedBy: "Admin",
    modifiedOn: "03/22/2025",
    branch: "Head Office",
    department: "Executive",
    email: "miguel.torres@company.ph",
    contact: "+63 923 789 0123"
  },
  {
    id: 8,
    employeeCode: "EMP-2025-008",
    employeeType: "Supervisor",
    name: "Carmen Bautista",
    designation: "Operations Supervisor",
    reportingTo: "Miguel Torres",
    modifiedBy: "Admin",
    modifiedOn: "03/21/2025",
    branch: "Makati",
    department: "Operations",
    email: "carmen.bautista@company.ph",
    contact: "+63 924 890 1234"
  },
  {
    id: 9,
    employeeCode: "EMP-2025-009",
    employeeType: "Agent",
    name: "Jose Rizal Santos",
    designation: "Corporate Insurance Agent",
    reportingTo: "Juan Dela Cruz",
    modifiedBy: "Roberto Reyes",
    modifiedOn: "03/20/2025",
    branch: "BGC Taguig",
    department: "Corporate Sales",
    email: "jose.santos@company.ph",
    contact: "+63 925 901 2345"
  },
  {
    id: 10,
    employeeCode: "EMP-2025-010",
    employeeType: "Accountant",
    name: "Elena Martinez",
    designation: "Finance Officer",
    reportingTo: "Carmen Bautista",
    modifiedBy: "Admin",
    modifiedOn: "03/19/2025",
    branch: "Makati",
    department: "Finance",
    email: "elena.martinez@company.ph",
    contact: "+63 926 012 3456"
  }
];

export default Productdata;