"""Content of the BrokerVerse role guides (read by build_decks.py): one deck per role of the broker role model.

Sources: brokerverse/src/utils/menuPermissions.js and components/SideBar/list.js (menus), the roles migrations
0115_role_inheritance and 0140_broker_roles (role codes, names, inheritance), report_definitions (report roles),
backend/src/db/seeds/jobs.json and the scheduled_jobs table (schedules), docs/e2e/ROLE_WALK.md (screens per role)
and the user manual (docs/manual/tools/manual_source.md) for the rules, flows and known limitations.
Screens: 'manual:<name>' is docs/manual/images/<name>.jpg, captured by docs/manual/tools/capture.py; the scene list
(docs/manual/tools/scenes.py) says which user each screen was captured as, and the captions below say so.
"""
import os
import sys

# ------------------------------------------------------------------ screens and captions
ROLE_OF = {
    'bea.admin': 'System Administrator (bea.admin)', 'maria.sales': 'Sales & Marketing (maria.sales)',
    'jose.uw': 'Processing Team (jose.uw)', 'ana.cs': 'Operations (ana.cs)', 'carlo.claims': 'Claims (carlo.claims)',
    'liza.finance': 'Accounting (liza.finance)', 'rosa.acctmgr': 'Accounting Manager',
}


def _scene_users():
    here = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, os.path.join(here, '..', '..', 'manual', 'tools'))
    try:
        import scenes
    except Exception:
        return {}
    out = {}
    for sc in getattr(scenes, 'SCENES', []) + getattr(scenes, 'LATE_SCENES', []):
        for st in sc['steps']:
            if st[0] == 'shot':
                out[st[1]] = sc['user']
    return out


SCENE_USER = _scene_users()


def shot(name, screen, crop=None):
    """A user manual screenshot with a caption that names the screen and the user it was captured as."""
    user = SCENE_USER.get(name)
    who = ROLE_OF.get(user, user)
    caption = (f'Live screen: {screen}. Signed in as {who}.' if who
               else f'Sign-in page: {screen} (example values, nothing sent to the server).')
    d = dict(shot='manual:' + name, caption=caption)
    if crop:
        d['crop'] = crop
    return d


# ------------------------------------------------------------------ broking cycle (user manual, chapter 3)
FLOW_STEPS = [
    ('Lead', 'Sales, Operations'),
    ('Broker Slip', 'Processing Team'),
    ('Quotation Slip', 'Sales, Processing'),
    ('Placement Slip', 'Processing Team'),
    ('Policy issue', 'Processing Team'),
    ('Payment capture', 'Operations, Sales, Processing'),
    ('Official receipt', 'Accounting'),
    ('Commission', 'Accounting, two users'),
    ('Remittance', 'Accounting, two users'),
    ('Endorsement', 'Operations, Processing'),
    ('Claim', 'Claims, two users'),
    ('Renewal', 'Operations, Sales, Processing'),
    ('Month-end', 'Accounting, Acct. Manager'),
]

# ------------------------------------------------------------------ reports (report_definitions, 39 reports)
# code: (name, what it shows, category, roles besides the System Administrator)
REPORTS = {
    'production-register': ('Production Register', 'Policies incepted in the period: premium, commission, new or renewal, billing mode', 'operational', ['sales', 'processing', 'operations', 'claims']),
    'premium-by-product': ('Premium by Product / Month / Insurer', 'Policy count, sum insured, premium and commission', 'operational', ['sales', 'processing', 'operations', 'claims', 'accounting']),
    'new-vs-renewal': ('New Business vs Renewals', 'New business and renewals by month or agent', 'operational', ['sales', 'processing', 'operations', 'claims', 'accounting']),
    'lead-conversion-funnel': ('Lead Conversion Funnel', 'Leads by stage with the conversion rate', 'operational', ['sales', 'processing', 'operations']),
    'placement-pipeline': ('Placement Pipeline', 'Broker Slips and Placement Slips of the period with status, lead insurer, premium and age', 'operational', ['sales', 'processing', 'operations']),
    'market-response': ('Market Response', 'Insurers approached: offers, declines, pending, response days and hit ratio', 'operational', ['sales', 'processing', 'operations']),
    'coinsurance-register': ('Co-insurance Register', "Co-insured policies with each participant's share, premium and commission", 'operational', ['sales', 'processing', 'accounting']),
    'cession-register': ('Reinsurance Cession Register', 'Cessions per treaty and policy', 'operational', ['processing', 'accounting']),
    'claims-position': ('Claims Position', 'Claims reported: estimate, approved, settled and age', 'operational', ['sales', 'processing', 'operations', 'claims']),
    'claims-ageing': ('Claims Ageing', 'Open claims by ageing bucket', 'operational', ['sales', 'processing', 'operations', 'claims']),
    'renewal-retention': ('Renewal Retention', 'Renewals due: retained, lost or pending, and the retention rate', 'operational', ['sales', 'processing', 'operations', 'claims']),
    'remittance-summary': ('Remittance Summary', 'Remittances to insurers: gross premium, commission, net due, status', 'operational', ['sales', 'processing', 'operations', 'claims', 'accounting']),
    'commission-statement': ('Broker Commission Statement', 'Commission per agent and policy: basis, rate, gross, WHT, net, paid status', 'operational', ['sales', 'processing', 'operations', 'claims', 'accounting']),
    'premium-receivable-soa': ('SOA / Premium Receivable', 'Bills issued: amount, paid, balance and age', 'financial', ['accounting', 'sales']),
    'collections-ageing': ('Receivables Ageing', 'Outstanding receivables by bucket', 'financial', ['accounting', 'sales']),
    'collections-summary': ('Collection Report', 'Bills due: billed, collected, balance, collection rate', 'financial', ['accounting']),
    'receipts-register': ('Receipts Register', 'Official receipts with bill, policy, mode, bank and reference', 'financial', ['accounting']),
    'disbursement-register': ('Payables / Disbursement Register', 'Payment vouchers with approval and paid dates', 'financial', ['accounting']),
    'direct-bill-commission': ('Commission Receivable (Direct Bill)', 'Commission and VAT due from insurers on direct-bill policies', 'financial', ['accounting']),
    'due-to-insurers-by-coinsurer': ('Due to Insurers by Co-insurer', 'Premium due to each insurer: due, collected, remitted, still held', 'financial', ['accounting']),
    'aged-payables-insurers': ('Aged Payables to Insurers', 'Premium payable to insurers not yet remitted, aged', 'financial', ['accounting']),
    'incentive-results': ('Incentive Results', 'Programme target, achieved and payout per person', 'financial', ['accounting', 'sales']),
    'journal-register': ('Journal Register', 'Journal lines with account, debit, credit, memo, status', 'financial', ['accounting']),
    'trial-balance': ('Trial Balance', 'Balance per account', 'financial', ['accounting']),
    'trial-balance-ocm': ('Trial Balance (Opening / Movement / Closing)', 'Opening, movement and closing per account', 'financial', ['accounting']),
    'gl-detail': ('General Ledger Detail', 'Every line of an account with running balance', 'financial', ['accounting']),
    'income-statement': ('Income Statement', 'Period, year to date and prior year', 'financial', ['accounting']),
    'balance-sheet': ('Balance Sheet', 'Balances against the prior year end', 'financial', ['accounting']),
    'month-end-close-status': ('Month-End Close Status', "Each period's close run and checklist result", 'financial', ['accounting']),
    'bir-vat-summary': ('VAT Summary', 'Working paper for BIR 2550M / 2550Q', 'financial', ['accounting']),
    'bir-sawt': ('SAWT', 'Tax withheld from the broker by insurers and clients', 'financial', ['accounting']),
    'bir-qap': ('QAP', 'Tax the broker withheld from its payees (1601EQ)', 'financial', ['accounting']),
    'bir-slsp-sales': ('SLSP Sales', 'Summary List of Sales', 'financial', ['accounting']),
    'bir-slsp-purchases': ('SLSP Purchases', 'Summary List of Purchases', 'financial', ['accounting']),
    'bank-reconciliation-statement': ('Bank Reconciliation Statement', 'Statement of an account as of a date', 'financial', ['accounting']),
    'bank-outstanding-cheques': ('Outstanding Cheques', 'Payments not cleared by the bank, aged', 'financial', ['accounting']),
    'bank-deposits-in-transit': ('Deposits in Transit', 'Receipts not yet on the bank statement', 'financial', ['accounting']),
    'bank-unmatched-lines': ('Unmatched Bank Lines', 'Statement lines not matched', 'financial', ['accounting']),
    'bank-book': ('Bank Book', 'Every movement of an account with running balance', 'financial', ['accounting']),
}
REPORT_GROUPS = [
    ('Production and placement', ['production-register', 'premium-by-product', 'new-vs-renewal', 'lead-conversion-funnel',
                                  'placement-pipeline', 'market-response', 'coinsurance-register', 'cession-register']),
    ('Claims and renewals', ['claims-position', 'claims-ageing', 'renewal-retention']),
    ('Insurers and commission', ['remittance-summary', 'commission-statement', 'direct-bill-commission',
                                 'due-to-insurers-by-coinsurer', 'aged-payables-insurers', 'incentive-results']),
    ('Receivables and cash', ['premium-receivable-soa', 'collections-ageing', 'collections-summary', 'receipts-register',
                              'disbursement-register']),
    ('Ledger and period end', ['journal-register', 'trial-balance', 'trial-balance-ocm', 'gl-detail', 'income-statement',
                               'balance-sheet', 'month-end-close-status']),
    ('BIR tax', ['bir-vat-summary', 'bir-sawt', 'bir-qap', 'bir-slsp-sales', 'bir-slsp-purchases']),
    ('Bank', ['bank-reconciliation-statement', 'bank-outstanding-cheques', 'bank-deposits-in-transit',
              'bank-unmatched-lines', 'bank-book']),
]


def reports_for(role):
    """Codes of the reports a role may run, in catalogue group order."""
    order = [c for _, cs in REPORT_GROUPS for c in cs]
    if role == 'system-admin':
        return order
    return [c for c in order if role in REPORTS[c][3]]


# ------------------------------------------------------------------ schedules (Master > Schedules, Manila time)
# code: (name, timing, delivered switched on)
JOBS = {
    'policy-expiry': ('Policy expiry', 'Daily 00:15', True),
    'quote-expiry': ('Quotation expiry', 'Daily 00:30', True),
    'accrual-reversal': ('Accrual auto-reversal', 'Day 1 of the month, 00:30', False),
    'recurring-journals': ('Recurring journals', 'Daily 01:15', False),
    'period-auto-soft-close': ('Period auto soft-close', 'Daily 02:00', False),
    'housekeeping': ('Housekeeping', 'Daily 02:45', True),
    'daily-reports': ('Daily reports', 'Daily 05:00', True),
    'renewal-pipeline': ('Renewal pipeline', 'Daily 05:30', True),
    'bank-auto-match': ('Bank reconciliation auto-match', 'Daily 05:45', False),
    'renewal-notices': ('Renewal notices', 'Daily 06:00', True),
    'receivable-ageing': ('Receivable ageing', 'Daily 07:00', True),
    'collection-reminders': ('Collection reminders', 'Daily 08:00', True),
    'month-end-reminder': ('Month-end close reminder', 'Daily 08:00', False),
    'email-outbox': ('E-mail outbox', 'Every 5 minutes', True),
    'renewal-queue': ('Renewal notice queue', 'Every minute', True),
    'report-schedules': ('Report schedules', 'Your own timetable', True),
}

# ------------------------------------------------------------------ support (user manual, appendix H)
SUPPORT = [
    ('First line', 'The key user of your team: how-to questions, checking that a role or setting is not the cause'),
    ('Second line', 'Your System Administrator: users, roles, passwords, two-step resets, settings and master data'),
    ('Third line', 'iorta TechNXT production support, raised by the System Administrator through the support agreement'),
]

# ------------------------------------------------------------------ menus (menuPermissions.js, SideBar/list.js)
OPS_ALL = ['Home', 'Leads/Prospects', 'Clients', 'Quotation', 'Broker Slips', 'Placement Slips', 'Policy', 'Claims',
           'Renewals (8 screens)', 'Open Items', 'Payments']
PC_ALL = ['Dashboard, Product Templates', 'Coverage Builder, Rating Engine', 'Acceptance Rules, Document Manager',
          'Approval Workflows', 'Market Mapping, Risk Mapping', 'Product Analytics']
ACC_ALL = ['Receipts, Collections', 'Accounting Query, All Clients Accounting', 'Open Entry Matching / Un-Matching',
           'Disbursement, Petty Cash (5 screens)', 'Journal Voucher, Correction JV, Reversal JV',
           'Period End (5 screens)', 'Bank Reconciliation (7 screens)', 'Tax (6 screens)', 'Remittance (16 screens)',
           'Incentive (4 screens)']
RI_ALL = ['Treaty Dashboard', 'Cession Tracking', 'Claims Recovery', 'Reconciliation', 'Analytics']
MASTER_ALL = ['System Settings, Configuration', 'Document Numbering, Schedules, Audit Trail',
              'Generals: company, branch, insurers, lines, products, covers, signatories, vehicles, locations, '
              'commission sharing, employees, users and roles',
              'Finance: account determination, posting rules, commission rate matrix, chart of accounts, currency, '
              'bank, taxation, close checklist, bank formats and types, petty cash, remittance',
              'Incentive Programs, Reinsurance Treaty']
REP_OPS = 'Operational Reports: Production, Claims, Renewal, Remittance, Broker Commission'

# ------------------------------------------------------------------ known limitations (user manual, appendix G)
LIM_TOKENS = 'The sign-in session is kept in the browser’s local storage: sign out on shared computers and keep the browser up to date.'
LIM_QR = 'Two-factor set-up shows a setup key and an app link but no QR code: type the key into the authenticator app.'
LIM_LANG = 'Filipino is configured as a language but has no screen translation yet.'
LIM_RATE = 'Sign-in and request limits are counted per application server; with several servers, add a limit at the load balancer.'
LIM_TZ = 'Some database queries use the database’s own date: the database time zone must be Asia/Manila.'
LIM_UPLOAD = 'Several masters have no Upload button yet (Company, Branch, Line of Business, Product, Cover, Signatories, Commission and others): load their templates through the API route on the template.'
LIM_BIR = 'The BIR reports give the figures in BIR column order: check them against the current BIR format before filing.'
LIM_CASH = 'The Settlement cash panel of a claim paid through the broker sits on the claim screens, which are not in the Accounting menu: the System Administrator records the funds received and the payment to the claimant on Accounting’s instruction.'
LIM_SETTLE = 'A settlement is marked as paid through the broker by its settlement type or through the API; the form offers Cash, Card and Cheque only.'
LIM_COMPANY = 'The Company master list opens with one empty row: type in the search box to list the companies.'
LIM_NO_BELL = 'A submitted month-end close or a prepared bank reconciliation does not raise a bell notice: check Month-End Close and Reconciliations for items waiting.'
COMMON_LIMITS = [LIM_TOKENS, LIM_QR, LIM_LANG]

PERSONAS = []

# ============================================================== System Administrator
PERSONAS.append(dict(
    user='bea.admin', file='BrokerVerse_System_Administrator_Guide.pptx', label='System Administrator',
    full_label='System Administrator (Super Admin Access)',
    users='bea.admin (and the delivered BrokerVerse user)', role_code='system-admin', landing='Executive Dashboard',
    title_chips=['Every menu', 'Users and masters', 'Settings and schedules'],
    does=[('Runs the platform:', 'users, roles, system settings, configuration and the scheduled jobs.'),
          ('Keeps the reference data:', 'company and letterhead, insurers and credit terms, products, locations, commission sharing.'),
          ('Owns the accounting set-up:', 'document numbering, commission rate matrix, posting rules and account determination, agreed with the Accounting Manager.'),
          ('Supports every team:', 'sees all 158 screens, so it can reproduce a problem on any of them.'),
          ('Reviews access:', 'audit trail, sign-in history, password resets and unlocking users.')],
    signin='User name bea.admin. Lands on the Executive Dashboard. Idle sessions end after 30 minutes; a role change '
           'or password reset ends the user’s other sessions.',
    hands_to='Processing Team (products and tariff in use), Accounting and the Accounting Manager (GL accounts, posting '
             'rules, numbering), every team for user requests.',
    partners='The role passes every permission check, but maker-checker still applies: you cannot approve a voucher, '
             'settlement, close run or reconciliation you prepared yourself.',
    menu=[('Dashboard', ['Executive Dashboard', 'Sales Dashboard', 'Processing Dashboard', 'Claims Dashboard']),
          ('Product Configurator', PC_ALL), ('Master', MASTER_ALL), ('Operations', OPS_ALL), ('Accounts', ACC_ALL),
          ('Commission', ['Commission Dashboard', 'Agents/Referrer Accounts']), ('Reinsurance', RI_ALL),
          ('Reports', ['All Reports (39 reports)', REP_OPS, 'Financial Reports (15 shortcuts)'])],
    menu_note='system-admin has every menu (all: true) and every permission, including approve:period-end and '
              'approve:bank-reconciliation. The role walk opened 158 screens with no errors.',
    functions=[
        dict(title='Users and account actions', **shot('m-user-actions', 'Master > Generals > User Management > User, account actions'),
             menu='Master > Generals > User Management > User',
             points=[('Add:', 'user name, e-mail, display name and one role. Leave the password empty: a temporary password is shown once.'),
                     ('First sign-in:', 'the user must choose a new password before anything else.'),
                     ('Row actions:', 'Unlock, Reset password, Turn off two-step verification, Sign-in history.'),
                     ('Leavers:', 'switch Status off. History is kept and open sessions end.')]),
        dict(title='The seven roles', **shot('m-roles', 'Master > Generals > User Management > Role'),
             menu='Master > Generals > User Management > Role',
             points=[('Fixed roles:', 'system-admin, sales, processing, operations, claims, accounting, accounting-manager.'),
                     ('Inheritance:', 'accounting-manager includes accounting and adds approve:period-end and approve:bank-reconciliation.'),
                     ('Retired:', 'the IT, Business and User Access administrator roles are merged into this one; the Agent login is withdrawn.'),
                     ('Referrers:', 'do not sign in. Sales enters their business and they are paid from the referrer master.')]),
        dict(title='Company and letterhead', **shot('m-company-edit', 'Master > Generals > Organization > Company, edit'),
             menu='Master > Generals > Organization > Company',
             points=[('Letterhead:', 'every PDF (slips, policy schedule, OR, PV, debit note, claim letters, BIR forms, reports) uses the letterhead company.'),
                     ('Fill in:', 'company name, Insurance Commission licence, TIN, logo, address, phone and e-mail.'),
                     ('One company:', 'only one company can hold Letterhead company.'),
                     ('Check:', 'print any billing statement as PDF after you save.')]),
        dict(title='Insurers and credit terms', **shot('m-insurer-edit', 'Master > Insurance Company, edit'),
             menu='Master > Generals > Insurance Management > Insurance Company',
             points=[('E-mail:', 'requests for quotation, firm orders, loss advices and remittance advices go to the insurer’s e-mail.'),
                     ('Premium payment warranty:', 'days the client has to pay; else collections.default_credit_days (30).'),
                     ('Remittance terms:', 'days after collection to remit; else remittance.default_due_days (30).'),
                     ('Default billing mode:', 'broker billed or direct bill for the insurer’s new policies.')]),
        dict(title='Document numbering', **shot('m-docnum', 'Master > Document Numbering'),
             menu='Master > Document Numbering',
             points=[('Series:', '52 series in 11 modules: POL, QT, BS, PS, OR, INV, PV, JV, CLM, END, DN, MEC, BRC, CWT and more.'),
                     ('Format:', 'tokens {PREFIX}, {YYYY}, {YY}, {MM}, {FY}, {BRANCH}, {LOB}, {SEQ}; delivered as POL-2026-00001.'),
                     ('Reset:', 'every calendar year, fiscal year, month or never.'),
                     ('Go-live:', 'Set next number continues the old system’s series. The OR series must match the Authority to Print.')]),
        dict(title='Commission Rate Matrix', **shot('m-crm', 'Master > Finance > Commission Rate Matrix'),
             menu='Master > Finance > Commission Rate Matrix',
             points=[('Holds:', 'the brokerage the broker earns by insurer, product, line and policy type, with effective dates.'),
                     ('Order:', 'most specific rate first, then the insurer’s default rate, then commission.default_rate (15%).'),
                     ('Test rate:', 'shows the rate a placement would get and where it came from.'),
                     ('Not the same as:', 'Master > Generals > Commission, which holds the sharing with referrers.')]),
        dict(title='Posting rules: from operations to the ledger', **shot('m-posting-rule', 'Master > Finance > Posting Rules, Policy issued (broker billed)'),
             menu='Master > Finance > Posting Rules',
             points=[('Events:', 'policy issued, endorsement, renewal, cancellation, receipt, comsub, voucher, remittance, claim funds, cessions and more.'),
                     ('Each line:', 'debit or credit, account role or GL account, amount, narration, split per co-insurer.'),
                     ('Simulate:', 'builds the journal with sample amounts, including a co-insured sample, and checks it balances.'),
                     ('Change:', 'New version from a date, only with the Accounting Manager. Older journals keep the old version.')]),
        dict(title='Account determination', **shot('m-acct-det', 'Master > Finance > Account Determination'),
             menu='Master > Finance > Account Determination',
             points=[('Account roles:', 'the GL account behind each role, e.g. brokerage income 3201001, premium payable 2201001.'),
                     ('Payee and payment mode:', 'payable account per payee type and cash account per payment mode.'),
                     ('Write-off reasons:', 'code, GL account and maximum amount for Open Entry Matching.'),
                     ('Effect:', 'applies to postings from the moment you save.')]),
        dict(title='Configuration: placement journey and security', **shot('m-config-placement', 'Master > Configuration, Placement tab'),
             menu='Master > Configuration',
             points=[('Tabs:', 'Accounting, BIR, Claims, Collections, Commission, Direct bill, Placement, Quotations, Renewals, Security, Taxes and more.'),
                     ('placement.journey:', 'which steps each line must, may or does not use (fire and IAR require a Placement Slip).'),
                     ('Security:', 'password rules, lockout, 2FA roles (none required when delivered; recommended for admin and accounting).'),
                     ('Audit:', 'every change applies at once and is recorded with old and new value.')]),
        dict(title='Schedules', **shot('m-schedules', 'Master > Schedules'),
             menu='Master > Configuration > Schedules',
             points=[('Jobs:', '15 jobs in Manila time. Six accounting jobs are delivered switched off.'),
                     ('Run now:', 'runs a job at once and shows the result, for example Updated: 5.'),
                     ('Pencil:', 'change the timetable, the job parameters, or switch it on or off.'),
                     ('History:', 'past runs with results. With several servers each run happens once.')]),
        dict(title='Audit trail', **shot('m-audit', 'Master > Audit Trail'),
             menu='Master > Configuration > Audit Trail',
             points=[('Contents:', 'every create, update, approval, report run and sign-in, newest first.'),
                     ('Search:', 'record type (session, policy, receipt, placement, period-close-run), record ID, user, dates.'),
                     ('Use:', 'investigations, access reviews, proof that maker and checker were different people.'),
                     ('Kept:', 'for good (housekeeping.audit_log_days is 0).')]),
        dict(title='Master uploads', **shot('m-upload', 'Master > Location > City Master, Upload'),
             menu='Upload button on each master',
             points=[('Template:', 'Download template gives a Data sheet with sample rows, a Columns sheet and Instructions.'),
                     ('Result:', 'rows created or updated, and each failed row with its problem.'),
                     ('Existing code:', 'an upload with an existing code updates the record.'),
                     ('Templates:', 'also delivered in docs/package/05_Delivery/Upload_Templates.')]),
    ],
    extras=[dict(kind='api', title='API and Postman collection', kicker='backend/docs/api',
                 stats=[('717', 'endpoints (GET 331, POST 277, PUT 74, DELETE 28, PATCH 7)'),
                        ('46', 'folders in the Postman collection'), ('1', 'OpenAPI file, generated from the code'),
                        ('1', 'touchpoints workbook: endpoint, screen, permission')],
                 left_title='What you get',
                 left=['BrokerVerse.postman_collection.json and its environment (set the base URL and token)',
                       'openapi.json with every path and its examples',
                       'BrokerVerse_API_Touchpoints.xlsx / .csv: endpoint, the screen that calls it, permission',
                       'Generated from the code, so it matches what is deployed'],
                 right_title='How to use it',
                 right=['POST /api/auth/login returns an access token; send it as Authorization: Bearer',
                        'Every endpoint checks read:, write: or approve: permissions; a wrong role gets 403',
                        'Masters without an Upload button are loaded through the route on their template',
                        'Share the collection with integration partners, never a password'])],
    flow_steps=[('Company, letterhead', 'You'), ('Users and roles', 'You'), ('Insurers, credit terms', 'You'),
                ('Master uploads', 'You'), ('Document numbering', 'You'), ('Commission rates', 'You'),
                ('Posting rules', 'You + Acct. Manager'), ('Configuration', 'You'), ('Schedules, e-mail', 'You'),
                ('Opening balances', 'Accounting'), ('Open items', 'Accounting'), ('Go-live', 'Everyone')],
    flow_mine=[1, 2, 3, 4, 5, 6, 7, 8, 9], flow_title='Go-live set-up: your part', flow_kicker='Before the first policy',
    flow_loop='After go-live: users, rates and settings as the business changes',
    flow_notes=['Set the SMTP mailbox (Office 365) and switch on e-mail before go-live.',
                'Match the official receipt series to the BIR Authority to Print.',
                'Agree GL accounts, posting rules and maker-checker switches with the Accounting Manager.',
                'Decide which roles must use two-factor authentication (security.require_2fa_roles).'],
    reports=reports_for('system-admin'), reports_note='Every report in the catalogue.',
    jobs=[('policy-expiry', 'Policies past expiry become Expired'),
          ('quote-expiry', 'Quotations past validity (30 days) expire'),
          ('housekeeping', 'Old tokens, job runs, read notices and sent e-mails deleted; audit trail kept'),
          ('daily-reports', 'Production Register, Collection Report and Claims Position each morning'),
          ('renewal-pipeline', 'Policies within 90 days enrolled; lapse after 30 days grace'),
          ('email-outbox', 'Queued e-mails sent through the configured mailbox'),
          ('bank-auto-match', 'Switch on when Accounting asks; same for the other accounting jobs')],
    notifications=[('Approval', 'Treaty awaiting approval', 'A new reinsurance treaty needs a second user (reinsurance.treaty_requires_approval).'),
                   ('Approval', 'Approvals of every module', 'The role holds every permission, so it can receive approval requests addressed to a permission.'),
                   ('Reminder', 'Premium overdue', 'Collection reminders for policies you own.'),
                   ('Task', 'Settlement cash on Accounting’s instruction', 'Record funds received and payment to claimant on the claim screen.'),
                   ('E-mail', 'Outbox', 'Customer e-mails wait in the outbox until the mailbox is set and e-mail is switched on.'),
                   ('Info', 'Master uploads', 'Each upload reports created, updated and failed rows.')],
    limits=[LIM_RATE, LIM_TZ, LIM_UPLOAD, LIM_CASH, LIM_COMPANY, LIM_QR],
    tips=['Keep this role for administration; do business work with a business role.',
          'Give each person one role, and this role to as few people as possible.',
          'Simulate a posting rule before you save a new version.',
          'Use Run now after changing a job’s settings, then read its history.',
          'Review the audit trail for sign-ins and approvals every week.'],
    access_contact='You: Master > Generals > User Management',
))

# ============================================================== Sales & Marketing
PERSONAS.append(dict(
    user='maria.sales', file='BrokerVerse_Sales_and_Marketing_Guide.pptx', label='Sales & Marketing',
    full_label='Sales & Marketing (Account Executive)',
    users='maria.sales (and the account executives agent.*)', role_code='sales', landing='Executive Dashboard',
    title_chips=['Leads and quotations', 'Renewals', 'Own production'],
    does=[('Finds business:', 'records prospects and leads, alone or in bulk from a spreadsheet.'),
          ('Quotes:', 'prices motor risks in the quotation wizard and sends them to the client for online acceptance.'),
          ('Hands over commercial risks:', 'agrees the risk details; the Processing Team markets them on a Broker Slip.'),
          ('Keeps the book:', 'works the renewal queue, at-risk policies and negotiations.'),
          ('Watches results:', 'Sales Dashboard, commission and incentive results for your own production.')],
    signin='User name maria.sales. Lands on the Executive Dashboard. Your own figures are on Dashboard > Sales Dashboard.',
    hands_to='Processing Team (Broker Slips, placement, policy issue, renewal terms), the client (accepts by e-mail '
             'link), Accounting (verifies payments you record).',
    partners='Your quotation is approved by another user, and renewal terms by the Processing Team. You never post '
             'receipts: you record the payment and Accounting confirms it.',
    menu=[('Dashboard', ['Executive Dashboard', 'Sales Dashboard']),
          ('Product Configurator', ['Dashboard', 'Product Templates']),
          ('Operations', OPS_ALL), ('Commission', ['Commission Dashboard']),
          ('Reports', ['All Reports (15 reports)', REP_OPS])],
    menu_note='Menus granted to sales in menuPermissions.js; anything else is hidden, refused by the route guard and by '
              'the API. The role walk opened 29 screens.',
    functions=[
        dict(title='Sales Dashboard', **shot('dash-sales', 'Dashboard > Sales Dashboard'),
             menu='Dashboard > Sales Dashboard (also Operations > Home)',
             points=[('Counts:', 'your leads, clients and policies.'),
                     ('Money:', 'earned commission and premium billed on your policies: collected, still due, total.'),
                     ('Direct bill:', 'left out of premium figures, because the client pays the insurer.'),
                     ('Shortcut:', 'Create Quote, and upcoming follow-ups from the activity monitor.')]),
        dict(title='Leads and prospects', **shot('lead-create-form', 'Leads/Prospects > Create Lead, motor prospect'),
             menu='Operations > Leads/Prospects > Create Lead',
             points=[('Line first:', 'Motor, Fire and Allied Perils, Industrial All Risks or Employee Benefit; then Retail or Corporate.'),
                     ('Checks:', 'age 18 to 100, valid e-mail, mobile 0917 123 4567 or +63 917 123 4567, 4-digit ZIP.'),
                     ('Corporate:', 'company name and TIN are required.'),
                     ('Bulk Upload:', 'up to 1,000 rows from Leads_Upload_Template.xlsx; failed rows listed with the reason.')]),
        dict(title='Motor quotation: coverage', **shot('quote-3-coverage', 'Create Quote, step 3 after Calculate'),
             menu='Lead Details > Create Quote (5 steps)',
             points=[('Own damage:', 'rate from the motor tariff, 2% for private cars.'),
                     ('CTPL and Auto Passenger PA:', 'always priced by the system from template MOT-003-2025.'),
                     ('Co-Insurance:', 'tick it on step 1 when several insurers share the risk; shares total 100% with one lead.'),
                     ('Calculate:', 'after every change. Nothing is saved until Completed Quote.')]),
        dict(title='Order summary, discount and referrer', **shot('quote-5-order-summary', 'Create Quote, step 5'),
             menu='Create Quote > Order Summary',
             points=[('Taxes:', 'VAT 12%, DST 12.5%, LGT 0.75% of the net premium; CTPL is not taxed again.'),
                     ('Discount:', '0% to 30%, taken from the broker’s commission, not the referrer’s share.'),
                     ('Referrer:', 'choose the referrer or Direct; comsub fills in from the rule (L1 8%, L2 5%).'),
                     ('Server check:', 'the saved premium is recalculated from the configured rates; typed amounts are refused.')]),
        dict(title='Send the quotation to the client', **shot('quote-detail-draft', 'Quotation detail, Draft'),
             menu='Operations > Quotation > eye icon',
             points=[('Send for Customer Approval:', 'e-mails a signed link valid 7 days; status Pending Customer.'),
                     ('Client:', 'opens the link, no sign-in needed, and selects Approve Quote.'),
                     ('You:', 'are told Customer accepted quotation; the Processing Team is notified.'),
                     ('Share:', 'Download, Email, WhatsApp, Send to Insurer or Copy Link. Quotations expire after 30 days.')]),
        dict(title='Follow a commercial placement', **shot('bs-list', 'Operations > Broker Slips'),
             menu='Operations > Broker Slips, Placement Slips',
             points=[('Who does it:', 'the Processing Team markets fire, IAR, marine and other commercial risks.'),
                     ('You see:', 'offers received, declines, best gross offer, response due date and status.'),
                     ('Next:', 'the chosen terms become a Quotation Slip for the client, or a Placement Slip.'),
                     ('Reports:', 'Placement Pipeline and Market Response.')]),
        dict(title='Record the client’s payment', **shot('policy-5-payment-capture', 'Policy > Proceed to Payment'),
             menu='Policy > Proceed to Payment',
             points=[('Choose:', 'Pay later, Bank transfer, Cheque, Online payment or Cash.'),
                     ('Enter:', 'reference, amount, payment date and proof of payment if you have it.'),
                     ('Then:', 'payment status Reviewing; Accounting gets Premium payment to verify.'),
                     ('Only Accounting:', 'posts the official receipt (Confirm) or rejects it with a reason.')]),
        dict(title='Renewals: queue and at-risk policies', **shot('renew-atrisk', 'Operations > Renewals > At-Risk Policies'),
             menu='Operations > Renewals',
             points=[('Timetable:', 'pipeline 90 days before expiry; notices at 60, 30 and 15 days; lapse 30 days after expiry.'),
                     ('Risk score:', 'claims in the term, unpaid premium, expiry within 30 days, premium increase, no contact, first renewal.'),
                     ('Negotiations:', 'Add Update for each call; Request Approval sends terms to the Processing Team.'),
                     ('Commission:', 'the renewal accrues to the original referrer.')]),
        dict(title='Commission dashboard', **shot('comm-dashboard', 'Commission > Commission Dashboard'),
             menu='Commission > Commission Dashboard',
             points=[('Shows:', 'brokerage income, comsub, net margin, outstanding payable and withholding tax.'),
                     ('Breakdowns:', 'by referrer, status, month, product and insurer.'),
                     ('Who earns:', 'only Sales & Marketing users earn commission on their production (commission.eligible_roles).'),
                     ('Payable:', 'when the premium is fully collected and the referrer has a bank account on file.')]),
    ],
    flow_mine=[1, 3, 6, 12], flow_loop='Your renewals start the next cycle',
    flow_notes=['1 Lead: record and qualify the prospect.', '3 Quotation Slip: price the motor risk and send the link.',
                '6 Payment capture: record how the client paid.', '12 Renewal: work the queue and at-risk list.'],
    reports=reports_for('sales'), reports_note='Fifteen reports in Reports > All Reports.',
    jobs=[('quote-expiry', 'Your quotations expire after 30 days'),
          ('renewal-pipeline', 'Your policies enter the renewal queue 90 days before expiry'),
          ('renewal-notices', 'Clients get notices at 60, 30 and 15 days; you get a reminder'),
          ('collection-reminders', 'Clients reminded 7 days before premium is due'),
          ('daily-reports', 'Production Register ready at 05:00')],
    notifications=[('Task', 'Customer accepted quotation', 'The client approved through the link.'),
                   ('Info', 'Quotation approved', 'Another user approved your quotation.'),
                   ('Info', 'Policy issued', 'Policy number, for policies you own.'),
                   ('Reminder', 'Renewal notice reminders', 'For each 60, 30 and 15-day notice on your policies.'),
                   ('Info', 'Renewal approved / returned', 'The Processing Team’s decision on your terms.'),
                   ('Alert', 'Policy lapsed', 'No renewal within 30 days after expiry.')],
    limits=COMMON_LIMITS + ['The lead needs an e-mail address before a quotation can be sent for approval.',
                            'A quotation converted to a policy cannot be edited: raise an endorsement instead.'],
    tips=['Start quotations from Lead Details, not from the quotation list.',
          'Choose the referrer on step 5; the commission follows that choice.',
          'Record declines and offers with the Processing Team: Market Response uses both.',
          'Look at At-Risk Policies every week.'],
))

# ============================================================== Processing Team
PERSONAS.append(dict(
    user='jose.uw', file='BrokerVerse_Processing_Team_Guide.pptx', label='Processing Team',
    full_label='Processing Team (Placement & Policy Processing)',
    users='jose.uw', role_code='processing', landing='Executive Dashboard',
    title_chips=['Broker and placement slips', 'Policy issue', 'Co-insurance'],
    does=[('Markets risks:', 'Broker Slips to several insurers, offers and declines recorded, offers compared.'),
          ('Binds cover:', 'Quotation Slips and Placement Slips, firm orders to the lead and co-insurers, confirmations.'),
          ('Issues policies:', 'from a bound Placement Slip, from a motor quotation, by direct placement or Record Issued Policy.'),
          ('Completes changes:', 'endorsements with the insurer’s document; approves renewal terms.'),
          ('Keeps products:', 'motor tariff, templates and acceptance rules; treaties and cessions.')],
    signin='User name jose.uw. Lands on the Executive Dashboard. Your workbench is Dashboard > Processing Dashboard.',
    hands_to='Insurers (requests for quotation, firm orders), Sales & Marketing and Operations (terms and policies), '
             'Accounting (bills, commission and remittance by insurer share).',
    partners='You are notified of quotations sent to clients (quotations.approval_notify_roles) and approve renewal '
             'terms (renewals.approver_roles). You cannot approve your own.',
    menu=[('Dashboard', ['Processing Dashboard', 'Executive Dashboard']), ('Product Configurator', PC_ALL),
          ('Operations', OPS_ALL), ('Reinsurance', RI_ALL), ('Reports', ['All Reports (13 reports)', REP_OPS])],
    menu_note='Menus granted to processing in menuPermissions.js. The role walk opened 41 screens.',
    functions=[
        dict(title='Processing Dashboard', **shot('dash-processing', 'Dashboard > Processing Dashboard'),
             menu='Dashboard > Processing Dashboard',
             points=[('Submissions:', 'quotations in progress: new this week and older.'),
                     ('Priority:', 'high from ₱ 5,000,000 sum insured (dashboard.high_sum_insured).'),
                     ('Open alerts:', 'duplicates, missing sums insured or dates, missing line of business.'),
                     ('Also:', 'average cycle time, workload by group, open tasks with due dates.')]),
        dict(title='New Broker Slip', **shot('bs-new', 'Operations > Broker Slips > New Broker Slip'),
             menu='Operations > Broker Slips > New Broker Slip',
             points=[('Customer:', 'a client or a lead, the product, the insured name and the period.'),
                     ('Risk and covers:', 'location, occupancy, construction; each cover with sum insured and deductible.'),
                     ('Market:', 'the insurers to approach, and remarks such as claims history.'),
                     ('Submit:', 'numbers the slip BS-, creates one offer per insurer and e-mails each a request for quotation.')]),
        dict(title='Record the insurers’ answers', **shot('bs-offer', 'Broker Slip > Market responses > Record response'),
             menu='Broker Slip > Market responses',
             points=[('Offered:', 'net premium at 100%, rate, line offered, taxes, validity, deductibles, special terms, reference.'),
                     ('Declined:', 'record the reason. Declines count in Market Response.'),
                     ('Attach:', 'the insurer’s offer letter.'),
                     ('Add insurer:', 'approach another insurer on an open slip.')]),
        dict(title='Compare offers and choose the security', **shot('bs-compare', 'Broker Slip > Compare offers'),
             menu='Broker Slip > Compare offers',
             points=[('Ranking:', 'by gross premium; the cheapest is marked Best, with the difference for each offer.'),
                     ('Select:', 'one offer at 100% for a single insurer, several for a co-insurance.'),
                     ('Lead:', 'choose one lead; its terms apply. Shares must total exactly 100%.'),
                     ('Next:', 'Prepare Quotation Slip (client accepts first) or Prepare Placement Slip.')]),
        dict(title='Placement Slip: firm order and confirmations', **shot('ps-sent', 'Placement Slip PS-2026-90001, sent'),
             menu='Operations > Placement Slips',
             points=[('Send to insurer(s):', 'each participant gets a placing slip showing its own share.'),
                     ('Confirm:', 'type the insurer’s policy or certificate number on its row.'),
                     ('Declined:', 'record the reason, then Edit participants so the shares total 100% again.'),
                     ('Bound:', 'when every participant has confirmed.')]),
        dict(title='Direct placement', **shot('ps-direct', 'Placement Slips > New direct placement', crop=(0, 0, 1400, 890)),
             menu='Operations > Placement Slips > New direct placement',
             points=[('When:', 'the client instructs placement with named insurers; no quotation is needed.'),
                     ('Enter:', 'customer and risk, period, sum insured, net premium, commission rate, billing mode.'),
                     ('Security:', 'each insurer with its share and one Lead; the line under the table checks 100%.'),
                     ('Then:', 'Create Placement Slip, send, confirm and issue as usual.')]),
        dict(title='Issue the policy from a bound slip', **shot('ps-issued', 'Placement Slip PS-2026-00001, issued as POL-2026-00001'),
             menu='Placement Slip > Issue Policy',
             points=[('Policy:', 'number issued; participants, shares and insurer references copied.'),
                     ('Client:', 'created from the lead if needed.'),
                     ('Money:', 'premium bill to the client (broker billed) or commission due from insurers (direct bill).'),
                     ('Journal:', 'each insurer’s payable and commission on its own line.')]),
        dict(title='Co-insurance on the policy', **shot('policy-coins', 'Policy POL-2026-00001, participants'),
             menu='Operations > Policy > policy > Participants',
             points=[('Example:', 'Malayan lead 60% and Standard 40% on ₱ 125,000,000 sum insured.'),
                     ('Split:', 'sum insured, premium, taxes, gross and commission by share; the rounding remainder goes to the lead.'),
                     ('Used by:', 'the bill journal, remittance per insurer, claim recoveries and the reports.'),
                     ('Rule:', 'shares always total 100% with exactly one lead.')]),
        dict(title='Motor: from quotation straight to policy', **shot('policy-3-review-billing', 'Convert Policy, review with participants and billing mode'),
             menu='Quotation > Proceed to Policy',
             points=[('KYC:', 'ID type, number and image, chassis, motor and plate or MV file number are required.'),
                     ('Photos:', 'left, right, front, rear and interior.'),
                     ('Billing mode:', 'broker billed (premium bill INV-) or direct bill (commission due from the insurer).'),
                     ('Send to Insurance Company:', 'issues the policy; then upload the insurer’s policy document.')]),
        dict(title='Record Issued Policy', **shot('ps-record-policy', 'Placement Slips > Record Issued Policy'),
             menu='Operations > Placement Slips > Record Issued Policy',
             points=[('When:', 'the insurer has already issued the policy, for example a renewal it processed itself.'),
                     ('One step:', 'policy, bill and commission are created together.'),
                     ('Security:', 'each participant with its share and its own policy or certificate number.'),
                     ('Refused:', 'on lines whose journey does not allow a direct policy entry.')]),
        dict(title='Complete an endorsement', **shot('end-view', 'Endorsement END-2026-95001, completed'),
             menu='Endorsement > Proceed > Complete',
             points=[('Start:', 'Operations raises the request and sends it to the insurer (Waiting for Update).'),
                     ('You:', 'upload the insurer’s endorsement with its number and dates, then Complete.'),
                     ('Money:', 'additional premium is billed; for a co-insured policy the journal splits it by share.'),
                     ('Return premium:', 'credited to the client; already remitted amounts are netted on the next remittance.')]),
        dict(title='Motor tariff', **shot('pc-template-ctpl', 'Product Templates > MOT-003-2025, CTPL & Auto PA'),
             menu='Product Configurator > Product Templates',
             points=[('Vehicle classes:', 'code, default seats, CTPL 1 year and 3 years, e.g. private cars ₱ 610.40 / ₱ 1,660.40.'),
                     ('Auto Passenger PA:', 'rate per seat and the limits per person offered.'),
                     ('Effect:', 'quotation screens use the values at once.'),
                     ('Taxes:', 'come from Master > Configuration, shown read-only on the template.')]),
    ],
    extras=[dict(kind='table', title='Placement journey by line of business', kicker='placement.journey',
                 intro='The journey of each line decides which steps are required. A required step cannot be skipped; '
                       'the screens show the journey as a progress bar and mark unused steps Not used.',
                 rows=[('Line of business', 'Broker Slip', 'Quotation Slip', 'Placement Slip', 'Record Issued Policy'),
                       ('Motor', 'Optional', 'Required', 'Optional', 'Optional'),
                       ('Fire, IAR, Marine, Casualty, Engineering', 'Optional', 'Optional', 'Required', 'Optional'),
                       ('Other lines (default)', 'Optional', 'Optional', 'Optional', 'Optional')],
                 widths=[4, 2, 2, 2, 2.3], size=14,
                 note='Renewals follow the journey only when placement.journey_applies_to_renewals is on (off when delivered). '
                      'The System Administrator changes the journey on Master > Configuration, tab Placement.')],
    flow_mine=[2, 3, 4, 5, 10, 12], flow_loop='Renewal terms you approve start the next term',
    flow_notes=['2 Broker Slip: market the risk and compare offers.', '3 and 4: Quotation Slip for the client, Placement Slip to bind.',
                '5 Policy issue: from the bound slip or the motor quotation.', '10 and 12: complete endorsements, approve renewal terms.'],
    reports=reports_for('processing'), reports_note='Thirteen reports in Reports > All Reports.',
    jobs=[('quote-expiry', 'Quotations expire after 30 days'),
          ('renewal-pipeline', 'Policies due within 90 days reach the renewal queue'),
          ('renewal-notices', 'Notices at 60, 30 and 15 days'),
          ('policy-expiry', 'Expired policies leave the in-force figures'),
          ('email-outbox', 'Requests for quotation and firm orders leave every 5 minutes'),
          ('daily-reports', 'Production Register each morning')],
    notifications=[('Approval', 'Quotation sent for approval', 'Client, quotation number and gross premium.'),
                   ('Approval', 'Renewal approval', 'Renewal terms waiting for your decision.'),
                   ('Info', 'Renewal approved / returned', 'Goes back to the maker with your note.'),
                   ('Info', 'Policy issued', 'Policy issued from a Placement Slip you own.'),
                   ('Approval', 'Treaty awaiting approval', 'When treaty approval is on; not your own treaty.'),
                   ('Info', 'Endorsement completed', 'Sent to the policy owner when you complete it.')],
    limits=COMMON_LIMITS + ['Only users with policy issuing rights see Issue Policy; others see “All insurers confirmed”.',
                            'Treaties are added by the System Administrator on Master > Reinsurance Treaty.'],
    tips=['Keep each insurer’s placement e-mail current: slips go there.',
          'Record declines as well as offers.', 'Check the shares total 100% before you send a Placement Slip.',
          'Use Placement Pipeline to chase slips that are getting old.'],
))

# ============================================================== Operations
PERSONAS.append(dict(
    user='ana.cs', file='BrokerVerse_Operations_Guide.pptx', label='Operations',
    full_label='Operations (Client Servicing)',
    users='ana.cs', role_code='operations', landing='Executive Dashboard',
    title_chips=['Client servicing', 'Endorsement requests', 'Open items'],
    does=[('Serves clients:', 'finds the client and answers from one view of policies, claims, renewals and endorsements.'),
          ('Raises endorsements:', 'personal details, vehicle and coverage changes, extensions and cancellations.'),
          ('Captures payments:', 'records how the client paid, for Accounting to verify.'),
          ('Chases open items:', 'expiring policies, pending payments, pending quotes and renewal requests.'),
          ('Renews:', 'starts renewal quotations and works the renewal screens with Sales.')],
    signin='User name ana.cs. Lands on the Executive Dashboard. Start the day on Operations > Open Items.',
    hands_to='Processing Team (completes endorsements with the insurer’s document), Accounting (verifies payments), '
             'Claims, Sales & Marketing.',
    partners='Your renewal terms go to the Processing Team for approval. Endorsements become final only when the '
             'Processing Team completes them.',
    menu=[('Dashboard', ['Executive Dashboard']), ('Product Configurator', ['Dashboard', 'Product Templates']),
          ('Operations', OPS_ALL), ('Reports', ['All Reports (11 reports)', REP_OPS])],
    menu_note='Menus granted to operations in menuPermissions.js. The role walk opened 27 screens.',
    functions=[
        dict(title='Open items', **shot('open-items', 'Operations > Open Items'),
             menu='Operations > Open Items',
             points=[('Boxes:', 'Expiring Policy, Pending Payments, Quote Pending and Renewal Request.'),
                     ('See More:', 'opens the full list of a box.'),
                     ('Source:', 'policies, bills and renewals, refreshed by the overnight jobs.'),
                     ('Use:', 'your daily worklist.')]),
        dict(title='Client view', **shot('client-view', 'Operations > Clients > client'),
             menu='Operations > Clients',
             points=[('Find:', 'tabs All, Individual, Corporate, or search by name.'),
                     ('Tabs:', 'Policy, Claim, Renewal and Endorsement.'),
                     ('Client code:', 'CL- is created when the first policy is issued.'),
                     ('Corrections:', 'name or address on an issued policy: raise a Personal Details Change endorsement.')]),
        dict(title='Policy list and row actions', **shot('policy-row-menu', 'Operations > Policy, row actions'),
             menu='Operations > Policy',
             points=[('List:', 'policy number, client, gross premium, dates, product, payment status.'),
                     ('Row menu:', 'Claim, Endorsement, Reminder.'),
                     ('Disabled:', 'while payment is Pending or Reviewing.'),
                     ('Not offered:', 'Endorsement on expired, lapsed, cancelled or renewed policies.')]),
        dict(title='Policy details and documents', **shot('policy-detail', 'Policy Details'),
             menu='Operations > Policy > policy',
             points=[('Sections:', 'policy, insured, vehicle and photos, coverage, premium breakdown.'),
                     ('Participants:', 'each insurer with its share on a co-insured policy.'),
                     ('Documents & Billing:', 'Generate Policy Invoice, Premium Accounting Entries, the policy document.'),
                     ('Payment:', 'Proceed to Payment while premium is due.')]),
        dict(title='Record the client’s payment', **shot('policy-5-payment-capture', 'Policy > Proceed to Payment'),
             menu='Policy > Proceed to Payment',
             points=[('How paid:', 'Pay later, Bank transfer, Cheque, Online payment or Cash.'),
                     ('Details:', 'reference, amount, date, remarks, proof of payment.'),
                     ('Result:', 'payment status Reviewing; Accounting receives Premium payment to verify.'),
                     ('Receipt:', 'Accounting confirms and posts the official receipt, or rejects with a reason.')]),
        dict(title='Choose the endorsement type', **shot('end-dialog', 'Policy > Endorsement, type'),
             menu='Policy > three dots > Endorsement',
             points=[('Motor:', 'Personal Details, Motor Details, Coverage Change, Policy Extend, Policy Cancel.'),
                     ('Fire:', 'Regular / Premium Change, Policy Cancellation (full, partial, pro-rata).'),
                     ('Proceed:', 'stays disabled until you tick a type.'),
                     ('Number:', 'END- when saved.')]),
        dict(title='Coverage change, priced again', **shot('end-coverage', 'Endorsement request, coverage change'),
             menu='Endorsement Request > Coverage Change',
             points=[('Recalculated:', 'net premium, VAT, DST, LGT, gross premium and Premium change.'),
                     ('CTPL:', 'stays as issued.'),
                     ('Send:', 'Save & Next, check the summary, Send to Insurance Company.'),
                     ('Money:', 'additional premium is billed when the Processing Team completes the endorsement.')]),
        dict(title='Renewal Policy', **shot('renew-policy', 'Operations > Renewals > Renewal Policy'),
             menu='Operations > Renewals > Renewal Policy',
             points=[('Shows:', 'active, expiring and expired policies.'),
                     ('Renew:', 'three dots > Renewal opens a quotation with the covers of the expiring term.'),
                     ('Then:', 'Calculate, Completed Quote, send for customer approval, Proceed to Policy.'),
                     ('Result:', 'new term issued, old policy Renewed, premium billed.')]),
        dict(title='Lapse management', **shot('renew-lapse', 'Operations > Renewals > Lapse Management'),
             menu='Operations > Renewals > Lapse Management',
             points=[('Grace:', 'an unrenewed policy lapses 30 days after expiry (renewals.grace_period_days).'),
                     ('Shows:', 'lapsed policies, policies in the grace period and win-back campaigns.'),
                     ('Batch:', 'Renewal Batch sends notices for up to 500 policies together.'),
                     ('Queue:', 'Renewal Queue lists days to expiry, risk and contact attempts.')]),
        dict(title='Payments', **shot('payments', 'Operations > Payments'),
             menu='Operations > Payments',
             points=[('Figures:', 'gross premium, collected premium, receivables and earned commission.'),
                     ('Tabs:', 'Paid, Pending, Reviewing.'),
                     ('Type:', 'policy, renewal or endorsement; DIRECT BILL for bills cancelled by direct billing.'),
                     ('Note:', 'Accounting posts the receipts; this screen shows the result.')]),
    ],
    flow_mine=[1, 6, 10, 12], flow_loop='Renewal follow-up starts the next cycle',
    flow_notes=['1 Lead: you can record prospects like Sales.', '6 Payment capture: record how the client paid.',
                '10 Endorsement: raise the request; Processing completes it.', '12 Renewal: chase expiring policies.'],
    reports=reports_for('operations'), reports_note='Eleven operational reports in Reports > All Reports.',
    jobs=[('renewal-notices', 'Clients get notices at 60, 30 and 15 days'),
          ('collection-reminders', 'Clients reminded 7 days before premium is due'),
          ('receivable-ageing', 'Pending payments move to older buckets'),
          ('policy-expiry', 'Expired policies show in Open Items'),
          ('renewal-pipeline', 'Policies within 90 days enter the renewal queue'),
          ('email-outbox', 'Client e-mails leave every 5 minutes')],
    notifications=[('Info', 'Endorsement completed', 'With the premium change, for policies you own.'),
                   ('Info', 'Policy cancelled by endorsement', 'When a cancellation is completed.'),
                   ('Reminder', 'Renewal notice reminders', 'For each notice on your policies.'),
                   ('Task', 'Customer accepted quotation', 'For quotations you created.'),
                   ('Reminder', 'Premium overdue', 'For policies you own.'),
                   ('Alert', 'Policy lapsed', 'No renewal within the grace period.')],
    limits=COMMON_LIMITS + ['Endorsement is offered only on policies in force whose premium is not Pending or Reviewing: renew an expired policy instead.'],
    tips=['Pick the endorsement type first, then Proceed.', 'Attach proof of payment when you record it.',
          'Start the day on Open Items.', 'Tell the Processing Team when the insurer’s endorsement arrives.'],
))

# ============================================================== Claims
PERSONAS.append(dict(
    user='carlo.claims', file='BrokerVerse_Claims_Guide.pptx', label='Claims', full_label='Claims',
    users='carlo.claims (maker), lisa.claims2 (checker)', role_code='claims', landing='Claims Dashboard',
    title_chips=['Register claims', 'Settle with a checker', 'Recoveries'],
    does=[('Registers claims:', 'from the policy, with date, place and cause of loss, the driver and third party.'),
          ('Follows up:', 'the insurer and the adjuster, documents and the insurer’s claim number.'),
          ('Settles:', 'submits the settlement; a second Claims user approves it.'),
          ('Recovers:', 'registers reinsurance recoveries on claims under a treaty.')],
    signin='User names carlo.claims and lisa.claims2. Both land on the Claims Dashboard.',
    hands_to='Insurer (Preliminary Loss Advice by e-mail), the second Claims user (approval), the policy owner '
             '(notified), Accounting (settlements paid through the broker).',
    partners='carlo.claims submits the settlement and lisa.claims2 approves it. The maker is refused when approving '
             '(claims.settlement_maker_checker).',
    menu=[('Dashboard', ['Claims Dashboard']), ('Operations', ['Home', 'Clients', 'Policy', 'Claims']),
          ('Reinsurance', ['Claims Recovery']), ('Reports', ['All Reports (8 reports)', REP_OPS])],
    menu_note='Menus granted to claims in menuPermissions.js. The role walk opened 12 screens.',
    functions=[
        dict(title='Claims Dashboard', **shot('dash-claims', 'Dashboard > Claims Dashboard'),
             menu='Dashboard > Claims Dashboard',
             points=[('Cards:', 'open claims, overdue, today’s claims, highest line, most claims by state.'),
                     ('Overdue:', 'past the handling time of 20 days (claims.sla_days).'),
                     ('Recent claims:', 'open a claim from the list.'),
                     ('Export Report:', 'claims data for the chosen dates.')]),
        dict(title='Claims list', **shot('claim-list', 'Operations > Claims'),
             menu='Operations > Claims',
             points=[('Row:', 'claim number, client, policy, date, product, status.'),
                     ('Icons:', 'Claim Details, the next step for the status, and the audit trail.'),
                     ('Statuses:', 'Pending, Processing, Pending Approval, Approved, Settled, Closed; Rejected.'),
                     ('Number:', 'CLM-YYYY-NNNNN.')]),
        dict(title='Register a claim', **shot('claim-request', 'Policy > three dots > Claim'),
             menu='Operations > Policy > three dots > Claim',
             points=[('Required:', 'date and address of incident, cause of loss, driver’s name.'),
                     ('Refused:', 'loss date outside the policy period or in the future, and while premium is unpaid.'),
                     ('Documents:', 'police report, photos, estimates; PNG, JPEG or PDF up to 2 MB each.'),
                     ('Saved:', 'claim Pending; Preliminary Loss Advice e-mailed to the insurer.')]),
        dict(title='Adjuster details', **shot('claim-adjuster', 'Claim > Proceed > adjuster details'),
             menu='Claims > eye icon > Proceed',
             points=[('When:', 'the insurer has assigned an adjuster.'),
                     ('Enter:', 'adjuster name, insurer claim number, dates, place, driver and third party.'),
                     ('Upload:', 'proof of documents.'),
                     ('Next:', 'status becomes Processing.')]),
        dict(title='Submit the settlement (maker)', **shot('claim-settlement', 'Claim Settlement'),
             menu='Claim > Claim Settlement',
             points=[('Enter:', 'settlement type (Cash, Card, Cheque), amount, issue date, settle date, documents.'),
                     ('Checks:', 'amount above zero; settle date not before the issue date.'),
                     ('Submit:', 'claim goes to Pending Approval; the other Claims users are notified.'),
                     ('Co-insured policy:', 'the settlement is split by each insurer’s share.')]),
        dict(title='Approve the settlement (checker)', **shot('claim-approval', 'Waiting for Settlement, checker view'),
             menu='Notification, or Claims > Pending Approval',
             points=[('Check:', 'the claim details and the settlement.'),
                     ('Proceed:', 'approves; Reject sends it back to the maker.'),
                     ('Rule:', 'the maker cannot approve his or her own settlement.'),
                     ('Result:', 'claim Settled, maker notified, dashboard and reports updated.')]),
        dict(title='Claim details and letters', **shot('claim-detail', 'Claim Details, CLM-2026-90007', crop=(0, 0, 1400, 1000)),
             menu='Operations > Claims > claim',
             points=[('Shows:', 'claim, incident, driver, policy, third party, insurer claim number, due date.'),
                     ('Letters:', 'Acknowledgment letter, Claims Discharge Voucher, Claims Data sheet, FIR on the letterhead.'),
                     ('Audit trail:', 'every status change with user and time.'),
                     ('Co-insurance:', 'each insurer’s share of the claim and of the settlement.')]),
        dict(title='Settlement cash (paid through the broker)', **shot('claim-cash', 'Settlement cash of CLM-2026-90007'),
             menu='Settled claim > Settlement cash',
             points=[('When:', 'the insurer pays the broker and the broker pays the claimant.'),
                     ('Booked at settlement:', 'amount recoverable from each insurer by share, against the amount payable to the claimant.'),
                     ('Recorded by:', 'the System Administrator on Accounting’s instruction in this release.'),
                     ('You:', 'tell Accounting when the insurer’s funds are due.')]),
        dict(title='Reinsurance claims recovery', **shot('ri-recovery', 'Reinsurance > Claims Recovery'),
             menu='Reinsurance > Claims Recovery',
             points=[('Shows:', 'amounts recoverable on claims under treaties.'),
                     ('Register Recovery:', 'record the recovery against the claim.'),
                     ('Posting:', 'a settled recovery is posted through its posting rule.'),
                     ('Report:', 'Reinsurance Cession Register is run by Processing and Accounting.')]),
    ],
    flow_mine=[11], flow_loop='Claims experience feeds the renewal price',
    flow_notes=['11 Claim: register, follow up, settle with a second user.', 'The policy period and paid premium are checked at registration.',
                'Owners are notified at each status change.', 'Recoveries go to Reinsurance > Claims Recovery.'],
    reports=reports_for('claims'), reports_note='Eight operational reports in Reports > All Reports.',
    jobs=[('daily-reports', 'Claims Position generated at 05:00'),
          ('policy-expiry', 'Losses after expiry are refused once the policy is Expired'),
          ('email-outbox', 'Loss advices to insurers leave every 5 minutes')],
    notifications=[('Task', 'New claim', 'Claim number and policy, to Claims users and the policy owner.'),
                   ('Approval', 'Settlement approval', 'Amount and claim, to the other Claims users.'),
                   ('Info', 'Claim status changes', 'Processing, Pending Approval, Approved, Settled.'),
                   ('Info', 'Settlement approved', 'Back to the maker.')],
    limits=COMMON_LIMITS + [LIM_SETTLE, 'Claims users do not create leads or policies: those buttons are hidden for this role.'],
    tips=['Check the policy period before you register.', 'Attach documents when you register.',
          'Record the insurer’s claim number as soon as you have it.', 'Ask your checker to approve the same day.'],
))

# ============================================================== Accounting
ACC_MENU = [('Dashboard', ['Executive Dashboard']), ('Operations', ['Open Items', 'Payments']),
            ('Accounts', ACC_ALL),
            ('Master > Finance', ['Taxation', 'Close Checklist', 'Bank Statement Formats', 'Bank Transaction Types']),
            ('Commission', ['Commission Dashboard', 'Agents/Referrer Accounts']), ('Reinsurance', ['Reconciliation']),
            ('Reports', ['All Reports (32 reports)', 'Financial Reports (15 shortcuts)',
                         'Operational Reports: Remittance, Broker Commission'])]
ACC_JOBS = [('receivable-ageing', 'Ageing buckets 30, 60, 90, 120 refreshed'),
            ('collection-reminders', 'Clients e-mailed 7 days before due, then every 7 days'),
            ('recurring-journals', 'Posts recurring templates on their next run date'),
            ('accrual-reversal', 'Reverses accruals, deferrals and FX revaluation on day 1'),
            ('period-auto-soft-close', 'Soft-closes ended periods when no blocking check fails'),
            ('bank-auto-match', 'Runs the matching rules on unmatched bank lines'),
            ('month-end-reminder', 'Reminds Accounting before and after a period ends')]
PERSONAS.append(dict(
    user='liza.finance', file='BrokerVerse_Accounting_Guide.pptx', label='Accounting', full_label='Accounting',
    users='liza.finance; fe.approver and fin.approver as second users', role_code='accounting', landing='Executive Dashboard',
    title_chips=['Receipts and remittance', 'Bank reconciliation', 'Month-end and BIR'],
    does=[('Collects:', 'verifies payments, posts official receipts, follows collections and ageing.'),
          ('Pays:', 'commission to referrers, net premium to each insurer by share, suppliers by voucher and cheque.'),
          ('Bills insurers:', 'direct-bill commission on debit notes and records the insurer’s payment.'),
          ('Keeps the ledger:', 'journal vouchers, write-offs, bank reconciliation, month-end and year-end preparation.'),
          ('Files tax:', 'BIR Form 2307, VAT Summary, SAWT, QAP and SLSP.')],
    signin='User name liza.finance. Lands on the Executive Dashboard. fe.approver and fin.approver hold the same role '
           'and act as the second user.',
    hands_to='A second Accounting user (vouchers, JVs, remittances, settlements, debit notes, incentive batches), the '
             'Accounting Manager (close runs, reconciliations), insurers and referrers.',
    partners='Maker-checker is on (finance.maker_checker_enabled, journal.require_approval): you cannot approve what '
             'you prepared.',
    menu=ACC_MENU,
    menu_note='Menus granted to accounting in menuPermissions.js. The role walk opened 81 screens.',
    functions=[
        dict(title='Verify a payment and post the receipt', **shot('acc-receipt-add', 'Accounts > Receipts > Receipt', crop=(0, 0, 1400, 1000)),
             menu='Notification “Premium payment to verify”, or Accounts > Receipts',
             points=[('Verify:', 'check the bank statement, then Confirm (posts the OR) or Reject with a reason.'),
                     ('Direct:', 'pick the client, policy and open bill; enter the amount or Pay full balance.'),
                     ('Journal:', 'Dr Cash in Bank / Cr Premiums Receivable; bill Partial or Paid.'),
                     ('Rule:', 'the amount cannot exceed the bill balance.')]),
        dict(title='Collections and ageing', **shot('acc-collections', 'Accounts > Collections'),
             menu='Accounts > Collections',
             points=[('Buckets:', 'Current, 1-30, 31-60, 61-90, over 90 days.'),
                     ('Due date:', 'the insurer’s premium payment warranty, else 30 days.'),
                     ('Reminders:', 'the 08:00 job, or Send Payment Reminders Now.'),
                     ('Go-live:', 'Import open items loads unpaid bills of the old system, with no journal.')]),
        dict(title='Pay commission to a referrer', **shot('comm-referrer', 'Commission > Agents/Referrer Accounts > referrer'),
             menu='Commission > Agents/Referrer Accounts',
             points=[('Eligible:', 'when the premium is fully collected and a bank account is on file.'),
                     ('WHT:', 'individual 5%, company 10% (commission.wht_rate_by_type).'),
                     ('Two users:', 'Approve the lines, Generate payout; a second user approves the voucher.'),
                     ('Journal:', 'Dr Commission Payable / Cr Cash in Bank and WHT payable.')]),
        dict(title='Remit premium to insurers', **shot('rem-settlement', 'Accounts > Remittance > Settlement'),
             menu='Accounts > Remittance',
             points=[('Draft:', 'Automated Processing creates REM- per insurer from collected premium.'),
                     ('Approve:', 'by a second user; level by amount (₱ 100,000, ₱ 1,000,000, above).'),
                     ('Settle:', 'premium less commission less tax, plus or minus adjustments; SET- raises the insurer PV.'),
                     ('Co-insurance:', 'each insurer is remitted its own share; refunds are netted.')]),
        dict(title='Direct bill: commission debit notes', **shot('rem-db-raise', 'Remittance > Direct Bill Processing'),
             menu='Accounts > Remittance > Direct Bill Processing',
             points=[('Raise:', 'insurer and dates, Load policies, tick them; commission plus 12% VAT, less 10% EWT.'),
                     ('Approve:', 'a second user approves, prints and e-mails the DN-.'),
                     ('Collect:', 'Post collection with cash and tax withheld; partial payments allowed.'),
                     ('Billing Mode tab:', 'switch a policy with a reason, unless premium was collected.')]),
        dict(title='Disbursement: vouchers and cheques', **shot('acc-disb-create', 'Accounts > Disbursement > Create'),
             menu='Accounts > Disbursement',
             points=[('Payee:', 'customer, insurer, agent or referrer, or supplier; then tick the payables.'),
                     ('Statuses:', 'Draft, For approval, Approved, Paid; Cancelled.'),
                     ('Checker:', 'approves the cheque; print it and the voucher becomes Paid.'),
                     ('Bulk:', 'Bulk Disburse, one payout voucher per referrer with approved commission.')]),
        dict(title='Journal vouchers', **shot('acc-jv-add', 'Accounts > Journal Voucher > Voucher'),
             menu='Accounts > Journal Voucher',
             points=[('Lines:', 'main account, sub account, debit or credit, branch, department, amount.'),
                     ('Balance:', 'an unbalanced voucher is refused with the difference.'),
                     ('Periods:', 'soft-closed only for the Accounting Manager; closed periods refuse it.'),
                     ('Correction and Reversal JV:', 'reverse and repost a posted voucher, after approval.')]),
        dict(title='What operations post to the ledger', **shot('policy-accounting', 'Premium accounting entries of POL-2026-00001'),
             menu='Policy > Documents & Billing > Premium Accounting Entries',
             points=[('Posting rules:', 'every system journal comes from the rule of its business event.'),
                     ('Per insurer:', 'payables and commission of a co-insured policy carry the insurer on each line.'),
                     ('Trail:', 'new business, receipts, commission, remittance, endorsements for one policy.'),
                     ('Changes:', 'posting rules are kept by the System Administrator, with the Accounting Manager.')]),
        dict(title='Bank reconciliation workspace', **shot('br-workspace', 'Bank Reconciliation workspace, ACC-BDO-001, August 2026', crop=(0, 0, 1400, 1000)),
             menu='Accounts > Bank Reconciliation > Reconciliation Workspace',
             points=[('Import:', 'CSV or XLSX in the bank’s format (BDO, BPI, Metrobank, generic); BST- issued.'),
                     ('Match:', 'Auto-match rules, then Match selected by hand with the treatment of any difference.'),
                     ('Bank items:', 'Create adjustment for charges and interest; Mark as bank error.'),
                     ('Prepare:', 'Start reconciliation (BRC-), difference ₱ 0.00, Prepare; the Accounting Manager approves.')]),
        dict(title='Month-end close: prepare', **shot('pe-close-run', 'Month-End Close 2026-08, MEC-2026-00001', crop=(0, 0, 1400, 1080)),
             menu='Accounts > Period End > Month-End Close',
             points=[('Steps:', 'accruals, recurring journals, commission deferral, FX revaluation, checklist.'),
                     ('Checklist:', 'automatic checks Passed, Warning or Failed; sign off the manual items.'),
                     ('Submit close:', 'blocked while a blocking item fails or is not signed off.'),
                     ('Approval:', 'the Accounting Manager approves; the period becomes closed.')]),
        dict(title='BIR Form 2307 and tax reports', **shot('tax-2307', 'Accounts > Tax > BIR Form 2307'),
             menu='Accounts > Tax',
             points=[('2307:', 'Issued by us (payees) or Received (insurers, clients), per quarter; CWT- when issued.'),
                     ('VAT Summary:', 'working paper for 2550M / 2550Q.'),
                     ('SAWT, QAP, SLSP:', 'alphalists in BIR column order.'),
                     ('Before filing:', 'fill in the BIR group of Master > Configuration.')]),
        dict(title='Due to insurers by co-insurer', **shot('rep-due-insurers', 'Reports > Financial Reports > Due to Insurers by Co-insurer'),
             menu='Reports > Financial Reports',
             points=[('Shows:', 'premium due to each insurer on the bills of the period.'),
                     ('Columns:', 'due, collected, remitted and still held, per participant.'),
                     ('With:', 'Co-insurance Register and Aged Payables to Insurers.'),
                     ('Formats:', 'CSV, Excel or PDF on the letterhead.')]),
    ],
    extras=[dict(kind='table', title='From operations to the ledger', kicker='Posting rules (Master > Finance)',
                 intro='Each business event posts its journal through a posting rule. The main events and their journals:',
                 rows=[('Event (who)', 'Journal'),
                       ('Policy issued, broker billed (Processing)', 'Dr Premiums Receivable / Cr Premiums Payable to Insurers, premium taxes, Brokerage Commission Income (per insurer)'),
                       ('Policy issued, direct bill (Processing)', 'Dr Commission Receivable - Insurers / Cr Brokerage Commission Income, Output VAT Payable'),
                       ('Official receipt (Accounting)', 'Dr Cash in Bank / Cr Premiums Receivable'),
                       ('Debit note collected (Accounting)', 'Dr Cash in Bank, Creditable Withholding Tax (2307) / Cr Commission Receivable - Insurers'),
                       ('Comsub approved and paid (Accounting)', 'Dr Commission Expense / Cr Commission Payable; then Dr Commission Payable / Cr Cash, WHT'),
                       ('Remittance settled (Accounting)', 'Dr Premiums Payable to Insurers / Cr Cash in Bank'),
                       ('Endorsement (Operations, Processing)', 'Additional premium billed, or return premium credited and netted on the next remittance'),
                       ('Claim through the broker (Claims)', 'Recoverable from each insurer by share / payable to the claimant')],
                 widths=[3.4, 8.9], size=11.5,
                 note='Example: POL-2026-00001 (Malayan 60%, Standard 40%) posted JV-2026-00087: receivable 334,031.25; '
                      'payable to insurers 228,375.00; premium taxes 66,281.25; commission income 39,375.00.')],
    flow_mine=[7, 8, 9, 13], flow_loop='Endorsement and renewal bills come back to you as receipts',
    flow_notes=['7 Official receipt: verify the payment and post the OR.', '8 Commission: approve lines, pay by voucher.',
                '9 Remittance: net premium to each insurer by share.', '13 Month-end: reconcile banks, prepare the close, BIR.'],
    reports=reports_for('accounting'), reports_note='32 reports; tax and bank reports also under Accounts.',
    jobs=ACC_JOBS,
    jobs_note='Jobs marked off are delivered switched off: ask the System Administrator to switch on the ones you want. '
              'Times are Manila time.',
    notifications=[('Approval', 'Premium payment to verify', 'A payment recorded by another team, with mode, amount and reference.'),
                   ('Approval', 'Journal voucher awaiting approval', 'To the other Accounting users.'),
                   ('Approval', 'Remittances awaiting approval', 'Batch and count.'),
                   ('Approval', 'Commission debit note awaiting approval', 'Direct-bill debit notes.'),
                   ('Approval', 'Incentive calculation / petty cash request', 'Not your own.'),
                   ('Alert', 'Petty cash below minimum', 'To the fund custodian.'),
                   ('Reminder', 'Month-end close reminder', 'When the job is switched on.'),
                   ('Info', 'Journal voucher approved / rejected', 'Back to the maker.')],
    limits=[LIM_CASH, LIM_BIR, LIM_NO_BELL, LIM_TZ],
    tips=['Pick the bill, not only the policy, when you receipt.', 'Reconcile each bank account before you submit the close.',
          'Import open items and opening balances with the same go-live date.',
          'Ask the second user to approve on the same day.', 'Keep the OR series in line with the Authority to Print.'],
))

# ============================================================== Accounting Manager
PERSONAS.append(dict(
    user='acct.manager', file='BrokerVerse_Accounting_Manager_Guide.pptx', label='Accounting Manager',
    full_label='Accounting Manager (inherits Accounting)',
    users='acct.manager', role_code='accounting-manager', landing='Executive Dashboard',
    title_chips=['Approves the close', 'Bank reconciliation sign-off', 'Period control'],
    does=[('Everything Accounting does:', 'the role includes accounting, so the menus and screens are the same.'),
          ('Approves the month-end close:', 'reviews the checklist and approves or rejects the submitted run.'),
          ('Closes the year:', 'closes income and expense to retained earnings and opens the next year.'),
          ('Signs off bank reconciliations:', 'approves or reopens each reconciliation.'),
          ('Controls periods:', 'soft-closes, closes and reopens periods; posts into soft-closed periods.')],
    signin='User name acct.manager. Lands on the Executive Dashboard, with the Accounting menus.',
    hands_to='Accounting (rejected runs and reconciliations go back with a reason), the System Administrator '
             '(posting rules, GL accounts, jobs), the auditors (statements and reports).',
    partners='You approve what Accounting prepared. You cannot approve a close run, reconciliation, voucher or batch '
             'you prepared yourself.',
    menu=ACC_MENU,
    menu_note='accounting-manager inherits accounting (roles.inherits) and adds approve:period-end and '
              'approve:bank-reconciliation. The role walk opened 81 screens.',
    functions=[
        dict(title='Period Management', **shot('pe-periods-mgr', 'Accounts > Period End > Period Management'),
             menu='Accounts > Period End > Period Management',
             points=[('Periods:', '12 months plus adjustment period 13 per fiscal year.'),
                     ('Open:', 'everyone with posting rights may post.'),
                     ('Soft-closed:', 'only you may post; others are refused.'),
                     ('Closed, Locked:', 'nobody posts. Reopen needs you and remarks, kept in the period history.')]),
        dict(title='Month-end close runs', **shot('pe-close-list', 'Accounts > Period End > Month-End Close'),
             menu='Accounts > Period End > Month-End Close',
             points=[('List:', 'MEC- run per period, run and period status, failures, warnings, preparer, approver.'),
                     ('Submitted:', 'open the run, read the steps and the checklist.'),
                     ('Approve:', 'closes the period. Reject returns it with a reason.'),
                     ('Rule:', 'the approver must differ from the preparer (accounting.period_close_requires_approval).')]),
        dict(title='What to check before you approve', **shot('pe-close-run', 'Month-End Close 2026-08, MEC-2026-00001', crop=(0, 0, 1400, 1080)),
             menu='Month-End Close > run',
             points=[('Blocking items:', 'no pending journals, trial balance balances, suspense cleared, bank reconciliations signed off.'),
                     ('Warnings:', 'unapplied receipts, unreconciled bank lines, unbilled policies, unpaid remittances.'),
                     ('Example:', '2026-08 warned that ACC-BDO-001 had no approved reconciliation.'),
                     ('Journals created:', 'reruns reverse their own earlier journals first.')]),
        dict(title='Close checklist', **shot('pe-checklist', 'Master > Finance > Close Checklist'),
             menu='Master > Finance > Close Checklist',
             points=[('Items:', 'automatic checks and manual sign-offs, each Blocking or Warning.'),
                     ('Add item:', 'a manual item of your own, e.g. payroll booked.'),
                     ('Severity:', 'make an item blocking to stop the submit.'),
                     ('Bank check:', 'from bank_reconciliation.check_from_period onwards.')]),
        dict(title='Year-end close', **shot('pe-year-end', 'Accounts > Period End > Year-End Close'),
             menu='Accounts > Period End > Year-End Close',
             points=[('Needs:', 'all twelve periods closed and period 13 open.'),
                     ('Run checks:', 'periods closed and trial balance balances; post audit adjustments in period 13.'),
                     ('Close the year:', 'income and expense to Current Year P/L, then Retained Earnings; next year opened.'),
                     ('Reverse:', 'with a reason, until the first period of the next year is closed.')]),
        dict(title='Bank reconciliation sign-off', **shot('br-rec', 'Reconciliation BRC-2026-00001, ACC-BDO-001', crop=(0, 0, 1400, 1040)),
             menu='Accounts > Bank Reconciliation > Reconciliations',
             points=[('Statement:', 'bank balance with deposits in transit and outstanding cheques against the books.'),
                     ('Difference:', 'must be ₱ 0.00 before Accounting selects Prepare.'),
                     ('Approve:', 'locks the matches cleared up to the period end.'),
                     ('Reopen:', 'with remarks, to correct a match; every change is in the history.')]),
        dict(title='Remittance approvals', **shot('rem-approval', 'Accounts > Remittance > Approval Workflow'),
             menu='Accounts > Remittance > Approval Workflow',
             points=[('Queue:', 'remittances, settlements, transfers and adjustments with SLA, level and amount.'),
                     ('Levels:', 'up to ₱ 100,000; up to ₱ 1,000,000; above.'),
                     ('Rule:', 'the initiator is refused.'),
                     ('Next:', 'settlement approval raises the insurer payment voucher.')]),
        dict(title='Incentive approvals', **shot('inc-approvals', 'Accounts > Incentive > Approvals'),
             menu='Accounts > Incentive > Approvals',
             points=[('Batches:', 'CALC- per programme and period with the amount per person.'),
                     ('Actions:', 'approve, reject or Bulk Approve, never your own.'),
                     ('After:', 'approved amounts are accrued and paid through their posting rules.'),
                     ('Report:', 'Incentive Results.')]),
        dict(title='Financial statements', **shot('pe-statements', 'Accounts > Period End > Financial Statements'),
             menu='Accounts > Period End > Financial Statements',
             points=[('Income Statement:', 'period, year to date, prior year period and prior year to date.'),
                     ('Balance Sheet:', 'balances at the To date against the prior year end.'),
                     ('Trial Balance:', 'opening, movement and closing per account.'),
                     ('PDF:', 'the same statements under Reports > Financial Reports, on the letterhead.')]),
    ],
    extras=[dict(kind='table', title='Your approvals', kicker='What only you can do',
                 rows=[('Approval', 'Where', 'Permission'),
                       ('Approve or reject a month-end close', 'Period End > Month-End Close > run', 'approve:period-end'),
                       ('Close the year, reverse a year-end close', 'Period End > Year-End Close', 'approve:period-end'),
                       ('Soft-close, close and reopen periods', 'Period End > Period Management', 'approve:period-end'),
                       ('Post into a soft-closed period', 'Any posting screen', 'approve:period-end'),
                       ('Approve or reopen a bank reconciliation', 'Bank Reconciliation > Reconciliations', 'approve:bank-reconciliation'),
                       ('Approve vouchers, JVs, remittances, batches of others', 'The approval screen of each module', 'as Accounting')],
                 widths=[4.5, 4.6, 3.2], size=12.5,
                 note='Posting rules, GL accounts, tax rates and maker-checker switches change only with your agreement; '
                      'the System Administrator makes the change on Master.')],
    flow_steps=[('Import statements', 'Accounting'), ('Match, adjust', 'Accounting'), ('Prepare BRC', 'Accounting'),
                ('Approve BRC', 'You'), ('Close run', 'Accounting'), ('Checklist sign-off', 'Accounting'),
                ('Submit close', 'Accounting'), ('Approve close', 'You'), ('Period closed', 'System'),
                ('BIR reports', 'Accounting'), ('Year-end close', 'You'), ('Next year opened', 'System')],
    flow_mine=[4, 8, 11], flow_title='Month-end and year-end: your part', flow_kicker='Bank to closed period',
    flow_loop='Each month; the year-end after period 12',
    flow_notes=['Approve each bank reconciliation before the close: it is a blocking checklist item.',
                'Read the warnings as well as the blocking items before you approve.',
                'Reopen a period only with remarks; the history keeps who and when.',
                'Check the Month-End Close Status report across periods.'],
    reports=reports_for('accounting'), reports_note='The 32 reports of Accounting.',
    jobs=ACC_JOBS,
    jobs_note='Jobs marked off are delivered switched off; you decide with the System Administrator which to switch on.',
    notifications=[('Approval', 'Journal voucher awaiting approval', 'You can approve vouchers of other users.'),
                   ('Approval', 'Remittances awaiting approval', 'Batch and count.'),
                   ('Approval', 'Incentive calculation awaiting approval', 'Batch and period.'),
                   ('Approval', 'Commission debit note awaiting approval', 'Direct-bill debit notes.'),
                   ('Reminder', 'Month-end close: period ends / still open', 'When the reminder job is switched on.'),
                   ('Task', 'Close runs and reconciliations', 'No bell notice: check the lists for Submitted and Prepared.')],
    limits=[LIM_NO_BELL, LIM_BIR, LIM_TZ, LIM_CASH],
    tips=['Approve reconciliations before close runs.', 'Reject with a clear reason: it goes back to the preparer.',
          'Keep soft-close for the review days, then close.', 'Agree posting rule changes and simulate them first.'],
))
