"""Content of the BrokerVerse persona guides (read by build_decks.py).

Sources: brokerverse/src/utils/menuPermissions.js and components/SideBar/list.js (menus), report_definitions
(backend/src/db/seeds/60_reports.sql, report roles), backend/src/db/seeds/jobs.json (schedules), app_settings
(business rules), docs/e2e/E2E_REPORT.md (flows and money trail) and docs/e2e/DEFECTS.md (open items only).
Screens: '<user>__<screen>.png' from capture_screens.py, or 'evidence:<file>' from docs/e2e/evidence.
"""

FLOW_STEPS = [
    ('Lead', 'Agent / Sales / CS'),
    ('Quote', 'Agent / Sales / UW'),
    ('Customer approval', 'Client (e-mail link)'),
    ('Policy', 'Agent / Sales / UW'),
    ('Billing', 'System at issuance'),
    ('Receipt', 'Finance'),
    ('Commission', 'Finance maker + checker'),
    ('Remittance', 'Finance maker + checker'),
    ('Endorsement', 'Customer Services'),
    ('Claim', 'Claims maker + checker'),
    ('Renewal', 'UW / Sales + schedules'),
]

# code: (name, what it shows, where, category)
REPORTS = {
    'production-register': ('Production Register', 'Policies incepted in the period: premium, commission, new or renewal; by agent, insurer or branch', 'Reports > Operational > Production', 'operational'),
    'claims-position': ('Claims Position', 'Claims reported: estimate, approved, settled, age; criteria All / Open / Settled / Rejected / Aging', 'Reports > Operational > Claims', 'operational'),
    'renewal-retention': ('Renewal Retention', 'Renewals due: retained, lost or pending, old vs new premium, retention rate', 'Reports > Operational > Renewal', 'operational'),
    'remittance-summary': ('Remittance Summary', 'Remittances to insurers: gross premium, commission retained, net due, status', 'Reports > Operational > Remittance', 'operational'),
    'commission-statement': ('Broker Commission Statement', 'Commission per agent and policy: basis, rate, gross, WHT, net, paid status', 'Reports > Operational > Broker Commission', 'operational'),
    'premium-by-product': ('Premium by Product / Month / Insurer', 'Policy count, sum insured, premium and commission by month, product or insurer', 'Executive Dashboard > Export Report', 'operational'),
    'new-vs-renewal': ('New Business vs Renewals', 'Policies and premium split into new business and renewals per month', 'Executive Dashboard > Export Report', 'operational'),
    'claims-ageing': ('Claims Ageing', 'Open claims by ageing bucket (30/60/90/180 days) with estimate and approved', 'Claims Dashboard > Export Report', 'operational'),
    'lead-conversion-funnel': ('Lead Conversion Funnel', 'Leads by stage (new to converted / lost) with share and conversion rate', 'Leads > Generate Report', 'operational'),
    'cession-register': ('Reinsurance Cession Register', 'Cessions per treaty and policy: sum insured, ceded sum and premium, share', 'Reinsurance > Cession Tracking', 'operational'),
    'premium-receivable-soa': ('SOA / Premium Receivable', 'Bills issued: amount, paid, balance, age and ageing bucket as of To Date', 'Reports > Financial > SOA / Premium Receivable', 'financial'),
    'collections-summary': ('Collection Report', 'Bills due: billed, collected, balance and collection rate', 'Reports > Financial > Collection Report', 'financial'),
    'collections-ageing': ('Receivables Ageing', 'Outstanding receivables by bucket (30/60/90/120 days)', 'Accounts > Collections > Aging Report', 'financial'),
    'receipts-register': ('Receipts Register', 'Official receipts: bill, policy, payment mode, bank, reference', 'Accounts > Receipts', 'financial'),
    'disbursement-register': ('Payables / Disbursement Register', 'Payment vouchers to insurers, agents, clients, vendors with approval and paid dates', 'Reports > Financial > Payables', 'financial'),
    'journal-register': ('Journal Register', 'Journal lines: account, debit, credit, memo', 'Reports > Financial > Journal', 'financial'),
    'trial-balance': ('Trial Balance', 'Opening, period debits and credits, closing balance per account (approved and posted JVs)', 'Reports > Financial > Trail Balance', 'financial'),
    'incentive-results': ('Incentive Results', 'Programme target, achieved, achievement % and payout per agent', 'Accounts > Incentive', 'financial'),
}
ALL_REPORTS = list(REPORTS)

# code: (name, plain-language timing, description)
JOBS = {
    'daily-reports': ('Daily reports', 'Every day, 05:00', 'Production register, collections, claims position'),
    'renewal-pipeline': ('Renewal pipeline', 'Every day, 05:30', ''),
    'renewal-notices': ('Renewal notices', 'Every day, 06:00', ''),
    'receivable-ageing': ('Receivable ageing', 'Every day, 07:00', ''),
    'collection-reminders': ('Collection reminders', 'Every day, 08:00', ''),
    'policy-expiry': ('Policy expiry', 'Every day, 00:15', ''),
    'quote-expiry': ('Quotation expiry', 'Every day, 00:30', ''),
    'email-outbox': ('E-mail outbox', 'Every 5 minutes', ''),
    'renewal-queue': ('Renewal notice queue', 'Every minute', ''),
    'report-schedules': ('Report schedules', 'Your own timetable', ''),
}

M_DASH_ALL = ['Executive Dashboard', 'Claims Dashboard', 'Underwriting Dashboard', 'Agent Dashboard']
M_PC_ALL = ['Dashboard', 'Product Templates', 'Coverage Builder', 'Rating Engine', 'Underwriting Rules',
            'Document Manager', 'Approval Workflows', 'Market / Risk Mapping', 'Product Analytics']
M_OPS_ALL = ['Home', 'Leads/Prospects', 'Clients', 'Quotation', 'Policy', 'Claims',
             'Renewals: Renewal Policy, Batch, Queue, Retention Analytics, At-Risk, Negotiations, Lapse Mgmt, Performance',
             'Open Items', 'Payments']
M_MASTER_ALL = ['System Settings, Configuration, Schedules, Audit Trail',
                'Generals: Organization, Insurance Mgmt, Location, Commission, Employee Mgmt, User Mgmt',
                'Finance: account setups, transaction codes, currency, FX, bank, accounts, taxation, petty cash, remittance',
                'Incentive Programs', 'Reinsurance Treaty']
M_ACC_ALL = ['Receipts, Collections', 'Accounting Query, All Clients Accounting', 'Open Entry Matching / Un-Matching',
             'Disbursement', 'Petty Cash (5 screens)', 'Journal, Correction and Reversal JV', 'Remittance (17 screens)',
             'Incentive (4 screens)']
M_RI_ALL = ['Treaty Dashboard', 'Cession Tracking', 'Claims Recovery', 'Reconciliation', 'Analytics']
M_REP_ALL = ['Operational: Production, Claims, Renewal, Remittance, Broker Commission',
             'Financial: SOA / Premium Receivable, Collection, Payables, Journal, Trial Balance']
MENU_ALL = [('Dashboard', M_DASH_ALL), ('Product Configurator', M_PC_ALL), ('Master', M_MASTER_ALL),
            ('Operations', M_OPS_ALL), ('Accounts', M_ACC_ALL), ('Commission', ['Commission Dashboard', 'Agents/Referrer Accounts']),
            ('Reinsurance', M_RI_ALL), ('Reports', M_REP_ALL)]

COMMON_LIMITS = [
    'Some date pickers still show month-first dates (MM/DD/YYYY) although the configured format is DD/MM/YYYY.',
    'A few screens use the browser’s own confirm boxes instead of in-app dialogs.',
]
QUOTE_LIMITS = [
    'Contact number accepts the 10-digit form (9171234567); 09… and +63… forms are not yet accepted.',
    'An existing lead has no “Create Quote” action yet: create the quote right after saving the lead.',
    'Some quote lists (policy types, vehicle details, signatories) are fixed lists until linked to the masters.',
    'CTPL treatment (separate policy or part of the premium) is awaiting a business decision.',
]
POLICY_LIMITS = [
    'ID card, ID number and vehicle identifiers are not yet mandatory at conversion: check them before Next.',
    'The payment step at conversion is a simulated confirmation; real receipting is done by Finance.',
]


def cap(screen, user, live=True):
    return (f'Live screen — {screen} — signed in as {user}' if live
            else f'Screen from the recorded end-to-end run — {screen} — {user}')


PERSONAS = []

# ============================================================== IT administrator
PERSONAS.append(dict(
    user='BrokerVerse', file='BrokerVerse_IT_Administrator_Guide.pptx', label='IT Administrator',
    users='BrokerVerse', role_code='it-admin', landing='Home (business overview dashboard)',
    title_chips=['All menus', 'Settings and schedules', 'Users and roles'],
    does=[('Runs the platform:', 'users, roles, system settings, configuration values and scheduled jobs.'),
          ('Keeps it safe:', 'password policy, sign-in limits, two-factor per role, audit trail review.'),
          ('Supports every persona:', 'full menu access to reproduce and fix issues on any screen.'),
          ('Owns integrations:', 'API (543 endpoints), Postman collection, OpenAPI and the e-mail outbox.'),
          ('Operates automation:', 'nine scheduled jobs and report schedules, with Run now and run history.')],
    signin='User name BrokerVerse on the BrokerVerse sign-in page. Lands on Home, the business overview '
           'dashboard. Idle sessions end after 30 minutes (setting).',
    hands_to='User Access Administrators for day-to-day user requests; Business Administrator for products, '
             'masters and rates; Finance for anything posted to the ledger.',
    partners='Administrator roles pass every permission check, but maker-checker still applies to vouchers, '
             'claims settlements and renewals: you cannot approve what you created.',
    menu=MENU_ALL, menu_note='The it-admin role has every menu (all: true) and every read / write permission.',
    functions=[
        dict(title='Executive dashboard', shot='BrokerVerse__exec.png', menu='Dashboard > Executive Dashboard',
             caption=cap('Dashboard > Executive Dashboard', 'BrokerVerse'),
             points=[('Purpose:', 'one view of revenue, active policies, new business and claims ratio.'),
                     ('Filters:', 'date range and period; Export Report gives Premium by Product and New vs Renewals.'),
                     ('Source:', 'live policies, bills and claims, so it moves as soon as a policy is issued.'),
                     ('Check:', 'after a release, confirm each dashboard loads for each persona.')]),
        dict(title='User management', shot='BrokerVerse__users.png', menu='Master > Generals > User Management > User',
             caption=cap('Master > User Management > User', 'BrokerVerse'),
             points=[('Purpose:', 'create, edit, deactivate and unlock users; assign one or more roles.'),
                     ('Rules:', 'at least one role; password min 8 with upper, lower, digit and symbol; last 5 not reused; 90-day expiry.'),
                     ('Lockout:', 'repeated failed sign-ins lock the user; unlock from the list (status).'),
                     ('Downstream:', 'every change is written to the audit trail with before and after values.')]),
        dict(title='Roles and permissions', shot='BrokerVerse__roles.png', menu='Master > Generals > User Management > Role',
             caption=cap('Master > User Management > Role', 'BrokerVerse'),
             points=[('Purpose:', 'the nine personas are roles: it-admin, ba, sales, underwriting, customer-services, claims, finance, agent, user-access-admin.'),
                     ('Permissions:', 'read / write per module (25 modules, e.g. write:receipts, read:audit).'),
                     ('Scope:', 'agents see only their own book (security.scoped_roles).'),
                     ('Rule:', 'only non-system roles with no users can be deleted.')]),
        dict(title='System settings: branding and locale', shot='BrokerVerse__syssettings.png', menu='Master > System Settings',
             caption=cap('Master > System Settings', 'BrokerVerse'),
             points=[('Purpose:', 'application title, logo presets, favicon, theme colours.'),
                     ('Locale:', 'display currency PHP, language, Philippine number grouping.'),
                     ('Effect:', 'applies to every user, including the sign-in page.'),
                     ('Tip:', 'use Theme preview before Save.')]),
        dict(title='Configuration: business parameters', shot='BrokerVerse__config.png', menu='Master > Configuration',
             caption=cap('Master > Configuration', 'BrokerVerse'),
             points=[('Purpose:', 'every business value in one place, grouped in tabs (accounting, branding, claims, collections, commission, currency, e-mail, security…).'),
                     ('Examples:', 'GL accounts, VAT 12%, DST, LGT 0.75%, renewal notice days 60/30/15, maker-checker switches.'),
                     ('Effect:', 'changes apply immediately and are audited.'),
                     ('Care:', 'change GL accounts only with Finance sign-off.')], size=12),
        dict(title='Schedules', shot='BrokerVerse__schedules.png', menu='Master > Configuration > Schedules',
             caption=cap('Master > Schedules', 'BrokerVerse'),
             points=[('Purpose:', 'nine jobs: renewal notices, expiries, ageing, daily reports, e-mail outbox, reminders.'),
                     ('Actions:', 'change timetable, enable / disable, Run now; results shown as “Updated: 5”.'),
                     ('History:', 'last run and status per job; each run is audited.'),
                     ('Time:', 'server time; set the server to Asia/Manila in production.')]),
        dict(title='Audit trail', shot='BrokerVerse__audit.png', menu='Master > Configuration > Audit Trail',
             caption=cap('Master > Audit Trail', 'BrokerVerse'),
             points=[('Purpose:', 'every create, update, approval, report run and sign-in, newest first.'),
                     ('Filters:', 'record type, record ID, user.'),
                     ('Coverage:', 'logins, reports, jobs, endorsements, receipts, claims, vouchers, cheques, remittances, settlements.'),
                     ('Use:', 'investigations, access reviews and proving maker-checker.')]),
        dict(title='Reports', shot='BrokerVerse__production.png', menu='Reports > Operational / Financial',
             caption=cap('Reports > Operational Reports > Production', 'BrokerVerse'),
             points=[('Purpose:', 'all 18 reports: criteria, date range, agent, company, branch, client.'),
                     ('Formats:', 'CSV, XLSX (default) and PDF (A4); up to 50,000 rows.'),
                     ('Delivery:', 'download links valid 72 hours; report schedules e-mail recipients.'),
                     ('Audit:', 'each generated report is recorded.')]),
    ],
    extras=[dict(kind='api', title='API and Postman touchpoints', kicker='backend/docs/api',
                 stats=[('543', 'endpoints (GET 258, POST 198, PUT 57, DELETE 23, PATCH 7)'), ('37', 'modules in the route registry'),
                        ('38', 'folders in the Postman collection'), ('1', 'OpenAPI file, generated from the code')],
                 left_title='What you get',
                 left=['BrokerVerse.postman_collection.json and environment (set base URL and token)',
                       'openapi.json: every path with request and response examples',
                       'BrokerVerse_API_Touchpoints.xlsx / .csv: endpoint, screen that calls it, permission',
                       'Generated from the code, so it matches what is deployed'],
                 right_title='How to use it',
                 right=['POST /api/auth/login returns an access token; send it as Authorization: Bearer',
                        'Refresh with /api/auth/refresh; sign-in is rate limited per IP',
                        'Every endpoint checks read: / write: permissions: a wrong role gets 403',
                        'Useful admin calls: /api/schedules, /api/settings, /api/users, /api/reports'])],
    flow_mine=list(range(1, 12)), flow_title='End-to-end flow: you configure every step',
    flow_loop='Renewal starts the next cycle',
    flow_notes=['Rates and taxes that price quotes come from Configuration and the Product Configurator.',
                'Numbering (LD, QT, POL, INV, OR, PV, JV, CLM, END) comes from settings.',
                'Schedules drive quote and policy expiry, renewal notices, ageing and reminders.',
                'Maker-checker switches (quotes, claims, finance, renewals) are settings you own.'],
    reports=ALL_REPORTS, reports_note='All 18 reports; e-mail schedules through the report schedules API.',
    jobs=[('daily-reports', 'Files ready for managers each morning'),
          ('renewal-pipeline', 'Policies within 90 days enrolled; lapsed after 30 days grace'),
          ('renewal-notices', 'Notices at 60, 30 and 15 days before expiry'),
          ('receivable-ageing', 'Ageing buckets 30/60/90/120 refreshed'),
          ('collection-reminders', 'Clients reminded 7 days before due, then every 7 days'),
          ('policy-expiry', 'Policies past expiry marked expired'),
          ('quote-expiry', 'Quotations past validity expired'),
          ('email-outbox', 'Queued e-mails delivered (needs SMTP configured)'),
          ('renewal-queue', 'Queued renewal notices sent, stale jobs retried')],
    notifications=[('Reminder', 'Premium overdue', 'Collection reminders for policies you own, e.g. “Premium overdue 55 day(s)”.'),
                   ('Approval', 'Remittances awaiting approval', 'Batches over an approval level land with approvers.'),
                   ('Approval', 'Journal voucher awaiting approval', 'Sent to finance approvers when a JV is submitted.'),
                   ('Approval', 'Treaty / incentive awaiting approval', 'Reinsurance treaties and incentive batches need approval.'),
                   ('Alert', 'Petty cash below minimum', 'Sent to the custodian when a fund drops below its minimum.'),
                   ('E-mail', 'Outbox', 'Customer e-mails wait in the outbox until SMTP is configured.')],
    limits=COMMON_LIMITS + [
        'Dashboard quick actions are shown to every role even if the role cannot open the target screen.',
        'Commission accrues to whoever created the policy, including an administrator: issue policies as the agent.',
        'Receipts API is shared with the in-app payment step; separating it is planned.',
        'Chart of accounts has no operating-expense accounts yet (to agree with Finance).'],
    tips=['Keep BrokerVerse for administration; use persona users for business work.',
          'Before go-live: SMTP, server time zone, logo, GL accounts, numbering prefixes.',
          'Use Run now on a schedule after changing its settings, then read the run history.',
          'Review the audit trail weekly for sign-ins and approvals.',
          'Share the Postman collection, not passwords, with integration partners.'],
))

# ============================================================== Business administrator
PERSONAS.append(dict(
    user='bea.admin', file='BrokerVerse_Business_Administrator_Guide.pptx', label='Business Administrator',
    users='bea.admin', role_code='ba', landing='Home (business overview dashboard)',
    title_chips=['Products and rates', 'Masters', 'All business menus'],
    does=[('Designs products:', 'templates, coverages, rating factors, underwriting rules and documents.'),
          ('Keeps masters right:', 'insurers, lines of business, products, covers, signatories, vehicles, locations.'),
          ('Sets commercial terms:', 'commission masters, incentive programmes and reinsurance treaties.'),
          ('Oversees the business:', 'every operational and financial menu, dashboards and all 18 reports.'),
          ('Approves changes:', 'product approval workflows and treaty approvals.')],
    signin='User name bea.admin. Lands on Home, the business overview dashboard.',
    hands_to='Sales, agents and underwriters use your products and rates; Finance uses your commission, tax and '
             'remittance masters; IT administrator owns users and system settings.',
    partners='Treaties and incentive batches need approval by a second person; you cannot approve your own '
             'finance vouchers, claims settlements or renewals.',
    menu=MENU_ALL, menu_note='The ba role has every menu (all: true); use it for business configuration, not user administration.',
    functions=[
        dict(title='Product Configurator dashboard', shot='bea.admin__pcdash.png', menu='Product Configurator > Dashboard',
             caption=cap('Product Configurator > Dashboard', 'bea.admin'),
             points=[('Purpose:', 'active products, total premium, average base rate and commission at a glance.'),
                     ('Actions:', 'Create New Product, open templates, analytics and quick actions.'),
                     ('Status:', 'draft, active or archived per product version.'),
                     ('Downstream:', 'active products appear in the quotation wizard.')]),
        dict(title='Product templates', shot='bea.admin__templates.png', menu='Product Configurator > Product Templates',
             caption=cap('Product Configurator > Product Templates', 'bea.admin'),
             points=[('Purpose:', 'one template per product: motor, property, travel, group health, marine…'),
                     ('Versioning:', 'each change is a new version; only active versions can be quoted.'),
                     ('Links:', 'coverages, rating factors, rules and documents attach to the template.'),
                     ('Approval:', 'approval workflows control publishing.')]),
        dict(title='Rating engine', shot='bea.admin__rating.png', menu='Product Configurator > Rating Engine',
             caption=cap('Product Configurator > Rating Engine', 'bea.admin'),
             points=[('Purpose:', 'rating factors (vehicle age, driver age, no-claims bonus, region, fleet…).'),
                     ('Types:', 'multiplier or discount, with rules per band.'),
                     ('Test Calculation:', 'try a premium before activating.'),
                     ('Downstream:', 'the server re-prices every quote with these rates and the configured taxes.')]),
        dict(title='Insurance company master', shot='bea.admin__insurer.png', menu='Master > Generals > Insurance Management',
             caption=cap('Master > Insurance Company', 'bea.admin'),
             points=[('Purpose:', 'insurers you place business with: code, name, placement e-mail, phone.'),
                     ('Upload:', 'bulk upload or add one at a time; status switch deactivates.'),
                     ('Downstream:', 'quotes, policies, remittances and statements are per insurer.'),
                     ('Tip:', 'keep the placement e-mail current: claims and endorsements are sent there.')]),
        dict(title='Product master', shot='bea.admin__product.png', menu='Master > Generals > Insurance Management > Product',
             caption=cap('Master > Product', 'bea.admin'),
             points=[('Purpose:', 'products by line of business (casualty, motor, fire, EB, marine) with commission code.'),
                     ('Rules:', 'unique product code; commission code must exist.'),
                     ('Downstream:', 'product drives commission accrual and report grouping.')]),
        dict(title='Commission master', shot='bea.admin__commission.png', menu='Master > Generals > Commission',
             caption=cap('Master > Commission', 'bea.admin'),
             points=[('Purpose:', 'brokerage per insurer, product and cover with effective dates.'),
                     ('Rules:', 'one active rate per insurer / product / cover for a date.'),
                     ('Downstream:', 'commission accrues at policy issuance (e.g. 4,200.75 on POL-2026-00001).'),
                     ('WHT:', 'withholding by referrer type (Individual 5%) is applied at payout.')]),
        dict(title='Reinsurance treaties', shot='bea.admin__treaty.png', menu='Master > Reinsurance Treaty',
             caption=cap('Master > Reinsurance Treaty', 'bea.admin'),
             points=[('Purpose:', 'quota share, surplus, excess of loss, stop loss treaties with reinsurer, share and period.'),
                     ('Approval:', 'a new treaty waits for approval before use (setting).'),
                     ('Downstream:', 'cessions, recoveries and the Cession Register report.')]),
        dict(title='Incentive programmes', shot='bea.admin__incentive.png', menu='Master > Incentive Programs',
             caption=cap('Master > Incentive Programs', 'bea.admin'),
             points=[('Purpose:', 'agent contests and bonuses: target, base, frequency, dates.'),
                     ('Flow:', 'Finance calculates, a second person approves the batch, statements follow.'),
                     ('Downstream:', 'Incentive Results report.')]),
    ],
    flow_mine=list(range(1, 12)), flow_title='End-to-end flow: your configuration drives every step',
    flow_loop='Renewal starts the next cycle',
    flow_notes=['Lead and quote: products, coverages, rating and signatories come from your masters.',
                'Policy and billing: product and insurer decide commission and taxes.',
                'Commission and remittance: commission masters and WHT settings.',
                'Claims and renewals: treaties for recoveries; renewal notice settings.'],
    reports=ALL_REPORTS, reports_note='All 18 reports are in your catalogue.',
    jobs=[('daily-reports', 'Production, collections and claims files each morning'),
          ('renewal-pipeline', 'Retention work starts 90 days before expiry'),
          ('renewal-notices', 'Clients get notices at 60, 30, 15 days'),
          ('receivable-ageing', 'Ageing buckets refreshed for collections'),
          ('collection-reminders', 'Clients reminded 7 days before premium is due'),
          ('quote-expiry', 'Old quotations expire after the configured validity')],
    notifications=[('Approval', 'Treaty awaiting approval', 'A new reinsurance treaty needs a second person.'),
                   ('Approval', 'Incentive calculation awaiting approval', 'A calculated batch needs approval before payout.'),
                   ('Info', 'Treaty / incentive approved or rejected', 'Returned to whoever submitted it.'),
                   ('Approval', 'Journal voucher / remittance', 'Admin roles can act as checker when finance is short.')],
    limits=COMMON_LIMITS + QUOTE_LIMITS[2:] + [
        'Chart of accounts has no operating-expense accounts yet.',
        'Direct Bill Processing (insured bill vs insurer remittance) awaits a business decision.'],
    tips=['Change rates with a new product version, then test with Test Calculation.',
          'Keep signatories and vehicle masters complete: the quote wizard will use them.',
          'Agree commission and WHT changes with Finance before the effective date.',
          'Use the Product Analytics tab to spot products that are not selling.'],
))

# ============================================================== Sales
PERSONAS.append(dict(
    user='maria.sales', file='BrokerVerse_Sales_Relationship_Manager_Guide.pptx', label='Sales / Relationship Manager',
    users='maria.sales', role_code='sales', landing='Home (business overview dashboard)',
    title_chips=['Leads and quotes', 'Policies', 'Renewals'],
    does=[('Wins business:', 'captures leads, builds and sends quotations, converts accepted quotes to policies.'),
          ('Looks after clients:', 'client 360 view with policies, claims, renewals and endorsements.'),
          ('Retains the book:', 'works the renewal queue, at-risk policies and negotiations.'),
          ('Tracks results:', 'executive and agent dashboards, commission dashboard, operational reports.')],
    signin='User name maria.sales. Lands on Home, the business overview dashboard; the Agent Dashboard is in the Dashboard menu.',
    hands_to='Underwriter (quote approval), client (accepts by e-mail link), Finance (receipts, commission), '
             'Customer Services (endorsements), Claims.',
    partners='Quotations are maker-checker: the underwriter is notified when you send one for approval.',
    menu=[('Dashboard', ['Executive Dashboard', 'Agent Dashboard']),
          ('Product Configurator', ['Dashboard', 'Product Templates']),
          ('Operations', M_OPS_ALL), ('Commission', ['Commission Dashboard']),
          ('Reports', ['Operational Reports: Production, Claims, Renewal, Remittance, Broker Commission'])],
    functions=[
        dict(title='Executive dashboard', shot='maria.sales__exec.png', menu='Dashboard > Executive Dashboard',
             caption=cap('Dashboard > Executive Dashboard', 'maria.sales'),
             points=[('Purpose:', 'revenue, active policies, new business and claims ratio against target.'),
                     ('Filters:', 'date range and period; Export Report for premium by product.'),
                     ('Source:', 'moves as soon as a policy is issued or a claim is registered.')]),
        dict(title='Leads / prospects', shot='maria.sales__leads.png', menu='Operations > Leads/Prospects',
             caption=cap('Operations > Leads/Prospects', 'maria.sales'),
             points=[('Purpose:', 'every prospect by line (Motor, Fire and Allied Perils, Industrial All Risks).'),
                     ('Create Lead:', 'name, category, date of birth, e-mail, 10-digit mobile are validated.'),
                     ('KPIs:', 'total, last 7 / 30 days, converted, conversion rate.'),
                     ('Next:', 'Create Quote straight after saving; Generate Report gives the Lead Conversion Funnel.')]),
        dict(title='Quotation', shot='maria.sales__quotes.png', menu='Operations > Quotation',
             caption=cap('Operations > Quotation', 'maria.sales'),
             points=[('Purpose:', 'all quotes with status: draft, sent for approval, approved, converted.'),
                     ('Pricing:', 'server re-prices with configured rates: VAT 12%, DST 12.5%, LGT 0.75%.'),
                     ('Approval:', 'sent quotes notify the underwriter; the client accepts by e-mail link (valid 7 days).'),
                     ('Expiry:', 'quotes past validity expire overnight.')]),
        dict(title='Policy', shot='maria.sales__policy.png', menu='Operations > Policy',
             caption=cap('Operations > Policy', 'maria.sales'),
             points=[('Purpose:', 'policies with insurer, premium, dates and payment status.'),
                     ('Convert:', 'an accepted quote becomes a policy with documents and vehicle photos.'),
                     ('Downstream:', 'bill INV + booking journal + collection item + commission accrual.'),
                     ('Actions:', 'endorsement, claim, renewal from the row menu.')]),
        dict(title='Renewal queue', shot='maria.sales__renewalq.png', menu='Operations > Renewals > Renewal Queue',
             caption=cap('Operations > Renewals > Renewal Queue', 'maria.sales'),
             points=[('Purpose:', 'policies due for renewal with days to expiry, risk level and assigned agent.'),
                     ('Timing:', 'enrolled 90 days before expiry; notices at 60 / 30 / 15 days.'),
                     ('Rules:', 'renewals are maker-checker; lapse after 30 days grace.'),
                     ('Related:', 'At-Risk Policies, Negotiations, Retention Analytics.')]),
        dict(title='Commission dashboard', shot='maria.sales__commission.png', menu='Commission > Commission Dashboard',
             caption=cap('Commission > Commission Dashboard', 'maria.sales'),
             points=[('Purpose:', 'brokerage income, comsub payable, net margin and outstanding payable.'),
                     ('Views:', 'by referrer, by status, monthly trend, by product and by insurer.'),
                     ('Source:', 'commission accrued at issuance and paid by Finance payouts.')]),
        dict(title='Operational reports', shot='maria.sales__production.png', crop=(0, 90, 1600, 1000),
             menu='Reports > Operational Reports',
             caption=cap('Reports > Operational Reports > Production', 'maria.sales'),
             points=[('Purpose:', 'Production, Claims, Renewal, Remittance and Broker Commission.'),
                     ('Criteria:', 'report criteria, from / to date, agent, company, branch, client.'),
                     ('Formats:', 'CSV, XLSX, PDF; generated files are kept in the history.')]),
    ],
    flow_mine=[1, 2, 4, 11], flow_loop='Your renewal starts the next cycle',
    flow_notes=['1 Lead: capture and qualify.', '2 Quote: price, send for approval and to the client.',
                '4 Policy: convert the accepted quote, upload documents.', '11 Renewal: work the queue and retain.'],
    reports=['production-register', 'claims-position', 'renewal-retention', 'remittance-summary', 'commission-statement',
             'premium-by-product', 'new-vs-renewal', 'claims-ageing', 'lead-conversion-funnel'],
    reports_note='Also via the report API: SOA, Receivables Ageing, Incentive Results.',
    jobs=[('quote-expiry', 'Your quotes past validity become expired'),
          ('renewal-pipeline', 'Your policies enter the renewal queue 90 days out'),
          ('renewal-notices', 'Clients get notices; you get a reminder per notice'),
          ('collection-reminders', 'Clients reminded before premium is due'),
          ('daily-reports', 'Production register ready each morning')],
    notifications=[('Info', 'Quotation approved', 'The underwriter approved your quote; you can convert it.'),
                   ('Task', 'Customer accepted quotation', 'The client accepted by e-mail link: proceed to policy.'),
                   ('Info', 'Policy issued', 'Policy number and first bill number.'),
                   ('Reminder', 'Renewal notice sent', 'First, second or final notice sent for your policy.'),
                   ('Info', 'Renewal approved / returned', 'Result of the renewal checker.'),
                   ('Alert', 'Policy lapsed', 'Grace period passed with no renewal.')],
    limits=QUOTE_LIMITS + POLICY_LIMITS[:1] + [
        'The Clients list can fail to open for this role in the current build: open a client from Policy instead.',
        'Report screens may show a permission message while loading the agent filter; the report still runs.'],
    tips=['Create the quote straight after saving the lead.', 'Check KYC and vehicle details before converting.',
          'Watch the At-Risk Policies view weekly.', 'Use the Agent Dashboard for your own numbers.'],
))

# ============================================================== Agent
PERSONAS.append(dict(
    user='ramon.agent', file='BrokerVerse_Agent_Referrer_Guide.pptx', label='Agent / Referrer',
    users='ramon.agent', role_code='agent', landing='Operations > Home',
    title_chips=['Own book only', 'Leads to policies', 'Commission'],
    does=[('Sells:', 'captures leads, prepares quotations, converts accepted quotes into policies.'),
          ('Own book only:', 'sees only the leads, clients, quotes and policies you created.'),
          ('Serves clients:', 'raises endorsements and claim notices, follows renewals.'),
          ('Earns:', 'commission accrues at issuance; Finance pays it with withholding tax.')],
    signin='User name ramon.agent. Lands on Operations > Home; the Agent Dashboard shows your leads, clients, '
           'policies sold and commission.',
    hands_to='Underwriter (quote approval), client (e-mail acceptance), Finance (receipts and commission payout), '
             'Claims (settlement), Customer Services.',
    partners='No approvals of your own: quotes go to the underwriter; payouts need a Finance maker and checker.',
    menu=[('Dashboard', ['Agent Dashboard']),
          ('Operations', ['Home', 'Leads/Prospects', 'Clients', 'Quotation', 'Policy', 'Claims',
                          'Renewals: Renewal Policy, Batch, Queue, Retention Analytics, At-Risk, Negotiations, Lapse Mgmt, Performance']),
          ('Commission', ['Commission Dashboard'])],
    functions=[
        dict(title='Agent dashboard', shot='ramon.agent__agentdash.png', menu='Dashboard > Agent Dashboard',
             caption=cap('Dashboard > Agent Dashboard', 'ramon.agent'),
             points=[('Purpose:', 'your leads, clients and policies sold, commission by month.'),
                     ('Money tiles:', 'earned commission (3,990.71 net after WHT), collected premium, receivables, gross premium.'),
                     ('Create Quote:', 'shortcut into the quotation wizard.'),
                     ('Scope:', 'only your own records are counted.')]),
        dict(title='Leads / prospects', shot='ramon.agent__leads.png', menu='Operations > Leads/Prospects',
             caption=cap('Operations > Leads/Prospects', 'ramon.agent'),
             points=[('Purpose:', 'your prospects by line with KPIs and conversion rate.'),
                     ('Create Lead:', 'required fields, e-mail format, 10-digit mobile, date of birth.'),
                     ('Actions:', 'View, Edit, Delete (draft only), Bulk Upload.'),
                     ('Next:', 'go straight to Create Quote after saving.')]),
        dict(title='Quotation', steps=['Choose insurer and product', 'Vehicle and cover details', 'Plan recommendation',
                                       'Coverage and add-ons', 'Order summary: taxes, commission', 'Send for approval'],
             menu='Operations > Quotation', caption='Quotation wizard steps (QT-2026-00001, MAPFRE, Toyota Rav4)',
             points=[('Pricing:', 'net 28,005.00 + VAT 3,360.60 + DST 3,500.63 + LGT 210.04 = gross 35,076.27.'),
                     ('Server check:', 'the API re-prices with the configured rates; tampered amounts are refused.'),
                     ('Approval:', 'the underwriter is notified; the client gets an e-mail link valid 7 days.'),
                     ('Expiry:', 'unconverted quotes expire after the validity period.')]),
        dict(title='Convert to policy', steps=['Client accepted (you are notified)', 'Customer information and ID',
                                               'Vehicle details and photos', 'Upload policy documents', 'Payment confirmation',
                                               'Policy issued'],
             menu='Operations > Quotation > Convert', caption='Conversion steps (POL-2026-00001)',
             points=[('Documents:', 'ID, vehicle photos and the insurer policy are stored with the policy.'),
                     ('Downstream:', 'bill INV-2026-00001, booking journal, collection item, commission 4,200.75 accrued.'),
                     ('Dashboard:', '+1 policy and +35,076.27 premium straight away.'),
                     ('Check:', 'complete KYC and vehicle identifiers before Next.')]),
        dict(title='Renewals', shot='ramon.agent__renewals.png', menu='Operations > Renewals > Renewal Policy',
             caption=cap('Operations > Renewals > Renewal Policy', 'ramon.agent'),
             points=[('Purpose:', 'your active, expiring (0-5 days) and expired policies.'),
                     ('Timing:', 'notices go to your clients at 60 / 30 / 15 days; you get a reminder each time.'),
                     ('Action:', 'start the renewal quote from the policy row.'),
                     ('Scope:', 'empty tiles mean none of your policies are due.')]),
        dict(title='Claims notice', steps=['Open the client or policy', 'Claim request: date, time, place of loss',
                                           'Cause of loss and estimate', 'Attach documents (2 MB, PNG / JPEG / PDF)',
                                           'Send to the insurer'],
             menu='Operations > Claims', caption='Claim request steps (the Claims Officer takes it from there)',
             points=[('Rule:', 'date of loss must be inside the policy period and not in the future.'),
                     ('Refusal:', 'the reason is shown, e.g. “outside the policy period 2026-09-28 to 2027-09-28”.'),
                     ('Follow-up:', 'you are notified at each status: Processing, Pending Approval, Approved, Settled.')]),
    ],
    flow_mine=[1, 2, 4], flow_loop='Renewals come back to you as leads for the next term',
    flow_notes=['1 Lead: capture the prospect.', '2 Quote: price and send for approval.',
                '4 Policy: convert once the client accepts.',
                'Later: follow receipts, claims and renewals of your book from notifications.'],
    reports=[], reports_title='Reports and figures you use',
    reports_note='The agent role has no Reports menu.',
    reports_alt=[('Agent Dashboard', 'Leads, clients, policies sold, commission by month, collected premium, receivables'),
                 ('Commission Dashboard', 'Commission earned and payable on your policies'),
                 ('Leads > KPI tiles', 'Total leads, last 7 / 30 days, converted, conversion rate'),
                 ('Renewal Policy tiles', 'Active, expiring soon and expired policies in your book'),
                 ('Broker Commission Statement', 'Ask Finance: commission per policy with WHT and net')],
    jobs=[('quote-expiry', 'Your unconverted quotes expire after the validity'),
          ('renewal-notices', 'Your clients get notices; you get a reminder each time'),
          ('renewal-pipeline', 'Your expiring policies enter the renewal queue'),
          ('collection-reminders', 'Your clients are reminded before premium is due'),
          ('policy-expiry', 'Policies past expiry are marked expired')],
    notifications=[('Task', 'Customer accepted quotation', 'Proceed to policy.'),
                   ('Info', 'Policy issued', 'Policy and bill numbers.'),
                   ('Info', 'Endorsement completed', 'With the premium change, if any.'),
                   ('Task', 'New claim registered', 'A claim was registered on your policy.'),
                   ('Info', 'Claim status changes', 'Processing, Pending Approval, Approved, Settled.'),
                   ('Reminder', 'Renewal notice sent', 'First, second or final notice for your policy.')],
    limits=QUOTE_LIMITS + POLICY_LIMITS + [
        'Commission accrues to the user who created the policy: create your own quotes.'],
    tips=['Save the lead, then create the quote immediately.', 'Use the Agent Dashboard every morning.',
          'Keep your bank details with Finance so payouts are not held.'],
))

# ============================================================== Underwriter
PERSONAS.append(dict(
    user='jose.uw', file='BrokerVerse_Underwriter_Guide.pptx', label='Underwriter',
    users='jose.uw', role_code='underwriting', landing='Home (business overview dashboard)',
    title_chips=['Quote approval', 'Rules and rating', 'Reinsurance'],
    does=[('Approves risk:', 'reviews quotations sent for approval and referred cases.'),
          ('Maintains rules:', 'coverages, rating factors, underwriting rules, documents and workflows.'),
          ('Renews:', 'prices renewal quotations and works the renewal queue.'),
          ('Reinsures:', 'treaty dashboard, cession tracking, claims recovery, reconciliation.')],
    signin='User name jose.uw. Lands on Home; the Underwriting Dashboard is in the Dashboard menu.',
    hands_to='Sales and agents (approved quotes), client (acceptance), Finance (remittance of reinsurance), '
             'Claims (recoveries).',
    partners='You are the checker for quotations (quotations.approval_notify_roles = underwriting) and a checker for renewals.',
    menu=[('Dashboard', ['Underwriting Dashboard', 'Executive Dashboard']),
          ('Product Configurator', ['Dashboard', 'Product Templates', 'Coverage Builder', 'Rating Engine', 'Underwriting Rules',
                                    'Document Manager', 'Approval Workflows', 'Market / Risk Mapping', 'Product Analytics']),
          ('Operations', M_OPS_ALL), ('Reinsurance', M_RI_ALL),
          ('Reports', ['Operational Reports: Production, Claims, Renewal, Remittance, Broker Commission'])],
    functions=[
        dict(title='Underwriting dashboard', shot='jose.uw__uwdash.png', menu='Dashboard > Underwriting Dashboard',
             caption=cap('Dashboard > Underwriting Dashboard', 'jose.uw'),
             points=[('Purpose:', 'submissions waiting, referred cases, average turnaround and open alerts.'),
                     ('Workload:', 'assignment groups and workload by underwriter.'),
                     ('Action:', 'New Submission and drill-down into each case.')]),
        dict(title='Quotation approval', shot='jose.uw__quotes.png', menu='Operations > Quotation',
             caption=cap('Operations > Quotation', 'jose.uw'),
             points=[('Purpose:', 'quotes by status: draft, sent for approval, approved, converted, expired.'),
                     ('Notified:', '“Quotation sent for approval” with client and gross premium.'),
                     ('Checks:', 'risk, sum insured, rating and taxes (server-priced).'),
                     ('Downstream:', 'approval lets the maker convert; the client accepts by e-mail.')]),
        dict(title='Underwriting rules', shot='jose.uw__uwrules.png', menu='Product Configurator > Underwriting Rules',
             caption=cap('Product Configurator > Underwriting Rules', 'jose.uw'),
             points=[('Purpose:', 'acceptance, validation and loading rules per product.'),
                     ('Effect:', 'rules refer, decline or load a quote automatically.'),
                     ('Change:', 'Add Rule; publishing follows the approval workflow.')]),
        dict(title='Rating engine', shot='jose.uw__rating.png', menu='Product Configurator > Rating Engine',
             caption=cap('Product Configurator > Rating Engine', 'jose.uw'),
             points=[('Purpose:', 'rating factors with multipliers and discounts.'),
                     ('Test Calculation:', 'try a premium before activating.'),
                     ('Downstream:', 'server-side pricing of every new and renewal quote.')]),
        dict(title='Coverage builder', shot='jose.uw__coverages.png', menu='Product Configurator > Coverage Builder',
             caption=cap('Product Configurator > Coverage Builder', 'jose.uw'),
             points=[('Purpose:', 'coverages (own damage, theft, CTPL, acts of nature, AOG, PA…) with type and deductible.'),
                     ('Types:', 'mandatory or optional; premium impact per coverage.'),
                     ('Downstream:', 'what the quote and endorsement coverage pages offer.')]),
        dict(title='Renewal queue', shot='jose.uw__renewalq.png', menu='Operations > Renewals > Renewal Queue',
             caption=cap('Operations > Renewals > Renewal Queue', 'jose.uw'),
             points=[('Purpose:', 'policies due, days to expiry, risk level, premium and agent.'),
                     ('Rules:', 'renewal maker-checker; notices in order (first, second, final).'),
                     ('Lapse:', '30 days after expiry without renewal.')]),
        dict(title='Renewal pricing', shot='evidence:20-renewal-order-summary.jpg', menu='Policy > Renew > Order Summary',
             caption=cap('Renewal order summary (net 32,005.00, gross 40,086.27)', 'jose.uw', live=False),
             points=[('Purpose:', 'renewal quote priced from the expiring policy.'),
                     ('Taxes:', 'VAT 12%, DST 12.5%, LGT 0.75%; discount 0-30% comes out of brokerage.'),
                     ('Commission:', 'brokerage, comsub, discount and margin shown before sending.'),
                     ('Downstream:', 'accepted renewal becomes the new policy term.')]),
        dict(title='Cession tracking', shot='jose.uw__cessions.png', menu='Reinsurance > Cession Tracking',
             caption=cap('Reinsurance > Cession Tracking', 'jose.uw'),
             points=[('Purpose:', 'policies ceded per treaty: ceded sum, ceded premium, commission earned.'),
                     ('Actions:', 'Process Cession, Generate Bordereaux.'),
                     ('Downstream:', 'Reinsurance Cession Register report and reconciliation.')]),
    ],
    flow_mine=[2, 4, 11], flow_loop='Renewal pricing feeds the next cycle',
    flow_notes=['2 Quote: approve quotes sent for approval.', '4 Policy: rules and rating behind every policy.',
                '11 Renewal: price and approve renewals.', 'Reinsurance: cessions and recoveries on large risks.'],
    reports=['production-register', 'claims-position', 'renewal-retention', 'remittance-summary', 'commission-statement',
             'premium-by-product', 'new-vs-renewal', 'claims-ageing', 'lead-conversion-funnel', 'cession-register'],
    reports_note='Ten reports in your catalogue.',
    jobs=[('quote-expiry', 'Unapproved quotes expire after the validity'),
          ('renewal-pipeline', 'Policies 90 days from expiry reach your queue'),
          ('renewal-notices', 'Notices at 60 / 30 / 15 days, in order'),
          ('policy-expiry', 'Expired policies drop out of in-force figures'),
          ('daily-reports', 'Production register each morning')],
    notifications=[('Approval', 'Quotation sent for approval', 'Client, quote number and gross premium.'),
                   ('Approval', 'Renewal approval', 'A renewal awaits your decision.'),
                   ('Info', 'Renewal approved / returned', 'Sent to the maker with your note.'),
                   ('Approval', 'Treaty awaiting approval', 'When treaty approval is switched on.')],
    limits=QUOTE_LIMITS[2:] + [
        'Renewal quotation linking to the expiring policy is being finalised; check insurer, client and vehicle.',
        'Endorsement is still offered on expired policies: do not use it there.',
        'The Clients list can fail to open for this role in the current build.'],
    tips=['Use Test Calculation after every rating change.', 'Keep quotes moving: they expire overnight.',
          'Review at-risk renewals weekly with Sales.'],
))

# ============================================================== Customer services
PERSONAS.append(dict(
    user='ana.cs', file='BrokerVerse_Customer_Services_Guide.pptx', label='Customer Services',
    users='ana.cs', role_code='customer-services', landing='Home (business overview dashboard)',
    title_chips=['Client service', 'Endorsements', 'Open items'],
    does=[('Serves clients:', 'answers questions from the client 360 view: policies, claims, renewals, endorsements.'),
          ('Changes policies:', 'personal details and coverage endorsements, re-priced by the server.'),
          ('Chases open items:', 'expiring policies, pending payments, pending quotes, renewal requests.'),
          ('Helps sell:', 'can capture leads and quotes like Sales.')],
    signin='User name ana.cs. Lands on Home, the business overview dashboard.',
    hands_to='Finance (endorsement bills), insurer (endorsement request e-mail), Claims, Sales / agents.',
    partners='Endorsements are sent to the insurer; extra premium is billed and receipted by Finance.',
    menu=[('Dashboard', ['Executive Dashboard']), ('Product Configurator', ['Dashboard', 'Product Templates']),
          ('Operations', M_OPS_ALL), ('Reports', ['Operational Reports: Production, Claims, Renewal, Remittance, Broker Commission'])],
    functions=[
        dict(title='Client 360 view', shot='ana.cs__clientview.png', menu='Operations > Clients > client',
             caption=cap('Operations > Clients > Andrea Villanueva', 'ana.cs'),
             points=[('Purpose:', 'one client with tabs for Policy, Claim, Renewal and Endorsement.'),
                     ('Row actions:', 'endorsement, claim request, renewal.'),
                     ('Example:', 'POL-2026-00001, gross 40,086.27 after endorsement, payment completed.')]),
        dict(title='Policy list', shot='ana.cs__policy.png', menu='Operations > Policy',
             caption=cap('Operations > Policy', 'ana.cs'),
             points=[('Purpose:', 'all policies with premium, dates and payment status.'),
                     ('Status:', 'completed, pending, expired.'),
                     ('Actions:', 'open, endorse, renew; Bulk Upload and Create Policy.')]),
        dict(title='Endorsement: personal details', shot='evidence:15-endorsement-personal-details.jpg',
             menu='Policy > Endorsement > Personal Details Change',
             caption=cap('Endorsement request, personal details (END-2026-00002)', 'ana.cs', live=False),
             points=[('Start:', 'choose the endorsement type first; Proceed stays disabled until you do.'),
                     ('Validation:', 'required fields, mobile number and 4-digit ZIP.'),
                     ('Downstream:', 'the client record is updated; the owner is notified.')]),
        dict(title='Endorsement: coverage change', shot='evidence:15-coverage-change-repriced.jpg',
             menu='Policy > Endorsement > Coverage Change',
             caption=cap('Endorsement request, coverage change (END-2026-00003)', 'ana.cs', live=False),
             points=[('Pricing:', 're-priced with configured rates; the server checks the premium difference.'),
                     ('Example:', 'own damage 1,400,000: gross 40,086.27, +5,010.00.'),
                     ('Downstream:', 'bill INV-2026-00002, journal 5,010 / 4,410 / 600, collection item.'),
                     ('Send:', 'Send to Insurance Company from the summary.')]),
        dict(title='Open items', shot='ana.cs__openitems.png', menu='Operations > Open Items',
             caption=cap('Operations > Open Items', 'ana.cs'),
             points=[('Purpose:', 'expiring policies, pending payments, pending quotes and renewal requests.'),
                     ('Use:', 'your daily worklist; See More opens the full list.'),
                     ('Source:', 'policies, bills and renewals updated by the schedules overnight.')]),
        dict(title='Payments', shot='ana.cs__payments.png', menu='Operations > Payments',
             caption=cap('Operations > Payments', 'ana.cs'),
             points=[('Purpose:', 'gross, collected, receivable premium and earned commission.'),
                     ('Tabs:', 'paid, pending, processing, by policy or endorsement.'),
                     ('Note:', 'receipts are posted by Finance; you see the result here.')]),
        dict(title='Expired and expiring policies', shot='ana.cs__renewals.png', menu='Operations > Renewals > Renewal Policy',
             caption=cap('Operations > Renewals > Renewal Policy', 'ana.cs'),
             points=[('Purpose:', 'active, expiring soon (0-5 days) and expired policies.'),
                     ('Action:', 'call the client and start the renewal quote.'),
                     ('Timing:', 'notices already went at 60 / 30 / 15 days.')]),
    ],
    flow_mine=[1, 9, 11], flow_loop='Renewal follow-up starts the next cycle',
    flow_notes=['9 Endorsement: personal and coverage changes.', 'Extra premium goes to Finance as a bill.',
                '1 Lead: can capture leads for Sales.', '11 Renewal: chase expiring policies.'],
    reports=['production-register', 'claims-position', 'renewal-retention', 'remittance-summary', 'commission-statement',
             'premium-by-product', 'new-vs-renewal', 'claims-ageing', 'lead-conversion-funnel'],
    reports_note='Nine operational reports in your catalogue.',
    jobs=[('renewal-notices', 'Clients get notices at 60 / 30 / 15 days'),
          ('collection-reminders', 'Clients reminded 7 days before premium is due'),
          ('receivable-ageing', 'Pending payments move to older buckets'),
          ('policy-expiry', 'Expired policies appear in Open Items'),
          ('email-outbox', 'Client e-mails leave every 5 minutes')],
    notifications=[('Info', 'Endorsement completed', 'With the premium change.'),
                   ('Info', 'Policy cancelled by endorsement', 'When a cancellation endorsement completes.'),
                   ('Reminder', 'Renewal notice sent', 'For policies you own.'),
                   ('Task', 'Customer accepted quotation', 'For quotes you created.')],
    limits=COMMON_LIMITS + [
        '“Proceed to payment” is still offered for an endorsement with no premium change: ignore it.',
        'Some endorsement and client headers may show an internal ID instead of the client code.',
        'The Clients list can fail to open for this role in the current build: use Policy and open the client.'],
    tips=['Pick the endorsement type first, then Proceed.', 'Check the summary before Send to Insurance Company.',
          'Tell Finance when an endorsement adds premium.', 'Start the day on Open Items.'],
))

# ============================================================== Claims
PERSONAS.append(dict(
    user='carlo.claims', file='BrokerVerse_Claims_Officer_Guide.pptx', label='Claims Officer',
    users='carlo.claims (maker), lisa.claims2 (checker)', role_code='claims', landing='Home (business overview dashboard)',
    title_chips=['Register claims', 'Settle with a checker', 'Claims reports'],
    does=[('Registers claims:', 'from the client or policy with date, time, place and cause of loss and estimate.'),
          ('Manages:', 'adjuster details, documents, status and insurer claim number.'),
          ('Settles:', 'submits the settlement for approval by a second claims user.'),
          ('Reports:', 'claims dashboard, claims position and ageing.')],
    signin='User names carlo.claims and lisa.claims2. Land on Home; the Claims Dashboard is in the Dashboard menu.',
    hands_to='Insurer (claim request e-mail), second claims officer (approval), agent / owner (notified), '
             'Finance (claim payments), Reinsurance (recoveries).',
    partners='carlo.claims makes the settlement, lisa.claims2 approves it; the maker is refused when approving.',
    menu=[('Dashboard', ['Claims Dashboard']), ('Operations', ['Home', 'Clients', 'Policy', 'Claims']),
          ('Reinsurance', ['Claims Recovery']),
          ('Reports', ['Operational Reports: Production, Claims, Renewal, Remittance, Broker Commission'])],
    functions=[
        dict(title='Claims dashboard', shot='carlo.claims__claimsdash.png', menu='Dashboard > Claims Dashboard',
             caption=cap('Dashboard > Claims Dashboard', 'carlo.claims'),
             points=[('Purpose:', 'open claims, overdue, today’s, top line and region.'),
                     ('Recent claims:', 'line, customer, policy, loss and report dates, priority, status, amount.'),
                     ('Export Report:', 'Claims Ageing.')]),
        dict(title='Claims list', shot='carlo.claims__claims.png', menu='Operations > Claims',
             caption=cap('Operations > Claims', 'carlo.claims'),
             points=[('Purpose:', 'all claims with client, policy, product and status.'),
                     ('Status:', 'pending, processing, pending approval, approved, settled, rejected.'),
                     ('Open:', 'the eye icon opens claim details and the settlement.')]),
        dict(title='Registering a claim: loss date rule', shot='evidence:16-claim-refused-outside-period.jpg',
             menu='Clients > policy > Claim Request', caption=cap('Claim request refused for a loss date outside cover', 'carlo.claims', live=False),
             points=[('Required:', 'date and cause of loss; date not in the future.'),
                     ('Rule:', 'loss date must be inside the policy period, or the claim is refused with the reason.'),
                     ('Documents:', 'up to 2 MB each, PNG, JPEG or PDF.'),
                     ('Send:', 'the request is e-mailed to the insurer.')]),
        dict(title='Claim raised', shot='evidence:16-claim-registered.jpg', menu='Clients > policy > Claim Request > Send',
             caption=cap('Claim CLM-2026-00002 raised', 'carlo.claims', live=False),
             points=[('Result:', 'claim number issued; the request is e-mailed to the insurer.'),
                     ('Next:', 'wait for the insurer to assign an adjuster, then Proceed.'),
                     ('Notified:', 'every claims officer and the policy owner get \u201cNew claim\u201d.'),
                     ('Edit:', 'correct the request before the insurer acts on it.')]),
        dict(title='Adjuster details', shot='evidence:16-claim-adjuster.jpg', menu='Claim > Adjuster submission',
             caption=cap('Adjuster submission', 'carlo.claims', live=False),
             points=[('Address:', 'country, province, city from the address master; 4-digit ZIP.'),
                     ('Same as Policy Holder:', 'copies the holder\u2019s address.'),
                     ('Required:', 'fields with an asterisk must be filled.')]),
        dict(title='Claim details and settlement', shot='carlo.claims__claimdetail.png', menu='Operations > Claims > claim',
             caption=cap('Claim CLM-2026-00002', 'carlo.claims'),
             points=[('Sections:', 'claim, incident, driver and policy information; insurer ref MAPFRE-MC-2026-4471.'),
                     ('Maker:', 'settlement type, amount and dates validated, then \u201csubmitted for approval\u201d.'),
                     ('Checker:', 'lisa.claims2 uses Review settlement and approves; the maker is refused.'),
                     ('Result:', 'settled 78,500 against an 85,000 estimate; dashboard and report updated.')]),
        dict(title='Claims report', shot='carlo.claims__claimsreport.png', crop=(0, 90, 1600, 1000),
             menu='Reports > Operational Reports > Claims', caption=cap('Reports > Operational Reports > Claims', 'carlo.claims'),
             points=[('Criteria:', 'All, Open, Settled, Rejected or Aging (by 30/60/90/180 days).'),
                     ('Content:', 'estimate, approved and settled amounts, age, bucket.'),
                     ('Formats:', 'CSV, XLSX, PDF.')]),
    ],
    flow_mine=[10], flow_loop='Claims experience informs the renewal price',
    flow_notes=['10 Claim: register, adjust, settle with a second officer.', 'Policy period is checked at registration.',
                'Owners and agents are notified at each status.', 'Recoveries go to Reinsurance > Claims Recovery.'],
    reports=['production-register', 'claims-position', 'renewal-retention', 'remittance-summary', 'commission-statement',
             'premium-by-product', 'new-vs-renewal', 'claims-ageing'],
    reports_note='Eight operational reports in your catalogue.',
    jobs=[('daily-reports', 'Claims position generated each morning'),
          ('policy-expiry', 'Expired policies: new losses after expiry are refused'),
          ('email-outbox', 'Claim request e-mails to insurers leave every 5 minutes')],
    notifications=[('Task', 'New claim registered', 'Claim number and policy, to every claims officer.'),
                   ('Approval', 'Settlement approval', 'Amount and claim, to the other claims officers.'),
                   ('Info', 'Claim status changes', 'Processing, Pending Approval, Approved, Settled.'),
                   ('Info', 'Settlement approved', 'Back to the maker once the checker approves.')],
    limits=COMMON_LIMITS + [
        'Address and adjuster fixes are awaiting re-test in the final run: report anything odd.',
        'The Clients list can fail to open for this role in the current build: use Policy instead.',
        'Report screens may show a permission message while loading the agent filter; the report still runs.'],
    tips=['Check the policy period before registering.', 'Attach documents when you register, not later.',
          'Record the insurer claim number as soon as you have it.', 'Ask your checker to use Review settlement.'],
))

# ============================================================== Finance
PERSONAS.append(dict(
    user='liza.finance', file='BrokerVerse_Finance_Accounts_Guide.pptx', label='Finance / Accounts',
    users='liza.finance (maker), fe.approver (checker)', role_code='finance', landing='Home (business overview dashboard)',
    title_chips=['Receipts and collections', 'Payouts and remittance', 'Ledger'],
    does=[('Collects:', 'official receipts against open bills, partial or full; collections and ageing.'),
          ('Pays:', 'commission payouts to agents and premium remittances to insurers, by voucher and cheque.'),
          ('Keeps the ledger:', 'journal vouchers, corrections, reversals, trial balance.'),
          ('Reports:', 'financial and operational reports; receivables and payables registers.')],
    signin='User names liza.finance and fe.approver. Land on Home, the business overview dashboard.',
    hands_to='fe.approver (checker for vouchers, remittances, settlements, JVs), insurers (remittance), agents (payouts).',
    partners='Maker-checker is on (finance.maker_checker_enabled): the maker cannot approve their own voucher, '
             'remittance, settlement or JV.',
    menu=[('Dashboard', ['Executive Dashboard']), ('Operations', ['Open Items', 'Payments']),
          ('Accounts', ['Receipts, Collections', 'Accounting Query, All Clients Accounting',
                        'Open Entry Matching / Un-Matching', 'Disbursement, Petty Cash (5 screens)',
                        'Journal, Correction and Reversal JV', 'Remittance (17 screens)', 'Incentive (4 screens)']),
          ('Commission', ['Commission Dashboard', 'Agents/Referrer Accounts']), ('Reinsurance', ['Reconciliation']),
          ('Reports', ['Financial: SOA, Collection, Payables, Journal, Trial Balance', 'Operational: all five'])],
    functions=[
        dict(title='Receipts', shot='liza.finance__receipts.png', menu='Accounts > Receipts',
             caption=cap('Accounts > Receipts', 'liza.finance'),
             points=[('Purpose:', 'official receipts (OR) with policy, customer and date.'),
                     ('Actions:', '+ Receipt, Bulk Upload, Bulk Print.'),
                     ('Downstream:', 'JV Dr cash / Cr premium receivable; bill Paid, collection item closed.')]),
        dict(title='Add receipt against open bills', shot='evidence:12-receipt-open-bills.jpg', menu='Accounts > Receipts > Add',
             caption=cap('Add receipt: open bills for POL-2026-00001', 'liza.finance', live=False),
             points=[('Pick:', 'customer, policy and the open bill (e.g. INV-2026-00002, 5,010.00).'),
                     ('Rule:', 'payment cannot exceed the balance (4,000 on 3,010 was refused).'),
                     ('Partial:', 'OR-2026-00020 2,000 left 3,010; OR-2026-00021 closed it.'),
                     ('Fields:', 'receipt mode, transaction code OR, reference and remarks.')]),
        dict(title='Collections', shot='liza.finance__collections.png', menu='Accounts > Collections',
             caption=cap('Accounts > Collections', 'liza.finance'),
             points=[('Purpose:', 'outstanding by client and policy, in buckets current / 1-30 / 31-60 / 61-90 / 90+.'),
                     ('Reminders:', 'Manual Trigger Reminder Now, or the 08:00 job.'),
                     ('Report:', 'Receivables Ageing.')]),
        dict(title='Commission payout', shot='evidence:13-payout-invoice-list.jpg', menu='Accounts > Disbursement > payout',
             caption=cap('Agent payout invoice list (PV-2026-00022)', 'liza.finance', live=False),
             points=[('Amounts:', 'gross 4,200.75, WHT 210.04 (Individual 5%), net 3,990.71.'),
                     ('Rule:', 'maker cannot approve own voucher; fe.approver approved.'),
                     ('Journal:', 'Dr commission payable / Cr cash / Cr WHT payable, balanced.')]),
        dict(title='Journal voucher', shot='liza.finance__jv.png', menu='Accounts > Journal Voucher',
             caption=cap('Accounts > Journal Voucher', 'liza.finance'),
             points=[('Rule:', 'debits must equal credits (screen and API refuse unbalanced).'),
                     ('Flow:', 'maker submits, checker approves and posts (JV-2026-00106).'),
                     ('Status:', 'draft, awaiting approval, posted.'),
                     ('Downstream:', 'trial balance counts approved and posted JVs only.')]),
        dict(title='Remittance tracking', shot='liza.finance__remtracking.png', menu='Accounts > Remittance > Tracking',
             caption=cap('Accounts > Remittance > Tracking', 'liza.finance'),
             points=[('Purpose:', 'remittances per insurer: gross, commission retained, net due, status.'),
                     ('Example:', 'REM-2026-00018 to MAPFRE, net 30,875.52.'),
                     ('Levels:', 'approval level by amount: up to 100,000; up to 1,000,000; above.')]),
        dict(title='Approval workflow', shot='evidence:14-approval-queue.jpg', menu='Accounts > Remittance > Approval Workflow',
             caption=cap('Remittance approval queue', 'fe.approver', live=False),
             points=[('Purpose:', 'pending approvals with SLA, level and amount.'),
                     ('Rule:', 'the initiator is refused; a second finance user approves.'),
                     ('Next:', 'settlement approval raises the insurer voucher; cheque approved, printed, voucher Paid.')]),
        dict(title='Agents / referrer accounts', shot='liza.finance__referrer.png', menu='Commission > Agents/Referrer Accounts',
             caption=cap('Commission > Agents/Referrer Accounts', 'liza.finance'),
             points=[('Purpose:', 'referrers with type, level, policies, net payable, WHT type and bank account.'),
                     ('Rule:', 'WHT rate follows the referrer type (Individual 5%).'),
                     ('Next:', 'Generate payout creates a draft disbursement.')]),
    ],
    flow_mine=[5, 6, 7, 8], flow_loop='Endorsement bills come back to you as receipts',
    flow_notes=['5 Billing: booked at issuance (INV + JV + collection item).', '6 Receipt: OR against open bills.',
                '7 Commission: payout with WHT, maker and checker.', '8 Remittance: net premium to the insurer.'],
    reports=['remittance-summary', 'commission-statement', 'premium-by-product', 'new-vs-renewal', 'cession-register',
             'premium-receivable-soa', 'collections-summary', 'collections-ageing', 'receipts-register',
             'disbursement-register', 'journal-register', 'trial-balance', 'incentive-results'],
    reports_note='Thirteen reports in your catalogue.',
    jobs=[('receivable-ageing', 'Buckets 30/60/90/120 refreshed; overdue flagged'),
          ('collection-reminders', 'Clients e-mailed 7 days before due, then every 7 days'),
          ('daily-reports', 'Collections summary each morning'),
          ('email-outbox', 'Reminders and statements leave every 5 minutes'),
          ('report-schedules', 'Trial balance or SOA e-mailed on your timetable')],
    notifications=[('Approval', 'Journal voucher awaiting approval', 'To finance approvers.'),
                   ('Info', 'Journal voucher approved / rejected', 'Back to the maker with the reason.'),
                   ('Approval', 'Remittances awaiting approval', 'Batch number and count.'),
                   ('Info', 'Direct bill / settlement approved', 'Back to the initiator.'),
                   ('Approval', 'Petty cash request', 'Requester and amount.'),
                   ('Alert', 'Petty cash below minimum', 'To the fund custodian.')],
    limits=[
        'Chart of accounts has no operating-expense accounts yet (rent, salaries, utilities).',
        'Receipts API is shared with the in-app payment step; separation is planned.',
        'Direct Bill Processing wording (insured bill vs insurer remittance) awaits a business decision.',
        'Remittance and settlement dates are shown month-first; the settlement date picker is MM/DD/YYYY.',
        'Commission can accrue to an administrator who issued a policy.'],
    tips=['Always pick the bill, not just the policy, when receipting.', 'Ask the checker to approve the same day (SLA).',
          'Print approved cheques so vouchers become Paid.', 'Run the trial balance after every posting day.'],
))

# ============================================================== User access administrator
PERSONAS.append(dict(
    user='carmela.morfe', file='BrokerVerse_User_Access_Administrator_Guide.pptx', label='User Access Administrator',
    users='carmela.morfe (and five other access administrators)', role_code='user-access-admin', landing='Master > Audit Trail',
    title_chips=['Users', 'Roles', 'Audit and sign-ins'],
    does=[('Manages users:', 'creates users, assigns roles, deactivates leavers, unlocks and resets passwords.'),
          ('Manages roles:', 'maintains roles and their read / write permissions.'),
          ('Reviews access:', 'audit trail and sign-in history for access reviews.'),
          ('No business data:', 'cannot open policies, receipts, claims or reports.')],
    signin='User name carmela.morfe. Lands on Master > Audit Trail, the first screen the role may open.',
    hands_to='IT administrator (settings, schedules, API), line managers (approve access requests).',
    partners='Access requests should be approved by the user’s manager before you act.',
    menu=[('Master', ['Generals > User Management > User', 'Generals > User Management > Role', 'Audit Trail']),
          ('Not in your menu', ['Dashboard, Product Configurator', 'Operations, Accounts', 'Commission, Reinsurance',
                                'Reports', 'System Settings, Configuration, Schedules'])],
    menu_note='Grants: master > "Generals > User Management" and "Audit Trail"; permissions read/write users and roles, read audit and settings.',
    functions=[
        dict(title='Users', shot='BrokerVerse__users.png', menu='Master > Generals > User Management > User',
             caption='Same screen as the access administrator sees (captured as BrokerVerse; your sidebar shows only Master)',
             points=[('Purpose:', 'user list with role, e-mail, display name and status.'),
                     ('Actions:', '+ Add, view, edit, activate / deactivate, unlock.'),
                     ('Leavers:', 'deactivate (soft delete); history is kept.')]),
        dict(title='Adding a user', steps=['+ Add on the User list', 'User name, display name, e-mail',
                                           'Tick one or more roles', 'Initial password (policy applies)', 'Save'],
             menu='Master > User Management > User > Add', caption='Steps to add a user',
             points=[('Rules:', 'at least one role; unique user name.'),
                     ('Password:', 'min 8, upper, lower, digit, symbol; last 5 not reused; expires after 90 days.'),
                     ('Two-factor:', 'required for roles listed in security.require_2fa_roles; reset for lost devices.'),
                     ('Audit:', 'creation and every change are recorded.')]),
        dict(title='Roles', shot='BrokerVerse__roles.png', menu='Master > Generals > User Management > Role',
             caption='Same screen as the access administrator sees (captured as BrokerVerse)',
             points=[('Purpose:', 'role code, name, status; view and edit permissions.'),
                     ('Permissions:', 'read / write per module, e.g. write:receipts, read:audit.'),
                     ('Rule:', 'system roles cannot be deleted; a role with users cannot be deleted.')]),
        dict(title='Audit trail', shot='BrokerVerse__audit.png', menu='Master > Audit Trail',
             caption='Same screen as the access administrator sees (captured as BrokerVerse)',
             points=[('Purpose:', 'every create, update, approval, report and sign-in.'),
                     ('Filters:', 'record type, record ID, user.'),
                     ('Change column:', 'before and after values of each change.')]),
        dict(title='Sign-in history', shot='evidence:21-persona_carmela.morfe.jpg', menu='Master > Audit Trail (record type: session)',
             caption=cap('Audit trail filtered to sign-ins', 'carmela.morfe', live=False),
             points=[('Purpose:', 'who signed in and when: record type “session”, action login.'),
                     ('Per user:', 'the API also gives each user’s sign-in history.'),
                     ('Lockout:', 'repeated failed sign-ins lock the account; unlock from the user list.'),
                     ('Limits:', '10 sign-in attempts per 5 minutes per address.')]),
    ],
    extras=[dict(kind='twocol', title='What you cannot do', kicker='Least privilege',
                 left_title='Blocked for this role', left_warn=True,
                 left=['Open business screens: a typed address such as /accounts/receipts shows “Not authorised”.',
                       'Call business APIs: GET /policies answers 403.',
                       'Change system settings, configuration or schedules (IT administrator).',
                       'Run reports or see dashboards.',
                       'Approve any business transaction.'],
                 shot='evidence:21-persona_carmela.morfe_forbidden.jpg',
                 caption='carmela.morfe opening /accounts/receipts: Not authorised')],
    flow_steps=[('Access request', 'Manager'), ('Create user', 'You'), ('Assign role', 'You'), ('First sign-in', 'User'),
                ('Change password', 'User'), ('Periodic review', 'You'), ('Unlock / reset', 'You'),
                ('Role change', 'You + manager'), ('Deactivate leaver', 'You'), ('Audit evidence', 'You')],
    flow_mine=[2, 3, 6, 7, 8, 9, 10], flow_title='Access lifecycle: your part', flow_kicker='Request to leaver',
    flow_loop='You are not part of the broking cycle itself',
    flow_notes=['Create and assign only after the manager approves.', 'Review users and roles periodically.',
                'Unlock or reset on a verified request.', 'Deactivate leavers on their last day.'],
    reports=[], reports_title='Evidence you use instead of reports',
    reports_note='This role has no report catalogue.',
    reports_alt=[('User list', 'Active and inactive users with their roles'),
                 ('Role list', 'Roles, status and permissions'),
                 ('Audit trail', 'Every change with before / after values, filtered by user or record'),
                 ('Sign-ins', 'Audit trail record type session, action login'),
                 ('User sign-in history', 'Per-user sign-in history through the user API (IT administrator)')],
    jobs=[('email-outbox', 'Password reset codes and notices leave every 5 minutes')],
    jobs_note='No business schedules affect this role. Password expiry (90 days) and lockout are rules, not jobs.',
    notifications=[('Info', 'Notifications', 'The bell shows general notices; there are no approvals for this role.'),
                   ('E-mail', 'Password reset code', 'Users who use Forgot password get a code by e-mail.')],
    limits=['User list shows the role code in capitals and names in upper case; action icons are small.',
            'E-mail column is empty when a user has none.',
            'There is no dedicated sign-in history screen yet: use the audit trail (session / login).'] + COMMON_LIMITS[1:],
    tips=['Give each person their own user; never share accounts.', 'Grant the smallest role that does the job.',
          'Keep maker and checker on different people.', 'Review users with managers every quarter.'],
    access_contact='IT administrator for settings; line manager to approve access requests',
))
