/**
 * Journals generated by period-end processing: recurring / accrual templates, auto-reversal on day 1 of the next
 * period, and the undo used when a month-end run is executed again (its previous entries are neutralised first,
 * so a rerun gives the same ledger as a single run).
 */
import { badRequest } from '../../lib/errors.js';
import { round2 } from '../../lib/money.js';
import { addDays } from '../../lib/dates.js';
import { nextNumber } from '../masters/helpers.js';
import { cancelJournal, createJournal, markReversed, reverseJournal } from '../accounting/lib/ledger.js';
import { addMonths, iso } from './fiscal.js';

const OPEN_JV = ['pending', 'draft', 'for-approval', 'approved'];
const STEP_MONTHS = { monthly: 1, quarterly: 3, yearly: 12 };

/** The next occurrence after `date`: same day of month n months later; a month end stays a month end. */
export function advance(date, frequency) {
  const n = STEP_MONTHS[frequency] || 1;
  const d = iso(date);
  const isMonthEnd = addDays(d, 1).slice(8, 10) === '01';
  const firstOfTarget = addMonths(d, n);
  const lastOfTarget = addDays(addMonths(firstOfTarget, 1), -1);
  if (isMonthEnd) return lastOfTarget;
  const day = Math.min(Number(d.slice(8, 10)), Number(lastOfTarget.slice(8, 10)));
  return `${firstOfTarget.slice(0, 8)}${String(day).padStart(2, '0')}`;
}

export const rjRow = (r) => r && ({
  id: r.id, code: r.code, name: r.name, description: r.description, kind: r.kind, frequency: r.frequency, startDate: iso(r.start_date),
  nextRunDate: r.next_run_date ? iso(r.next_run_date) : null, endDate: r.end_date ? iso(r.end_date) : null, autoPost: r.auto_post, autoReverse: r.auto_reverse,
  currency: r.currency, lines: r.lines, status: r.status, lastRunDate: r.last_run_date ? iso(r.last_run_date) : null, lastJournalId: r.last_jv_id,
  totalDebit: round2((r.lines || []).reduce((s, l) => s + Number(l.debit || 0), 0)), createdBy: r.created_by, createdAt: r.created_at, updatedAt: r.updated_at,
});

function checkLines(lines) {
  const ls = (lines || []).map((l) => ({ accountCode: String(l.accountCode || '').trim(), debit: round2(l.debit || 0), credit: round2(l.credit || 0), memo: l.memo || null }))
    .filter((l) => l.accountCode && (l.debit > 0 || l.credit > 0));
  if (ls.length < 2) throw badRequest('A recurring journal needs at least two lines with an amount');
  const d = round2(ls.reduce((s, l) => s + l.debit, 0)); const c = round2(ls.reduce((s, l) => s + l.credit, 0));
  if (d !== c) throw badRequest(`Recurring journal is not balanced: debit ${d} vs credit ${c}`);
  return ls;
}

async function checkAccounts(db, lines) {
  const codes = [...new Set(lines.map((l) => l.accountCode))];
  const found = new Set((await db.query('SELECT code FROM gl_accounts WHERE code = ANY($1) AND status = \'active\'', [codes])).rows.map((r) => r.code));
  const missing = codes.filter((c) => !found.has(c));
  if (missing.length) throw badRequest(`Unknown or inactive GL account(s): ${missing.join(', ')}`);
}

export async function saveRecurring(db, b, user, id = null) {
  const current = id ? (await db.query('SELECT * FROM recurring_journals WHERE id = $1 OR code = $1', [id])).rows[0] : null;
  if (id && !current) throw badRequest('Recurring journal not found');
  const merged = { ...(current ? rjRow(current) : {}), ...b };
  const lines = checkLines(merged.lines);
  await checkAccounts(db, lines);
  const kind = merged.kind || 'recurring';
  if (!merged.name) throw badRequest('name is required');
  if (!merged.startDate) throw badRequest('startDate is required');
  const start = iso(merged.startDate);
  const end = merged.endDate ? iso(merged.endDate) : null;
  if (end && end < start) throw badRequest('endDate must be on or after startDate');
  const next = b.nextRunDate ? iso(b.nextRunDate) : (current?.next_run_date && !b.startDate ? iso(current.next_run_date) : start);
  const autoReverse = merged.autoReverse ?? (kind === 'accrual');
  const values = [merged.name, merged.description || null, kind, merged.frequency || 'monthly', start, next, end, merged.autoPost !== false, !!autoReverse,
    merged.currency || 'PHP', JSON.stringify(lines), merged.status || 'active', user?.id ?? null];
  if (current) {
    return (await db.query(`UPDATE recurring_journals SET name = $1, description = $2, kind = $3, frequency = $4, start_date = $5, next_run_date = $6, end_date = $7,
      auto_post = $8, auto_reverse = $9, currency = $10, lines = $11, status = $12, updated_by = $13, updated_at = now() WHERE id = $14 RETURNING *`, [...values, current.id])).rows[0];
  }
  const code = await nextNumber('recurring_journal');
  return (await db.query(`INSERT INTO recurring_journals(name, description, kind, frequency, start_date, next_run_date, end_date, auto_post, auto_reverse, currency, lines, status, created_by, code)
    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`, [...values, code])).rows[0];
}

/**
 * Generate the occurrences of active templates of `kind` due up to `asOf` (and, with `from`, not before it: earlier
 * missed occurrences are skipped). Idempotent: one journal per template and occurrence date. With `onlyId`, one
 * template. Returns { created: [{ recurringId, code, occurrence, jvId, jvNumber, status, autoReverseOn }], errors }.
 */
export async function generateDue(db, { kind, asOf, from = null, user = null, closeRunId = null, onlyId = null }) {
  const templates = (await db.query(`SELECT * FROM recurring_journals WHERE status = 'active' AND kind = $1 AND next_run_date <= $2 AND ($3::text IS NULL OR id = $3)
    ORDER BY next_run_date, code FOR UPDATE`, [kind, asOf, onlyId])).rows;
  const created = []; const errors = [];
  for (const t of templates) {
    let next = iso(t.next_run_date);
    while (next <= asOf && (!t.end_date || next <= iso(t.end_date))) {
      if (from && next < from) { next = advance(next, t.frequency); continue; }
      const dup = (await db.query('SELECT jv_id FROM recurring_journal_runs WHERE recurring_id = $1 AND occurrence_date = $2 AND status IN (\'posted\',\'pending\')', [t.id, next])).rows[0];
      if (!dup) {
        await db.query('SAVEPOINT rj');
        try {
          const jv = await createJournal(db, {
            date: next, description: `${t.name} – ${next}`, source: 'recurring-journal', kind: 'standard', entryType: kind === 'accrual' ? 'ACCRUAL' : 'RECURRING_JOURNAL',
            transactionCode: t.code, referenceType: 'RecurringJournal', referenceId: t.id, currency: t.currency,
            status: t.auto_post ? 'posted' : 'pending', requiresApproval: !t.auto_post,
            lines: t.lines.map((l) => ({ accountCode: l.accountCode, debit: l.debit, credit: l.credit, memo: l.memo || t.name })),
          }, user);
          const run = (await db.query(`INSERT INTO recurring_journal_runs(recurring_id, occurrence_date, period, jv_id, close_run_id, status, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id`,
            [t.id, next, next.slice(0, 7), jv.id, closeRunId, jv.status === 'posted' ? 'posted' : 'pending', user?.id ?? null])).rows[0];
          const autoReverseOn = t.auto_reverse ? addDays(next, 1) : null;
          if (t.auto_reverse) {
            await db.query(`INSERT INTO period_close_entries(run_id, period, step, jv_id, auto_reverse_on, recurring_run_id) VALUES ($1,$2,$3,$4,$5,$6)`,
              [closeRunId, next.slice(0, 7), kind === 'accrual' ? 'accrual' : 'recurring', jv.id, autoReverseOn, run.id]);
          }
          await db.query('UPDATE recurring_journals SET last_run_date = $2, last_jv_id = $3 WHERE id = $1', [t.id, next, jv.id]);
          await db.query('RELEASE SAVEPOINT rj');
          created.push({ recurringId: t.id, code: t.code, name: t.name, occurrence: next, jvId: jv.id, jvNumber: jv.jv_number, status: jv.status, autoReverseOn });
        } catch (e) {
          await db.query('ROLLBACK TO SAVEPOINT rj');
          errors.push({ recurringId: t.id, code: t.code, occurrence: next, error: e.message });
          break; // keep next_run_date at the failed occurrence so it is retried
        }
      }
      next = advance(next, t.frequency);
    }
    const done = t.end_date && next > iso(t.end_date);
    if (!errors.some((e) => e.recurringId === t.id)) {
      await db.query('UPDATE recurring_journals SET next_run_date = $2, status = $3, updated_at = now() WHERE id = $1', [t.id, next, done ? 'completed' : 'active']);
    } else {
      const failedAt = errors.find((e) => e.recurringId === t.id).occurrence;
      await db.query('UPDATE recurring_journals SET next_run_date = $2, updated_at = now() WHERE id = $1', [t.id, failedAt]);
    }
  }
  return { created, errors };
}

/** Mirror a journal (debits and credits swapped) with createJournal, on `date` / `period`. */
export async function mirrorJournal(db, jv, { date, period = null, description, source = 'period-close', user = null, markOriginal = false }) {
  const lines = (await db.query('SELECT * FROM journal_lines WHERE jv_id = $1 ORDER BY line_no', [jv.id])).rows;
  const m = await createJournal(db, {
    date, period, description, source, kind: 'reversal', entryType: jv.entry_type, entrySubType: 'REVERSAL', transactionCode: jv.transaction_code,
    referenceType: jv.reference_type, referenceId: jv.reference_id, currency: jv.currency, status: 'posted', reversalOf: markOriginal ? jv.id : null,
    lines: lines.map((l) => ({ accountCode: l.account_code, debit: Number(l.credit), credit: Number(l.debit), memo: l.memo, clientId: l.client_id, policyId: l.policy_id,
      currencyCode: l.currency_code, foreignAmount: l.foreign_amount, exchangeRate: l.exchange_rate })),
  }, user);
  if (markOriginal) await markReversed(db, jv.id, m.id);
  return m;
}

const getJv = async (db, id) => (await db.query('SELECT * FROM journal_vouchers WHERE id = $1 FOR UPDATE', [id])).rows[0];

/**
 * Neutralise a generated entry (rerun): an unposted journal is cancelled; a posted one is reversed on its own date;
 * one already reversed by its auto-reversal has that reversal reversed and is mirrored on its own date.
 */
export async function undoEntry(db, e, user) {
  const jv = await getJv(db, e.jv_id);
  const created = [];
  if (OPEN_JV.includes(jv.status)) {
    await cancelJournal(db, jv.id, user || { id: null });
  } else if (jv.status === 'posted') {
    created.push((await reverseJournal(db, jv.id, user, { date: iso(jv.jv_date), description: `Rerun of month-end close: reversal of ${jv.jv_number}` })).id);
  } else if (jv.status === 'reversed') {
    if (e.reversal_jv_id) {
      const r = await getJv(db, e.reversal_jv_id);
      if (r?.status === 'posted') created.push((await reverseJournal(db, r.id, user, { date: iso(r.jv_date), description: `Rerun of month-end close: reversal of ${r.jv_number}` })).id);
      else if (r && OPEN_JV.includes(r.status)) await cancelJournal(db, r.id, user || { id: null });
    }
    created.push((await mirrorJournal(db, jv, { date: iso(jv.jv_date), description: `Rerun of month-end close: reversal of ${jv.jv_number}`, user })).id);
  }
  await db.query('UPDATE period_close_entries SET status = \'undone\', undo_jv_ids = $2, updated_at = now() WHERE id = $1', [e.id, created]);
  if (e.recurring_run_id) {
    const run = (await db.query('UPDATE recurring_journal_runs SET status = \'undone\' WHERE id = $1 RETURNING recurring_id, occurrence_date', [e.recurring_run_id])).rows[0];
    if (run) {
      await db.query(`UPDATE recurring_journals SET next_run_date = LEAST(next_run_date, $2), status = CASE WHEN status = 'completed' THEN 'active' ELSE status END, updated_at = now()
        WHERE id = $1`, [run.recurring_id, run.occurrence_date]);
    }
  }
  return created;
}

/**
 * Post the auto-reversals that are due (auto_reverse_on <= asOf) for posted entries: a mirror journal dated the
 * reversal date. Each is done in a savepoint; failures (e.g. the next period is closed) are returned and retried later.
 */
export async function reverseDue(db, { asOf, user = null, runId = null }) {
  const due = (await db.query(`SELECT e.*, j.status AS jv_status, j.jv_number FROM period_close_entries e JOIN journal_vouchers j ON j.id = e.jv_id
    WHERE e.status = 'active' AND e.reversal_jv_id IS NULL AND e.auto_reverse_on <= $1 AND ($2::text IS NULL OR e.run_id = $2) ORDER BY e.id`, [asOf, runId])).rows;
  const reversed = []; const errors = [];
  for (const e of due) {
    if (e.jv_status !== 'posted') continue;
    await db.query('SAVEPOINT rev');
    try {
      const r = await reverseJournal(db, e.jv_id, user, { date: iso(e.auto_reverse_on), description: `Auto-reversal of ${e.jv_number} (${e.step})` });
      await db.query('UPDATE period_close_entries SET reversal_jv_id = $2, error = NULL, updated_at = now() WHERE id = $1', [e.id, r.id]);
      await db.query('RELEASE SAVEPOINT rev');
      reversed.push({ entryId: e.id, jvNumber: e.jv_number, reversalId: r.id, reversalNumber: r.jv_number, date: iso(e.auto_reverse_on) });
    } catch (err) {
      await db.query('ROLLBACK TO SAVEPOINT rev');
      await db.query('UPDATE period_close_entries SET error = $2, updated_at = now() WHERE id = $1', [e.id, err.message]);
      errors.push({ entryId: e.id, jvNumber: e.jv_number, error: err.message });
    }
  }
  return { reversed, errors };
}
