-- Placement journey reports: Placement Pipeline (broker slips and placement slips by status and age) and Market Response
-- (offers per insurer, response rate and hit ratio). Queries: src/modules/reports/queries.js (placementPipeline, marketResponse).
INSERT INTO app_settings(key, value, "group", label, type) VALUES
 ('reports.placement_age_buckets', '[7,14,30,60]'::jsonb, 'reports', 'Placement pipeline ageing buckets (days since the slip was created)', 'json'),
 ('reports.placement_open_statuses', '["draft","submitted","responses-in","sent","bound","declined"]'::jsonb, 'reports', 'Broker slip / placement slip statuses counted as open in the placement pipeline', 'json')
ON CONFLICT (key) DO NOTHING;

INSERT INTO report_definitions(code, name, category, description, screen, query_name, parameters, default_columns, roles, sort_order) VALUES
 ('placement-pipeline', 'Placement Pipeline', 'operational', 'Broker slips and placement slips created in the period with status, lead insurer, sum insured, premium and age (open slips by age bucket).', 'Operations > Placement Slips > Reports', 'placementPipeline',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Slip Type","Status","Open by Age","Agent"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Agent":{"type":"string","title":"Agent","description":"id, code or name","x-options":"users"},"Company":{"type":"string","title":"Company (lead insurer)","description":"id, code or name","x-options":"insurance_companies"},"Branch":{"type":"string","title":"Branch","description":"id, code or name","x-options":"branches"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"Status":{"type":"string","title":"Status","description":"draft, submitted, responses-in, closed, sent, bound, declined, issued, cancelled"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"slipType","label":"Slip","type":"text"},{"key":"slipNumber","label":"Slip No.","type":"text"},{"key":"createdDate","label":"Created","type":"date"},{"key":"status","label":"Status","type":"text"},{"key":"client","label":"Client / Insured","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"lob","label":"LOB","type":"text"},{"key":"insurer","label":"Lead Insurer","type":"text"},{"key":"insurers","label":"Insurers","type":"integer","total":false},{"key":"agent","label":"Agent","type":"text"},{"key":"sumInsured","label":"Sum Insured","type":"money"},{"key":"premium","label":"Premium (best offer / gross)","type":"money"},{"key":"ageDays","label":"Age (days)","type":"integer","total":false},{"key":"ageBucket","label":"Age Bucket","type":"text"}]'::jsonb,
  ARRAY['sales','underwriting','customer-services']::text[], 95),
 ('market-response', 'Market Response', 'operational', 'Insurers approached on broker slips in the period: offers, declines, pending, response rate, average response days, offers taken and hit ratio (offers taken / offers made).', 'Operations > Broker Slips > Reports', 'marketResponse',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Line of Business","Agent"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Agent":{"type":"string","title":"Agent","description":"id, code or name","x-options":"users"},"Company":{"type":"string","title":"Company (insurer)","description":"id, code or name","x-options":"insurance_companies"},"Branch":{"type":"string","title":"Branch","description":"id, code or name","x-options":"branches"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"lob","label":"LOB","type":"text"},{"key":"agent","label":"Agent","type":"text"},{"key":"approached","label":"Approached","type":"integer"},{"key":"offered","label":"Offers","type":"integer"},{"key":"declined","label":"Declined","type":"integer"},{"key":"pending","label":"Pending","type":"integer"},{"key":"selected","label":"Offers Taken","type":"integer"},{"key":"responseRate","label":"Response %","type":"number","total":false},{"key":"hitRatio","label":"Hit Ratio %","type":"number","total":false},{"key":"averageResponseDays","label":"Avg Response (days)","type":"number","total":false},{"key":"offeredPremium","label":"Premium Offered","type":"money"}]'::jsonb,
  ARRAY['sales','underwriting','customer-services']::text[], 96)
ON CONFLICT (code) DO NOTHING;
