-- Co-insurance reports: Co-insurance Register (participants of co-insured policies with their shares) and Due to Insurers
-- by Co-insurer (premium due to each insurer, collected, remitted and still held, a co-insured bill split per participant).
INSERT INTO report_definitions(code, name, category, description, screen, query_name, parameters, default_columns, roles, sort_order) VALUES
 ('coinsurance-register', 'Co-insurance Register', 'operational', 'Co-insured policies incepted in the period: every participating insurer with its role, share, premium, commission, premium taxes and premium due as booked on the bills.',
  'Reports > Financial Reports > Co-insurance Register', 'coInsuranceRegister',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Co-insurer","Policy","Agent"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Agent":{"type":"string","title":"Agent","description":"id, code or name","x-options":"users"},"Company":{"type":"string","title":"Company (participating insurer)","description":"id, code or name","x-options":"insurance_companies"},"Branch":{"type":"string","title":"Branch","description":"id, code or name","x-options":"branches"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"Status":{"type":"string","title":"Status","description":"policy status"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"inceptionDate","label":"Inception","type":"date"},{"key":"client","label":"Client","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"leadInsurer","label":"Lead Insurer","type":"text"},{"key":"insurer","label":"Insurer","type":"text"},{"key":"role","label":"Role","type":"text"},{"key":"sharePercent","label":"Share %","type":"number","total":false},{"key":"sumInsured","label":"Sum Insured","type":"money"},{"key":"premium","label":"Premium","type":"money"},{"key":"commission","label":"Commission","type":"money"},{"key":"taxes","label":"Premium Taxes","type":"money"},{"key":"dueToInsurer","label":"Due to Insurer","type":"money"},{"key":"insurerReference","label":"Insurer Ref.","type":"text"},{"key":"agent","label":"Agent","type":"text"},{"key":"status","label":"Status","type":"text"}]'::jsonb,
  ARRAY['finance','underwriting','sales']::text[], 190),
 ('due-to-insurers-by-coinsurer', 'Due to Insurers by Co-insurer', 'financial', 'Premium due to each insurer on bills issued in the period (co-insured bills split per participant, net of that insurer''s commission): due, collected from clients, remitted and still held for the insurer.',
  'Reports > Financial Reports > Due to Insurers by Co-insurer', 'dueToInsurers',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Co-insurer","Co-insurer and Policy","Placement"],"default":"Co-insurer"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Agent":{"type":"string","title":"Agent","description":"id, code or name","x-options":"users"},"Company":{"type":"string","title":"Company (insurer)","description":"id, code or name","x-options":"insurance_companies"},"Branch":{"type":"string","title":"Branch","description":"id, code or name","x-options":"branches"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"Status":{"type":"string","title":"Status","description":"bill status"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"placement","label":"Placement","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"bills","label":"Bills","type":"integer"},{"key":"premium","label":"Premium","type":"money"},{"key":"commission","label":"Commission","type":"money"},{"key":"dueToInsurer","label":"Due to Insurer","type":"money"},{"key":"collectedDue","label":"Collected","type":"money"},{"key":"remitted","label":"Remitted","type":"money"},{"key":"outstanding","label":"Held for Insurer","type":"money"},{"key":"uncollected","label":"Not yet Collected","type":"money"}]'::jsonb,
  ARRAY['finance']::text[], 195)
ON CONFLICT (code) DO NOTHING;
