-- Indexes for foreign-key columns used in joins and filters, plus the operational log indexes.
--
-- The list below was generated from the catalog with `node scripts/fk-index-report.js --sql`: every foreign key with no
-- index starting with its columns, on tables that grow (transactions, documents, lines, logs). Foreign keys on small
-- master / set-up tables (products, policy types, reinsurers, vehicle models, ...) and maker-checker stamp columns
-- (approved_by, rejected_by, ...) are left out; the script lists them too. IF NOT EXISTS keeps the migration idempotent.

-- ---------- operational logs ----------
CREATE INDEX IF NOT EXISTS job_runs_job_started_idx ON job_runs (job_id, started_at);
CREATE INDEX IF NOT EXISTS email_outbox_status_created_idx ON email_outbox (status, created_at);
CREATE INDEX IF NOT EXISTS audit_log_at_idx ON audit_log (at);
CREATE INDEX IF NOT EXISTS audit_log_username_idx ON audit_log (username);
CREATE INDEX IF NOT EXISTS audit_log_entity_idx ON audit_log (entity, entity_id);

-- ---------- foreign keys (generated) ----------
CREATE INDEX IF NOT EXISTS agent_events_user_id_fk_idx ON agent_events (user_id);
CREATE INDEX IF NOT EXISTS broker_slips_owner_user_id_fk_idx ON broker_slips (owner_user_id);
CREATE INDEX IF NOT EXISTS broker_slips_product_id_fk_idx ON broker_slips (product_id);
CREATE INDEX IF NOT EXISTS broker_slips_quote_id_fk_idx ON broker_slips (quote_id);
CREATE INDEX IF NOT EXISTS cessions_facultative_reinsurer_id_fk_idx ON cessions (facultative_reinsurer_id);
CREATE INDEX IF NOT EXISTS cessions_policy_id_fk_idx ON cessions (policy_id);
CREATE INDEX IF NOT EXISTS cessions_treaty_id_fk_idx ON cessions (treaty_id);
CREATE INDEX IF NOT EXISTS checkbooks_disbursement_id_fk_idx ON checkbooks (disbursement_id);
CREATE INDEX IF NOT EXISTS checkbooks_journal_id_fk_idx ON checkbooks (journal_id);
CREATE INDEX IF NOT EXISTS claims_handler_user_id_fk_idx ON claims (handler_user_id);
CREATE INDEX IF NOT EXISTS clients_owner_user_id_fk_idx ON clients (owner_user_id);
CREATE INDEX IF NOT EXISTS collection_items_assigned_to_fk_idx ON collection_items (assigned_to);
CREATE INDEX IF NOT EXISTS collection_items_client_id_fk_idx ON collection_items (client_id);
CREATE INDEX IF NOT EXISTS collection_items_policy_id_fk_idx ON collection_items (policy_id);
CREATE INDEX IF NOT EXISTS commission_debit_note_collections_journal_id_fk_idx ON commission_debit_note_collections (journal_id);
CREATE INDEX IF NOT EXISTS commission_debit_note_lines_item_id_fk_idx ON commission_debit_note_lines (item_id);
CREATE INDEX IF NOT EXISTS commission_debit_note_lines_policy_id_fk_idx ON commission_debit_note_lines (policy_id);
CREATE INDEX IF NOT EXISTS commissions_accrual_jv_id_fk_idx ON commissions (accrual_jv_id);
CREATE INDEX IF NOT EXISTS commissions_agent_user_id_fk_idx ON commissions (agent_user_id);
CREATE INDEX IF NOT EXISTS commissions_disbursement_id_fk_idx ON commissions (disbursement_id);
CREATE INDEX IF NOT EXISTS commissions_endorsement_id_fk_idx ON commissions (endorsement_id);
CREATE INDEX IF NOT EXISTS commissions_payment_jv_id_fk_idx ON commissions (payment_jv_id);
CREATE INDEX IF NOT EXISTS commissions_quote_id_fk_idx ON commissions (quote_id);
CREATE INDEX IF NOT EXISTS direct_bill_items_booking_jv_id_fk_idx ON direct_bill_items (booking_jv_id);
CREATE INDEX IF NOT EXISTS direct_bill_items_debit_note_id_fk_idx ON direct_bill_items (debit_note_id);
CREATE INDEX IF NOT EXISTS direct_bill_items_endorsement_id_fk_idx ON direct_bill_items (endorsement_id);
CREATE INDEX IF NOT EXISTS direct_bill_items_reversal_jv_id_fk_idx ON direct_bill_items (reversal_jv_id);
CREATE INDEX IF NOT EXISTS disbursements_bank_id_fk_idx ON disbursements (bank_id);
CREATE INDEX IF NOT EXISTS disbursements_client_id_fk_idx ON disbursements (client_id);
CREATE INDEX IF NOT EXISTS disbursements_insurance_company_id_fk_idx ON disbursements (insurance_company_id);
CREATE INDEX IF NOT EXISTS disbursements_journal_id_fk_idx ON disbursements (journal_id);
CREATE INDEX IF NOT EXISTS disbursements_policy_id_fk_idx ON disbursements (policy_id);
CREATE INDEX IF NOT EXISTS endorsements_client_id_fk_idx ON endorsements (client_id);
CREATE INDEX IF NOT EXISTS endorsements_receivable_id_fk_idx ON endorsements (receivable_id);
CREATE INDEX IF NOT EXISTS entry_matches_write_off_jv_id_fk_idx ON entry_matches (write_off_jv_id);
CREATE INDEX IF NOT EXISTS incentive_results_calculation_id_fk_idx ON incentive_results (calculation_id);
CREATE INDEX IF NOT EXISTS invoice_lists_client_id_fk_idx ON invoice_lists (client_id);
CREATE INDEX IF NOT EXISTS invoice_lists_disbursement_id_fk_idx ON invoice_lists (disbursement_id);
CREATE INDEX IF NOT EXISTS invoice_lists_insurance_company_id_fk_idx ON invoice_lists (insurance_company_id);
CREATE INDEX IF NOT EXISTS invoice_lists_policy_id_fk_idx ON invoice_lists (policy_id);
CREATE INDEX IF NOT EXISTS invoice_lists_receipt_id_fk_idx ON invoice_lists (receipt_id);
CREATE INDEX IF NOT EXISTS journal_lines_policy_id_fk_idx ON journal_lines (policy_id);
CREATE INDEX IF NOT EXISTS journal_vouchers_client_id_fk_idx ON journal_vouchers (client_id);
CREATE INDEX IF NOT EXISTS journal_vouchers_correction_of_fk_idx ON journal_vouchers (correction_of);
CREATE INDEX IF NOT EXISTS journal_vouchers_posting_rule_id_fk_idx ON journal_vouchers (posting_rule_id);
CREATE INDEX IF NOT EXISTS journal_vouchers_reversal_of_fk_idx ON journal_vouchers (reversal_of);
CREATE INDEX IF NOT EXISTS journal_vouchers_reversed_by_jv_fk_idx ON journal_vouchers (reversed_by_jv);
CREATE INDEX IF NOT EXISTS leads_client_id_fk_idx ON leads (client_id);
CREATE INDEX IF NOT EXISTS leads_owner_user_id_fk_idx ON leads (owner_user_id);
CREATE INDEX IF NOT EXISTS leads_product_id_fk_idx ON leads (product_id);
CREATE INDEX IF NOT EXISTS password_resets_user_id_fk_idx ON password_resets (user_id);
CREATE INDEX IF NOT EXISTS period_close_entries_jv_id_fk_idx ON period_close_entries (jv_id);
CREATE INDEX IF NOT EXISTS period_close_entries_reversal_jv_id_fk_idx ON period_close_entries (reversal_jv_id);
CREATE INDEX IF NOT EXISTS petty_cash_disbursements_fund_id_fk_idx ON petty_cash_disbursements (fund_id);
CREATE INDEX IF NOT EXISTS petty_cash_disbursements_journal_id_fk_idx ON petty_cash_disbursements (journal_id);
CREATE INDEX IF NOT EXISTS petty_cash_disbursements_request_id_fk_idx ON petty_cash_disbursements (request_id);
CREATE INDEX IF NOT EXISTS petty_cash_receipts_fund_id_fk_idx ON petty_cash_receipts (fund_id);
CREATE INDEX IF NOT EXISTS petty_cash_receipts_journal_id_fk_idx ON petty_cash_receipts (journal_id);
CREATE INDEX IF NOT EXISTS petty_cash_replenishments_fund_id_fk_idx ON petty_cash_replenishments (fund_id);
CREATE INDEX IF NOT EXISTS petty_cash_replenishments_journal_id_fk_idx ON petty_cash_replenishments (journal_id);
CREATE INDEX IF NOT EXISTS petty_cash_request_lines_request_id_fk_idx ON petty_cash_request_lines (request_id);
CREATE INDEX IF NOT EXISTS petty_cash_requests_fund_id_fk_idx ON petty_cash_requests (fund_id);
CREATE INDEX IF NOT EXISTS petty_cash_requests_requester_user_id_fk_idx ON petty_cash_requests (requester_user_id);
CREATE INDEX IF NOT EXISTS placements_client_id_fk_idx ON placements (client_id);
CREATE INDEX IF NOT EXISTS placements_insurance_company_id_fk_idx ON placements (insurance_company_id);
CREATE INDEX IF NOT EXISTS placements_lead_id_fk_idx ON placements (lead_id);
CREATE INDEX IF NOT EXISTS placements_owner_user_id_fk_idx ON placements (owner_user_id);
CREATE INDEX IF NOT EXISTS placements_policy_id_fk_idx ON placements (policy_id);
CREATE INDEX IF NOT EXISTS placements_policy_type_id_fk_idx ON placements (policy_type_id);
CREATE INDEX IF NOT EXISTS placements_product_id_fk_idx ON placements (product_id);
CREATE INDEX IF NOT EXISTS policies_insurance_company_id_fk_idx ON policies (insurance_company_id);
CREATE INDEX IF NOT EXISTS policies_lead_id_fk_idx ON policies (lead_id);
CREATE INDEX IF NOT EXISTS policies_owner_user_id_fk_idx ON policies (owner_user_id);
CREATE INDEX IF NOT EXISTS policies_placement_id_fk_idx ON policies (placement_id);
CREATE INDEX IF NOT EXISTS policies_policy_type_id_fk_idx ON policies (policy_type_id);
CREATE INDEX IF NOT EXISTS policies_product_id_fk_idx ON policies (product_id);
CREATE INDEX IF NOT EXISTS policies_renewed_from_fk_idx ON policies (renewed_from);
CREATE INDEX IF NOT EXISTS policy_payments_receipt_id_fk_idx ON policy_payments (receipt_id);
CREATE INDEX IF NOT EXISTS policy_payments_receivable_id_fk_idx ON policy_payments (receivable_id);
CREATE INDEX IF NOT EXISTS quotes_agent_user_id_fk_idx ON quotes (agent_user_id);
CREATE INDEX IF NOT EXISTS quotes_broker_slip_id_fk_idx ON quotes (broker_slip_id);
CREATE INDEX IF NOT EXISTS quotes_client_id_fk_idx ON quotes (client_id);
CREATE INDEX IF NOT EXISTS quotes_insurance_company_id_fk_idx ON quotes (insurance_company_id);
CREATE INDEX IF NOT EXISTS quotes_policy_id_fk_idx ON quotes (policy_id);
CREATE INDEX IF NOT EXISTS quotes_policy_type_id_fk_idx ON quotes (policy_type_id);
CREATE INDEX IF NOT EXISTS quotes_product_id_fk_idx ON quotes (product_id);
CREATE INDEX IF NOT EXISTS quotes_signatory_id_fk_idx ON quotes (signatory_id);
CREATE INDEX IF NOT EXISTS receipt_applications_journal_id_fk_idx ON receipt_applications (journal_id);
CREATE INDEX IF NOT EXISTS receipt_applications_receipt_id_fk_idx ON receipt_applications (receipt_id);
CREATE INDEX IF NOT EXISTS receipt_applications_receipt_line_id_fk_idx ON receipt_applications (receipt_line_id);
CREATE INDEX IF NOT EXISTS receipt_lines_policy_id_fk_idx ON receipt_lines (policy_id);
CREATE INDEX IF NOT EXISTS receipts_bank_id_fk_idx ON receipts (bank_id);
CREATE INDEX IF NOT EXISTS receipts_client_id_fk_idx ON receipts (client_id);
CREATE INDEX IF NOT EXISTS receipts_receivable_id_fk_idx ON receipts (receivable_id);
CREATE INDEX IF NOT EXISTS receivable_credits_journal_id_fk_idx ON receivable_credits (journal_id);
CREATE INDEX IF NOT EXISTS receivable_credits_receivable_id_fk_idx ON receivable_credits (receivable_id);
CREATE INDEX IF NOT EXISTS receivable_participants_insurance_company_id_fk_idx ON receivable_participants (insurance_company_id);
CREATE INDEX IF NOT EXISTS receivables_booking_jv_id_fk_idx ON receivables (booking_jv_id);
CREATE INDEX IF NOT EXISTS recurring_journal_runs_jv_id_fk_idx ON recurring_journal_runs (jv_id);
CREATE INDEX IF NOT EXISTS reinsurance_bordereaux_reinsurer_id_fk_idx ON reinsurance_bordereaux (reinsurer_id);
CREATE INDEX IF NOT EXISTS reinsurance_bordereaux_treaty_id_fk_idx ON reinsurance_bordereaux (treaty_id);
CREATE INDEX IF NOT EXISTS reinsurance_exceptions_reconciliation_id_fk_idx ON reinsurance_exceptions (reconciliation_id);
CREATE INDEX IF NOT EXISTS reinsurance_reconciliations_reinsurer_id_fk_idx ON reinsurance_reconciliations (reinsurer_id);
CREATE INDEX IF NOT EXISTS reinsurance_recoveries_cession_id_fk_idx ON reinsurance_recoveries (cession_id);
CREATE INDEX IF NOT EXISTS reinsurance_recoveries_claim_id_fk_idx ON reinsurance_recoveries (claim_id);
CREATE INDEX IF NOT EXISTS reinsurance_recoveries_treaty_id_fk_idx ON reinsurance_recoveries (treaty_id);
CREATE INDEX IF NOT EXISTS remittance_allocations_insurance_company_id_fk_idx ON remittance_allocations (insurance_company_id);
CREATE INDEX IF NOT EXISTS remittance_allocations_invoice_list_id_fk_idx ON remittance_allocations (invoice_list_id);
CREATE INDEX IF NOT EXISTS remittance_approvals_initiator_id_fk_idx ON remittance_approvals (initiator_id);
CREATE INDEX IF NOT EXISTS remittance_items_insurance_company_id_fk_idx ON remittance_items (insurance_company_id);
CREATE INDEX IF NOT EXISTS remittance_items_remittance_id_fk_idx ON remittance_items (remittance_id);
CREATE INDEX IF NOT EXISTS remittance_lines_insurance_company_id_fk_idx ON remittance_lines (insurance_company_id);
CREATE INDEX IF NOT EXISTS remittance_lines_policy_id_fk_idx ON remittance_lines (policy_id);
CREATE INDEX IF NOT EXISTS remittance_lines_remittance_id_fk_idx ON remittance_lines (remittance_id);
CREATE INDEX IF NOT EXISTS remittances_agent_user_id_fk_idx ON remittances (agent_user_id);
CREATE INDEX IF NOT EXISTS remittances_insurance_company_id_fk_idx ON remittances (insurance_company_id);
CREATE INDEX IF NOT EXISTS renewal_batch_policies_policy_id_fk_idx ON renewal_batch_policies (policy_id);
CREATE INDEX IF NOT EXISTS renewal_batch_policies_renewal_id_fk_idx ON renewal_batch_policies (renewal_id);
CREATE INDEX IF NOT EXISTS renewals_client_id_fk_idx ON renewals (client_id);
CREATE INDEX IF NOT EXISTS renewals_new_policy_id_fk_idx ON renewals (new_policy_id);
CREATE INDEX IF NOT EXISTS year_end_runs_closing_jv_id_fk_idx ON year_end_runs (closing_jv_id);
CREATE INDEX IF NOT EXISTS year_end_runs_transfer_jv_id_fk_idx ON year_end_runs (transfer_jv_id);
