-- Lists offered on master forms instead of free text:
--   bir.rdo_codes                       BIR Revenue District Offices offered for the RDO code of a company (Master >
--                                       Organization > Company > Tax registration), as { code, name }. The list is kept in
--                                       System Settings, so an office the BIR adds or renames is maintained there; the
--                                       company form still takes a code that is not in the list (3 digits and a letter at
--                                       most). Starter list of the district offices of the BIR revenue regions; the large
--                                       taxpayers offices are not listed.
--   cost-centre responsiblePerson       Master > Finance > Cost Centres: the responsible person is picked from the active
--                                       users (the department already comes from the department master).
-- Idempotent.

INSERT INTO app_settings(key, value, "group", label, type) VALUES
 ('bir.rdo_codes', $j$[
  {"code": "001", "name": "Laoag City, Ilocos Norte"},
  {"code": "002", "name": "Vigan, Ilocos Sur"},
  {"code": "003", "name": "San Fernando, La Union"},
  {"code": "004", "name": "Calasiao, West Pangasinan"},
  {"code": "005", "name": "Alaminos, Pangasinan"},
  {"code": "006", "name": "Urdaneta, Pangasinan"},
  {"code": "007", "name": "Bangued, Abra"},
  {"code": "008", "name": "Baguio City"},
  {"code": "009", "name": "La Trinidad, Benguet"},
  {"code": "010", "name": "Bontoc, Mt. Province"},
  {"code": "011", "name": "Tabuk City, Kalinga-Apayao"},
  {"code": "012", "name": "Santiago City, Isabela"},
  {"code": "013", "name": "Tuguegarao, Cagayan"},
  {"code": "014", "name": "Bayombong, Nueva Vizcaya"},
  {"code": "015", "name": "Naguilian, Isabela"},
  {"code": "016", "name": "Cabarroguis, Quirino"},
  {"code": "017A", "name": "Tarlac City, Tarlac"},
  {"code": "017B", "name": "Paniqui, Tarlac"},
  {"code": "018", "name": "Olongapo City"},
  {"code": "019", "name": "Subic Bay Freeport Zone"},
  {"code": "020", "name": "Balanga, Bataan"},
  {"code": "021A", "name": "North Pampanga"},
  {"code": "021B", "name": "South Pampanga"},
  {"code": "021C", "name": "Clark Freeport Zone"},
  {"code": "022", "name": "Baler, Aurora"},
  {"code": "023A", "name": "North Nueva Ecija"},
  {"code": "023B", "name": "South Nueva Ecija"},
  {"code": "024", "name": "Valenzuela City"},
  {"code": "025A", "name": "Plaridel, Bulacan (West)"},
  {"code": "025B", "name": "Sta. Maria, Bulacan (East)"},
  {"code": "026", "name": "Malabon - Navotas"},
  {"code": "027", "name": "Caloocan City"},
  {"code": "028", "name": "Novaliches"},
  {"code": "029", "name": "Tondo - San Nicolas"},
  {"code": "030", "name": "Binondo"},
  {"code": "031", "name": "Sta. Cruz"},
  {"code": "032", "name": "Quiapo - Sampaloc - San Miguel - Sta. Mesa"},
  {"code": "033", "name": "Intramuros - Ermita - Malate"},
  {"code": "034", "name": "Paco - Pandacan - Sta. Ana - San Andres"},
  {"code": "035", "name": "Odiongan, Romblon"},
  {"code": "036", "name": "Puerto Princesa City, Palawan"},
  {"code": "037", "name": "San Jose, Occidental Mindoro"},
  {"code": "038", "name": "North Quezon City"},
  {"code": "039", "name": "South Quezon City"},
  {"code": "040", "name": "Cubao"},
  {"code": "041", "name": "Mandaluyong City"},
  {"code": "042", "name": "San Juan City"},
  {"code": "043A", "name": "Pasig City"},
  {"code": "044", "name": "Taguig - Pateros"},
  {"code": "045", "name": "Marikina City"},
  {"code": "046", "name": "Cainta - Taytay"},
  {"code": "047", "name": "East Makati"},
  {"code": "048", "name": "West Makati"},
  {"code": "049", "name": "North Makati"},
  {"code": "050", "name": "South Makati"},
  {"code": "051", "name": "Pasay City"},
  {"code": "052", "name": "Parañaque City"},
  {"code": "053A", "name": "Las Piñas City"},
  {"code": "053B", "name": "Muntinlupa City"},
  {"code": "054A", "name": "Trece Martires City, East Cavite"},
  {"code": "054B", "name": "Kawit, West Cavite"},
  {"code": "055", "name": "San Pablo City"},
  {"code": "056", "name": "Calamba, Laguna"},
  {"code": "057", "name": "Biñan, Laguna"},
  {"code": "058", "name": "Batangas City"},
  {"code": "059", "name": "Lipa City"},
  {"code": "060", "name": "Lucena City"},
  {"code": "061", "name": "Gumaca, Quezon"},
  {"code": "062", "name": "Boac, Marinduque"},
  {"code": "063", "name": "Calapan, Oriental Mindoro"},
  {"code": "064", "name": "Talisay, Camarines Norte"},
  {"code": "065", "name": "Naga City"},
  {"code": "066", "name": "Iriga City"},
  {"code": "067", "name": "Legazpi City, Albay"},
  {"code": "068", "name": "Sorsogon, Sorsogon"},
  {"code": "069", "name": "Virac, Catanduanes"},
  {"code": "070", "name": "Masbate, Masbate"},
  {"code": "071", "name": "Kalibo, Aklan"},
  {"code": "072", "name": "Roxas City"},
  {"code": "073", "name": "San Jose, Antique"},
  {"code": "074", "name": "Iloilo City"},
  {"code": "075", "name": "Zarraga, Iloilo"},
  {"code": "076", "name": "Victorias City, Negros Occidental"},
  {"code": "077", "name": "Bacolod City"},
  {"code": "078", "name": "Binalbagan, Negros Occidental"},
  {"code": "079", "name": "Dumaguete City"},
  {"code": "080", "name": "Mandaue City"},
  {"code": "081", "name": "Cebu City North"},
  {"code": "082", "name": "Cebu City South"},
  {"code": "083", "name": "Talisay City, Cebu"},
  {"code": "084", "name": "Tagbilaran City"},
  {"code": "085", "name": "Catarman, Northern Samar"},
  {"code": "086", "name": "Borongan, Eastern Samar"},
  {"code": "087", "name": "Calbayog City, Samar"},
  {"code": "088", "name": "Tacloban City"},
  {"code": "089", "name": "Ormoc City"},
  {"code": "090", "name": "Maasin, Southern Leyte"},
  {"code": "091", "name": "Dipolog City"},
  {"code": "092", "name": "Pagadian City"},
  {"code": "093A", "name": "Zamboanga City"},
  {"code": "093B", "name": "Ipil, Zamboanga Sibugay"},
  {"code": "094", "name": "Isabela, Basilan"},
  {"code": "095", "name": "Jolo, Sulu"},
  {"code": "096", "name": "Bongao, Tawi-Tawi"},
  {"code": "097", "name": "Gingoog City"},
  {"code": "098", "name": "Cagayan de Oro City"},
  {"code": "099", "name": "Malaybalay City, Bukidnon"},
  {"code": "100", "name": "Ozamis City"},
  {"code": "101", "name": "Iligan City"},
  {"code": "102", "name": "Marawi City"},
  {"code": "103", "name": "Butuan City"},
  {"code": "104", "name": "Bayugan City, Agusan del Sur"},
  {"code": "105", "name": "Surigao City"},
  {"code": "106", "name": "Tandag, Surigao del Sur"},
  {"code": "107", "name": "Cotabato City"},
  {"code": "108", "name": "Kidapawan City"},
  {"code": "109", "name": "Tacurong, Sultan Kudarat"},
  {"code": "110", "name": "General Santos City"},
  {"code": "111", "name": "Koronadal City"},
  {"code": "112", "name": "Tagum City, Davao del Norte"},
  {"code": "113A", "name": "West Davao City"},
  {"code": "113B", "name": "East Davao City"},
  {"code": "114", "name": "Mati, Davao Oriental"},
  {"code": "115", "name": "Digos, Davao del Sur"}
]$j$, 'bir', 'Revenue District Offices offered for the RDO code of a company (code and name)', 'json')
ON CONFLICT (key) DO NOTHING;

UPDATE master_types t SET fields = (
    SELECT jsonb_agg(CASE WHEN f->>'name' = 'responsiblePerson' THEN f || '{"optionsFrom":"user"}'::jsonb ELSE f END ORDER BY ord)
    FROM jsonb_array_elements(t.fields) WITH ORDINALITY AS x(f, ord)),
  updated_at = now()
WHERE t.code = 'cost-centre' AND t.fields @> '[{"name":"responsiblePerson"}]' AND NOT t.fields @> '[{"name":"responsiblePerson","optionsFrom":"user"}]';
