import { BASE_URL } from "../utility/constant";
import authService from "./authService";
import { apiErrorMessage } from "./mastersService";

/**
 * Upload templates and spreadsheet imports: download a template workbook generated by the API (the same column list
 * the importer reads) and upload a filled CSV / XLSX file with optional form fields (e.g. goLiveDate).
 */
const fileNameOf = (response, fallback) => {
  const match = /filename="?([^";]+)"?/i.exec(response.headers.get("Content-Disposition") || "");
  return match ? match[1] : fallback;
};

const importService = {
  /** Downloads the template at `path` (e.g. /masters/city/template) to the user's computer. */
  async downloadTemplate(path, fallbackName = "Upload_Template.xlsx") {
    const response = await fetch(`${BASE_URL}${path}`, { headers: { ...authService.getAuthHeader() } });
    if (!response.ok) {
      const json = await response.json().catch(() => ({}));
      throw new Error(apiErrorMessage(json, response.status));
    }
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileNameOf(response, fallbackName);
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  },

  /** Uploads `file` (multipart field "file") with extra form fields; returns the result data of the API. A refusal throws an error with the API's message (`summary`) and row errors (`errors`). */
  async upload(path, file, fields = {}) {
    const form = new FormData();
    Object.entries(fields).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== "") form.append(key, value);
    });
    form.append("file", file);
    const response = await fetch(`${BASE_URL}${path}`, { method: "POST", headers: { ...authService.getAuthHeader() }, body: form });
    const json = await response.json().catch(() => ({}));
    if (!response.ok || json.success === false) {
      const error = new Error(apiErrorMessage(json, response.status));
      error.status = response.status;
      error.errors = json.errors || [];
      error.summary = json.message || null;
      throw error;
    }
    return { message: json.message, ...(json.data || {}) };
  },
};

export default importService;
