// vehicleType: Insurance Commission vehicle class codes (motor tariff), "Any" or "Any except Motorcycles/Tricycles/Trailers".
export const PRIORITY_RULES = [
  {
    priority: 1,
    policyType: "MCY",
    vehicleType: ["motorcycles_tricycles"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "CTPL",
  },
  {
    priority: 2,
    policyType: "CV",
    vehicleType: ["taxi_puj_and_mini_bus"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 3,
    policyType: "CV",
    vehicleType: ["pub_and_tourist_bus"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 4,
    policyType: "CV",
    vehicleType: ["heavy_trucks"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 5,
    policyType: "CV",
    vehicleType: ["light_medium_trucks"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 6,
    policyType: "PC",
    vehicleType: ["private_cars"],
    brand: ["BMW"],
    modelVariant: ["X5"],
    seating: "Any",
    ageCondition: "≤7",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 7,
    policyType: "PC",
    vehicleType: ["ac_and_tourist_cars"],
    brand: ["BMW"],
    modelVariant: ["X5"],
    seating: "Any",
    ageCondition: "≤7",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 8,
    policyType: "PC",
    vehicleType: ["private_cars"],
    brand: ["Toyota", "Ford", "Honda"],
    modelVariant: ["Camry", "Fusion", "Accord"],
    seating: "Any",
    ageCondition: "≤3",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 9,
    policyType: "PC",
    vehicleType: ["ac_and_tourist_cars"],
    brand: ["Toyota", "Ford", "Honda"],
    modelVariant: ["Camry", "Fusion", "Accord"],
    seating: "Any",
    ageCondition: "≤3",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 10,
    policyType: "PC",
    vehicleType: ["private_cars"],
    brand: ["Toyota", "Ford", "Honda"],
    modelVariant: ["Camry", "Fusion", "Accord"],
    seating: "Any",
    ageCondition: "4-7",
    location: "Any",
    recommendedPlan: "Basic",
  },
  {
    priority: 11,
    policyType: "PC",
    vehicleType: ["ac_and_tourist_cars"],
    brand: ["Toyota", "Ford", "Honda"],
    modelVariant: ["Camry", "Fusion", "Accord"],
    seating: "Any",
    ageCondition: "4-7",
    location: "Any",
    recommendedPlan: "Basic",
  },
  {
    priority: 12,
    policyType: "PC",
    vehicleType: ["private_cars"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "≥8",
    location: "Any",
    recommendedPlan: "CTPL",
  },
  {
    priority: 13,
    policyType: "PC",
    vehicleType: ["ac_and_tourist_cars"],
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "≥8",
    location: "Any",
    recommendedPlan: "CTPL",
  },
  {
    priority: 14,
    policyType: ["PC", "CV"],
    vehicleType: "Any except Motorcycles/Tricycles/Trailers",
    brand: "Any",
    modelVariant: "Any",
    seating: "≥10",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 15,
    policyType: ["PC", "CV"],
    vehicleType: "Any except Motorcycles/Tricycles/Trailers",
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "≤7",
    location: "High-risk area",
    recommendedPlan: "Comprehensive",
  },
  {
    priority: 16,
    policyType: "Any",
    vehicleType: "Any",
    brand: "Any",
    modelVariant: "Any",
    seating: "Any",
    ageCondition: "Any",
    location: "Any",
    recommendedPlan: "Basic",
  },
];

// Illustrative plan tiers shown on the product recommendation step (not rated premiums).
export const PLAN_TIERS = [
  {
    id: "1",
    company: "Selected Carrier",
    name: "CTPL",
    description:
      "Compulsory Third Party Liability - Basic protection required by law",
    monthlyPremium: 1500,
    deductible: 5000,
    features: [
      "Third-party liability coverage",
      "Bodily injury protection",
      "Property damage coverage",
      "Legal compliance",
    ],
    highlight: "RECOMMENDED",
    reason:
      "Based on your vehicle profile and driving history, CTPL provides essential legal protection while keeping costs minimal. Perfect for low-risk drivers seeking basic coverage.",
  },
  {
    id: "2",
    company: "Selected Carrier",
    name: "Basic",
    description: "Enhanced protection with additional coverage options",
    monthlyPremium: 3500,
    deductible: 10000,
    features: [
      "All CTPL benefits",
      "Own damage coverage",
      "Theft protection",
      "Fire and lightning coverage",
    ],
    highlight: null,
    reason:
      "Ideal balance between coverage and affordability. Includes essential protections for common risks while maintaining reasonable premiums.",
  },
  {
    id: "3",
    company: "Selected Carrier",
    name: "Comprehensive",
    description: "Complete protection with maximum coverage",
    monthlyPremium: 6500,
    deductible: 15000,
    features: [
      "All Basic benefits",
      "Full comprehensive coverage",
      "Acts of nature protection",
      "Personal accident benefits",
      "24/7 roadside assistance",
    ],
    highlight: null,
    reason:
      "Maximum protection for peace of mind. Comprehensive coverage protects against all major risks including natural disasters and provides additional benefits for you and your passengers.",
  },
  {
    id: "4",
    company: "Alternative Insurer A",
    name: "CTPL",
    description: "Competitive basic coverage option",
    monthlyPremium: 1450,
    deductible: 5000,
    features: [
      "Third-party liability coverage",
      "Bodily injury protection",
      "Property damage coverage",
    ],
    highlight: "BEST VALUE",
    reason:
      "Slightly lower premium with similar coverage. Good alternative if price is the primary concern.",
  },
  {
    id: "5",
    company: "Alternative Insurer B",
    name: "Basic",
    description: "Enhanced coverage from trusted provider",
    monthlyPremium: 3400,
    deductible: 10000,
    features: ["All CTPL benefits", "Own damage coverage", "Theft protection"],
    highlight: null,
    reason:
      "Competitive pricing with reliable coverage. Established provider with strong claims processing.",
  },
  {
    id: "6",
    company: "Alternative Insurer C",
    name: "Comprehensive",
    description: "Premium protection package",
    monthlyPremium: 6800,
    deductible: 15000,
    features: [
      "All Basic benefits",
      "Full comprehensive coverage",
      "Acts of nature protection",
      "Personal accident benefits",
    ],
    highlight: null,
    reason:
      "Premium option with extensive coverage. Higher premium but includes additional benefits and faster claims processing.",
  },
];
