// Thailand User Master Mock Data - Synchronized with Employee Master

const Productdata = [
  {
    id: 1,
    userName: "admin",
    employeeCode: "ADMIN-001",
    employeeName: "System Administrator",
    assignedRole: "System Administrator",
    roleCode: "ROLE-ADMIN",
    email: "admin@company.ph",
    phoneNumber: "+63 917 000 0001",
    branch: "Head Office",
    department: "IT",
    modifiedBy: "System",
    modifiedOn: "03/28/2025",
    status: "Active",
    lastLogin: "03/28/2025 08:45 AM"
  },
  {
    id: 2,
    userName: "miguel.torres",
    employeeCode: "EMP-2025-007",
    employeeName: "Miguel Torres",
    assignedRole: "Director",
    roleCode: "ROLE-DIR",
    email: "miguel.torres@company.ph",
    phoneNumber: "+63 923 789 0123",
    branch: "Head Office",
    department: "Executive",
    modifiedBy: "Admin",
    modifiedOn: "03/27/2025",
    status: "Active",
    lastLogin: "03/28/2025 07:30 AM"
  },
  {
    id: 3,
    userName: "roberto.reyes",
    employeeCode: "EMP-2025-003",
    employeeName: "Roberto Reyes",
    assignedRole: "Branch Manager",
    roleCode: "ROLE-MGR",
    email: "roberto.reyes@company.ph",
    phoneNumber: "+63 919 345 6789",
    branch: "Makati",
    department: "Management",
    modifiedBy: "Admin",
    modifiedOn: "03/26/2025",
    status: "Active",
    lastLogin: "03/28/2025 08:00 AM"
  },
  {
    id: 4,
    userName: "juan.delacruz",
    employeeCode: "EMP-2025-001",
    employeeName: "Juan Dela Cruz",
    assignedRole: "Insurance Agent",
    roleCode: "ROLE-AGENT",
    email: "juan.delacruz@company.ph",
    phoneNumber: "+63 917 123 4567",
    branch: "Makati",
    department: "Sales",
    modifiedBy: "Roberto Reyes",
    modifiedOn: "03/25/2025",
    status: "Active",
    lastLogin: "03/28/2025 09:15 AM"
  },
  {
    id: 5,
    userName: "maria.santos",
    employeeCode: "EMP-2025-002",
    employeeName: "Maria Santos",
    assignedRole: "Insurance Agent",
    roleCode: "ROLE-AGENT",
    email: "maria.santos@company.ph",
    phoneNumber: "+63 918 234 5678",
    branch: "Quezon City",
    department: "Sales",
    modifiedBy: "Roberto Reyes",
    modifiedOn: "03/24/2025",
    status: "Active",
    lastLogin: "03/28/2025 09:00 AM"
  },
  {
    id: 6,
    userName: "pedro.gonzales",
    employeeCode: "EMP-2025-005",
    employeeName: "Pedro Gonzales",
    assignedRole: "Underwriter",
    roleCode: "ROLE-UW",
    email: "pedro.gonzales@company.ph",
    phoneNumber: "+63 921 567 8901",
    branch: "Makati",
    department: "Underwriting",
    modifiedBy: "Carmen Bautista",
    modifiedOn: "03/23/2025",
    status: "Active",
    lastLogin: "03/28/2025 08:30 AM"
  },
  {
    id: 7,
    userName: "rosa.fernandez",
    employeeCode: "EMP-2025-006",
    employeeName: "Rosa Fernandez",
    assignedRole: "Claims Officer",
    roleCode: "ROLE-CLM",
    email: "rosa.fernandez@company.ph",
    phoneNumber: "+63 922 678 9012",
    branch: "Davao",
    department: "Claims",
    modifiedBy: "Pedro Gonzales",
    modifiedOn: "03/22/2025",
    status: "Active",
    lastLogin: "03/27/2025 04:45 PM"
  },
  {
    id: 8,
    userName: "carmen.bautista",
    employeeCode: "EMP-2025-008",
    employeeName: "Carmen Bautista",
    assignedRole: "Supervisor",
    roleCode: "ROLE-SUP",
    email: "carmen.bautista@company.ph",
    phoneNumber: "+63 924 890 1234",
    branch: "Makati",
    department: "Operations",
    modifiedBy: "Miguel Torres",
    modifiedOn: "03/21/2025",
    status: "Active",
    lastLogin: "03/28/2025 08:15 AM"
  },
  {
    id: 9,
    userName: "elena.martinez",
    employeeCode: "EMP-2025-010",
    employeeName: "Elena Martinez",
    assignedRole: "Finance Officer",
    roleCode: "ROLE-FIN",
    email: "elena.martinez@company.ph",
    phoneNumber: "+63 926 012 3456",
    branch: "Makati",
    department: "Finance",
    modifiedBy: "Carmen Bautista",
    modifiedOn: "03/20/2025",
    status: "Active",
    lastLogin: "03/28/2025 08:45 AM"
  },
  {
    id: 10,
    userName: "ana.garcia",
    employeeCode: "EMP-2025-004",
    employeeName: "Ana Garcia",
    assignedRole: "Insurance Agent",
    roleCode: "ROLE-AGENT",
    email: "ana.garcia@company.ph",
    phoneNumber: "+63 920 456 7890",
    branch: "Cebu",
    department: "Sales",
    modifiedBy: "Maria Santos",
    modifiedOn: "03/19/2025",
    status: "Active",
    lastLogin: "03/28/2025 09:30 AM"
  },
  {
    id: 11,
    userName: "client.demo",
    employeeCode: "CLIENT-001",
    employeeName: "Demo Client User",
    assignedRole: "Client User",
    roleCode: "ROLE-CLIENT",
    email: "client.demo@gmail.com",
    phoneNumber: "+63 917 555 0001",
    branch: "N/A",
    department: "External",
    modifiedBy: "Admin",
    modifiedOn: "03/28/2025",
    status: "Active",
    lastLogin: "03/28/2025 10:00 AM",
    clientId: "CL-2025-001",
    policyNumbers: ["MIC-2025-MOT-00123", "AXA-2025-HLT-00567"]
  },
  {
    id: 12,
    userName: "auditor.view",
    employeeCode: "AUD-001",
    employeeName: "Insurance Commission Auditor",
    assignedRole: "Read-Only User",
    roleCode: "ROLE-VIEWER",
    email: "auditor@insurance.gov.ph",
    phoneNumber: "+63 2 8123 4567",
    branch: "External",
    department: "Compliance",
    modifiedBy: "Admin",
    modifiedOn: "03/28/2025",
    status: "Active",
    lastLogin: "03/27/2025 02:30 PM",
    accessExpiry: "06/30/2025"
  }
];

export default Productdata;