"""Render the architecture diagrams in docs/architecture/diagrams to PNG (for the documents) and SVG (for the web).

    python3 docs/architecture/tools/render_diagrams.py

Sources in docs/architecture/diagrams:
  *.dot   Graphviz (component, deployment, topology diagrams); needs the `dot` binary (apt-get install graphviz)
  *.seq   sequence diagrams in a small text format, drawn by this script with Pillow (see parse_seq)
  er_*.dot ER diagrams, generated first from tools/data/db_snapshot.json (one per domain group), then rendered
"""
import html
import json
import os
import re
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
DIAGRAMS = os.path.join(os.path.dirname(HERE), 'diagrams')
SNAPSHOT = os.path.join(HERE, 'data', 'db_snapshot.json')
sys.path.insert(0, HERE)
from table_catalog import TABLES  # noqa: E402

BLUE, CYAN, DARK, LIGHT, GREY, LINE = '#0065B3', '#00ACF1', '#1F2937', '#EAF6FD', '#5B6776', '#9FB3C8'
FONT_REG = [os.path.expanduser('~/.fonts/Nunito-400-normal.ttf'), '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf']
FONT_BOLD = [os.path.expanduser('~/.fonts/Nunito-700-normal.ttf'), '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf']

# ------------------------------------------------------------------ ER diagrams from the database snapshot
ER_GROUPS = {
    'er_sales_policy': ('Sales and policy', ['leads', 'clients', 'quotes', 'policies', 'endorsements', 'policy_payments']),
    'er_renewals': ('Renewals', ['renewals', 'renewal_quotes', 'renewal_notices', 'renewal_activities', 'renewal_batches', 'renewal_batch_policies', 'winback_campaigns']),
    'er_finance_ledger': ('Billing, receipts and ledger', ['receivables', 'receipts', 'receipt_lines', 'receipt_applications', 'collection_items', 'collection_actions',
                                                  'gl_accounts', 'journal_vouchers', 'journal_lines', 'entry_matches']),
    'er_disbursement_pettycash': ('Disbursements and petty cash', ['disbursements', 'invoice_lists', 'checkbooks', 'petty_cash_funds', 'petty_cash_requests',
                                                                   'petty_cash_request_lines', 'petty_cash_disbursements', 'petty_cash_receipts', 'petty_cash_replenishments']),
    'er_claims': ('Claims', ['claims', 'claim_history', 'claim_field_changes', 'reinsurance_recoveries']),
    'er_remittance_directbill': ('Remittance and direct bill', ['remittances', 'remittance_lines', 'remittance_items', 'remittance_approvals', 'remittance_delegations',
                                                                'commission_debit_notes', 'commission_debit_note_lines', 'commission_debit_note_collections', 'direct_bill_items']),
    'er_reinsurance': ('Reinsurance', ['reinsurers', 'reinsurance_treaties', 'cessions', 'reinsurance_recoveries', 'reinsurance_bordereaux',
                                       'reinsurance_reconciliations', 'reinsurance_exceptions']),
    'er_commission_incentive': ('Commission and incentive', ['commissions', 'commission_referrers', 'incentive_programs', 'incentive_calculations', 'incentive_results']),
    'er_config_security': ('Security and identity', ['users', 'roles', 'permissions', 'role_permissions', 'user_roles', 'refresh_tokens', 'password_resets',
                                                     'password_history', 'login_history', 'audit_log', 'notifications', 'agent_events']),
    'er_platform': ('Configuration and platform services', ['app_settings', 'email_outbox', 'scheduled_jobs', 'job_runs', 'job_queue', 'documents', 'sequences',
                                                           'schema_migrations', 'master_types', 'master_records', 'report_definitions', 'report_schedules', 'generated_reports']),
    'er_masters': ('Reference masters', ['countries', 'states', 'cities', 'districts', 'postal_codes', 'currencies', 'banks', 'insurance_companies', 'products',
                                         'policy_types', 'vehicle_brands', 'vehicle_models', 'vehicle_variants', 'coverages', 'signatories', 'branches']),
    'er_product': ('Product configurator', ['product_templates', 'product_components', 'product_risk_mappings', 'product_risk_sections']),
}
# FKs to users are shown only in the security diagram (almost every table has one); elsewhere they are listed as columns.
USER_REF_HIDDEN = True
ER_RANKDIR = {}
ER_PACK = {'er_masters': 6}


def er_dot(name, title, tables, snap):
    t = snap['tables']
    lines = [f'// Generated by tools/render_diagrams.py from tools/data/db_snapshot.json: {title}. Do not edit by hand.',
             'digraph ER {', f'  graph [rankdir={ER_RANKDIR.get(name, "TB")}, splines=true, nodesep=0.25, ranksep=0.5, fontname="Nunito", bgcolor="white", pad=0.2, pack=true, packmode="array_u{ER_PACK.get(name, 3)}"];',
             '  node [shape=plain, fontname="Nunito", fontsize=10];', f'  edge [color="{LINE}", arrowhead=crow, arrowtail=none, dir=both, arrowsize=0.7, penwidth=1.1];']
    external = set()
    edges = {}
    for tb in tables:
        info = t[tb]
        fk_cols = {f['column']: f for f in info['fks']}
        rows = []
        for c in info['pk']:
            rows.append(f'<tr><td align="left" balign="left"><b>PK</b></td><td align="left">{c}</td></tr>')
        for u in info['unique'][:2]:
            rows.append(f'<tr><td align="left"><font color="{GREY}">UK</font></td><td align="left">{html.escape(u.replace(",", ", "))}</td></tr>')
        shown = 0
        for c, f in fk_cols.items():
            if c in info['pk']:
                continue
            if shown >= 9:
                rows.append(f'<tr><td></td><td align="left"><font color="{GREY}">+{len(fk_cols) - shown} more FKs</font></td></tr>')
                break
            ref = f['refTable']
            mark = '' if f['indexed'] else '<font color="#C0392B">*</font>'
            drawn = ref != tb and not (USER_REF_HIDDEN and ref == 'users' and name != 'er_config_security')
            target = '' if drawn else f' <font color="{GREY}" point-size="8">&#8594; {ref}</font>'
            rows.append(f'<tr><td align="left"><font color="{BLUE}">FK</font></td><td align="left">{c}{mark}{target}</td></tr>')
            shown += 1
            if ref == tb:
                continue
            if USER_REF_HIDDEN and ref == 'users' and name != 'er_config_security':
                continue
            if ref not in tables:
                external.add(ref)
            edges.setdefault((ref, tb), []).append(c)
        if info['jsonb']:
            rows.append(f'<tr><td align="left"><font color="{GREY}">{{ }}</font></td><td align="left"><font color="{GREY}">{html.escape(", ".join(info["jsonb"][:4]))}</font></td></tr>')
        label = (f'<<table border="1" cellborder="0" cellspacing="0" cellpadding="3" color="{BLUE}">'
                 f'<tr><td colspan="2" bgcolor="{BLUE}"><font color="white"><b>{tb}</b></font></td></tr>{"".join(rows)}</table>>')
        lines.append(f'  "{tb}" [label={label}];')
    for ext in sorted(external):
        lines.append(f'  "{ext}" [shape=box, style="rounded,dashed", color="{GREY}", fontcolor="{GREY}", label="{ext}"];')
    for (a, b), cols in sorted(edges.items()):
        lines.append(f'  "{a}" -> "{b}";')
    lines.append('}')
    with open(os.path.join(DIAGRAMS, f'{name}.dot'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def generate_er():
    if not os.path.exists(SNAPSHOT):
        print('no db_snapshot.json: ER diagrams not regenerated')
        return
    snap = json.load(open(SNAPSHOT, encoding='utf-8'))
    for name, (title, tables) in ER_GROUPS.items():
        er_dot(name, title, tables, snap)


# ------------------------------------------------------------------ sequence diagrams
def font(bold=False, size=13):
    for p in (FONT_BOLD if bold else FONT_REG):
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def parse_seq(text):
    """Format:
        title: <text>
        participant <id> "<label>"          (in display order)
        <a> -> <b>: <message>               solid arrow (request / action)
        <a> --> <b>: <message>              dashed arrow (response / asynchronous)
        <a> -> <a>: <message>               self call
        note: <text>                        note across the whole diagram
        == <text> ==                        section divider
    """
    parts, steps, title = [], [], ''
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('title:'):
            title = line[6:].strip()
        elif line.startswith('participant '):
            m = re.match(r'participant\s+(\S+)\s+"(.*)"', line)
            parts.append((m.group(1), m.group(2)))
        elif line.startswith('note:'):
            steps.append(('note', line[5:].strip()))
        elif line.startswith('=='):
            steps.append(('section', line.strip('= ').strip()))
        else:
            m = re.match(r'(\S+)\s*(-->|->)\s*(\S+)\s*:\s*(.*)', line)
            if not m:
                raise ValueError(f'bad sequence line: {line}')
            steps.append(('msg', m.group(1), m.group(2), m.group(3), m.group(4)))
    return title, parts, steps


class Canvas:
    """Draws the same primitives into a Pillow image (PNG, scaled) and an SVG document."""

    def __init__(self, w, h, scale=2):
        self.w, self.h, self.s = w, h, scale
        self.img = Image.new('RGB', (int(w * scale), int(h * scale)), 'white')
        self.d = ImageDraw.Draw(self.img)
        self.svg = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" font-family="Nunito, DejaVu Sans, Arial, sans-serif">',
                    '<rect width="100%" height="100%" fill="white"/>',
                    f'<defs><marker id="ah" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto"><path d="M0,0 L10,4 L0,8 z" fill="{DARK}"/></marker></defs>']

    def rect(self, x, y, w, h, fill, outline=None, radius=6, dash=False):
        s = self.s
        self.d.rounded_rectangle([x * s, y * s, (x + w) * s, (y + h) * s], radius=radius * s, fill=fill, outline=outline, width=int(1 * s))
        dash_attr = ' stroke-dasharray="4 3"' if dash else ''
        self.svg.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}" stroke="{outline or "none"}"{dash_attr}/>')

    def line(self, x1, y1, x2, y2, color=DARK, dash=False, width=1.2, arrow=False):
        s = self.s
        if dash:
            length = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5 or 1
            n = int(length // 7)
            for i in range(n):
                if i % 2 == 0:
                    a, b = i / n, min(1, (i + 1) / n)
                    self.d.line([(x1 + (x2 - x1) * a) * s, (y1 + (y2 - y1) * a) * s, (x1 + (x2 - x1) * b) * s, (y1 + (y2 - y1) * b) * s], fill=color, width=int(width * s))
        else:
            self.d.line([x1 * s, y1 * s, x2 * s, y2 * s], fill=color, width=int(width * s))
        if arrow:
            direction = 1 if x2 >= x1 else -1
            self.d.polygon([(x2 * s, y2 * s), ((x2 - 9 * direction) * s, (y2 - 4) * s), ((x2 - 9 * direction) * s, (y2 + 4) * s)], fill=color)
        attrs = ' stroke-dasharray="5 4"' if dash else ''
        mk = ' marker-end="url(#ah)"' if arrow else ''
        self.svg.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"{attrs}{mk}/>')

    def text(self, x, y, s_text, size=12, bold=False, color=DARK, anchor='middle'):
        f = font(bold, int(size * self.s))
        tw = self.d.textlength(s_text, font=f) / self.s
        tx = x - tw / 2 if anchor == 'middle' else x
        self.d.text((tx * self.s, (y - size * 0.8) * self.s), s_text, font=f, fill=color)
        weight = ' font-weight="bold"' if bold else ''
        self.svg.append(f'<text x="{x}" y="{y}" font-size="{size}" text-anchor="{"middle" if anchor == "middle" else "start"}" fill="{color}"{weight}>{html.escape(s_text)}</text>')

    def measure(self, s_text, size=12, bold=False):
        return self.d.textlength(s_text, font=font(bold, int(size * self.s))) / self.s

    def save(self, base):
        self.img.save(base + '.png', dpi=(200, 200))
        with open(base + '.svg', 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.svg + ['</svg>']) + '\n')


def wrap(c, text, width, size):
    words, lines, cur = text.split(), [], ''
    for w in words:
        trial = f'{cur} {w}'.strip()
        if c.measure(trial, size) <= width or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def render_seq(path):
    title, parts, steps = parse_seq(open(path, encoding='utf-8').read())
    col, margin, top = 150, 30, 70
    width = margin * 2 + col * len(parts)
    xs = {pid: margin + col * i + col / 2 for i, (pid, _) in enumerate(parts)}
    probe = Canvas(10, 10)
    # layout pass: height of every step
    heights = []
    for st in steps:
        if st[0] == 'msg':
            _, a, _, b, msg = st
            span = max(abs(xs[b] - xs[a]) - 16, col - 30) if a != b else col - 20
            n = len(wrap(probe, msg, span, 11))
            heights.append(20 + 14 * n + (14 if a == b else 0))
        elif st[0] == 'note':
            heights.append(18 + 15 * len(wrap(probe, st[1], width - 2 * margin - 30, 11)))
        else:
            heights.append(34)
    height = top + 40 + sum(heights) + 50
    c = Canvas(width, height)
    c.text(margin, 26, title, size=16, bold=True, color=BLUE, anchor='start')
    for pid, label in parts:
        x = xs[pid]
        lines = wrap(c, label, col - 24, 11.5)
        bh = 12 + 15 * len(lines)
        for yy in (top - 10, height - 40 - bh + 20):
            c.rect(x - col / 2 + 8, yy, col - 16, bh, fill=LIGHT, outline=BLUE)
            for i, ln in enumerate(lines):
                c.text(x, yy + 19 + 15 * i, ln, size=11.5, bold=True, color=BLUE)
        c.line(x, top - 10 + bh, x, height - 40 - bh + 20, color=LINE, dash=True, width=1)
    y = top + 30 + 12
    for st, h in zip(steps, heights):
        if st[0] == 'msg':
            _, a, kind, b, msg = st
            dashed = kind == '-->'
            if a == b:
                x = xs[a]
                lines = wrap(c, msg, col - 20, 11)
                for i, ln in enumerate(lines):
                    c.text(x + 8, y + 4 + 14 * i, ln, size=11, anchor='start')
                yl = y + 10 + 14 * (len(lines) - 1)
                c.line(x, yl, x + 26, yl, width=1.1)
                c.line(x + 26, yl, x + 26, yl + 12, width=1.1)
                c.line(x + 26, yl + 12, x + 2, yl + 12, width=1.1, arrow=True)
            else:
                x1, x2 = xs[a], xs[b]
                span = max(abs(x2 - x1) - 16, col - 30)
                lines = wrap(c, msg, span, 11)
                mid = (x1 + x2) / 2
                for i, ln in enumerate(lines):
                    c.text(mid, y + 4 + 14 * i, ln, size=11, color=GREY if dashed else DARK)
                yl = y + 13 + 14 * (len(lines) - 1)
                c.line(x1, yl, x2 + (-2 if x2 > x1 else 2), yl, dash=dashed, width=1.2, arrow=True, color=GREY if dashed else DARK)
        elif st[0] == 'note':
            lines = wrap(c, st[1], width - 2 * margin - 30, 11)
            c.rect(margin + 5, y - 6, width - 2 * margin - 10, h - 6, fill='#FFF8E1', outline='#E0B23A', radius=4)
            for i, ln in enumerate(lines):
                c.text(margin + 18, y + 10 + 15 * i, ln, size=11, anchor='start')
        else:
            c.line(margin, y + 8, width - margin, y + 8, color=CYAN, width=1)
            tw = c.measure(st[1], 11.5, True) + 20
            c.rect(width / 2 - tw / 2, y - 3, tw, 22, fill='white', outline=CYAN, radius=10)
            c.text(width / 2, y + 12, st[1], size=11.5, bold=True, color=BLUE)
        y += h
    c.save(os.path.splitext(path)[0])


# ------------------------------------------------------------------ main
def render_dot(path):
    base = os.path.splitext(path)[0]
    subprocess.run(['dot', '-Tpng', '-Gdpi=200', path, '-o', base + '.png'], check=True)
    subprocess.run(['dot', '-Tsvg', path, '-o', base + '.svg'], check=True)


def main():
    generate_er()
    names = sorted(os.listdir(DIAGRAMS))
    for n in names:
        p = os.path.join(DIAGRAMS, n)
        if n.endswith('.dot'):
            render_dot(p)
        elif n.endswith('.seq'):
            render_seq(p)
    print(f'rendered {sum(1 for n in names if n.endswith((".dot", ".seq")))} diagrams in {DIAGRAMS}')


if __name__ == '__main__':
    main()
