"""Hand-maintained catalogue of the BrokerVerse tables: domain, owning backend module, one-line purpose and retention
class. The database facts (columns, keys, rows, sizes) come from data/db_snapshot.json; this file adds the meaning.

Retention classes (document 10 gives the recommended periods):
  FIN  financial record: ledger, billing, receipts, payments, commissions, remittances; keep for the statutory period
  TXN  business transaction record: leads, quotations, policies, endorsements, claims, renewals, reinsurance
  REF  reference data / configuration: masters, settings, product templates, roles
  LOG  log and audit trail: audit log, sign-in history, field-change history, job run history
  TMP  temporary / operational: tokens, reset codes, outbox, queues, generated files, counters
"""

DOMAINS = [
    ('security', 'Security and identity'),
    ('platform', 'Platform services'),
    ('reference', 'Reference masters'),
    ('product', 'Product configurator'),
    ('sales', 'Sales and policy'),
    ('placement', 'Placement and co-insurance'),
    ('claims', 'Claims'),
    ('renewals', 'Renewals'),
    ('billing', 'Billing, receipts and collections'),
    ('ledger', 'General ledger and posting rules'),
    ('periodend', 'Period end and tax'),
    ('bankrec', 'Bank reconciliation'),
    ('disbursement', 'Disbursements and petty cash'),
    ('commission', 'Commission'),
    ('remittance', 'Remittance and direct bill'),
    ('reinsurance', 'Reinsurance'),
    ('incentive', 'Incentive'),
    ('reporting', 'Reporting'),
    ('distribution', 'Distribution and marketing'),
    ('specialty', 'Fleet, marine and motor claims'),
    ('payables', 'Payables and fixed assets'),
    ('bir', 'BIR returns and invoicing'),
    ('compliance', 'Compliance: AML, Insurance Commission and data privacy'),
    ('integration', 'Integrations'),
    ('golive', 'Go-live data load and work management'),
]

RETENTION = {
    'FIN': 'Financial',
    'TXN': 'Transaction',
    'REF': 'Reference',
    'LOG': 'Log / audit',
    'TMP': 'Temporary',
}

# table: (domain, owning module(s), purpose, retention class)
TABLES = {
    # Security and identity
    'roles': ('security', 'users', 'Role catalogue: system-admin, sales, processing, operations, claims, accounting, accounting-manager (inherits accounting) and custom roles', 'REF'),
    'permissions': ('security', 'users', 'Permission codes read:<module>, write:<module> (27 modules) and approve:<area> (period end, bank reconciliation)', 'REF'),
    'role_permissions': ('security', 'users', 'Grant of permissions to roles', 'REF'),
    'users': ('security', 'users, auth', 'User accounts: bcrypt password hash, status, lockout counter, 2FA (encrypted TOTP secret), token version', 'REF'),
    'user_roles': ('security', 'users', 'Assignment of roles to users', 'REF'),
    'refresh_tokens': ('security', 'auth', 'Refresh-token register (jti, family, expiry, rotation / revocation reason)', 'TMP'),
    'password_resets': ('security', 'auth', 'One-time password reset codes (HMAC hash only), expiry and attempts', 'TMP'),
    'password_history': ('security', 'auth', 'Previous password hashes for the history rule (last N kept)', 'LOG'),
    'login_history': ('security', 'auth', 'Every sign-in attempt: user, IP, user agent, success, reason, method', 'LOG'),
    # Platform services
    'document_numbering': ('platform', 'document-numbering', 'Document number series: prefix, pattern, width, reset rule, start number', 'REF'),
    'app_settings': ('platform', 'settings, system-settings', 'Configuration keys (JSONB value, group, label, type); every business parameter', 'REF'),
    'audit_log': ('platform', 'all (lib/audit.js)', 'Who did what to which record, with before / after JSON and IP', 'LOG'),
    'notifications': ('platform', 'notifications', 'In-app notifications per user or per permission audience', 'TMP'),
    'email_outbox': ('platform', 'lib/mailer.js', 'Queued e-mails (to, subject, HTML body, status, attempts, error)', 'TMP'),
    'scheduled_jobs': ('platform', 'schedules, jobs', 'Cron jobs (code, cron, handler, params, enabled, last status)', 'REF'),
    'job_runs': ('platform', 'jobs', 'Run history of scheduled and manual job runs (status, output, error)', 'LOG'),
    'job_queue': ('platform', 'renewals', 'Background work queue (renewal notice batches); status, progress, attempts', 'TMP'),
    'documents': ('platform', 'uploads and file writers', 'Registry of stored files: storage key, name, type, size, owning entity, uploader', 'TXN'),
    'sequences': ('platform', 'document-numbering', 'Document-number counters per series and reset period (year, fiscal year, month or ALL)', 'REF'),
    'schema_migrations': ('platform', 'db/migrate.js', 'Applied migration files', 'REF'),
    'master_types': ('platform', 'masters', 'Master screen registry: fields, storage table, keys of each configurable master', 'REF'),
    'master_records': ('platform', 'masters', 'Generic master records (JSONB data) for masters without their own table', 'REF'),
    'agent_events': ('platform', 'payments (open items)', 'Calendar events and reminders of a user (open items screen)', 'TXN'),
    # Reference masters
    'countries': ('reference', 'masters', 'Countries', 'REF'),
    'regions': ('reference', 'masters', 'Philippine regions (PSGC code), above Province (migration 0250)', 'REF'),
    'states': ('reference', 'masters', 'Provinces (PSGC code, region); the table keeps its earlier name "states"', 'REF'),
    'cities': ('reference', 'masters', 'Cities and municipalities (PSGC code, city class, ZIP code, region)', 'REF'),
    'districts': ('reference', 'addresses', 'Barangays (PSGC code) with postal code; master type Barangay', 'REF'),
    'postal_codes': ('reference', 'addresses', 'Postal code lookup (province, city, district)', 'REF'),
    'currencies': ('reference', 'masters', 'Currencies (base flag, decimals, exchange rate)', 'REF'),
    'banks': ('reference', 'masters', 'Banks and mortgagees', 'REF'),
    'insurance_companies': ('reference', 'masters', 'Insurers (principals): contact, default commission rate, credit terms, billing mode', 'REF'),
    'products': ('reference', 'masters', 'Insurance products / lines', 'REF'),
    'policy_types': ('reference', 'masters', 'Policy types per product', 'REF'),
    'vehicle_brands': ('reference', 'quotations', 'Vehicle makes', 'REF'),
    'vehicle_models': ('reference', 'quotations', 'Vehicle models per make', 'REF'),
    'vehicle_variants': ('reference', 'quotations', 'Vehicle variants (body type, seating)', 'REF'),
    'coverages': ('reference', 'quotations', 'BI / PD / PA cover options with amount and premium', 'REF'),
    'signatories': ('reference', 'masters', 'Authorised signatories for documents', 'REF'),
    'branches': ('reference', 'masters', 'Broker branches', 'REF'),
    # Product configurator
    'product_templates': ('product', 'product-configurator', 'Versioned product templates (config JSONB, rates, limits, insurers)', 'REF'),
    'product_components': ('product', 'product-configurator', 'Template components: covers, rating tables, rules, documents (JSONB data)', 'REF'),
    'product_risk_mappings': ('product', 'product-configurator', 'Product / line-of-business risk definitions', 'REF'),
    'product_risk_sections': ('product', 'product-configurator', 'Risk sections of a mapping with default rates', 'REF'),
    # Sales and policy
    'leads': ('sales', 'leads', 'Leads / prospects (individual or corporate), owner, status', 'TXN'),
    'clients': ('sales', 'clients', 'Clients (insured parties) with KYC fields and owner', 'TXN'),
    'quotes': ('sales', 'quotations', 'Quotations: vehicle / coverage JSONB, premium, taxes, commission, approval token hash', 'TXN'),
    'policies': ('sales', 'policies', 'Issued policies: term, premium, insurer, billing mode, details / doc JSONB', 'TXN'),
    'endorsements': ('sales', 'endorsements', 'Policy endorsements and cancellations, premium delta, billing link', 'TXN'),
    'policy_payments': ('sales', 'policies', 'Premium payments captured on a policy, awaiting finance confirmation', 'FIN'),
    # Placement and co-insurance
    'broker_slips': ('placement', 'placement', 'Broker slips (BS-): a client risk sent to several insurers for terms', 'TXN'),
    'insurer_offers': ('placement', 'placement', 'Insurer offers (OFR-) on a broker slip: premium, rate, taxes, deductibles, validity, share, or a decline', 'TXN'),
    'placements': ('placement', 'placement', 'Placement slips (PS-): firm order to the chosen insurers, binding per participant, policy issue', 'TXN'),
    'risk_participants': ('placement', 'placement, policies', 'Co-insurance participants of a broker slip, quotation, placement or policy: lead, share, premium and commission', 'TXN'),
    # Claims
    'claims': ('claims', 'claims', 'Claims: loss details, estimate, approved and settled amounts, handler, lifecycle status', 'TXN'),
    'claim_history': ('claims', 'claims', 'Claim status history', 'LOG'),
    'claim_field_changes': ('claims', 'claims', 'Field-level audit trail of claim edits', 'LOG'),
    'claim_settlement_movements': ('claims', 'claims', 'Claim settlement cash: funds received from each insurer and payments to the claimant, with journal', 'FIN'),
    # Renewals
    'renewals': ('renewals', 'renewals', 'Renewal cases of expiring policies (status, notices, contact, premium old / new)', 'TXN'),
    'renewal_quotes': ('renewals', 'renewals', 'Renewal quotations (loading, discount, variance)', 'TXN'),
    'renewal_notices': ('renewals', 'renewals', 'Renewal notices sent (stage, method, recipient, status)', 'LOG'),
    'renewal_activities': ('renewals', 'renewals', 'Contact and follow-up activities on a renewal', 'LOG'),
    'renewal_batches': ('renewals', 'renewals', 'Batch renewal notice runs', 'TXN'),
    'renewal_batch_policies': ('renewals', 'renewals', 'Policies in a renewal batch and their notice status', 'TXN'),
    'winback_campaigns': ('renewals', 'renewals', 'Win-back campaigns for lapsed business', 'TXN'),
    # Billing, receipts and collections
    'receivables': ('billing', 'receipts', 'Premium bills (INV-) per policy / endorsement / renewal with balance and ageing', 'FIN'),
    'receipts': ('billing', 'receipts', 'Official receipts (OR-) header: payer, amount, mode, status', 'FIN'),
    'receipt_lines': ('billing', 'receipts', 'Receipt lines per policy (premium, taxes, EWT, discounts)', 'FIN'),
    'receipt_applications': ('billing', 'receipts', 'Application of receipt lines to bills, with journal link', 'FIN'),
    'collection_items': ('billing', 'collections', 'Collection follow-up items for open bills (commitment, escalation, assignee)', 'TXN'),
    'collection_actions': ('billing', 'collections', 'Collection actions: calls, e-mails, commitments', 'LOG'),
    'receivable_credits': ('billing', 'receipts', 'Return premium and cancellation credits applied to a bill, with the refund part and journal', 'FIN'),
    'receivable_participants': ('billing', 'receipts', 'Per-insurer split of a co-insured bill: share, gross, commission, taxes, due to insurer', 'FIN'),
    'write_off_reasons': ('billing', 'masters, accounting', 'Write-off reasons with GL account and maximum amount', 'REF'),
    # General ledger
    'gl_accounts': ('ledger', 'accounting', 'Chart of accounts (type, statement group, normal balance, open-item flag)', 'REF'),
    'accounting_periods': ('ledger', 'accounting, period-end', 'Periods 1 to 12 and adjustment period 13 per fiscal year: dates and status (open, soft_closed, closed, locked)', 'FIN'),
    'journal_vouchers': ('ledger', 'journal-vouchers, accounting', 'Journal vouchers (JV-): source, status, maker-checker, reversal / correction links', 'FIN'),
    'journal_lines': ('ledger', 'journal-vouchers, accounting', 'Journal lines: account, debit / credit, branch, department, client / policy tags', 'FIN'),
    'entry_matches': ('ledger', 'accounting', 'Open-item matching of debit and credit journal lines', 'FIN'),
    'posting_rules': ('ledger', 'posting-rules', 'Posting rule versions per business event (effective date, entry type, narration)', 'REF'),
    'posting_rule_lines': ('ledger', 'posting-rules', 'Lines of a posting rule: side, account or account role, amount key, split per co-insurer', 'REF'),
    # Period end and tax
    'fiscal_years': ('periodend', 'period-end', 'Fiscal years (FY2026): dates and status', 'FIN'),
    'period_status_history': ('periodend', 'period-end', 'Every change of an accounting period status, with source and user', 'LOG'),
    'period_close_checklist': ('periodend', 'period-end', 'Month-end checklist items (automatic or manual, severity)', 'REF'),
    'period_close_runs': ('periodend', 'period-end', 'Month-end close runs (MEC-): steps, preparer, approval', 'FIN'),
    'period_close_run_checks': ('periodend', 'period-end', 'Checklist results of a close run and sign-off of manual items', 'LOG'),
    'period_close_entries': ('periodend', 'period-end', 'Journals created by a close run and their automatic reversal', 'FIN'),
    'recurring_journals': ('periodend', 'period-end', 'Recurring and accrual journal templates (frequency, lines, auto-post, auto-reverse)', 'REF'),
    'recurring_journal_runs': ('periodend', 'period-end', 'Journals generated from a recurring template per occurrence', 'FIN'),
    'year_end_runs': ('periodend', 'period-end', 'Year-end close runs (YEC-): closing and transfer journals, net income, reversal', 'FIN'),
    'opening_balances': ('periodend', 'period-end', 'Opening balances per fiscal year and account: carried forward by the year-end close or loaded at go-live', 'FIN'),
    'tax_codes': ('periodend', 'period-end', 'Tax codes: VAT, expanded withholding with ATC, DST, LGT; rate and GL account', 'REF'),
    'bir_2307_certificates': ('periodend', 'period-end', 'BIR Form 2307 certificates issued and received, per payee and quarter', 'FIN'),
    # Bank reconciliation
    'bank_statement_formats': ('bankrec', 'bank-reconciliation', 'Bank statement file layouts (columns, date format, sign convention)', 'REF'),
    'bank_transaction_types': ('bankrec', 'bank-reconciliation', 'Bank-side transaction types (charges, interest, direct credits) and their GL account role', 'REF'),
    'bank_match_rules': ('bankrec', 'bank-reconciliation', 'Automatic matching rules (reference, amount-date, one-to-many, many-to-one)', 'REF'),
    'bank_statements': ('bankrec', 'bank-reconciliation', 'Imported or keyed bank statements per bank account and period, with file hash', 'FIN'),
    'bank_statement_lines': ('bankrec', 'bank-reconciliation', 'Statement lines (amount, reference, line hash), status and adjustment journal', 'FIN'),
    'bank_rec_matches': ('bankrec', 'bank-reconciliation', 'Matches between bank lines and cash-account journal lines, with difference treatment', 'FIN'),
    'bank_rec_match_items': ('bankrec', 'bank-reconciliation', 'Bank and book lines of a match', 'FIN'),
    'bank_reconciliations': ('bankrec', 'bank-reconciliation', 'Monthly bank reconciliation statements (BRC-): figures, preparer, approver', 'FIN'),
    'bank_reconciliation_history': ('bankrec', 'bank-reconciliation', 'Status history of a reconciliation', 'LOG'),
    # Disbursements and petty cash
    'disbursements': ('disbursement', 'disbursements', 'Payment vouchers (PV-) to insurers, agents, clients; approval and payment', 'FIN'),
    'invoice_lists': ('disbursement', 'disbursements', 'Invoice lists (IL-) settled by a disbursement', 'FIN'),
    'checkbooks': ('disbursement', 'disbursements', 'Cheques issued (instrument, approval, printing)', 'FIN'),
    'petty_cash_funds': ('disbursement', 'payments', 'Petty cash funds (size, limits, custodian, available cash)', 'FIN'),
    'petty_cash_requests': ('disbursement', 'payments', 'Petty cash requests and approval', 'FIN'),
    'petty_cash_request_lines': ('disbursement', 'payments', 'Lines of a petty cash request', 'FIN'),
    'petty_cash_disbursements': ('disbursement', 'payments', 'Petty cash payments (VAT, WHT, journal)', 'FIN'),
    'petty_cash_receipts': ('disbursement', 'payments', 'Receipts into a petty cash fund', 'FIN'),
    'petty_cash_replenishments': ('disbursement', 'payments', 'Fund replenishments from bank', 'FIN'),
    # Commission
    'commissions': ('commission', 'commission, policies', 'Commission lines per policy / endorsement and referrer: accrual, eligibility, approval, payment', 'FIN'),
    'commission_referrers': ('commission', 'commission', 'Referrers / sub-agents (no sign-in): hierarchy, WHT rate, bank account', 'REF'),
    'commission_adjustments': ('commission', 'commission', 'Commission reversed or clawed back when premium is returned or a policy cancelled', 'FIN'),
    'commission_rates': ('commission', 'commission-rates', 'Commission rate matrix: rate per insurer, product, line and policy type with effective dates', 'REF'),
    # Remittance and direct bill
    'remittances': ('remittance', 'remittance', 'Premium remittances / bills to insurers (REM-): gross, commission, net due, approval, settlement', 'FIN'),
    'remittance_lines': ('remittance', 'remittance', 'Policies included in a remittance', 'FIN'),
    'remittance_items': ('remittance', 'remittance', 'Remittance work items (settlements, adjustments, transfers, exceptions)', 'FIN'),
    'remittance_approvals': ('remittance', 'remittance', 'Multi-level approval requests with SLA and history', 'LOG'),
    'remittance_delegations': ('remittance', 'remittance', 'Approval delegations (period, transaction types, amount limit)', 'REF'),
    'commission_debit_notes': ('remittance', 'remittance (direct bill)', 'Commission debit notes (DN-) to insurers for direct-billed policies', 'FIN'),
    'commission_debit_note_lines': ('remittance', 'remittance (direct bill)', 'Policies / items on a debit note', 'FIN'),
    'commission_debit_note_collections': ('remittance', 'remittance (direct bill)', 'Insurer payments against a debit note (cash, EWT, Form 2307)', 'FIN'),
    'direct_bill_items': ('remittance', 'remittance (direct bill)', 'Commission receivable items booked for direct-billed policies', 'FIN'),
    'remittance_allocations': ('remittance', 'receipts, remittance', 'Premium collected on a co-insured policy, split for remittance to each insurer', 'FIN'),
    'insurer_refund_credits': ('remittance', 'remittance', 'Refunds due from insurers on returned premium already remitted; netted against the next remittance', 'FIN'),
    # Reinsurance
    'reinsurers': ('reinsurance', 'reinsurance', 'Reinsurers (rating, capacity, contact)', 'REF'),
    'reinsurance_treaties': ('reinsurance', 'reinsurance', 'Treaties (type, capacity, share, retention, approval)', 'TXN'),
    'cessions': ('reinsurance', 'reinsurance', 'Cessions of policies to treaties / facultative reinsurers', 'TXN'),
    'reinsurance_recoveries': ('reinsurance', 'reinsurance', 'Claim recoveries from reinsurers', 'FIN'),
    'reinsurance_bordereaux': ('reinsurance', 'reinsurance', 'Premium / claims bordereaux (entries JSONB, file)', 'TXN'),
    'reinsurance_reconciliations': ('reinsurance', 'reinsurance', 'Reinsurer statement reconciliations', 'FIN'),
    'reinsurance_exceptions': ('reinsurance', 'reinsurance', 'Reconciliation exceptions and resolution', 'LOG'),
    # Incentive
    'incentive_programs': ('incentive', 'incentive', 'Incentive programmes (metric, targets, tiers, eligibility)', 'REF'),
    'incentive_calculations': ('incentive', 'incentive', 'Incentive calculation batches with maker-checker and payment', 'FIN'),
    'incentive_results': ('incentive', 'incentive', 'Incentive results and payouts per participant', 'FIN'),
    # Reporting
    'report_definitions': ('reporting', 'reports', 'Report catalogue (parameters, query, columns, roles, permission)', 'REF'),
    'report_schedules': ('reporting', 'reports', 'E-mailed report schedules (cron, format, recipients)', 'REF'),
    'generated_reports': ('reporting', 'reports', 'Generated report files (code, parameters, format, storage key, rows)', 'TMP'),
    # Distribution and marketing (migrations 0300 to 0308, 0320)
    'lead_assignment_rules': ('distribution', 'leads', 'Lead assignment rules: who receives a new prospect by branch, line, source, channel and territory', 'REF'),
    'lead_assignment_history': ('distribution', 'leads', 'Every assignment and reassignment of a prospect (automatic, manual, bulk, queue) with the reason', 'LOG'),
    'distribution_channels': ('distribution', 'channels', 'Dealer groups and branches, financing banks and affinity partners in one hierarchy', 'REF'),
    'channel_billing_accounts': ('distribution', 'channels', 'Client account a channel is billed through when it pays a premium for its customers', 'REF'),
    'motor_programmes': ('distribution', 'motor-programmes', 'Brand-new vehicle dealer programmes: insurer, own damage rate, CTPL term, free or subsidised first year', 'REF'),
    'dealer_sales_batches': ('distribution', 'motor-programmes', 'Uploaded dealer sales batches of a programme, validated and converted into business', 'TXN'),
    'dealer_sales': ('distribution', 'motor-programmes', 'One vehicle sold by a dealer under a programme, with the buyer and the resulting policy', 'TXN'),
    'comparison_reports': ('distribution', 'comparison-reports', 'Client comparison and recommendation reports between insurer options', 'TXN'),
    'campaigns': ('distribution', 'campaigns', 'Marketing campaigns to consenting clients and prospects: segment, template, schedule, status', 'TXN'),
    'campaign_segments': ('distribution', 'campaigns', 'Who a campaign is for: clients, prospects or both, narrowed by line, place, channel and type', 'REF'),
    'campaign_templates': ('distribution', 'campaigns', 'E-mail templates of campaigns with merge fields and the opt-out link', 'REF'),
    'campaign_recipients': ('distribution', 'campaigns', 'Recipients of a campaign run: consent checked, sent, failed or opted out', 'LOG'),
    'report_builder_reports': ('reporting', 'report-builder', 'Ad hoc reports designed by users over curated datasets: columns, filters, grouping, sharing', 'REF'),
    'bi_extract_runs': ('reporting', 'report-builder', 'Runs of the scheduled BI extract (one CSV file per dataset) with status and files', 'LOG'),
    'sales_activities': ('distribution', 'sales-activities', 'Calls, meetings, e-mails and visits logged on a prospect, quotation or client, with the next step (package G)', 'TXN'),
    # Fleet, marine open cover, facultative and motor claims (migrations 0294, 0295, 0303 to 0305)
    'fleet_schedules': ('specialty', 'fleet', 'Fleet of a client under one motor policy with one insurer and one period', 'TXN'),
    'fleet_vehicles': ('specialty', 'fleet', 'Vehicles of a fleet schedule with their premium, additions and deletions', 'TXN'),
    'open_covers': ('specialty', 'marine', 'Marine cargo open cover contracts: period, goods, voyages, limit and rate per conveyance', 'TXN'),
    'open_cover_certificates': ('specialty', 'marine', 'Marine insurance certificates issued against an open cover, one per shipment', 'TXN'),
    'open_cover_declarations': ('specialty', 'marine', 'Monthly declarations of the shipments of an open cover, billed as a premium', 'TXN'),
    'fac_placements': ('reinsurance', 'reinsurance', 'Facultative reinsurance slips offered by a cedant, placed by the broker as reinsurance broker', 'TXN'),
    'fac_placement_shares': ('reinsurance', 'reinsurance', 'Reinsurers approached on a facultative slip and their written and signed lines', 'TXN'),
    'fac_settlements': ('reinsurance', 'reinsurance', 'Facultative premium received from the cedant and paid to each reinsurer, with journals', 'FIN'),
    'claim_repair_estimates': ('specialty', 'motor-claims', 'Motor repair estimates of an accredited repair shop and their approval, with supplementary estimates', 'TXN'),
    'claim_loas': ('specialty', 'motor-claims', 'Letters of authority to the repair shop issued from an approved estimate', 'TXN'),
    'claim_vehicle_releases': ('specialty', 'motor-claims', 'Release of the repaired vehicle to the insured', 'TXN'),
    'claim_document_items': ('claims', 'claim-documents', 'Documents a claim needs, copied from the checklist master, with received and waived status', 'TXN'),
    'claim_document_reminders': ('claims', 'claim-documents', 'Missing-document reminders sent to the claimant', 'LOG'),
    # Operations and accounting (migrations 0290 to 0298, 0321)
    'cover_notes': ('sales', 'cover-notes', 'Cover notes (binders) issued while the insurer policy is pending: cover period, status, superseding policy', 'TXN'),
    'post_dated_cheques': ('billing', 'pdc', 'Post-dated cheques received against bills, kept until their date, deposited into an official receipt or returned', 'FIN'),
    'supplier_invoices': ('payables', 'payables', 'Supplier invoices with input VAT and expanded withholding tax, approved by maker-checker', 'FIN'),
    'supplier_invoice_lines': ('payables', 'payables', 'Expense lines of a supplier invoice (account, amount, VAT, EWT)', 'FIN'),
    'supplier_payments': ('payables', 'payables', 'Payments to suppliers, posted through rule ap.payment', 'FIN'),
    'supplier_payment_allocations': ('payables', 'payables', 'Allocation of a supplier payment to the invoices it settles', 'FIN'),
    'fixed_assets': ('payables', 'fixed-assets', 'Fixed asset register: class, cost, useful life, straight-line schedule, status', 'FIN'),
    'fixed_asset_depreciation': ('payables', 'fixed-assets', 'Monthly depreciation of each asset and the journal that posted it', 'FIN'),
    'fixed_asset_disposals': ('payables', 'fixed-assets', 'Sale or write-off of an asset with the gain or loss posted (package G)', 'FIN'),
    # BIR returns, invoicing and override commission (migrations 0280 to 0284)
    'bir_return_filings': ('bir', 'bir', 'Filing record of each BIR return period (0619-E, 1601-EQ, 1604-E, 2551Q): status, reference, payment', 'FIN'),
    'sales_invoices': ('bir', 'bir', 'Sales invoices under the Ease of Paying Taxes Act for commission, fees and override commission', 'FIN'),
    'sales_invoice_lines': ('bir', 'bir', 'Lines of a sales invoice (description, amount, VAT)', 'FIN'),
    'sales_invoice_payments': ('bir', 'bir', 'Payments received against a sales invoice', 'FIN'),
    'cas_book_prints': ('bir', 'bir', 'Loose-leaf books of accounts printed per period for the CAS registration pack, with page numbers', 'LOG'),
    'eis_submissions': ('bir', 'bir', 'E-invoice submissions to the BIR Electronic Invoicing System: payload, status, attempts, reply', 'TMP'),
    'override_agreements': ('commission', 'insurer-overrides', 'Overriding, profit and contingent commission agreements with insurers: basis, period, lines', 'REF'),
    'override_agreement_tiers': ('commission', 'insurer-overrides', 'Tiers of an override agreement: from and to value of the basis and the rate', 'REF'),
    'override_computations': ('commission', 'insurer-overrides', 'Override commission computed for a period, accrued through rule override_commission.accrual', 'FIN'),
    'override_settlements': ('commission', 'insurer-overrides', 'Settlement of an override computation by the insurer, with its sales invoice and journal', 'FIN'),
    # Compliance: AML/CFT (migrations 0260 to 0263)
    'client_signatories': ('compliance', 'aml', 'Authorised signatories of a juridical client with the board resolution or certificate', 'TXN'),
    'client_beneficial_owners': ('compliance', 'aml', 'Natural persons who own or control a juridical client (beneficial owners)', 'TXN'),
    'client_kyc_documents': ('compliance', 'aml', 'Customer due diligence documents: IDs, registration certificates, board resolutions, EDD evidence', 'TXN'),
    'aml_risk_factors': ('compliance', 'aml', 'Scoring table of the customer risk rating (factor, value, score)', 'REF'),
    'aml_risk_assessments': ('compliance', 'aml', 'Every customer risk rating made, with the factors that scored and the resulting risk', 'LOG'),
    'aml_edd_reviews': ('compliance', 'aml', 'Enhanced due diligence of a high-risk client: source of wealth and funds, findings, approval', 'TXN'),
    'aml_screening_lists': ('compliance', 'aml', 'Lists screened against (UN Security Council, AMLC designations, PEP and internal lists)', 'REF'),
    'aml_list_versions': ('compliance', 'aml', 'Loaded versions of a screening list', 'REF'),
    'aml_list_entries': ('compliance', 'aml', 'Names and identifiers of a screening list version', 'REF'),
    'aml_screenings': ('compliance', 'aml', 'Every screening run of a party (event, provider, result)', 'LOG'),
    'aml_screening_hits': ('compliance', 'aml', 'Potential matches of a screening and their disposition (true match, false positive)', 'TXN'),
    'aml_provider_requests': ('compliance', 'aml', 'Outbox of requests to a commercial screening provider (status, attempts)', 'TMP'),
    'aml_rules': ('compliance', 'aml', 'Covered and suspicious transaction monitoring rules with their parameters', 'REF'),
    'aml_alerts': ('compliance', 'aml', 'Alerts raised by a monitoring rule on a transaction, reviewed by the compliance officer', 'TXN'),
    'aml_cases': ('compliance', 'aml', 'Compliance officer case files: CTR to file, STR investigation or review', 'TXN'),
    'aml_reports': ('compliance', 'aml', 'CTR and STR files generated in the AMLC reporting layout', 'TXN'),
    'aml_report_items': ('compliance', 'aml', 'Transactions included in an AMLC report file', 'TXN'),
    # Compliance: Insurance Commission and data privacy (package B, migrations 0270 to 0277)
    'compliance_licences': ('compliance', 'ic-compliance', 'Licences issued by the IC or another authority to the firm, its officers and individuals, with expiry', 'REF'),
    'compliance_licence_reminders': ('compliance', 'ic-compliance', 'Licence expiry reminders sent', 'LOG'),
    'compliance_fit_proper': ('compliance', 'ic-compliance', 'Fit and proper declarations and checks of officers and staff', 'TXN'),
    'ic_statement_lines': ('compliance', 'ic-compliance', 'Lines of the IC annual statement schedules mapped to GL accounts', 'REF'),
    'complaints': ('compliance', 'ic-compliance', 'Complaints register under RA 11765: complainant, product, deadlines, resolution', 'TXN'),
    'complaint_reminders': ('compliance', 'ic-compliance', 'Acknowledgement and resolution deadline reminders of complaints', 'LOG'),
    'personal_data_breaches': ('compliance', 'data-breaches', 'Personal data breach and security incident register with the NPC 72-hour notification', 'TXN'),
    'personal_data_breach_reminders': ('compliance', 'data-breaches', 'Notification deadline reminders of breaches', 'LOG'),
    # Integrations (migrations 0310 to 0314)
    'integration_connectors': ('integration', 'integrations', 'Configured connections to third parties: adapter, mode test or live, endpoint, credential variable names', 'REF'),
    'integration_outbox': ('integration', 'integrations', 'Every message to send through a connector: status, attempts, next attempt, last error', 'TMP'),
    'integration_attempts': ('integration', 'integrations', 'One row per send attempt (duration, result, error) for the monitor', 'LOG'),
    'integration_inbox': ('integration', 'integrations', 'Messages received from a third party (webhook) or read from an imported file', 'LOG'),
    'message_templates': ('integration', 'integrations (messaging)', 'SMS and Viber text templates per event', 'REF'),
    'coc_series': ('integration', 'integrations (CTPL)', 'CTPL certificate of cover number series received from an insurer', 'REF'),
    'ctpl_authentications': ('integration', 'integrations (CTPL)', 'CTPL cover authentications: COC number, vehicle identifiers, authentication result', 'TXN'),
    'insurer_api_mappings': ('integration', 'integrations (insurer)', 'Per insurer: API connector, broker code, product codes, request and response maps', 'REF'),
    'bank_file_layouts': ('integration', 'integrations (bank files)', 'Layout of a bank bulk credit, InstaPay or PESONet upload file', 'REF'),
    'payee_bank_accounts': ('integration', 'integrations (bank files)', 'Bank accounts of payees credited by bank payment files', 'REF'),
    'bank_payment_batches': ('integration', 'integrations (bank files)', 'Batches of payment vouchers paid through one bank account and layout', 'FIN'),
    'bank_payment_batch_lines': ('integration', 'integrations (bank files)', 'One line per voucher in a bank payment batch, with the status from the bank', 'FIN'),
    # Go-live data load, e-signatures and work management (migrations 0243 to 0254)
    'data_load_batches': ('golive', 'data-load', 'Go-live workbooks uploaded (configuration or migration kit): validation, errors, load and reconciliation', 'LOG'),
    'data_load_rows': ('golive', 'data-load', 'Rows of an uploaded go-live workbook with their validation result and loaded record', 'TMP'),
    'data_load_comparisons': ('golive', 'data-load', 'Environment comparison reports of configuration and masters between environments', 'LOG'),
    'work_tasks': ('golive', 'my-work', 'Tasks and follow-ups of the My Work diary: due date, priority, reminder, related record', 'TXN'),
    'e_signatures': ('platform', 'e-signatures', 'Signature images of signatories and approving or issuing users, with consent and capture details', 'REF'),
    'document_signature_slots': ('platform', 'e-signatures', 'Which signature prints in which slot of which document type, and when', 'REF'),
    # Added from the data dictionary metadata (migrations 0160 to 0241)
    'access_review_items': ('security', 'access-control', "One user in an access review: the roles held, last sign-in and the reviewer's decision to keep or revoke", 'LOG'),
    'access_reviews': ('security', 'access-control', 'Periodic access review (recertification) campaign: scope, reviewer, due date and closure', 'LOG'),
    'authority_limits': ('security', 'access-control', 'Authority matrix: approval limit per role or per user and transaction type, effective once approved by another administrator', 'REF'),
    'authority_transaction_types': ('security', 'access-control', 'Transactions that need an approver and are limited by amount or percent (authority matrix rows)', 'REF'),
    'sod_rules': ('security', 'access-control', 'Segregation-of-duties rules: pairs of roles one person should not hold together, with block or warn', 'REF'),
    'user_delegations': ('security', 'access-control', "Out-of-office delegation: the delegate may approve with the delegator's authority for the listed transaction types and dates", 'REF'),
    'accounting_config_changes': ('ledger', 'posting-rules', 'Pending, approved or rejected changes to posting rules and account determination (maker-checker); a change takes effect only on approval by a different user', 'LOG'),
    'bank_account_links': ('bankrec', 'bank-reconciliation', 'View: bank account masters with their GL cash account', 'REF'),
    'bank_book_lines': ('bankrec', 'bank-reconciliation', 'View: posted journal lines on bank cash accounts, the book side of bank matching', 'FIN'),
    'client_credit_exceptions': ('billing', 'credit-control', "Policies issued beyond a client's credit limit: exposure before and after, and Accounting's acknowledgement", 'LOG'),
    'premium_instalment_plans': ('billing', 'credit-control', 'Instalment plan of a premium bill: frequency, number of instalments, first due date and down payment', 'FIN'),
    'premium_instalments': ('billing', 'credit-control', 'Instalments of a plan: sequence, due date and amount', 'FIN'),
    'premium_warranty_actions': ('billing', 'credit-control', 'Premium warranty monitor actions: reminders, extension decisions and cancellation requests', 'LOG'),
    'premium_warranty_extensions': ('billing', 'credit-control', 'Requests to extend the premium payment warranty deadline of a policy (maker-checker)', 'TXN'),
    'data_subject_requests': ('compliance', 'privacy', 'Register of data subject requests (DSR-): type, requester, party, date received, due date, status, assignee, outcome and the exports and anonymisation done', 'LOG'),
    'privacy_consents': ('compliance', 'privacy', 'Consent given, refused or withdrawn by a client or prospect per purpose (processing, marketing, sharing), with channel, notice version and evidence; never deleted', 'LOG'),
    'direct_bill_client_payments': ('remittance', 'remittance (direct bill)', "Client's premium payment made directly to the insurer on a direct-billed policy, with the insurer's receipt reference and proof; no journal is posted", 'FIN'),
    'insurer_statement_formats': ('remittance', 'insurer-reconciliation', "Column mapping of an insurer's statement export (CSV or XLSX)", 'REF'),
    'insurer_statements': ('remittance', 'insurer-reconciliation', 'Imported insurer statement of account (ISR): premium remittance confirmation or commission statement, totals, sign-off', 'FIN'),
    'insurer_statement_lines': ('remittance', 'insurer-reconciliation', "Lines of an insurer statement with their match to the broker's remittance line, debit note line or policy and the differences", 'FIN'),
    'insurer_statement_resolutions': ('remittance', 'insurer-reconciliation', 'How a statement difference, or a broker record missing on the statement, was settled: note or adjustment journal', 'FIN'),
    'insurer_rate_tables': ('product', 'packages', 'Insurer rates per product for the quick quote comparison of packaged products: rate basis, minimum premium, deductible, commission', 'REF'),
    'package_bundles': ('product', 'packages', 'Packaged product bundles (for example a multi-line SME cover): segment, term, discount, online issue', 'REF'),
    'package_bundle_sections': ('product', 'packages', 'Sections of a bundle: product, default sum insured, rate, minimum premium and the insurers that may carry it', 'REF'),
    'lgu_tax_rates': ('product', 'premium-charges', 'Local government (LGT) tax rates per province or city with effective dates', 'REF'),
    'premium_charge_rules': ('product', 'premium-charges', 'Premium charge rules (VAT, premium tax, DST, FST, LGT, other): method, rate, unit size, minimum and effective dates', 'REF'),
    'package_quotes': ('sales', 'packages', 'Bundle quotations: client, location, premium, discount, taxes, commission and status', 'TXN'),
    'package_sections': ('sales', 'packages', 'Priced sections of a bundle quotation or package policy, each with its insurer, premium, taxes and commission', 'TXN'),
    'package_endorsements': ('sales', 'packages', 'Endorsements of one section of a package policy: change of sum insured and the additional premium billed', 'TXN'),
    'payment_gateways': ('sales', 'payment-gateway', 'Online payment gateways (Dragonpay, PayMongo, sandbox): mode, methods, fee handling, link validity; credentials stay in the environment', 'REF'),
    'payment_links': ('sales', 'payment-gateway', 'Payment links sent to a client to pay a package quotation, quotation or policy premium online, and the result', 'FIN'),
    'payment_events': ('sales', 'payment-gateway', 'Every notification received from a payment gateway (or simulated), valid or not: the payments log', 'LOG'),
    'quote_customer_responses': ('sales', 'quotations', 'Customer responses to a quotation recorded by staff (phone, Viber, meeting, signed form) as evidence of the status change', 'LOG'),
}
