-- Claims and renewals configuration (editable from System Settings). Idempotent.
INSERT INTO app_settings(key, value, "group", label, type) VALUES
 ('claims.block_unpaid_premium', 'true', 'claims', 'Block claim registration when the policy has unpaid premium', 'boolean'),
 ('claims.validate_loss_date', 'true', 'claims', 'Block claim registration when the loss date is outside the policy period', 'boolean'),
 ('claims.settlement_maker_checker', 'true', 'claims', 'Settlement needs approval by a second user', 'boolean'),
 ('claims.auto_settle_on_approval', 'true', 'claims', 'Mark the claim settled as soon as the settlement is approved', 'boolean'),
 ('claims.sla_days', '20', 'claims', 'Claim handling SLA (days from report to due date)', 'number'),
 ('claims.aging_thresholds', '[7, 15, 30]', 'claims', 'Claim ageing thresholds in days (recent / moderate / high / critical)', 'json'),
 ('claims.open_statuses', '["registered", "in-review", "pending-approval", "approved"]', 'claims', 'Statuses counted as open claims', 'json'),
 ('claims.status_labels', '{"registered": "Pending", "in-review": "Processing", "pending-approval": "Pending Approval", "approved": "Approved", "settled": "Settled", "closed": "Closed", "rejected": "Rejected"}', 'claims', 'Display label for each claim status', 'json'),
 ('claims.status_aliases', '{"pending": "registered", "processing": "in-review", "in progress": "in-review", "under investigation": "in-review", "documents required": "in-review", "pending approval": "pending-approval", "completed": "settled"}', 'claims', 'Other status names accepted from the front end', 'json'),
 ('claims.default_priority', '"Medium"', 'claims', 'Default claim priority', 'string'),
 ('claims.pla_enabled', 'true', 'claims', 'Send a Preliminary Loss Advice e-mail when a claim is registered', 'boolean'),
 ('claims.pla_default_recipient', '"claims@brokerverse.local"', 'claims', 'Preliminary Loss Advice recipient when the insurer has no claims e-mail', 'string'),
 ('claims.pla_subject', '"Preliminary Loss Advice - {{claimNumber}} / {{policyNumber}}"', 'claims', 'Preliminary Loss Advice subject', 'string'),
 ('claims.pla_template', '"<p>Dear {{insurerName}},</p><p>We advise a loss under policy <b>{{policyNumber}}</b> of {{insuredName}}.</p><p>Claim reference: {{claimNumber}}<br/>Date of loss: {{lossDate}} {{lossTime}}<br/>Place of loss: {{lossPlace}}<br/>Nature of loss: {{lossType}}<br/>Estimated amount: {{currency}} {{estimate}}</p><p>{{message}}</p><p>{{companyName}} Claims</p>"', 'claims', 'Preliminary Loss Advice body (HTML, placeholders in double braces)', 'string'),
 ('claims.documents', '{"Claims Acknowledgement Letter": ["We acknowledge receipt of your claim {{claimNumber}} under policy {{policyNumber}}.", "Insured: {{insuredName}}", "Date of loss: {{lossDate}}", "Reported on: {{reportedDate}}", "Our claims team will contact you within {{slaDays}} days."], "Claims Discharge Voucher": ["Claim {{claimNumber}} under policy {{policyNumber}}", "Insured: {{insuredName}}", "Settlement amount: {{currency}} {{settledAmount}}", "Settlement type: {{settlementType}}", "I accept the above amount in full and final settlement of this claim.", "Signature: ______________________   Date: ____________"], "Claims Data Sheet": ["Claim number: {{claimNumber}}", "Policy number: {{policyNumber}}", "Insured: {{insuredName}}", "Insurer: {{insurerName}}", "Line of business: {{lob}}", "Status: {{status}}", "Date of loss: {{lossDate}} {{lossTime}}", "Place of loss: {{lossPlace}}", "Nature of loss: {{lossType}}", "Estimated amount: {{currency}} {{estimate}}", "Approved amount: {{currency}} {{approvedAmount}}", "Settled amount: {{currency}} {{settledAmount}}"]}', 'claims', 'Printable claim documents (title: lines with placeholders)', 'json'),
 ('claims.upload_document_names', '{"claimDocument": "Claim Document", "file": "FIR", "settlementDocument": "Settlement Document"}', 'claims', 'Document name given to each uploaded claim file', 'json'),
 ('numbering.renewal.prefix', '"RN"', 'numbering', 'Renewal number prefix', 'string'),
 ('numbering.renewal_quote.prefix', '"RQ"', 'numbering', 'Renewal quote number prefix', 'string'),
 ('numbering.renewal_batch.prefix', '"RB"', 'numbering', 'Renewal batch number prefix', 'string'),
 ('numbering.campaign.prefix', '"WB"', 'numbering', 'Win-back campaign number prefix', 'string'),
 ('renewals.pipeline_days', '90', 'renewals', 'Policies expiring within this many days enter the renewal pipeline', 'number'),
 ('renewals.grace_period_days', '30', 'renewals', 'Grace period after expiry before an unrenewed policy lapses', 'number'),
 ('renewals.enforce_notice_order', 'true', 'renewals', 'Renewal notices must go out first, second, final in order', 'boolean'),
 ('renewals.notice_stages', '[{"stage": 1, "code": "first", "label": "First Notice"}, {"stage": 2, "code": "second", "label": "Second Notice"}, {"stage": 3, "code": "final", "label": "Final Notice"}]', 'renewals', 'Renewal notice stages', 'json'),
 ('renewals.notice_subject', '"{{noticeLabel}}: renewal of policy {{policyNumber}} (expires {{expiryDate}})"', 'renewals', 'Renewal notice e-mail subject', 'string'),
 ('renewals.notice_template', '"<p>Dear {{clientName}},</p><p>Your policy <b>{{policyNumber}}</b> with {{insurerName}} expires on {{expiryDate}}.</p><p>Renewal premium: {{currency}} {{premium}}.</p><p>Please contact us to renew and keep your cover in force.</p><p>{{companyName}}</p>"', 'renewals', 'Renewal notice e-mail body (HTML)', 'string'),
 ('renewals.maker_checker', 'true', 'renewals', 'Renewal quote needs approval by a second user before the policy is renewed', 'boolean'),
 ('renewals.rating_rates', '{"motor": 0.0275, "fire": 0.0022, "marine": 0.0045, "accident": 0.0035, "casualty": 0.004, "eb": 0.012, "default": 0.003}', 'renewals', 'Current base rates on sum insured by product line (used to re-rate renewals)', 'json'),
 ('renewals.claims_loading_rate', '0.1', 'renewals', 'Premium loading per claim in the expiring term', 'number'),
 ('renewals.claims_loading_cap', '0.3', 'renewals', 'Maximum claims loading', 'number'),
 ('renewals.loyalty_discount_rate', '0.02', 'renewals', 'Loyalty discount per completed renewal', 'number'),
 ('renewals.loyalty_discount_cap', '0.1', 'renewals', 'Maximum loyalty discount', 'number'),
 ('renewals.quote_validity_days', '30', 'renewals', 'Renewal quote validity (days)', 'number'),
 ('renewals.create_receivable', 'true', 'renewals', 'Create a premium receivable when a renewal is completed', 'boolean'),
 ('renewals.risk_weights', '{"claims": 25, "unpaid": 20, "firstRenewal": 15, "noContact": 10, "increase": 20, "dueSoon": 10}', 'renewals', 'Retention risk score weights', 'json'),
 ('renewals.risk_bands', '{"Low": 0, "Medium": 30, "High": 55, "Critical": 75}', 'renewals', 'Retention risk bands (minimum score)', 'json'),
 ('renewals.status_labels', '{"pipeline": "Pending", "notice-1": "First Notice Sent", "notice-2": "Second Notice Sent", "final-notice": "Final Notice Sent", "quoted": "Quote Sent", "pending-approval": "Pending Approval", "approved": "Approved", "renewed": "Renewed", "lapsed": "Lapsed"}', 'renewals', 'Display label for each renewal status', 'json'),
 ('renewals.batch_max_policies', '500', 'renewals', 'Maximum policies in one renewal batch', 'number'),
 ('renewals.approver_roles', '["processing"]', 'renewals', 'Roles notified to approve renewal terms', 'json'),
 ('renewals.reinstatement_days', '90', 'renewals', 'Days after lapse during which a renewal can be reinstated', 'number'),
 ('renewals.risk_actions', '{"Claims History": ["Review claims experience with the insurer", "Prepare a claims-adjusted quote"], "Unpaid Premium": ["Collect outstanding premium before renewal", "Offer an instalment plan"], "First Renewal": ["Call the client personally", "Highlight service record over the first year"], "No Contact": ["Send the first renewal notice now"], "Premium Increase": ["Seek alternative terms from other insurers", "Explain the rate change with a coverage comparison"], "Due Soon": ["Escalate to the account manager"]}', 'renewals', 'Recommended actions per retention risk factor', 'json')
ON CONFLICT (key) DO NOTHING;
