-- Product configurator sample data: templates, components, risk mappings. Idempotent.
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Motor Insurance Basic Plan$s$, (SELECT id FROM products WHERE code = $s$MOTOR$s$), 3, $j${"taxes":{"dst":12.5,"fst":0,"lgt":0.75,"vat":12},"ctplSetting":{"heavy_trucks":"957.88","private_cars":"447.01","ac_and_tourist_cars":"957.88","light_medium_trucks":"957.88","pub_and_tourist_bus":"1047.00","motorcycles_tricycles":"199.55","taxi_puj_and_mini_bus":"486.92"},"deductibles":[1000,3000,5000,10000],"premiumRates":{"heavy_trucks":"6","private_cars":"2","comprehensive":[{"to":500000,"from":0,"rate":2.5},{"to":1000000,"from":500000,"rate":2.25},{"to":null,"from":1000000,"rate":2}],"acts_of_nature":"0.5","ac_and_tourist_cars":"1.5","light_medium_trucks":"1.15","pub_and_tourist_bus":"5","roadside_assistance":"0.25","motorcycles_tricycles":"1","taxi_puj_and_mini_bus":"2.5","personal_accident_cover":"2"},"ratingFactor":{"over_60_years_old":"1.3","25_to_60_years_old":"1.0","under_25_years_old":"1.5","annual_depreciation_rate":"10","maximum_depreciation_years":"10"},"riskInformation":{"loading":{"type":"POLICY","description":"UW loading"},"discount":{"rate":"20","type":"POLICY","amount":"10","description":"No claim bonus","discountCode":"RI09"}}}$j$, $s$Active$s$, $s$MOT-003-2025$s$, $s$Motor$s$, $s$Motor Vehicle$s$, $s$Comprehensive motor insurance coverage for the Philippine market with competitive rates.$s$, $s$v3.2$s$, $s$2025-01-01$s$, $s$2026-12-31$s$, 2.5, 10000, 500000, 12, $j${"optional":["Acts of Nature","Personal Accident","Towing"],"mandatory":["CTPL","Own Damage"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp."]$j$, $j$["Philippines","Motor","Popular"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$MOT-003-2025$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$First Class Motor Insurance$s$, (SELECT id FROM products WHERE code = $s$MOTOR$s$), 1, $j${"taxes":{"dst":12.5,"fst":0,"lgt":0.75,"vat":12},"ctplSetting":{"heavy_trucks":"957.88","private_cars":"447.01","ac_and_tourist_cars":"957.88","light_medium_trucks":"957.88","pub_and_tourist_bus":"1047.00","motorcycles_tricycles":"199.55","taxi_puj_and_mini_bus":"486.92"},"deductibles":[1000,3000,5000,10000],"premiumRates":{"heavy_trucks":"6","private_cars":"2","comprehensive":[{"to":500000,"from":0,"rate":2.5},{"to":1000000,"from":500000,"rate":2.25},{"to":null,"from":1000000,"rate":2}],"acts_of_nature":"0.5","ac_and_tourist_cars":"1.5","light_medium_trucks":"1.15","pub_and_tourist_bus":"5","roadside_assistance":"0.25","motorcycles_tricycles":"1","taxi_puj_and_mini_bus":"2.5","personal_accident_cover":"2"},"ratingFactor":{"over_60_years_old":"1.3","25_to_60_years_old":"1.0","under_25_years_old":"1.5","annual_depreciation_rate":"10","maximum_depreciation_years":"10"},"riskInformation":{"loading":{"type":"COVER"},"discount":{"type":"COVER","description":"Deductible Discount","discountCode":"PO01"}}}$j$, $s$Active$s$, $s$MOT-001-2026$s$, $s$Motor$s$, $s$Motor Vehicle$s$, $s$Highest protection: collision, fire, theft, acts of nature, medical expenses and bail bond.$s$, $s$v1$s$, $s$2026-04-30$s$, $s$2027-04-29$s$, 2.75, 15000, 750000, 15, $j${"mandatory":["CTPL","Own Damage","Theft"],"optional":["Acts of Nature","Bail Bond"]}$j$, $j$["MAPFRE Insurance Corporation","FPG Insurance Co., Inc."]$j$, $j$["Motor","Premium"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$MOT-001-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Travel$s$, (SELECT id FROM products WHERE code = $s$PA$s$), 1, $j${}$j$, $s$Active$s$, $s$1001$s$, $s$Travel$s$, $s$Travel & Personal Accident$s$, $s$About travel plans$s$, $s$v1$s$, $s$2025-12-08$s$, $s$2026-12-31$s$, NULL, NULL, NULL, NULL, $j${}$j$, $j$[]$j$, $j$[]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$1001$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Motor Comprehensive Insurance$s$, (SELECT id FROM products WHERE code = $s$MOTOR$s$), 2, $j${}$j$, $s$Active$s$, $s$MOTOR-COMP-2026$s$, $s$Motor$s$, $s$Motor Vehicle$s$, $s$Comprehensive motor insurance with CTPL and AOG coverage$s$, $s$v2.1$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 2.5, 15000, NULL, 15, $j${"mandatory":["CTPL","Own Damage"],"optional":["Acts of God","Personal Accident","Towing Service"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc."]$j$, $j$["Motor"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Group Health Insurance$s$, (SELECT id FROM products WHERE code = $s$EB$s$), 1, $j${}$j$, $s$Active$s$, $s$HEALTH-GROUP-2026$s$, $s$Health$s$, $s$Health & Medical$s$, $s$Group health insurance for corporate clients$s$, $s$v1.5$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 1200, 1200, NULL, 10, $j${"mandatory":["Hospitalization","Outpatient","Emergency"],"optional":["Dental","Maternity","Executive Check-up"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc.","Standard Insurance Co., Inc."]$j$, $j$["Health"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Property Fire Insurance$s$, (SELECT id FROM products WHERE code = $s$FIRE$s$), 3, $j${}$j$, $s$Active$s$, $s$PROP-FIRE-2026$s$, $s$Property$s$, $s$Fire & Allied Perils$s$, $s$Standard fire insurance with allied perils$s$, $s$v3.0$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 0.35, 5000, NULL, 20, $j${"mandatory":["Fire","Lightning"],"optional":["Typhoon","Flood","Earthquake","Riot & Strike"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp."]$j$, $j$["Property"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$PROP-FIRE-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$International Travel Insurance$s$, (SELECT id FROM products WHERE code = $s$PA$s$), 1, $j${}$j$, $s$Active$s$, $s$TRAVEL-INT-2026$s$, $s$Travel$s$, $s$Travel & Personal Accident$s$, $s$Comprehensive travel insurance for international trips$s$, $s$v1.8$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 500, 500, NULL, 25, $j${"mandatory":["Medical Expenses","Emergency Evacuation","Trip Cancellation"],"optional":["Baggage Loss","Flight Delay","Adventure Sports"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc."]$j$, $j$["Travel"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$TRAVEL-INT-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Group Life Insurance$s$, (SELECT id FROM products WHERE code = $s$EB$s$), 2, $j${}$j$, $s$Active$s$, $s$EB-LIFE-2026$s$, $s$Employee Benefits$s$, $s$Employee Benefits$s$, $s$Group life insurance for employees with optional dependent coverage$s$, $s$v2.0$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 500, 500, NULL, 15, $j${"mandatory":["Basic Life","Total Permanent Disability"],"optional":["Accidental Death","Dependent Life","Burial Assistance"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc.","Standard Insurance Co., Inc."]$j$, $j$["Employee Benefits"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$EB-LIFE-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Employee Health & Medical$s$, (SELECT id FROM products WHERE code = $s$EB$s$), 2, $j${}$j$, $s$Active$s$, $s$EB-HEALTH-2026$s$, $s$Employee Benefits$s$, $s$Employee Benefits$s$, $s$Comprehensive health coverage for employees including HMO$s$, $s$v2.5$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 3500, 3500, NULL, 12, $j${"mandatory":["Hospitalization","Outpatient","Emergency"],"optional":["Dental","Optical","Maternity","Mental Health","Executive Check-up"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp."]$j$, $j$["Employee Benefits"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$EB-HEALTH-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Group Personal Accident$s$, (SELECT id FROM products WHERE code = $s$EB$s$), 1, $j${}$j$, $s$Active$s$, $s$EB-ACCIDENT-2026$s$, $s$Employee Benefits$s$, $s$Employee Benefits$s$, $s$24/7 worldwide accident protection for employees$s$, $s$v1.8$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 250, 250, NULL, 18, $j${"mandatory":["Accidental Death","Dismemberment"],"optional":["Medical Reimbursement","Daily Hospital Income","Bereavement"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc."]$j$, $j$["Employee Benefits"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$EB-ACCIDENT-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Group Retirement Plan$s$, (SELECT id FROM products WHERE code = $s$EB$s$), 1, $j${}$j$, $s$Draft$s$, $s$EB-RETIREMENT-2026$s$, $s$Employee Benefits$s$, $s$Employee Benefits$s$, $s$Retirement savings with insurance component$s$, $s$v1.5$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 1000, 1000, NULL, 10, $j${"mandatory":["Retirement Fund","Life Insurance"],"optional":["Investment Options","Disability Waiver","Loan Facility"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp.","FPG Insurance Co., Inc.","Standard Insurance Co., Inc."]$j$, $j$["Employee Benefits"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$EB-RETIREMENT-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$Marine Cargo Insurance$s$, (SELECT id FROM products WHERE code = $s$MARINE$s$), 2, $j${}$j$, $s$Active$s$, $s$MARINE-CARGO-2026$s$, $s$Marine$s$, $s$Marine Cargo$s$, $s$Coverage for goods in transit via sea, air, or land$s$, $s$v2.3$s$, $s$2026-01-01$s$, $s$2026-12-31$s$, 0.25, 3000, NULL, 15, $j${"mandatory":["Institute Cargo Clauses"],"optional":["War Risk","SRCC","Theft Pilferage"]}$j$, $j$["Malayan Insurance Co., Inc.","Pioneer Insurance & Surety Corp."]$j$, $j$["Marine"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$MARINE-CARGO-2026$s$);
INSERT INTO product_templates(name, product_id, version, config, status, template_code, category, line_of_business, description, version_label, effective_date, expiry_date, base_rate, min_premium, max_premium, commission_rate, features, insurers, tags, created_by, updated_by)
SELECT $s$CTPL Standard 2024$s$, (SELECT id FROM products WHERE code = $s$CTPL$s$), 1, $j${}$j$, $s$Retired$s$, $s$CTPL-2024$s$, $s$Motor$s$, $s$Motor Vehicle$s$, $s$Superseded CTPL plan$s$, $s$v1$s$, $s$2024-01-01$s$, $s$2024-12-31$s$, NULL, 560, NULL, 10, $j${"mandatory":["CTPL"]}$j$, $j$["Standard Insurance Co., Inc."]$j$, $j$["Motor"]$j$, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_templates WHERE template_code = $s$CTPL-2024$s$);
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$CTPL$s$, $s$CTPL (Compulsory Third Party Liability)$s$, $j${"coverageName":"CTPL (Compulsory Third Party Liability)","coverageCode":"CTPL","type":"Mandatory","description":"Mandatory coverage for bodily injury/death to third parties","limits":[{"type":"Per Person","amount":100000,"currency":"PHP"},{"type":"Per Event","amount":500000,"currency":"PHP"}],"deductible":0,"waitingPeriod":0,"exclusions":["Intentional damage","Racing","DUI"],"premiumImpact":"Base","requiredDocuments":["OR/CR","Valid License"]}$j$, 'Active', 1, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$CTPL$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$AOG$s$, $s$Acts of God$s$, $j${"coverageName":"Acts of God","coverageCode":"AOG","type":"Optional","description":"Coverage for typhoon, flood, earthquake damages","limits":[{"type":"Maximum","amount":1000000,"currency":"PHP"}],"deductible":5000,"waitingPeriod":0,"exclusions":["Gradual deterioration","Wear and tear"],"premiumImpact":"+0.5%","requiredDocuments":[]}$j$, 'Active', 2, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$AOG$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$HOSP$s$, $s$Hospitalization Benefit$s$, $j${"coverageName":"Hospitalization Benefit","coverageCode":"HOSP","type":"Mandatory","description":"Inpatient coverage including room and board","limits":[{"type":"Annual","amount":500000,"currency":"PHP"},{"type":"Per Illness","amount":150000,"currency":"PHP"}],"deductible":0,"waitingPeriod":30,"exclusions":["Pre-existing conditions","Cosmetic surgery"],"premiumImpact":"Base","requiredDocuments":["Medical History Form"]}$j$, 'Active', 3, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$HOSP$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$VEH_AGE$s$, $s$Vehicle Age$s$, $j${"factorName":"Vehicle Age","factorCode":"VEH_AGE","type":"Multiplicative","rules":[{"condition":"0-1 years","factor":1,"description":"New vehicle"},{"condition":"2-5 years","factor":1.1,"description":"Slightly used"},{"condition":"6-10 years","factor":1.3,"description":"Moderately used"},{"condition":"> 10 years","factor":1.5,"description":"Old vehicle"}]}$j$, 'Active', 4, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$VEH_AGE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$DRV_AGE$s$, $s$Driver Age$s$, $j${"factorName":"Driver Age","factorCode":"DRV_AGE","type":"Multiplicative","rules":[{"condition":"< 25 years","factor":1.3,"description":"Young driver"},{"condition":"25-65 years","factor":1,"description":"Standard risk"},{"condition":"> 65 years","factor":1.2,"description":"Senior driver"}]}$j$, 'Active', 5, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$DRV_AGE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$NCB$s$, $s$NCB (No Claim Bonus)$s$, $j${"factorName":"NCB (No Claim Bonus)","factorCode":"NCB","type":"Discount","rules":[{"condition":"1 year","factor":0.95,"description":"5% discount"},{"condition":"2 years","factor":0.9,"description":"10% discount"},{"condition":"3+ years","factor":0.85,"description":"15% discount"}]}$j$, 'Active', 6, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$NCB$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$PROP-FIRE-2026$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$CONST_TYPE$s$, $s$Construction Type$s$, $j${"factorName":"Construction Type","factorCode":"CONST_TYPE","type":"Multiplicative","rules":[{"condition":"Concrete","factor":1,"description":"Standard rate"},{"condition":"Mixed","factor":1.2,"description":"20% loading"},{"condition":"Wood","factor":1.5,"description":"50% loading"}]}$j$, 'Active', 7, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$CONST_TYPE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$PROP-FIRE-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$VEH_AGE_LIMIT$s$, $s$Vehicle Age Limit$s$, $j${"ruleName":"Vehicle Age Limit","ruleCode":"VEH_AGE_LIMIT","type":"Acceptance","condition":"Vehicle Age <= 15 years","action":"Auto-Accept","message":"Vehicle within acceptable age","authority":"System","exceptions":["Vintage cars with appraisal"]}$j$, 'Active', 8, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$VEH_AGE_LIMIT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$SI_VALIDATION$s$, $s$Sum Insured Validation$s$, $j${"ruleName":"Sum Insured Validation","ruleCode":"SI_VALIDATION","type":"Validation","condition":"Sum Insured <= Fair Market Value * 1.1","action":"Refer","message":"Sum insured exceeds fair market value","authority":"Underwriter Level 1","exceptions":["New vehicles","Imported vehicles"]}$j$, 'Active', 9, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$SI_VALIDATION$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$GRP_SIZE_MIN$s$, $s$Group Size Minimum$s$, $j${"ruleName":"Group Size Minimum","ruleCode":"GRP_SIZE_MIN","type":"Acceptance","condition":"Number of Members >= 10","action":"Auto-Accept","message":"Meets minimum group size","authority":"System","exceptions":["Family plans"]}$j$, 'Active', 10, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$GRP_SIZE_MIN$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$PROP-FIRE-2026$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$HIGH_RISK_LOC$s$, $s$High Risk Location$s$, $j${"ruleName":"High Risk Location","ruleCode":"HIGH_RISK_LOC","type":"Loading","condition":"Location in Flood Prone Area","action":"Apply Loading","message":"Additional 25% loading for flood-prone area","authority":"Underwriter Level 2","exceptions":["With flood mitigation measures"]}$j$, 'Active', 11, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$HIGH_RISK_LOC$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$PROP-FIRE-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$documents$s$, $s$MOTOR_SCHED$s$, $s$Motor Policy Schedule$s$, $j${"documentName":"Motor Policy Schedule","documentCode":"MOTOR_SCHED","type":"Policy Document","format":"PDF","template":"motor_schedule_template.pdf","mandatory":true,"stage":"Policy Issuance","variables":["PolicyNumber","InsuredName","VehicleDetails","Premium"]}$j$, 'Active', 12, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$documents$s$ AND code IS NOT DISTINCT FROM $s$MOTOR_SCHED$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$documents$s$, $s$CTPL_CERT$s$, $s$CTPL Certificate$s$, $j${"documentName":"CTPL Certificate","documentCode":"CTPL_CERT","type":"Certificate","format":"PDF","template":"ctpl_certificate.pdf","mandatory":true,"stage":"Policy Issuance","variables":["PolicyNumber","PlateNumber","CoverageAmount"]}$j$, 'Active', 13, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$documents$s$ AND code IS NOT DISTINCT FROM $s$CTPL_CERT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1), $s$documents$s$, $s$MEMBER_ENROLL$s$, $s$Member Enrollment Form$s$, $j${"documentName":"Member Enrollment Form","documentCode":"MEMBER_ENROLL","type":"Application","format":"Excel","template":"member_enrollment.xlsx","mandatory":true,"stage":"Quotation","variables":["CompanyName","MemberList","CoverageDetails"]}$j$, 'Active', 14, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$documents$s$ AND code IS NOT DISTINCT FROM $s$MEMBER_ENROLL$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$HEALTH-GROUP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT NULL, $s$workflows$s$, $s$NEW_PROD_APPR$s$, $s$New Product Approval$s$, $j${"workflowName":"New Product Approval","workflowCode":"NEW_PROD_APPR","type":"Sequential","stages":[{"level":1,"role":"Product Manager","action":"Review & Recommend","sla":"2 days","escalation":"Department Head"},{"level":2,"role":"Compliance Officer","action":"Compliance Check","sla":"1 day","escalation":"Chief Compliance"},{"level":3,"role":"Chief Product Officer","action":"Final Approval","sla":"1 day","escalation":"CEO"}],"triggers":["New Product","Major Version Change"]}$j$, 'Active', 15, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$workflows$s$ AND code IS NOT DISTINCT FROM $s$NEW_PROD_APPR$s$ AND template_id IS NOT DISTINCT FROM NULL);
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT NULL, $s$workflows$s$, $s$RATE_CHG_APPR$s$, $s$Rate Change Approval$s$, $j${"workflowName":"Rate Change Approval","workflowCode":"RATE_CHG_APPR","type":"Parallel","stages":[{"level":1,"role":"Actuarial Team","action":"Rate Validation","sla":"3 days","escalation":"Chief Actuary"},{"level":1,"role":"Sales Head","action":"Market Impact Review","sla":"2 days","escalation":"Chief Sales Officer"}],"triggers":["Rate Change > 10%"]}$j$, 'Active', 16, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$workflows$s$ AND code IS NOT DISTINCT FROM $s$RATE_CHG_APPR$s$ AND template_id IS NOT DISTINCT FROM NULL);
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$market-mappings$s$, $s$MAL-MOTOR-COMP$s$, $s$Malayan Insurance Co., Inc.$s$, $j${"insurerName":"Malayan Insurance Co., Inc.","productCode":"MAL-MOTOR-COMP","commissionRate":15,"overrideRate":2,"profitShare":5,"targetPremium":100000000,"ytdPremium":45000000,"specialTerms":"Exclusive fleet discount available","validFrom":"2026-01-01","validTo":"2026-12-31"}$j$, 'Active', 17, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$market-mappings$s$ AND code IS NOT DISTINCT FROM $s$MAL-MOTOR-COMP$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$market-mappings$s$, $s$PGA-AUTO-2025$s$, $s$Pioneer Insurance & Surety Corp.$s$, $j${"insurerName":"Pioneer Insurance & Surety Corp.","productCode":"PGA-AUTO-2025","commissionRate":14,"overrideRate":1.5,"profitShare":3,"targetPremium":80000000,"ytdPremium":38000000,"specialTerms":"Quick claim settlement","validFrom":"2026-01-01","validTo":"2026-12-31"}$j$, 'Active', 18, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$market-mappings$s$ AND code IS NOT DISTINCT FROM $s$PGA-AUTO-2025$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1), $s$commissions$s$, $s$CS-MTR-STD$s$, $s$Standard Motor Commission$s$, $j${"structureCode":"CS-MTR-STD","structureName":"Standard Motor Commission","type":"Tiered","tiers":[{"from":0,"to":1000000,"rate":12,"description":"Base tier"},{"from":1000001,"to":5000000,"rate":14,"description":"Silver tier"},{"from":5000001,"to":10000000,"rate":16,"description":"Gold tier"},{"from":10000001,"to":null,"rate":18,"description":"Platinum tier"}],"bonusScheme":{"quarterly":{"target":25000000,"bonus":2},"annual":{"target":100000000,"bonus":5}}}$j$, 'Active', 19, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$commissions$s$ AND code IS NOT DISTINCT FROM $s$CS-MTR-STD$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOTOR-COMP-2026$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$OD$s$, $s$Own Damage$s$, $j${"coverageCode":"OD","coverageName":"Own Damage","type":"Mandatory","description":"Own Damage cover","deductible":3000,"waitingPeriod":0,"premiumImpact":"Base","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 20, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$OD$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$THEFT$s$, $s$Theft$s$, $j${"coverageCode":"THEFT","coverageName":"Theft","type":"Mandatory","description":"Theft cover","deductible":3000,"waitingPeriod":0,"premiumImpact":"Base","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 21, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$THEFT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$CTPL$s$, $s$Compulsory Third Party Liability$s$, $j${"coverageCode":"CTPL","coverageName":"Compulsory Third Party Liability","type":"Mandatory","description":"Compulsory Third Party Liability cover","deductible":0,"waitingPeriod":0,"premiumImpact":"Base","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 22, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$CTPL$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$AOG$s$, $s$Acts of Nature$s$, $j${"coverageCode":"AOG","coverageName":"Acts of Nature","type":"Optional","description":"Acts of Nature cover","deductible":5000,"waitingPeriod":0,"premiumImpact":"+0.5%","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 23, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$AOG$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$VTPL-BI$s$, $s$Excess Bodily Injury$s$, $j${"coverageCode":"VTPL-BI","coverageName":"Excess Bodily Injury","type":"Optional","description":"Excess Bodily Injury cover","deductible":0,"waitingPeriod":0,"premiumImpact":"+0.5%","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 24, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$VTPL-BI$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$VTPL-PD$s$, $s$Property Damage$s$, $j${"coverageCode":"VTPL-PD","coverageName":"Property Damage","type":"Optional","description":"Property Damage cover","deductible":0,"waitingPeriod":0,"premiumImpact":"+0.5%","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 25, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$VTPL-PD$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$coverages$s$, $s$APA$s$, $s$Auto Personal Accident$s$, $j${"coverageCode":"APA","coverageName":"Auto Personal Accident","type":"Optional","description":"Auto Personal Accident cover","deductible":0,"waitingPeriod":0,"premiumImpact":"+0.5%","limits":[],"exclusions":[],"requiredDocuments":["OR/CR"]}$j$, 'Active', 26, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$coverages$s$ AND code IS NOT DISTINCT FROM $s$APA$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$VEH_AGE$s$, $s$Vehicle Age$s$, $j${"factorCode":"VEH_AGE","factorName":"Vehicle Age","type":"Multiplicative","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 27, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$VEH_AGE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$DRV_AGE$s$, $s$Driver Age$s$, $j${"factorCode":"DRV_AGE","factorName":"Driver Age","type":"Multiplicative","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 28, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$DRV_AGE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$NCB$s$, $s$No Claim Bonus$s$, $j${"factorCode":"NCB","factorName":"No Claim Bonus","type":"Discount","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 29, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$NCB$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$USE$s$, $s$Vehicle Use$s$, $j${"factorCode":"USE","factorName":"Vehicle Use","type":"Multiplicative","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 30, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$USE$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$REGION$s$, $s$Garaging Region$s$, $j${"factorCode":"REGION","factorName":"Garaging Region","type":"Multiplicative","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 31, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$REGION$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$FLEET$s$, $s$Fleet Size$s$, $j${"factorCode":"FLEET","factorName":"Fleet Size","type":"Discount","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 32, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$FLEET$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$DED$s$, $s$Voluntary Deductible$s$, $j${"factorCode":"DED","factorName":"Voluntary Deductible","type":"Discount","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 33, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$DED$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-factors$s$, $s$BRAND$s$, $s$Brand Risk Group$s$, $j${"factorCode":"BRAND","factorName":"Brand Risk Group","type":"Multiplicative","rules":[{"condition":"Standard","factor":1,"description":"Base"}]}$j$, 'Active', 34, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-factors$s$ AND code IS NOT DISTINCT FROM $s$BRAND$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$VEH_AGE_LIMIT$s$, $s$Vehicle Age Limit$s$, $j${"ruleCode":"VEH_AGE_LIMIT","ruleName":"Vehicle Age Limit","type":"Acceptance","condition":"Vehicle Age <= 15 years","action":"Auto-Accept","message":"Vehicle Age Limit","authority":"System","exceptions":[]}$j$, 'Active', 35, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$VEH_AGE_LIMIT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$SI_VALIDATION$s$, $s$Sum Insured Validation$s$, $j${"ruleCode":"SI_VALIDATION","ruleName":"Sum Insured Validation","type":"Validation","condition":"Sum Insured <= Fair Market Value * 1.1","action":"Refer","message":"Sum Insured Validation","authority":"Underwriter Level 1","exceptions":[]}$j$, 'Active', 36, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$SI_VALIDATION$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$HIGH_SI$s$, $s$High Sum Insured$s$, $j${"ruleCode":"HIGH_SI","ruleName":"High Sum Insured","type":"Referral","condition":"Sum Insured > 5,000,000","action":"Refer","message":"High Sum Insured","authority":"Underwriter Level 1","exceptions":[]}$j$, 'Active', 37, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$HIGH_SI$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$PUV$s$, $s$Public Utility Vehicle$s$, $j${"ruleCode":"PUV","ruleName":"Public Utility Vehicle","type":"Acceptance","condition":"Vehicle Use = PUV","action":"Decline","message":"Public Utility Vehicle","authority":"System","exceptions":[]}$j$, 'Active', 38, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$PUV$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$CLAIMS_HIST$s$, $s$Claims History$s$, $j${"ruleCode":"CLAIMS_HIST","ruleName":"Claims History","type":"Loading","condition":"Claims in last 3 years >= 2","action":"Apply Loading","message":"Claims History","authority":"System","exceptions":[]}$j$, 'Active', 39, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$CLAIMS_HIST$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$YOUNG_DRV$s$, $s$Young Driver$s$, $j${"ruleCode":"YOUNG_DRV","ruleName":"Young Driver","type":"Loading","condition":"Driver Age < 21","action":"Apply Loading","message":"Young Driver","authority":"System","exceptions":[]}$j$, 'Active', 40, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$YOUNG_DRV$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$underwriting-rules$s$, $s$MODIFIED$s$, $s$Modified Vehicle$s$, $j${"ruleCode":"MODIFIED","ruleName":"Modified Vehicle","type":"Referral","condition":"Vehicle has modifications","action":"Refer","message":"Modified Vehicle","authority":"Underwriter Level 1","exceptions":[]}$j$, 'Active', 41, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$underwriting-rules$s$ AND code IS NOT DISTINCT FROM $s$MODIFIED$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$taxes$s$, $s$DST$s$, $s$Documentary Stamp Tax$s$, $j${"taxCode":"DST","taxName":"Documentary Stamp Tax","rate":12.5,"basis":"Premium","settingKey":"tax.dst_rate"}$j$, 'Active', 42, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$taxes$s$ AND code IS NOT DISTINCT FROM $s$DST$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$taxes$s$, $s$LGT$s$, $s$Local Government Tax$s$, $j${"taxCode":"LGT","taxName":"Local Government Tax","rate":0.75,"basis":"Premium","settingKey":"tax.lgt_rate"}$j$, 'Active', 43, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$taxes$s$ AND code IS NOT DISTINCT FROM $s$LGT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$taxes$s$, $s$VAT$s$, $s$Value Added Tax$s$, $j${"taxCode":"VAT","taxName":"Value Added Tax","rate":12,"basis":"Premium","settingKey":"tax.vat_rate"}$j$, 'Active', 44, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$taxes$s$ AND code IS NOT DISTINCT FROM $s$VAT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$acceptance-limits$s$, $s$MTR-LIMIT$s$, $s$Private car acceptance$s$, $j${"limitCode":"MTR-LIMIT","limitName":"Private car acceptance","minSumInsured":200000,"maxSumInsured":5000000,"maxVehicleAge":15,"authorityLimit":3000000}$j$, 'Active', 45, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$acceptance-limits$s$ AND code IS NOT DISTINCT FROM $s$MTR-LIMIT$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-parameters$s$, $s$DEPRECIATION$s$, $s$Annual depreciation$s$, $j${"parameterCode":"DEPRECIATION","parameterName":"Annual depreciation","value":10,"unit":"%"}$j$, 'Active', 46, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-parameters$s$ AND code IS NOT DISTINCT FROM $s$DEPRECIATION$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$rating-parameters$s$, $s$MAX_DEP_YEARS$s$, $s$Maximum depreciation years$s$, $j${"parameterCode":"MAX_DEP_YEARS","parameterName":"Maximum depreciation years","value":10,"unit":"years"}$j$, 'Active', 47, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$rating-parameters$s$ AND code IS NOT DISTINCT FROM $s$MAX_DEP_YEARS$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_components(template_id, kind, code, name, data, status, sort_order, created_by, updated_by)
SELECT (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1), $s$market-mappings$s$, $s$MAL-MOTOR-BASIC$s$, $s$Malayan Insurance Co., Inc.$s$, $j${"insurerName":"Malayan Insurance Co., Inc.","productCode":"MAL-MOTOR-BASIC","commissionRate":12,"overrideRate":1,"profitShare":3,"targetPremium":50000000,"ytdPremium":21500000,"specialTerms":"Fleet discount above 10 units","validFrom":"2026-01-01","validTo":"2026-12-31"}$j$, 'Active', 48, 'seed', 'seed'
WHERE NOT EXISTS (SELECT 1 FROM product_components WHERE kind = $s$market-mappings$s$ AND code IS NOT DISTINCT FROM $s$MAL-MOTOR-BASIC$s$ AND template_id IS NOT DISTINCT FROM (SELECT id FROM product_templates WHERE template_code = $s$MOT-003-2025$s$ ORDER BY version DESC LIMIT 1));
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_ctpl$s$, $s$PRD-CTP$s$, $s$CTPL$s$, $s$CTPL$s$, $s$Non-life · Liability$s$, $s$LIABILITY_FIELDS$s$, $s$Liability cover fields$s$, 'Active', $j${"type":"CTPL"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_fire$s$, $s$PRD-FIR$s$, $s$FIRE$s$, $s$Fire$s$, $s$Non-life · Property$s$, $s$PROPERTY_RISK_FIELDS$s$, $s$Property risk fields$s$, 'Active', $j${"type":"FIRE"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_health$s$, $s$PRD-HEA$s$, $s$HEALTH$s$, $s$Health$s$, $s$Non-life · Health$s$, $s$HEALTH_COVER_FIELDS$s$, $s$Health cover fields$s$, 'Active', $j${"type":"HEALTH"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_iar$s$, $s$PRD-IAR$s$, $s$IAR$s$, $s$Industrial All Risks (IAR)$s$, $s$Non-life · Industrial All Risks$s$, $s$RISK_SECTIONS$s$, $s$Risk sections$s$, 'Active', $j${"type":"IAR","defaultVatPercent":12}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_life$s$, $s$PRD-LIF$s$, $s$LIFE$s$, $s$Life$s$, $s$Non-life · Life$s$, $s$LIFE_COVER_FIELDS$s$, $s$Life cover fields$s$, 'Active', $j${"type":"LIFE"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_motor$s$, $s$PRD-MTR$s$, $s$MOTOR$s$, $s$Motor$s$, $s$Non-life · Motor$s$, $s$VEHICLE_DETAILS$s$, $s$Vehicle details$s$, 'Active', $j${"type":"MOTOR"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_property$s$, $s$PRD-PRP$s$, $s$PROPERTY$s$, $s$Property$s$, $s$Non-life · Property$s$, $s$PROPERTY_RISK_FIELDS$s$, $s$Property risk fields$s$, 'Active', $j${"type":"PROPERTY"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_mappings(id, product_code, lob_code, product_name, line_of_business, definition_type, definition_label, status, configuration, created_by, updated_by)
VALUES ($s$prm_travel$s$, $s$PRD-TRV$s$, $s$TRAVEL$s$, $s$Travel$s$, $s$Non-life · Travel$s$, $s$TRAVEL_RISK_FIELDS$s$, $s$Travel risk fields$s$, 'Active', $j${"type":"TRAVEL"}$j$, 'seed', 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_risk_sections(id, mapping_id, section_code, section_label, remarks, default_rate_percent, sort_order, created_by, updated_by)
VALUES ($s$prs_iar_motor$s$, 'prm_iar', $s$MOTOR$s$, $s$Motor Commercial$s$, $s$Owned commercial fleet$s$, 0.35, 1, 'seed', 'seed') ON CONFLICT (mapping_id, section_code) DO NOTHING;
INSERT INTO product_risk_sections(id, mapping_id, section_code, section_label, remarks, default_rate_percent, sort_order, created_by, updated_by)
VALUES ($s$prs_iar_fire$s$, 'prm_iar', $s$FIRE$s$, $s$Fire Material Damage$s$, $s$Buildings, plant and stock$s$, 0.15, 2, 'seed', 'seed') ON CONFLICT (mapping_id, section_code) DO NOTHING;
INSERT INTO product_risk_sections(id, mapping_id, section_code, section_label, remarks, default_rate_percent, sort_order, created_by, updated_by)
VALUES ($s$prs_iar_ctpl$s$, 'prm_iar', $s$CTPL$s$, $s$Compulsory Third Party Liability$s$, NULL, 0.25, 4, 'seed', 'seed') ON CONFLICT (mapping_id, section_code) DO NOTHING;
INSERT INTO product_risk_sections(id, mapping_id, section_code, section_label, remarks, default_rate_percent, sort_order, created_by, updated_by)
VALUES ($s$prs_iar_life$s$, 'prm_iar', $s$LIFE$s$, $s$Life$s$, NULL, 0.3, 6, 'seed', 'seed') ON CONFLICT (mapping_id, section_code) DO NOTHING;

-- Templates name their line of business by the Line of Business master code (migration 0242_product_template_lob_codes.sql).
UPDATE product_templates t SET line_of_business = lob.code, updated_at = now()
FROM products p, master_records lob
WHERE p.id = t.product_id AND lob.type_code = 'line-of-business' AND lob.status = 'active' AND lob.code = upper(p.line)
  AND t.line_of_business IS DISTINCT FROM lob.code;

UPDATE product_templates t SET line_of_business = lob.code, updated_at = now()
FROM master_records lob
WHERE lob.type_code = 'line-of-business' AND lob.status = 'active' AND t.line_of_business IS DISTINCT FROM lob.code
  AND (lower(lob.code) = lower(t.line_of_business) OR lower(lob.name) = lower(t.line_of_business))
  AND NOT EXISTS (SELECT 1 FROM master_records x WHERE x.type_code = 'line-of-business' AND x.code = t.line_of_business);
