-- Bank reconciliation reference data (the tables are created by migration 0116; document_numbering and the period-end
-- checklist come from later migrations, so these rows live here). Idempotent; administrator edits are kept.

-- Document numbering series: bank statements (BST) and bank reconciliation runs (BRC)
INSERT INTO document_numbering(code, name, module, prefix, description, created_by)
SELECT s.code, s.name, 'accounting', COALESCE(NULLIF(btrim((SELECT value #>> '{}' FROM app_settings WHERE key = 'numbering.' || s.code || '.prefix')), ''), s.prefix), s.description, 'seed'
FROM (VALUES ('bank_statement', 'Bank Statement', 'BST', 'Imported or manually entered bank statement'),
             ('bank_reconciliation', 'Bank Reconciliation', 'BRC', 'Bank reconciliation run per bank account and period')) AS s(code, name, prefix, description)
ON CONFLICT (code) DO NOTHING;

-- Bank account master: the GL cash account the account posts to and its default statement format (added only when the
-- type does not have the field yet, so administrator edits of the definition are kept)
UPDATE master_types t SET fields = t.fields || (
  SELECT COALESCE(jsonb_agg(f), '[]'::jsonb) FROM jsonb_array_elements($j$[
    {"name":"glAccountCode","label":"GL Cash Account (bank reconciliation)","type":"string","required":false},
    {"name":"statementFormat","label":"Bank Statement Format","type":"string","required":false},
    {"name":"reconcileFrom","label":"Reconcile From (date)","type":"date","required":false}
  ]$j$::jsonb) f
  WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements(t.fields) e WHERE e->>'name' = f->>'name'))
WHERE t.code = 'bank-account';

-- The month-end checklist item now reads the bank reconciliation module (severity stays configurable on the master)
UPDATE period_close_checklist SET description = 'Every bank account linked to a GL cash account with activity in the period (GL postings or statement lines) has an approved bank reconciliation for the period (Accounts > Bank Reconciliation). Make the item blocking to stop the close until then.'
WHERE code = 'unreconciled_bank' AND description = 'Unreconciled bank statement lines up to the period end (when bank reconciliation is in use)';

-- Month-End Close Status report: bank reconciliations approved / required per period
UPDATE report_definitions SET default_columns = default_columns || '[{"key":"bankReconciliations","label":"Bank Recs Approved / Required","type":"text"}]'::jsonb
WHERE code = 'month-end-close-status' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(default_columns) e WHERE e->>'key' = 'bankReconciliations');

-- Report catalogue (queries in src/modules/reports/bankRecQueries.js)
INSERT INTO report_definitions(code, name, category, description, screen, query_name, parameters, default_columns, roles, sort_order) VALUES
 ('bank-reconciliation-statement', 'Bank Reconciliation Statement', 'financial', 'Bank reconciliation runs with an as-of date in the range: balance per bank statement, deposits in transit, outstanding cheques and bank errors (adjusted bank balance); balance per books, bank credits and charges not yet booked and book errors (adjusted book balance); the difference must be zero to approve.', 'Accounts > Bank Reconciliation; Reports > Financial Reports > Bank Reconciliation Statement', 'bankRecStatement',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Bank Account"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"BankAccount":{"type":"string","title":"Bank Account","description":"bank account code","x-options":"bank_accounts"},"Status":{"type":"string","title":"Status","enum":["draft","prepared","approved"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"recNumber","label":"Reconciliation No.","type":"text"},{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"bankAccountName","label":"Account Name","type":"text"},{"key":"glAccount","label":"GL Account","type":"text"},{"key":"period","label":"Period","type":"text"},{"key":"asOfDate","label":"As of","type":"date"},{"key":"status","label":"Status","type":"text"},{"key":"bankBalance","label":"Balance per Bank","type":"money","total":false},{"key":"depositsInTransit","label":"Deposits in Transit","type":"money","total":false},{"key":"outstandingCheques","label":"Outstanding Cheques","type":"money","total":false},{"key":"bankErrors","label":"Bank Errors","type":"money","total":false},{"key":"adjustedBankBalance","label":"Adjusted Bank Balance","type":"money","total":false},{"key":"bookBalance","label":"Balance per Books","type":"money","total":false},{"key":"unbookedCredits","label":"Bank Credits not Booked","type":"money","total":false},{"key":"unbookedDebits","label":"Bank Charges not Booked","type":"money","total":false},{"key":"bookErrors","label":"Book Errors","type":"money","total":false},{"key":"adjustedBookBalance","label":"Adjusted Book Balance","type":"money","total":false},{"key":"difference","label":"Difference","type":"money","total":false},{"key":"preparedBy","label":"Prepared By","type":"text"},{"key":"preparedAt","label":"Prepared At","type":"datetime"},{"key":"approvedBy","label":"Approved By","type":"text"},{"key":"approvedAt","label":"Approved At","type":"datetime"}]'::jsonb,
  ARRAY['accounting']::text[], 400),
 ('bank-outstanding-cheques', 'Outstanding Cheques', 'financial', 'Payments recorded in the books (cheques, transfers) on or before To Date that have not cleared the bank as of To Date, aged; cheques older than bank_reconciliation.stale_cheque_days are stale.', 'Accounts > Bank Reconciliation; Reports > Financial Reports > Outstanding Cheques', 'outstandingCheques',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Bank Account","Status"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"BankAccount":{"type":"string","title":"Bank Account","description":"bank account code","x-options":"bank_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"glAccount","label":"GL Account","type":"text"},{"key":"date","label":"Date","type":"date"},{"key":"journalNumber","label":"Journal No.","type":"text"},{"key":"documentType","label":"Document","type":"text"},{"key":"documentNumber","label":"Document No.","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"payee","label":"Payee","type":"text"},{"key":"description","label":"Description","type":"text"},{"key":"amount","label":"Amount","type":"money"},{"key":"ageDays","label":"Age (days)","type":"integer","total":false},{"key":"status","label":"Status","type":"text"}]'::jsonb,
  ARRAY['accounting']::text[], 410),
 ('bank-deposits-in-transit', 'Deposits in Transit', 'financial', 'Collections recorded in the books (official receipts, other debits to the bank account) on or before To Date that have not reached the bank statement as of To Date.', 'Accounts > Bank Reconciliation; Reports > Financial Reports > Deposits in Transit', 'depositsInTransit',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Bank Account"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"BankAccount":{"type":"string","title":"Bank Account","description":"bank account code","x-options":"bank_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"glAccount","label":"GL Account","type":"text"},{"key":"date","label":"Date","type":"date"},{"key":"journalNumber","label":"Journal No.","type":"text"},{"key":"documentType","label":"Document","type":"text"},{"key":"documentNumber","label":"Document No.","type":"text"},{"key":"reference","label":"Reference","type":"text"},{"key":"payer","label":"Payer","type":"text"},{"key":"description","label":"Description","type":"text"},{"key":"amount","label":"Amount","type":"money"},{"key":"ageDays","label":"Age (days)","type":"integer","total":false}]'::jsonb,
  ARRAY['accounting']::text[], 420),
 ('bank-unmatched-lines', 'Unmatched Bank Lines', 'financial', 'Bank statement lines dated in the range that are not matched to the books as of To Date, with the suggested bank transaction type (bank charges, interest, returned cheques, direct credits).', 'Accounts > Bank Reconciliation; Reports > Financial Reports > Unmatched Bank Lines', 'unmatchedBankLines',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Bank Account","Suggested Type"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"BankAccount":{"type":"string","title":"Bank Account","description":"bank account code","x-options":"bank_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"statementNumber","label":"Statement No.","type":"text"},{"key":"date","label":"Date","type":"date"},{"key":"valueDate","label":"Value Date","type":"date"},{"key":"description","label":"Description","type":"text"},{"key":"reference","label":"Reference","type":"text"},{"key":"debit","label":"Debit","type":"money"},{"key":"credit","label":"Credit","type":"money"},{"key":"amount","label":"Net","type":"money"},{"key":"suggestedType","label":"Suggested Type","type":"text"},{"key":"status","label":"Status","type":"text"},{"key":"ageDays","label":"Age (days)","type":"integer","total":false}]'::jsonb,
  ARRAY['accounting']::text[], 430),
 ('bank-book', 'Bank Book', 'financial', 'GL detail of each bank account''s cash-in-bank account: opening balance at From Date, every posted receipt, payment and journal with its source document, the running balance and whether it has cleared the bank.', 'Accounts > Bank Reconciliation; Reports > Financial Reports > Bank Book', 'bankBook',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Bank Account","Overall"],"default":"Bank Account"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"BankAccount":{"type":"string","title":"Bank Account","description":"bank account code","x-options":"bank_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"glAccount","label":"GL Account","type":"text"},{"key":"date","label":"Date","type":"date"},{"key":"journalNumber","label":"Journal No.","type":"text"},{"key":"documentType","label":"Document","type":"text"},{"key":"documentNumber","label":"Document No.","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"party","label":"Payee / Payer","type":"text"},{"key":"description","label":"Description","type":"text"},{"key":"openingBalance","label":"Opening Balance","type":"money","total":false},{"key":"debit","label":"Debit","type":"money"},{"key":"credit","label":"Credit","type":"money"},{"key":"runningBalance","label":"Balance","type":"money","total":false},{"key":"reconciled","label":"Reconciled","type":"text"}]'::jsonb,
  ARRAY['accounting']::text[], 440)
ON CONFLICT (code) DO NOTHING;
