-- TISPH finance configuration from the Finance & General Accounting BRD workbook (the authority for finance; sheet names
-- below). Runs after the reference seeds, on a new database and on every start of an existing one. Idempotent: a row is
-- added only when missing, and a reference value is replaced only while it is still the reference value and nobody has
-- changed it (updated_by empty), so administrator changes are kept. The starter accounts stay in the chart (inactive
-- only by decision of Finance), so the ledger already posted to them keeps its history.

-- ---------------------------------------------------------------- FGA.01 COA: chart of accounts
-- 319 SAP accounts (6 digits). The Tax type is an expense account in the "Income Tax" group; accumulated depreciation
-- has a credit balance; property, equipment and software (160000 to 179999) are non-current (FGA.07 TIS02). Control
-- accounts are open-item accounts. The SAP subledger type (Vendor / Customer / Fixed Asset) is kept in the description.
INSERT INTO gl_accounts(code, name, account_type, fs_group, normal_balance, is_open_item, allow_manual, description)
SELECT v.code, v.name, v.account_type, v.fs_group, v.normal_balance, v.is_open_item, true, v.description
FROM (VALUES
 ('100000', 'Cash on Hand', 'asset', 'Current Assets', NULL, false, NULL),
 ('100001', 'Cash in Vault', 'asset', 'Current Assets', NULL, false, NULL),
 ('100002', 'Check and Other Cash Items', 'asset', 'Current Assets', NULL, false, NULL),
 ('100010', 'Petty Cash Fund', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('106010', 'MBT Bank Balance Php_561', 'asset', 'Current Assets', NULL, false, NULL),
 ('110030', 'Accounts Receivable - Suppliers', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110031', 'Other Receivables', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110032', 'Accounts Receivable-Clients', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Customer'),
 ('110060', 'Accounts Receivable-Intercompany', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110100', 'Accounts Receivable-Employees', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110110', 'Receivable from Employees', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110120', 'Rental Receivable - Employee', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('110200', 'Gross Receipts Tax Receivable', 'asset', 'Current Assets', NULL, false, NULL),
 ('110400', 'Receivable from Insurance Company', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('111012', 'Accrued Interest Receivables - Retail PN', 'asset', 'Current Assets', NULL, false, NULL),
 ('113000', 'Advances to Employees', 'asset', 'Current Assets', NULL, true, 'SAP subledger: Vendor'),
 ('135000', 'Input Value Added Tax-Current', 'asset', 'Current Assets', NULL, false, NULL),
 ('135010', 'Input Value Added Tax-Deferred', 'asset', 'Current Assets', NULL, false, NULL),
 ('135030', 'Creditable Withholding Tax', 'asset', 'Current Assets', NULL, false, NULL),
 ('136010', 'Creditable Withholding Tax - Insurance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144010', 'Prepaid Expense - Doc Stamps', 'asset', 'Current Assets', NULL, false, NULL),
 ('144040', 'Prepaid Expense-eDST', 'asset', 'Current Assets', NULL, false, NULL),
 ('144070', 'Prepaid DST- Fixed Rate Notes', 'asset', 'Current Assets', NULL, false, NULL),
 ('144086', 'Prepaid DST- TMFNL', 'asset', 'Current Assets', NULL, false, NULL),
 ('144093', 'Prepaid DST- TMCC', 'asset', 'Current Assets', NULL, false, NULL),
 ('144100', 'Prepaid Expense - Office Rent', 'asset', 'Current Assets', NULL, false, NULL),
 ('144110', 'Prepaid Expense - Warehouse Rent', 'asset', 'Current Assets', NULL, false, NULL),
 ('144120', 'Prepaid Expense - Telecoms', 'asset', 'Current Assets', NULL, false, NULL),
 ('144130', 'Prep. Exp- Hardware Maintenance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144131', 'Prep. Exp- Computer Sofware', 'asset', 'Current Assets', NULL, false, NULL),
 ('144132', 'Prep. Exp- Software Maintenance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144133', 'Prep. Exp- R&M Software Peripherals', 'asset', 'Current Assets', NULL, false, NULL),
 ('144150', 'Prepaid Expense-Parking', 'asset', 'Current Assets', NULL, false, NULL),
 ('144160', 'Prepaid Expense - LBT', 'asset', 'Current Assets', NULL, false, NULL),
 ('144170', 'Prep. Exp- Medical,Dental & Hospitalization', 'asset', 'Current Assets', NULL, false, NULL),
 ('144171', 'Prep. Exp- Staff-Benefits Medical Allow', 'asset', 'Current Assets', NULL, false, NULL),
 ('144172', 'Prep. Exp- Staff-Ben Medical Allow_FBT', 'asset', 'Current Assets', NULL, false, NULL),
 ('144180', 'Prepaid Expense-Housing Allowance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144190', 'Prepaid expense - Membership Fees', 'asset', 'Current Assets', NULL, false, NULL),
 ('144200', 'Prep. Exp- Office Supplies NS', 'asset', 'Current Assets', NULL, false, NULL),
 ('144201', 'Prep. Exp- Office Supplies Stock', 'asset', 'Current Assets', NULL, false, NULL),
 ('144210', 'Prepaid Expense - Other Taxes', 'asset', 'Current Assets', NULL, false, NULL),
 ('144220', 'Prepaid Expense-Insurance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144230', 'Prepaid Insurance-Others', 'asset', 'Current Assets', NULL, false, NULL),
 ('144240', 'Prepaid Expense Office Premises and FFE', 'asset', 'Current Assets', NULL, false, NULL),
 ('144245', 'Prepaid Expense IT Insurance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144250', 'Prepaid Exp-Office Repairs&Maintenance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144251', 'Prep. Exp- WH-Repairs & Maintenance', 'asset', 'Current Assets', NULL, false, NULL),
 ('144260', 'Prep. Exp- Staff Ben-Uniform/Clothing Allow', 'asset', 'Current Assets', NULL, false, NULL),
 ('144261', 'Prep. Exp- Staff Ben-Uniform/Clothing Allow_FBT', 'asset', 'Current Assets', NULL, false, NULL),
 ('144262', 'Prep. Exp- Staff Ben-Laundry Allow', 'asset', 'Current Assets', NULL, false, NULL),
 ('144270', 'Prep. Exp- Warehouse Rent -Docs', 'asset', 'Current Assets', NULL, false, NULL),
 ('144300', 'Prep. Exp- Postage,Cable & Telegram', 'asset', 'Current Assets', NULL, false, NULL),
 ('144310', 'Prepaid Expense - Others', 'asset', 'Current Assets', NULL, false, NULL),
 ('144320', 'Prepaid Expense - Security Services', 'asset', 'Current Assets', NULL, false, NULL),
 ('151020', 'Investment in Retail Promissory Note', 'asset', 'Current Assets', NULL, false, NULL),
 ('160050', 'Leasehold Improvements', 'asset', 'Non-current Assets', NULL, false, NULL),
 ('160070', 'Office Furniture and Fixtures', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160090', 'Computer Equipment', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160100', 'Software', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160110', 'Company Cars', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160120', 'Leasehold Rights and Improvements(LVA)', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160121', 'Furniture,Fixtures & Equipments(LVA)', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160122', 'Computers(LVA)', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160123', 'Software(LVA)', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160160', 'Assets Under Construction - LRI', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160161', 'Assets Under Construction - Software', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160162', 'Assets Under Construction - Computer', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160163', 'Assets Under Construction - Car', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160164', 'Assets Under Construction - FFE', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('160170', 'Right-of-Use Asset (ROU)', 'asset', 'Non-current Assets', NULL, false, NULL),
 ('160210', 'Operating Lease - KINTO Company Car', 'asset', 'Non-current Assets', NULL, true, 'SAP subledger: Fixed Asset'),
 ('170050', 'Accum Depr-Leasehold Rights & Improvemen', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170070', 'Accum Depr-FFE', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170090', 'Accum Depr-Computers', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170100', 'Accum Depr-Software', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170110', 'Accum Depr-Company Cars', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170115', 'Accum Depr-KINTO Company Car', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170120', 'Accum Depr-Leasehold Rights & Improvemen(LVA)', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170121', 'Accum Depr-FFE(LVA)', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170122', 'Accum Depr-Computers(LVA)', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170123', 'Accum Depr-Software(LVA)', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('170126', 'Accumulated Depreciation-ROU', 'asset', 'Non-current Assets', 'credit', false, NULL),
 ('170210', 'Accum Depr-KINTO Company Car', 'asset', 'Non-current Assets', 'credit', true, 'SAP subledger: Fixed Asset'),
 ('180203', 'Deferred Charges-Fixed Rate Notes', 'asset', 'Current Assets', NULL, false, NULL),
 ('180240', 'Other Assets - Security Deposits', 'asset', 'Current Assets', NULL, false, NULL),
 ('210000', 'Accounts Payable-Corporate', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210030', 'Accrued Payables', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('210060', 'Accounts Payable-Intercompany', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210080', 'Bank Loans-Short', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210081', 'Notes Payable-Retail(Short)', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210085', 'Fixed Rate Notes', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210087', 'Bonds Payable', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210090', 'SSS,Medicare,Employees Compensation Prem', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('210091', 'Home Devt. Mutual Fund Payable', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('210100', 'Accounts Payable - Employee', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210110', 'Accounts Payable - Employee - Car Plan', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210225', 'Accounts Payable-Suppliers', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210230', 'Accounts Payable-Clients', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('210235', 'Accounts Payable-Others', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('210240', 'Accounts Payable- Dealer', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210250', 'Accounts Payable - Stale Checks', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('210300', 'Lease Liability-ROU', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('211000', 'GR/IR-Clearing', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('235000', 'Output Value Added Tax-Current', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('235010', 'Output Value Added Tax-Deferred', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('235020', 'Output Tax Clearing', 'liability', 'Current Liabilities', NULL, false, 'SAP subledger: Vendor'),
 ('235030', 'Withholding Tax Payable', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240071', 'Accrued Other Tax-EWT', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240072', 'Accrued other tax - Fringe Benefits Tax', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240073', 'Accrued FinalTax', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240074', 'Accrued Final Tax - Prom Notes', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240080', 'Accrued Other Tax - Corporate', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('240085', 'Accrued Other Tax-EWT - Toyota Wallet', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('245001', 'Accrued Interest Payable on Bank Loans', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('245002', 'Acc Int Pay-Ret PN', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('245004', 'Acc Int Pay - TMFNL USD', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('245006', 'Acc Int Pay-FRN', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('245021', 'Acc Int Pay - TMCC USD', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('246000', 'Accrued Other Expenses Payable', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('251001', 'Bank Loans-Long', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('251002', 'Notes Payable-Retail(Long)', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('251300', 'TMFNL Loans - Long', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('251301', 'TMFNL Loans - Short', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('251303', 'TMCC Loan - Short', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('251305', 'TMCC Loan - Long', 'liability', 'Current Liabilities', NULL, true, 'SAP subledger: Vendor'),
 ('260200', 'Accrued Severance Indemnity', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('260210', 'Reserve for Compensation', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('260340', 'Refundable Bid Bond Deposit', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('260400', 'Due to BSP', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('290000', 'Deposit for Future Subscription', 'liability', 'Current Liabilities', NULL, false, NULL),
 ('300000', 'Capital Stock', 'equity', 'Equity', NULL, false, NULL),
 ('340000', 'Retained Earnings - Unappropriated', 'equity', 'Equity', NULL, false, NULL),
 ('340005', 'Retained Earnings - Appropriated', 'equity', 'Equity', NULL, false, NULL),
 ('340020', 'Current Earnings', 'equity', 'Equity', NULL, false, NULL),
 ('350000', 'Actuarial Gain (Loss)', 'equity', 'Equity', NULL, false, NULL),
 ('410010', 'Commision Income - Travel Insurance', 'income', 'Revenue', NULL, false, NULL),
 ('410020', 'Commision Income - Fire/Property Insurance', 'income', 'Revenue', NULL, false, NULL),
 ('410030', 'Commision Income - Personal Accident', 'income', 'Revenue', NULL, false, NULL),
 ('410040', 'Commision Income - Credit Life Insurance', 'income', 'Revenue', NULL, false, NULL),
 ('410050', 'Commision Income - Motor Insurance', 'income', 'Revenue', NULL, false, NULL),
 ('410060', 'Commission Income - CGL', 'income', 'Revenue', NULL, false, NULL),
 ('410070', 'Commission Income - Fidelity', 'income', 'Revenue', NULL, false, NULL),
 ('410080', 'Commission Income - Surety Bond', 'income', 'Revenue', NULL, false, NULL),
 ('410090', 'Commission Income - Engineering', 'income', 'Revenue', NULL, false, NULL),
 ('410100', 'Commission Income - Replevin', 'income', 'Revenue', NULL, false, NULL),
 ('600000', 'Remuneration-Regular Employees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600250', 'Remuneration-Regular Employee-OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600500', 'Contribution to Retirement Fund', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600510', 'Bonuses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600520', 'Meals', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600530', 'Recreation', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600538', 'Staff-Benefits - Laundry Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600539', 'Staff-Benefits - Special Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600540', 'Staff-Benefits - Rice Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600541', 'Staff-Benefits - Medical Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600542', 'Staff-Benefits -Hazard Pay', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600543', 'Staff-Benefits - Teller''s Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600544', 'Staff-Benefits - Uniform /Clothing Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600545', 'Staff-Benefits -Christmas GC''s & Birthday Allow', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600546', 'Staff-Benefits - Multi-purpose Loan', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600547', 'Staff-Benefits - Assistance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600548', 'Staff-Benefits - Loyalty Awardee', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600549', 'Staff-Benefits (Others)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600550', 'Staff Benefits - Supplies', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600551', 'Staff Benefits - Meals', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600552', 'Staff Benefits - Transpo', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600553', 'Housing Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600554', 'Provision for Severance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600559', 'SSS, Med. & Employees Comp. (Co. Share)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600560', 'Home Devt. Mutual Fund (Co. share)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600561', 'Medical,Dental & Hospitalization', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600562', 'Officer Representation Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600563', 'OJT Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600564', 'Educational Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600565', 'Home Leave Allowance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600566', 'Staff-Benefits - Medical Allowance_FBT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600567', 'Staff-Benefits - Uniform/Clothing Allowance_FBT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600575', 'Hiring', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600580', 'Relocation Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600585', 'Training', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600595', 'Director''s & Committee Members'' Fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('600600', 'Fringe Benefit Tax', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('610000', 'Office Repairs & Maintenance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('610020', 'Car Repairs & Maintenance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('610100', 'Repairs&Maintenance-Office Peripherals', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('610200', 'Repairs&Maintenance-Computer Peripherals', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('610300', 'Repairs&Maintenance-Software Peripherals', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('611000', 'Electricity/Power', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('611012', 'Water', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('611022', 'Gasoline/Oil', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612000', 'Transportation - Air Fare', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612010', 'Transportation- Ferry Boat', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612040', 'Transportation - Taxi / Land fare', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612060', 'Transportation - Toll Fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612080', 'Transportation - Terminal fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612100', 'Transportation - Others', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612200', 'Foreign Transportation', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612240', 'Foreign Transportation - taxi Fare', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612280', 'Foreign Transportation - Toll fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612320', 'Foreign Transportation - Terminal fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612360', 'Foreign Transportation - Others', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612401', 'Hotel - Accomodation', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612430', 'Hotel - Per diem', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612451', 'Hotel Foreign - Accomodation', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612470', 'Hotel Foreign - Per diem', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612800', 'Telephone - Trunkline', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612801', 'Telephone - Direct Lines', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612802', 'Telephone - Inbound Calls', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612820', 'Cellphone Expenses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612840', 'Internet Expenses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612860', 'IT Network Communication Expenses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612880', 'Postage,Cable & Telegram', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612881', 'Postage,Cable & Telegram (Courier_Client)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612900', 'Insurance Exp. Office Premises & FFE', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612905', 'IT Insurance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612910', 'Car Insurance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('612920', 'Other Insurance Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620000', 'Office Rental', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620001', 'Warehouse Rent - Documents', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620002', 'Rental-Parking', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620003', 'Rent-Copier', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620004', 'Rental - Furniture', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('620013', 'Copier Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('630010', 'Commission Expense - Sales Partner', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('630011', 'Commission Expense - Caller', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('631000', 'Insurance License and Agency Fee', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('640001', 'Office Supplies (Stock items)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('640400', 'Office Supplies (Non Stock)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645050', 'Depreciation-Leasehold Rights & Impvts.', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645060', 'Depreciation-Leasehold Rights & Improvemen(LVA)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645070', 'Depreciation Expense-FFE', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645090', 'Depreciation-Computer Equipment', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645100', 'Amortization-Software', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645105', 'Amortization Expense-ROU', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645110', 'Depreciation-Company cars', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645115', 'Depreciation Expense - KINTO Company Car', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645120', 'Marketing Collateral - Items', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645130', 'Marketing Collateral - Forms', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645150', 'Media Placements', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645160', 'Other Marketing  - Sponsorship -Non Dealer', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645170', 'Other Marketing  - Sponsorship -Dealer', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645180', 'Other Marketing  - Digital Marketing / Website Mai', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645190', 'Other Marketing  - Events', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645200', 'Other Marketing  - Annual Reports', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645220', 'Other Marketing  - Dealer distributor activities', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645240', 'Other Marketing  - Other Charges', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645260', 'Other Promotional  - DOYA', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645280', 'Other Promotional  - Regular', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645285', 'Other Promotional  - Kizuna', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('645300', 'Other Promotional  - Others', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('650010', 'Bank Charges', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('651000', 'Legal Fees - Notarial Fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('651100', 'Legal Fees - Attorney''s fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652500', 'LITIGATION -Filing Fee', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652505', 'LITIGATION -Representation/Facilitation Fee', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652510', 'LITIGATION -Ex Parte', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652515', 'LITIGATION -Transportation', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652520', 'LITIGATION -Gasoline', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652525', 'LITIGATION -Notary Fee', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652540', 'LITIGATION -Others', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652700', 'LITIGATION -Filing Fee (Client''s Fee)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('652906', 'Collection Exp-Digital Representative (Insurance)', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('654300', 'LITIGATION -Hotel', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('654350', 'LITIGATION -Per Diem', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655000', 'Management & Other Prof. Fees-Others', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655100', 'Management & Other Prof. Fees-Shared Service', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655300', 'Management & Other Prof. Fees-IT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655500', 'Mngt. & Oth Prof.-TF', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655700', 'Contractual-Outsource Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('655900', 'Contractual-Outsource Services - OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656000', 'Security Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656100', 'Security Services-OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656200', 'Messengerial Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656300', 'Messengerial Services-OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656400', 'Janitorial Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656500', 'Janitorial Services-OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656600', 'Driver''s Services', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('656700', 'Driver''s Services OT', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658000', 'Auditing Fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658100', 'BSP Supervision Fees', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658200', 'Periodicals & Magazines', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658300', 'Entertainment', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658400', 'Hardware Maintenance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658500', 'Software Maintenance', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658600', 'Computer Software Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('658700', 'Computer Hardware Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('659100', 'Membership Fees & Dues -Regular', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('659150', 'Photocopy Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('659200', 'Freight Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('659400', 'Fines, Penalties & Other Charges', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('659700', 'Miscellaneous Expenses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('660000', 'Local Taxes & Licenses', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('660100', 'Other Taxes', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('661000', 'Documentary Stamps Expense', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('670000', 'Interest on Bank Loans', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('670250', 'Finance Charges-Fixed Rate Notes', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('670300', 'Int Exp Fixed Rate Notes', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('670400', 'Interest on Bonds Payable', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('670630', 'Finance Charges', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671000', 'Int Exp - Retail PN', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671200', 'Interest Expense on TMFNL Loans', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671205', 'Finance Charges-TMFNL Loan USD', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671206', 'Finance Charges-TMFNL Cross Currency Swap', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671207', 'Interest Expense on TMCC Loans', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671208', 'Finance Charges-TMCC Loan USD', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('671209', 'Finance Charges-TMCC Cross Currency Swap', 'expense', 'Operating Expenses', NULL, false, NULL),
 ('700020', 'Foreign Exchange Gain/(Loss)', 'income', 'Revenue', NULL, false, NULL),
 ('740000', 'Interest - Deposit with Banks', 'income', 'Revenue', NULL, false, NULL),
 ('740020', 'Interest Income - Retail PN', 'income', 'Revenue', NULL, false, NULL),
 ('750000', 'Profit/(Loss) from Assets Sold/Exchanged', 'income', 'Revenue', NULL, false, NULL),
 ('770300', 'Service Charges-Other Income', 'income', 'Revenue', NULL, false, NULL),
 ('770310', 'Service Fees - Credit Life', 'income', 'Revenue', NULL, false, NULL),
 ('770400', 'Miscellaneous Income', 'income', 'Revenue', NULL, false, NULL),
 ('800000', 'Provision for Income Tax', 'expense', 'Income Tax', NULL, false, NULL),
 ('800004', 'Provision for Income Tax-Final', 'expense', 'Income Tax', NULL, false, NULL),
 ('800005', 'Provision for Final Tax', 'expense', 'Income Tax', NULL, false, NULL),
 ('800006', 'Provision for Deferred Tax Asset', 'expense', 'Income Tax', NULL, false, NULL),
 ('860000', 'Asset Disposal Clearing Account', 'expense', 'Operating Expenses', NULL, false, NULL)
) AS v(code, name, account_type, fs_group, normal_balance, is_open_item, description)
ON CONFLICT (code) DO NOTHING;

-- Main Account master mirror of the new accounts (as 56_chart_of_accounts_masters.sql does for the reference chart).
INSERT INTO master_records(type_code, code, name, data, status, created_by)
SELECT 'main-account', a.code, a.name, jsonb_build_object('mainAccountCode', a.code, 'mainAccountName', a.name, 'description', COALESCE(a.description, a.name),
    'accountCategoryCode', CASE a.account_type WHEN 'asset' THEN 'AC-ASSET' WHEN 'liability' THEN 'AC-LIAB' WHEN 'equity' THEN 'AC-EQTY' WHEN 'income' THEN 'AC-INC' ELSE 'AC-EXP' END,
    'accountType', initcap(a.account_type), 'openEntry', CASE WHEN a.is_open_item THEN 'Yes' ELSE 'No' END, 'openEntryType', COALESCE(a.category, ''), 'fsGroup', a.fs_group),
  a.status, 'gl-sync'
FROM gl_accounts a WHERE a.parent_code IS NULL AND a.code ~ '^[0-9]{6}$'
  AND NOT EXISTS (SELECT 1 FROM master_records m WHERE m.type_code = 'main-account' AND lower(m.code) = lower(a.code) AND m.status <> 'deleted');

-- Account determination: the roles with one TISPH account named for them. The other roles keep the starter accounts
-- until Finance confirms them (premium receivable and the insurer and premium tax payables depend on the remittance
-- model; commission income is one account per line in the TISPH chart; CWT, EWT payable, supplier payable, accrued
-- expenses, commission expense and service fee income have two candidate accounts; the rest have none).
UPDATE app_settings s SET value = to_jsonb(v.code), updated_at = now()
FROM (VALUES ('accounting.account.cash_on_hand', '1101001', '100000'),
             ('accounting.account.cash_in_bank', '1102001', '106010'),
             ('accounting.account.petty_cash_fund', '1103001', '100010'),
             ('accounting.account.commission_receivable', '1203001', '110400'),
             ('accounting.account.employee_advances', '1205001', '113000'),
             ('accounting.account.input_vat', '1301001', '135000'),
             ('accounting.account.output_vat', '2204003', '235000'),
             ('accounting.account.client_refund_payable', '2205001', '210230'),
             ('accounting.account.bank_charges', '4401004', '650010'),
             ('accounting.account.interest_income', '3301001', '740000'),
             ('accounting.account.retained_earnings', '5101001', '340000'),
             ('accounting.account.current_year_pl', '5102001', '340020')) AS v(key, starter, code)
WHERE s.key = v.key AND s.value = to_jsonb(v.starter) AND s.updated_by IS NULL
  AND EXISTS (SELECT 1 FROM gl_accounts a WHERE a.code = v.code AND a.status = 'active');

-- The same accounts in the cash account per payment mode and the payable account per payee (e-wallet clearing, the
-- insurer, agent and supplier payables keep their starter accounts).
UPDATE app_settings SET value = value
    || CASE WHEN value->>'cash' = '1101001' THEN '{"cash": "100000"}'::jsonb ELSE '{}'::jsonb END
    || CASE WHEN value->>'check' = '1102001' THEN '{"check": "106010"}'::jsonb ELSE '{}'::jsonb END
    || CASE WHEN value->>'bank-transfer' = '1102001' THEN '{"bank-transfer": "106010"}'::jsonb ELSE '{}'::jsonb END
    || CASE WHEN value->>'card' = '1102001' THEN '{"card": "106010"}'::jsonb ELSE '{}'::jsonb END,
  updated_at = now()
 WHERE key = 'accounting.cash_account_by_payment_mode' AND updated_by IS NULL
   AND (value->>'cash' = '1101001' OR '1102001' IN (value->>'check', value->>'bank-transfer', value->>'card'));
UPDATE app_settings SET value = value
    || CASE WHEN value->>'Client' = '2205001' THEN '{"Client": "210230"}'::jsonb ELSE '{}'::jsonb END
    || CASE WHEN value->>'Customer' = '2205001' THEN '{"Customer": "210230"}'::jsonb ELSE '{}'::jsonb END,
  updated_at = now()
 WHERE key = 'accounting.payable_account_by_payee' AND updated_by IS NULL AND '2205001' IN (value->>'Client', value->>'Customer');

-- Tax codes book to the accounts of their roles.
UPDATE tax_codes SET gl_account = v.code, updated_at = now()
FROM (VALUES ('2204003', '235000'), ('1301001', '135000')) AS v(starter, code)
WHERE tax_codes.gl_account = v.starter AND tax_codes.updated_by IS NULL;

-- ---------------------------------------------------------------- FGA.06 Tax: VAT codes
-- The TISPH VAT codes next to the reference codes (the tax code settings keep the reference codes until Finance retires
-- them). Rates are percentages.
INSERT INTO tax_codes(code, description, tax_type, rate, gl_account, applies_to, payee_kind, sort_order, remarks, created_by)
SELECT v.code, v.description, 'VAT', v.rate, v.gl, v.applies, 'any', v.sort, 'TISPH VAT code (FGA.06)', 'seed'
FROM (VALUES ('I0', 'Input Tax 0%', 0, NULL, 'purchases', 51),
             ('I1', 'Input Tax 12% Goods', 12, '135000', 'purchases', 52),
             ('IX', 'Input Tax Exempt', 0, NULL, 'purchases', 53),
             ('O0', 'Zero-rated Sales', 0, NULL, 'sales', 54),
             ('O1', 'Output Tax 12% Sales', 12, '235000', 'sales', 55),
             ('OX', 'Output Tax Exempt', 0, NULL, 'sales', 56)) AS v(code, description, rate, gl, applies, sort)
WHERE NOT EXISTS (SELECT 1 FROM tax_codes t WHERE t.code = v.code);

-- ---------------------------------------------------------------- FGA.06 Tax: withholding tax codes
-- One code per ATC (the build's key): codes 38 (WI150) and 41 (WC160) repeat codes 24 and 31 and are left out. ATCs the
-- reference list has already keep their row; their TISPH code is noted in the remarks. WC140 (TISPH 10%) and WI140
-- (TISPH 5%) keep the reference rates until TISPH Finance confirms the rate (the reference splits them by threshold
-- with WC139 / WI139). The new ATCs are TISPH's payments, booked to the withholding tax payable account.
INSERT INTO tax_codes(code, description, tax_type, rate, atc, gl_account, applies_to, payee_kind, sort_order, remarks, created_by)
SELECT v.atc, v.description, 'EWT', v.rate, v.atc,
       (SELECT value #>> '{}' FROM app_settings WHERE key = 'accounting.account.wht_payable'), 'purchases', v.payee, 500 + v.tis::int,
       'TISPH tax code ' || v.tis || ' (FGA.06)', 'seed'
FROM (VALUES ('06', 'WC050', 'WC050[10%]CORP:Mgnt&Tech Cons.<720K', 10, 'corporate'),
             ('07', 'WC051', 'WC051[15%]CORP:Mgn''t&Tech Cons.>720K', 15, 'corporate'),
             ('14', 'WI050', 'WI050[5%]IND:Mgnt&Tech Cons.<3M', 5, 'individual'),
             ('16', 'WI070', 'WI070[5%]IND:Ins. Agents/Adj.<3M', 5, 'individual'),
             ('17', 'WI080', 'WI080[5%]-other recipient of talent fee', 5, 'individual'),
             ('18', 'WI090', 'WI090[5%]IND:Fees of Dir. not Emp<3M', 5, 'individual'),
             ('21', 'WI120', 'WI120[2%]IND:Prime Contractors/Subcon', 2, 'individual'),
             ('24', 'WI150', 'WI150[5%]IND:Med Service thru Hosp<3M', 5, 'individual'),
             ('33', 'WI051', 'WI051[10%]IND:Mgn''t&Tech Cons.>3M', 10, 'individual'),
             ('34', 'WI071', 'WI071[10%]IND:Ins. Agents/Adj.>3M', 10, 'individual'),
             ('35', 'WI081', 'WI081[10%]IND:RecipientTalent Fees>3M', 10, 'individual'),
             ('36', 'WI091', 'WI091[10%]IND:Fees of Dir. not Emp>3M', 10, 'individual'),
             ('37', 'WI141', 'WI141[5%]IND:MedPractitioners thru Part', 5, 'individual')) AS v(tis, atc, description, rate, payee)
WHERE NOT EXISTS (SELECT 1 FROM tax_codes t WHERE t.code = v.atc OR t.atc = v.atc);

UPDATE tax_codes SET remarks = v.remarks, updated_at = now()
FROM (VALUES ('WC010', 'TISPH tax code 01 (FGA.06)'), ('WC100', 'TISPH tax code 02 (FGA.06)'), ('WC011', 'TISPH tax code 03 (FGA.06)'),
             ('WC120', 'TISPH tax code 04 (FGA.06)'),
             ('WC140', 'TISPH tax code 05 (FGA.06) at 10%: the rate stays as listed until TISPH Finance confirms it'),
             ('WC158', 'TISPH tax code 09 (FGA.06)'), ('WI010', 'TISPH tax code 10 (FGA.06)'), ('WI100', 'TISPH tax code 19 (FGA.06)'),
             ('WI140', 'TISPH tax code 23 (FGA.06) at 5%: the rate stays as listed until TISPH Finance confirms it'),
             ('WI158', 'TISPH tax code 28 (FGA.06)'), ('WI160', 'TISPH tax code 30 (FGA.06)'), ('WC160', 'TISPH tax code 31 (FGA.06)'),
             ('WI011', 'TISPH tax code 32 (FGA.06)'), ('WI515', 'TISPH tax code 39 (FGA.06)'), ('WC515', 'TISPH tax code 40 (FGA.06)')) AS v(atc, remarks)
WHERE tax_codes.atc = v.atc AND tax_codes.remarks IS NULL AND tax_codes.updated_by IS NULL;
