-- TISPH report layouts in the report catalogue (CR-14 operations, CR-15 cash control, CR-16 finance and general ledger;
-- queries in src/modules/reports/tisphQueries.js), each for the broker role and the TISPH roles that use it. Idempotent:
-- a report is added once; changes made on the screen are kept.

INSERT INTO report_definitions(code, name, category, description, screen, query_name, parameters, default_columns, roles, permission, sort_order) VALUES
 -- CR-16 (TIS-BRD-RPT-FGA-01, FGA-02)
 ('tisph-fs-by-version', 'Financial Statement by Version', 'financial', 'The trial balance grouped by the lines of a financial statement version (TIS01 local FS, TIS02 balance sheet and income statement, TIS03 budget): opening balance, movement of the period, closing balance, year to date and the same window a year earlier; lines with nothing to show are left out.',
  'Reports > All Reports > Financial Statement by Version', 'fsByVersion',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["FS Line","GL Account"],"default":"FS Line"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"FsVersion":{"type":"string","title":"FS Version","description":"financial statement version (the default version when empty)","x-options":"fs_versions"},"Account":{"type":"string","title":"GL Account","description":"account code or its first digits","x-options":"gl_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"statement","label":"Statement","type":"text"},{"key":"section","label":"Section","type":"text"},{"key":"caption","label":"FS Line","type":"text"},{"key":"accountCode","label":"GL Account","type":"text"},{"key":"accountName","label":"Account Name","type":"text"},{"key":"openingBalance","label":"Opening","type":"money"},{"key":"periodMovement","label":"Movement","type":"money"},{"key":"closingBalance","label":"Closing","type":"money"},{"key":"yearToDate","label":"Year to Date","type":"money"},{"key":"priorYearToDate","label":"Prior Year to Date","type":"money"}]'::jsonb,
  ARRAY['accounting', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 600),
 -- CR-16 (TIS-BRD-RPT-FGA-03)
 ('tisph-daily-gl-balance', 'Daily GL Balance', 'financial', 'The beginning balance and the balance at the end of each calendar day from From Date (up to 31 days), per GL account grouped by the lines of the financial statement version.',
  'Reports > All Reports > Daily GL Balance', 'dailyGlBalance',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["GL Account","FS Line"],"default":"GL Account"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"FsVersion":{"type":"string","title":"FS Version","description":"financial statement version (the default version when empty)","x-options":"fs_versions"},"Account":{"type":"string","title":"GL Account","description":"account code or its first digits","x-options":"gl_accounts"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"statement","label":"Statement","type":"text"},{"key":"section","label":"Section","type":"text"},{"key":"caption","label":"FS Line","type":"text"},{"key":"accountCode","label":"GL Account","type":"text"},{"key":"accountName","label":"Account Name","type":"text"},{"key":"beginningBalance","label":"Beginning Balance","type":"money"},{"key":"d01","label":"1","type":"money","pdf":false},{"key":"d02","label":"2","type":"money","pdf":false},{"key":"d03","label":"3","type":"money","pdf":false},{"key":"d04","label":"4","type":"money","pdf":false},{"key":"d05","label":"5","type":"money","pdf":false},{"key":"d06","label":"6","type":"money","pdf":false},{"key":"d07","label":"7","type":"money","pdf":false},{"key":"d08","label":"8","type":"money","pdf":false},{"key":"d09","label":"9","type":"money","pdf":false},{"key":"d10","label":"10","type":"money","pdf":false},{"key":"d11","label":"11","type":"money","pdf":false},{"key":"d12","label":"12","type":"money","pdf":false},{"key":"d13","label":"13","type":"money","pdf":false},{"key":"d14","label":"14","type":"money","pdf":false},{"key":"d15","label":"15","type":"money","pdf":false},{"key":"d16","label":"16","type":"money","pdf":false},{"key":"d17","label":"17","type":"money","pdf":false},{"key":"d18","label":"18","type":"money","pdf":false},{"key":"d19","label":"19","type":"money","pdf":false},{"key":"d20","label":"20","type":"money","pdf":false},{"key":"d21","label":"21","type":"money","pdf":false},{"key":"d22","label":"22","type":"money","pdf":false},{"key":"d23","label":"23","type":"money","pdf":false},{"key":"d24","label":"24","type":"money","pdf":false},{"key":"d25","label":"25","type":"money","pdf":false},{"key":"d26","label":"26","type":"money","pdf":false},{"key":"d27","label":"27","type":"money","pdf":false},{"key":"d28","label":"28","type":"money","pdf":false},{"key":"d29","label":"29","type":"money","pdf":false},{"key":"d30","label":"30","type":"money","pdf":false},{"key":"d31","label":"31","type":"money","pdf":false},{"key":"endingBalance","label":"Ending Balance","type":"money"}]'::jsonb,
  ARRAY['accounting', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 610),
 -- CR-15 (TIS-BRD-RPT-CCD-01)
 ('tisph-payment-summary', 'Payment Summary', 'financial', 'Payments received in the period with payment and posting dates, contract, reference, client, amount, bank, cheque, channel, receipt and posting status, by user or payment method.',
  'Reports > All Reports > Payment Summary', 'paymentSummary',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","User","Payment Method","Posting Status"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"paymentDate","label":"Payment Date","type":"date"},{"key":"postingDate","label":"Posting Date","type":"date"},{"key":"receiptNumber","label":"OR No.","type":"text"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"referenceNo","label":"Reference","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"amount","label":"Amount","type":"money"},{"key":"bank","label":"Bank","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"paymentMethod","label":"Payment Method","type":"text"},{"key":"channel","label":"Channel","type":"text"},{"key":"status","label":"Status","type":"text"},{"key":"user","label":"User","type":"text"},{"key":"postingStatus","label":"Posting Status","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 620),
 -- CR-15 (TIS-BRD-RPT-CCD-02)
 ('tisph-daily-reversals', 'Daily Reversals', 'financial', 'Receipts reversed and cheques bounced (DAIF and other reasons) in the period, with sub-totals per bank account: reason, reversal and actual dates, contract, client, amount, cheque, method and user.',
  'Reports > All Reports > Daily Reversals', 'dailyReversals',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Bank Account","Overall","Kind"],"default":"Bank Account"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"kind","label":"Kind","type":"text"},{"key":"reference","label":"Reference","type":"text"},{"key":"reason","label":"Reason","type":"text"},{"key":"reversalDate","label":"Reversal Date","type":"date"},{"key":"actualDate","label":"Actual Date","type":"date"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"amount","label":"Amount","type":"money"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"paymentMethod","label":"Method","type":"text"},{"key":"user","label":"User","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 630),
 -- CR-15 (TIS-BRD-RPT-CCD-03)
 ('tisph-pdc-encoded', 'PDC Encoded Summary', 'financial', 'Post-dated cheques encoded in the period by warehouse bank and user: contract, client, transaction and due dates, cheque and bank, amount, amortisation and contract state.',
  'Reports > All Reports > PDC Encoded Summary', 'pdcEncoded',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Warehouse Bank","User","Overall"],"default":"Warehouse Bank"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Status":{"type":"string","title":"Status","enum":["Received at TIS","Forwarded","Warehoused","Deposited","Cleared","Bounced","Replaced","Cancellation pending","Cancelled","Returned"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"encodedDate","label":"Encoded","type":"date"},{"key":"transactionDate","label":"Received","type":"date"},{"key":"pdcNumber","label":"PDC No.","type":"text"},{"key":"setNumber","label":"Set No.","type":"text"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"bank","label":"Bank","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"chequeDate","label":"Cheque Date","type":"date"},{"key":"amount","label":"Amount","type":"money"},{"key":"amortisation","label":"Amortisation","type":"text"},{"key":"warehouse","label":"Warehouse Bank","type":"text"},{"key":"status","label":"Status","type":"text"},{"key":"contractState","label":"Contract State","type":"text"},{"key":"encodedBy","label":"Encoded By","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 640),
 -- CR-15 (TIS-BRD-RPT-CCD-04)
 ('tisph-pdc-cancelled', 'PDC Cancelled Summary', 'financial', 'Post-dated cheques cancelled in the period with the reason, who asked and who approved, and the totals.',
  'Reports > All Reports > PDC Cancelled Summary', 'pdcCancelled',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Reason"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"cancelledDate","label":"Cancelled","type":"date"},{"key":"pdcNumber","label":"PDC No.","type":"text"},{"key":"setNumber","label":"Set No.","type":"text"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"bank","label":"Bank","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"chequeDate","label":"Cheque Date","type":"date"},{"key":"amount","label":"Amount","type":"money"},{"key":"amortisation","label":"Amortisation","type":"text"},{"key":"warehouse","label":"Warehouse Bank","type":"text"},{"key":"reason","label":"Reason","type":"text"},{"key":"remarks","label":"Remarks","type":"text"},{"key":"requestedBy","label":"Requested By","type":"text"},{"key":"cancelledBy","label":"Approved By","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 650),
 -- CR-15 (TIS-BRD-RPT-CCD-05)
 ('tisph-pdc-maturing', 'PDC Maturing', 'financial', 'Open post-dated cheques dated in the period: instalment date, end of term, amount, amortisation, cheque status and suspension (held for cancellation, remittance on hold), by product or warehouse bank.',
  'Reports > All Reports > PDC Maturing', 'pdcMaturing',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Product","Warehouse Bank"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Status":{"type":"string","title":"Status","enum":["Received at TIS","Forwarded","Warehoused","Deposited","Cleared","Bounced","Replaced","Cancellation pending","Cancelled","Returned"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"product","label":"Product","type":"text"},{"key":"pdcNumber","label":"PDC No.","type":"text"},{"key":"setNumber","label":"Set No.","type":"text"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"bank","label":"Bank","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"chequeDate","label":"Cheque Date","type":"date"},{"key":"amount","label":"Amount","type":"money"},{"key":"amortisation","label":"Amortisation","type":"text"},{"key":"warehouse","label":"Warehouse Bank","type":"text"},{"key":"status","label":"Status","type":"text"},{"key":"instalmentDate","label":"Instalment Date","type":"date"},{"key":"endOfTerm","label":"End of Term","type":"date"},{"key":"suspension","label":"Suspension","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 660),
 -- CR-15 (TIS-BRD-RPT-CCD-05)
 ('tisph-pdc-maturing-matrix', 'PDC Maturing by Product and Warehouse Bank', 'financial', 'The open post-dated cheques dated in the period counted and totalled per product and warehouse bank.',
  'Reports > All Reports > PDC Maturing Matrix', 'pdcMaturingMatrix',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Product and Warehouse Bank","Product","Warehouse Bank"],"default":"Product and Warehouse Bank"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"product","label":"Product","type":"text"},{"key":"warehouse","label":"Warehouse Bank","type":"text"},{"key":"cheques","label":"Cheques","type":"integer"},{"key":"amount","label":"Amount","type":"money"},{"key":"heldForCancellation","label":"Held","type":"integer"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 670),
 -- CR-15 (TIS-BRD-RPT-CCD-06)
 ('tisph-pdc-history', 'PDC History Log', 'financial', 'Every action on the post-dated cheques in the period (encoding, forwarding, partner receipt, deposit, clearing, bounce, cancellation, replacement, return) per cheque or contract.',
  'Reports > All Reports > PDC History Log', 'pdcHistory',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Cheque","Contract"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"eventAt","label":"When","type":"datetime"},{"key":"pdcNumber","label":"PDC No.","type":"text"},{"key":"chequeNumber","label":"Cheque No.","type":"text"},{"key":"bank","label":"Bank","type":"text"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"event","label":"Action","type":"text"},{"key":"statusAfter","label":"Status After","type":"text"},{"key":"detail","label":"Detail","type":"text"},{"key":"user","label":"User","type":"text"},{"key":"amount","label":"Amount","type":"money","total":false}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 680),
 -- CR-15 (TIS-BRD-RPT-CCD-07)
 ('tisph-pdc-acknowledgements', 'Acknowledgement Receipts of Received PDCs', 'financial', 'The sets of post-dated cheques received in the period, each with its acknowledgement receipt (printed from the set); no journal is posted when a cheque is received.',
  'Reports > All Reports > PDC Acknowledgement Receipts', 'pdcAcknowledgements',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Payable To"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"setNumber","label":"Set No.","type":"text"},{"key":"receivedDate","label":"Received","type":"date"},{"key":"policyNumber","label":"Contract","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"insurer","label":"Insurance Partner","type":"text"},{"key":"payableTo","label":"Payable To","type":"text"},{"key":"cheques","label":"Cheques","type":"integer"},{"key":"amount","label":"Amount","type":"money"},{"key":"receivedBy","label":"Received By","type":"text"},{"key":"status","label":"Status","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:pdc', 690),
 -- CR-14 (TIS-BRD-RPT-OPS-05, FGA-PR-02)
 ('tisph-net-remittance-fully-paid', 'Net Remittance - Fully Paid', 'operational', 'Broker-billed policies fully paid in the period, per insurer: gross premium, commission, remitting rate, net remittance, taxes and the remittance that carries them.',
  'Reports > All Reports > Net Remittance - Fully Paid', 'netRemittanceFullyPaid',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Principal Insurer","Overall"],"default":"Principal Insurer"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"inceptionDate","label":"Inception","type":"date"},{"key":"grossPremium","label":"Gross Premium","type":"money"},{"key":"commission","label":"Commission","type":"money"},{"key":"remittingRate","label":"Remitting Rate %","type":"number","total":false},{"key":"netRemittance","label":"Net Remittance","type":"money"},{"key":"taxes","label":"Taxes","type":"money"},{"key":"paidToDate","label":"Paid to Date","type":"money"},{"key":"outstanding","label":"Outstanding","type":"money"},{"key":"lastPaymentDate","label":"Last Payment","type":"date"},{"key":"paymentStatus","label":"Payment Status","type":"text"},{"key":"remittanceNumber","label":"Remittance No.","type":"text"},{"key":"remittanceStatus","label":"Remittance Status","type":"text"}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 700),
 -- CR-14 (TIS-BRD-RPT-OPS-06, FGA-PR-03)
 ('tisph-net-remittance-partially-paid', 'Net Remittance - Partially Paid', 'operational', 'Broker-billed policies with a payment in the period and a balance still open, per insurer: the fully paid layout plus the amount paid to date and the outstanding balance.',
  'Reports > All Reports > Net Remittance - Partially Paid', 'netRemittancePartiallyPaid',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Principal Insurer","Overall"],"default":"Principal Insurer"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"inceptionDate","label":"Inception","type":"date"},{"key":"grossPremium","label":"Gross Premium","type":"money"},{"key":"commission","label":"Commission","type":"money"},{"key":"remittingRate","label":"Remitting Rate %","type":"number","total":false},{"key":"netRemittance","label":"Net Remittance","type":"money"},{"key":"taxes","label":"Taxes","type":"money"},{"key":"paidToDate","label":"Paid to Date","type":"money"},{"key":"outstanding","label":"Outstanding","type":"money"},{"key":"lastPaymentDate","label":"Last Payment","type":"date"},{"key":"paymentStatus","label":"Payment Status","type":"text"},{"key":"remittanceNumber","label":"Remittance No.","type":"text"},{"key":"remittanceStatus","label":"Remittance Status","type":"text"}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 710),
 -- CR-14 (TIS-BRD-RPT-OPS-04)
 ('tisph-premium-payment-status', 'Premium Report by Payment Status', 'operational', 'Broker-billed policies incepting in the period as fully paid, partially paid, cancelled or pending, with the official receipts and the remittance batch.',
  'Reports > All Reports > Premium Report', 'premiumPaymentStatus',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Payment Status","Overall","Principal Insurer"],"default":"Payment Status"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"inceptionDate","label":"Inception","type":"date"},{"key":"client","label":"Client","type":"text"},{"key":"insurer","label":"Insurer","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"premium","label":"Premium","type":"money"},{"key":"paid","label":"Paid","type":"money"},{"key":"outstanding","label":"Outstanding","type":"money"},{"key":"paymentStatus","label":"Payment Status","type":"text"},{"key":"receiptNumbers","label":"OR No.","type":"text"},{"key":"remittanceBatch","label":"Remittance Batch","type":"text"},{"key":"remittanceStatus","label":"Remittance Status","type":"text"}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 720),
 -- CR-14 (TIS-BRD-RPT-OPS-12, FGA-BR-03, FGA-BR-04)
 ('tisph-insufficient-payments', 'Insufficient Payments', 'financial', 'Bank payments of the period below what the policy owed (beyond the matching tolerance): expected premium, amount paid, shortfall, date, bank account and what the policy still owes.',
  'Reports > All Reports > Insufficient Payments', 'insufficientPayments',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Principal Insurer","Bank Account"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"paidOn","label":"Paid","type":"date"},{"key":"reference","label":"Reference","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"insurer","label":"Insurer","type":"text"},{"key":"expectedPremium","label":"Expected","type":"money"},{"key":"paid","label":"Paid","type":"money"},{"key":"shortfall","label":"Shortfall","type":"money"},{"key":"stillOwed","label":"Still Owed","type":"money"},{"key":"bankAccount","label":"Bank Account","type":"text"},{"key":"channel","label":"Channel","type":"text"},{"key":"batch","label":"Batch","type":"text"},{"key":"receiptNumber","label":"OR No.","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 730),
 -- CR-14 (TIS-BRD-RPT-OPS-13, FGA-BR-05 to BR-07)
 ('tisph-overpayments', 'Overpayments', 'financial', 'Payments of the period above what the policy owed, held On Account: the excess, what is still held and whether it was allocated or refunded.',
  'Reports > All Reports > Overpayments', 'overpayments',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Overall","Status","Channel"],"default":"Overall"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Status":{"type":"string","title":"Status","enum":["Open","Allocated","Refunded"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"receivedDate","label":"Received","type":"date"},{"key":"reference","label":"Receipt / Reference","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"insurer","label":"Insurer","type":"text"},{"key":"expectedPremium","label":"Expected","type":"money"},{"key":"paid","label":"Paid","type":"money"},{"key":"excess","label":"Excess","type":"money"},{"key":"heldBalance","label":"Still Held","type":"money"},{"key":"status","label":"Status","type":"text"},{"key":"channel","label":"Channel","type":"text"},{"key":"allocateBy","label":"Allocate By","type":"date"},{"key":"refundReason","label":"Refund Reason","type":"text"}]'::jsonb,
  ARRAY['accounting', 'tis-ccd-pdu', 'tis-ccd-pdc', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 740),
 -- CR-14 (TIS-BRD-RPT-OPS-10)
 ('tisph-invoice-tracker', 'Invoice Tracker', 'operational', 'The premium bills of the period not due, overdue, partially paid and paid, aged 1-15, 16-30, 31-60 and over 60 days overdue as of To Date, with the count of overpayments held On Account.',
  'Reports > All Reports > Invoice Tracker', 'invoiceTracker',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Ageing","Status","Payment State","Overall"],"default":"Ageing"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Client":{"type":"string","title":"Client","description":"id, code or name","x-options":"clients"},"Status":{"type":"string","title":"Status","enum":["Not due","Overdue","Paid"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"billNumber","label":"Bill No.","type":"text"},{"key":"billDate","label":"Billed","type":"date"},{"key":"dueDate","label":"Due","type":"date"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Client","type":"text"},{"key":"insurer","label":"Insurer","type":"text"},{"key":"amount","label":"Amount","type":"money"},{"key":"paid","label":"Paid","type":"money"},{"key":"balance","label":"Balance","type":"money"},{"key":"paymentState","label":"Payment State","type":"text"},{"key":"status","label":"Status","type":"text"},{"key":"ageBucket","label":"Ageing","type":"text"},{"key":"days","label":"Days Overdue","type":"integer","total":false}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 750),
 -- CR-14 (TIS-BRD-RPT-OPS-08)
 ('tisph-soa-per-partner', 'Statement of Account per Insurance Partner', 'operational', 'The broker-billed policies of each insurance partner incepting in the period: the premium section (gross, net, VAT, DST, LGT), the remitting section (net remitting, collected, remittance) and the commission section (commission, VAT, withholding tax).',
  'Reports > All Reports > Statement of Account per Insurance Partner', 'soaPerPartner',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Principal Insurer","Product","Overall"],"default":"Principal Insurer"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Product":{"type":"string","title":"Product","description":"id, code or name","x-options":"products"},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"client","label":"Insured","type":"text"},{"key":"product","label":"Product","type":"text"},{"key":"inceptionDate","label":"Inception","type":"date"},{"key":"grossPremium","label":"Gross Premium","type":"money"},{"key":"netPremium","label":"Net Premium","type":"money"},{"key":"vat","label":"VAT","type":"money"},{"key":"dst","label":"DST","type":"money"},{"key":"lgt","label":"LGT","type":"money"},{"key":"netRemitting","label":"Net Remitting","type":"money"},{"key":"collected","label":"Collected","type":"money"},{"key":"remittanceNumber","label":"Remittance No.","type":"text"},{"key":"remittanceStatus","label":"Remittance Status","type":"text"},{"key":"commission","label":"Commission","type":"money"},{"key":"commissionVat","label":"Commission VAT","type":"money"},{"key":"commissionEwt","label":"EWT","type":"money"}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 760),
 -- CR-14 (TIS-BRD-RPT-OPS-09)
 ('tisph-reconciliation-schedule', 'Reconciliation Schedule', 'operational', 'Each line of the insurance partners statements of the period against the broker records: gross premium, commission and amount paid on both sides with the differences and the match status.',
  'Reports > All Reports > Reconciliation Schedule', 'reconciliationSchedule',
  '{"type":"object","required":["ReportCriteria"],"properties":{"ReportCriteria":{"type":"string","title":"Report Criteria","enum":["Principal Insurer","Status","Overall"],"default":"Principal Insurer"},"FromDate":{"type":"string","format":"date","title":"From Date"},"ToDate":{"type":"string","format":"date","title":"To Date"},"Company":{"type":"string","title":"Company (principal insurer)","description":"id, code or name","x-options":"insurance_companies"},"Status":{"type":"string","title":"Status","enum":["Matched","Unmatched","Difference"]},"format":{"type":"string","enum":["csv","xlsx","pdf"],"default":"xlsx","title":"File format (generate only)"},"period":{"type":"string","enum":["today","yesterday","last-7-days","last-30-days","month-to-date","previous-month","year-to-date"],"title":"Relative period (schedules; used when no dates are given)"}}}'::jsonb,
  '[{"key":"insurer","label":"Insurer","type":"text"},{"key":"statementNumber","label":"Statement No.","type":"text"},{"key":"statementReference","label":"Partner Reference","type":"text"},{"key":"periodTo","label":"Period To","type":"date"},{"key":"lineNo","label":"Line","type":"integer","total":false},{"key":"policyNumber","label":"Policy No.","type":"text"},{"key":"insuredName","label":"Insured","type":"text"},{"key":"partnerGross","label":"Partner Gross","type":"money"},{"key":"tisphGross","label":"TISPH Gross","type":"money"},{"key":"grossDifference","label":"Gross Difference","type":"money"},{"key":"partnerCommission","label":"Partner Commission","type":"money"},{"key":"tisphCommission","label":"TISPH Commission","type":"money"},{"key":"commissionDifference","label":"Commission Difference","type":"money"},{"key":"partnerPaid","label":"Partner Paid","type":"money"},{"key":"tisphAmount","label":"TISPH Amount","type":"money"},{"key":"paidDifference","label":"Paid Difference","type":"money"},{"key":"status","label":"Status","type":"text"},{"key":"statementStatus","label":"Statement Status","type":"text"}]'::jsonb,
  ARRAY['operations', 'accounting', 'tis-ops-officer', 'tis-ops-unit-head', 'tis-ccd-bp', 'tis-ccd-recon', 'tis-finance', 'tis-general-manager', 'tis-it-admin']::text[], 'read:reports', 770)
ON CONFLICT (code) DO NOTHING;
