import SvgArrow from "../../../assets/icons/SvgArrow";

export const BankAccountService = {
    getBankAccountsData() {
        return [
            {
                id: 'BA001',
                accountCode: 'ACC-BDO-001',
                accountName: 'INXT Insurance Brokers Inc. - Operating Account',
                bankName: 'BDO Unibank, Inc.',
                bankCode: 'BDO',
                accountNumber: '001234567890',
                accountType: 'Current Account',
                currency: 'THB',
                branch: 'Makati Main Branch',
                branchCode: 'MAK001',
                swiftCode: 'BNORPHMM',
                currentBalance: '₱5,250,000.00',
                status: 'Active',
                openingDate: '01 JAN 2020',
                contactPerson: 'Maria Santos',
                contactNumber: '+63 2 8840 7000',
                email: 'corporate@bdo.com.ph',
                purpose: 'Main Operating Account',
                signatories: 'Juan Dela Cruz, Maria Santos',
                actions: <SvgArrow/>
            },
            {
                id: 'BA002',
                accountCode: 'ACC-BPI-001',
                accountName: 'INXT Insurance Brokers Inc. - Premium Collection',
                bankName: 'Bangkok Bank',
                bankCode: 'BPI',
                accountNumber: '3456789012',
                accountType: 'Savings Account',
                currency: 'THB',
                branch: 'Ayala Avenue Branch',
                branchCode: 'AYA001',
                swiftCode: 'BOPIPHMM',
                currentBalance: '₱12,850,000.00',
                status: 'Active',
                openingDate: '01 FEB 2020',
                contactPerson: 'Roberto Reyes',
                contactNumber: '+63 2 889 10000',
                email: 'business@bpi.com.ph',
                purpose: 'Premium Collections',
                signatories: 'Juan Dela Cruz, Roberto Reyes',
                actions: <SvgArrow/>
            },
            {
                id: 'BA003',
                accountCode: 'ACC-MBTC-001',
                accountName: 'INXT Insurance Brokers Inc. - Claims Settlement',
                bankName: 'Metrobank',
                bankCode: 'MBTC',
                accountNumber: '789012345678',
                accountType: 'Current Account',
                currency: 'THB',
                branch: 'Ortigas Center Branch',
                branchCode: 'ORT001',
                swiftCode: 'MBTCPHMM',
                currentBalance: '₱3,500,000.00',
                status: 'Active',
                openingDate: '15 MAR 2020',
                contactPerson: 'Ana Garcia',
                contactNumber: '+63 2 8898 8788',
                email: 'corporate@metrobank.com.ph',
                purpose: 'Claims Settlement Account',
                signatories: 'Maria Santos, Ana Garcia',
                actions: <SvgArrow/>
            },
            {
                id: 'BA004',
                accountCode: 'ACC-BDO-002',
                accountName: 'INXT Insurance Brokers Inc. - USD Account',
                bankName: 'BDO Unibank, Inc.',
                bankCode: 'BDO',
                accountNumber: '002345678901',
                accountType: 'Foreign Currency Account',
                currency: 'USD',
                branch: 'BGC Branch',
                branchCode: 'BGC001',
                swiftCode: 'BNORPHMM',
                currentBalance: '$125,000.00',
                status: 'Active',
                openingDate: '01 JUN 2020',
                contactPerson: 'Pedro Gonzales',
                contactNumber: '+63 2 8840 7000',
                email: 'forex@bdo.com.ph',
                purpose: 'International Transactions',
                signatories: 'Juan Dela Cruz, Pedro Gonzales',
                actions: <SvgArrow/>
            },
            {
                id: 'BA005',
                accountCode: 'ACC-UBP-001',
                accountName: 'INXT Insurance Brokers Inc. - Payroll Account',
                bankName: 'Krung Thai Bank',
                bankCode: 'UBP',
                accountNumber: '456789012345',
                accountType: 'Payroll Account',
                currency: 'THB',
                branch: 'Paseo de Roxas Branch',
                branchCode: 'PDR001',
                swiftCode: 'KRTHTHBK',
                currentBalance: '₱1,850,000.00',
                status: 'Active',
                openingDate: '01 JUL 2020',
                contactPerson: 'Carmen Bautista',
                contactNumber: '+63 2 8841 8000',
                email: 'payroll@unionbank.ph',
                purpose: 'Employee Payroll',
                signatories: 'Maria Santos, Carmen Bautista',
                actions: <SvgArrow/>
            },
            {
                id: 'BA006',
                accountCode: 'ACC-SBC-001',
                accountName: 'INXT Insurance Brokers Inc. - Trust Account',
                bankName: 'Security Bank Corporation',
                bankCode: 'SBC',
                accountNumber: '678901234567',
                accountType: 'Trust Account',
                currency: 'THB',
                branch: 'Makati Avenue Branch',
                branchCode: 'MAV001',
                swiftCode: 'SETCPHMM',
                currentBalance: '₱8,200,000.00',
                status: 'Active',
                openingDate: '01 SEP 2020',
                contactPerson: 'Miguel Torres',
                contactNumber: '+63 2 8887 9188',
                email: 'trust@securitybank.com.ph',
                purpose: 'Client Premium Trust',
                signatories: 'Juan Dela Cruz, Miguel Torres',
                actions: <SvgArrow/>
            },
            {
                id: 'BA007',
                accountCode: 'ACC-LAND-001',
                accountName: 'INXT Insurance Brokers Inc. - Reserve Fund',
                bankName: 'Kasikorn Bank',
                bankCode: 'LAND',
                accountNumber: '890123456789',
                accountType: 'Time Deposit',
                currency: 'THB',
                branch: 'Manila Main Branch',
                branchCode: 'MNL001',
                swiftCode: 'TLBPPHMM',
                currentBalance: '₱10,000,000.00',
                status: 'Active',
                openingDate: '01 NOV 2020',
                contactPerson: 'Elena Martinez',
                contactNumber: '+63 2 8405 7000',
                email: 'timedeposit@landbank.com.ph',
                purpose: 'Reserve Fund',
                signatories: 'Juan Dela Cruz, Maria Santos',
                maturityDate: '01 NOV 2025',
                interestRate: '4.5% p.a.',
                actions: <SvgArrow/>
            },
            {
                id: 'BA008',
                accountCode: 'ACC-PNB-001',
                accountName: 'INXT Insurance Brokers Inc. - Commission Account',
                bankName: 'Siam Commercial Bank',
                bankCode: 'PNB',
                accountNumber: '234567890123',
                accountType: 'Current Account',
                currency: 'THB',
                branch: 'Escolta Branch',
                branchCode: 'ESC001',
                swiftCode: 'PNBMPHMM',
                currentBalance: '₱4,750,000.00',
                status: 'Active',
                openingDate: '01 DEC 2020',
                contactPerson: 'Carlos Mendoza',
                contactNumber: '+63 2 8573 8888',
                email: 'corporate@pnb.com.ph',
                purpose: 'Commission Receipts',
                signatories: 'Roberto Reyes, Carlos Mendoza',
                actions: <SvgArrow/>
            },
            {
                id: 'BA009',
                accountCode: 'ACC-CHINA-001',
                accountName: 'INXT Insurance Brokers Inc. - Investment Account',
                bankName: 'ChinaBank',
                bankCode: 'CHINA',
                accountNumber: '345678901234',
                accountType: 'Investment Account',
                currency: 'THB',
                branch: 'Binondo Main Branch',
                branchCode: 'BIN001',
                swiftCode: 'CHBKPHMM',
                currentBalance: '₱15,000,000.00',
                status: 'Active',
                openingDate: '01 JAN 2021',
                contactPerson: 'Teresa Aquino',
                contactNumber: '+63 2 8924 2388',
                email: 'investment@chinabank.ph',
                purpose: 'Investment Portfolio',
                signatories: 'Juan Dela Cruz, Teresa Aquino',
                actions: <SvgArrow/>
            },
            {
                id: 'BA010',
                accountCode: 'ACC-RCBC-001',
                accountName: 'INXT Insurance Brokers Inc. - Escrow Account',
                bankName: 'RCBC (Rizal Commercial Banking Corporation)',
                bankCode: 'RCBC',
                accountNumber: '567890123456',
                accountType: 'Escrow Account',
                currency: 'THB',
                branch: 'Gil Puyat Branch',
                branchCode: 'GIL001',
                swiftCode: 'RCBCPHMM',
                currentBalance: '₱6,800,000.00',
                status: 'Active',
                openingDate: '01 MAR 2021',
                contactPerson: 'Jose Rizal',
                contactNumber: '+63 2 8894 9000',
                email: 'escrow@rcbc.com.ph',
                purpose: 'Escrow Services',
                signatories: 'Maria Santos, Jose Rizal',
                actions: <SvgArrow/>
            },
            {
                id: 'BA011',
                accountCode: 'ACC-EWB-001',
                accountName: 'INXT Insurance Brokers Inc. - Digital Wallet',
                bankName: 'EastWest Bank',
                bankCode: 'EWB',
                accountNumber: '789012345678',
                accountType: 'Digital Account',
                currency: 'THB',
                branch: 'Digital Banking',
                branchCode: 'DIG001',
                swiftCode: 'EWBCPHMM',
                currentBalance: '₱850,000.00',
                status: 'Active',
                openingDate: '01 JUN 2021',
                contactPerson: 'Andres Bonifacio',
                contactNumber: '+63 2 8888 1700',
                email: 'digital@eastwestbank.com.ph',
                purpose: 'Online Transactions',
                signatories: 'Pedro Gonzales, Andres Bonifacio',
                actions: <SvgArrow/>
            },
            {
                id: 'BA012',
                accountCode: 'ACC-DBP-001',
                accountName: 'INXT Insurance Brokers Inc. - Government Transactions',
                bankName: 'Government Savings Bank Thailand',
                bankCode: 'DBP',
                accountNumber: '901234567890',
                accountType: 'Government Account',
                currency: 'THB',
                branch: 'Sen. Gil Puyat Branch',
                branchCode: 'SGP001',
                swiftCode: 'GSBATHBK',
                currentBalance: '₱2,200,000.00',
                status: 'Inactive',
                openingDate: '01 AUG 2021',
                closedDate: '31 DEC 2024',
                contactPerson: 'Emilio Aguinaldo',
                contactNumber: '+63 2 8818 9511',
                email: 'government@dbp.ph',
                purpose: 'Government Insurance',
                signatories: 'Juan Dela Cruz, Emilio Aguinaldo',
                actions: <SvgArrow/>
            }
        ];
    },

    getBankAccountsSummary() {
        return {
            totalAccounts: 12,
            activeAccounts: 11,
            inactiveAccounts: 1,
            totalBalanceTHB: '฿78,600,000.00',
            totalBalanceUSD: '$125,000.00',
            accountsByBank: {
                'BDO': 2,
                'BPI': 1,
                'Metrobank': 1,
                'UnionBank': 1,
                'Security Bank': 1,
                'Landbank': 1,
                'PNB': 1,
                'ChinaBank': 1,
                'RCBC': 1,
                'EastWest': 1,
                'DBP': 1
            },
            accountsByType: {
                'Current Account': 4,
                'Savings Account': 1,
                'Foreign Currency': 1,
                'Payroll Account': 1,
                'Trust Account': 1,
                'Time Deposit': 1,
                'Investment Account': 1,
                'Escrow Account': 1,
                'Digital Account': 1,
                'Government Account': 1
            }
        };
    },

    getBankAccountsMini() {
        return Promise.resolve(this.getBankAccountsData().slice(0, 5));
    },

    getBankAccountsSmall() {
        return Promise.resolve(this.getBankAccountsData().slice(0, 10));
    },

    getBankAccounts() {
        return Promise.resolve(this.getBankAccountsData());
    }
};

// Keep the old export for backward compatibility if needed
export const ProductService = BankAccountService;