const Productdata = [
  {
    id: 1,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 2,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 1,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 3,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Debit",
    action: "",
  },
  {
    id: 4,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 1,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 5,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Debit",
    action: "",
  },
  {
    id: 6,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 1,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 7,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 8,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 1,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Debit",
    action: "",
  },
  {
    id: 9,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Credit",
    action: "",
  },
  {
    id: 10,
    accountCategoryCode: "AC00123",
    accountCategoryName: "Debtor",
    status: 0,
    mainAccountCode: "Main00123",
    description: "Informative explanation",
    openEntry: "NO",
    openEntryType: "Debit",
    action: "",
  },
];
export default Productdata;
