"""Steps of the swimlane diagrams of the Process Flow Document (source/process-flows.md).

Each flow: id (file name of the picture), lanes (codes of LANES, left to right) and steps in order. A step:
  n      the number of the step in the document (printed on the box)
  lane   the lane code
  text   the short text in the box (at most three lines)
  kind   task (default), system, decision, start, end, external
  to     the steps it leads to: [n] or [(n, 'label')]; without it, the next step of the list
  same   True: drawn on the same row as the step before (parallel work in another lane)
Keep the numbers equal to the numbered steps of the document.
"""

LANES = {
    'CL': 'Client', 'AE': 'Sales & Marketing', 'PT': 'Processing Team', 'OP': 'Operations',
    'CM': 'Claims', 'CM2': 'Claims (second user)', 'AC': 'Accounting', 'AC2': 'Accounting (second user)',
    'AM': 'Accounting Manager', 'SA': 'System Administrator', 'CO': 'Compliance Officer', 'SY': 'BrokerVerse',
    'IN': 'Insurer', 'RF': 'Agent or referrer', 'AMLC': 'AMLC portal', 'BIR': 'BIR eFPS / eBIRForms',
    'CP': 'Complainant', 'CXO': 'Complaints officer', 'IC': 'Insurance Commission', 'DPO': 'DPO and privacy team',
    'IT': 'IT and iorta TechNXT support', 'NPC': 'National Privacy Commission', 'DS': 'Data subjects',
    'DO': 'Broker data owners', 'ML': 'Migration lead', 'SC': 'Steering committee', 'DEV': 'Developer and CI',
    'RM': 'Release manager and CAB', 'DV': 'DevOps', 'DL': 'Dealer', 'BK': 'Financing bank', 'CD': 'Cedant (insurer)',
    'RE': 'Reinsurers', 'TX': 'Accounting Manager or tax adviser', 'HD': 'Handler (Operations or Claims)',
}

FLOWS = [
    # ------------------------------------------------------------------------------------------------ F01
    {'id': 'f01_lead_to_policy', 'lanes': ['CL', 'AE', 'PT', 'SY'], 'steps': [
        {'n': 1, 'lane': 'AE', 'kind': 'start', 'text': 'Create prospect (LD-)'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Assignment rule gives the prospect an account executive'},
        {'n': 3, 'lane': 'AE', 'text': 'Create quote: Quick Quote or the motor quote wizard'},
        {'n': 4, 'lane': 'SY', 'kind': 'system', 'text': 'Price on the server, apply product rules, save Draft (QT-)'},
        {'n': 5, 'lane': 'SY', 'kind': 'decision', 'text': 'Referred by a rule?', 'to': [(6, 'Yes'), (7, 'No')]},
        {'n': 6, 'lane': 'PT', 'text': 'Approve the referral within the authority limit', 'to': [7]},
        {'n': 7, 'lane': 'AE', 'text': 'Send for Customer Approval (link)'},
        {'n': 8, 'lane': 'CL', 'kind': 'decision', 'text': 'Client answer', 'to': [(9, 'Accepted'), (3, 'Revise'), (14, 'Declined')]},
        {'n': 9, 'lane': 'AE', 'text': 'Proceed to Policy: ID, vehicle, photos, billing mode'},
        {'n': 10, 'lane': 'SY', 'kind': 'system', 'text': 'Checks: KYC, AML, insurer authority, credit limit'},
        {'n': 11, 'lane': 'SY', 'kind': 'system', 'text': 'Issue policy, client, bill, journal, commission, COC'},
        {'n': 12, 'lane': 'AE', 'text': 'Upload insurer policy; Pay Later or Proceed to Payment'},
        {'n': 13, 'lane': 'AE', 'kind': 'end', 'text': 'Policy Active'},
        {'n': 14, 'lane': 'CL', 'kind': 'end', 'text': 'Quotation Rejected'},
    ]},
    # ------------------------------------------------------------------------------------------------ F02
    {'id': 'f02_rfq_coinsurance', 'lanes': ['CL', 'AE', 'PT', 'SY', 'IN'], 'steps': [
        {'n': 1, 'lane': 'PT', 'kind': 'start', 'text': 'New Request for Quotation: risk, covers, insurers'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Checks, BS- number, offer per insurer, e-mails'},
        {'n': 3, 'lane': 'IN', 'kind': 'external', 'text': 'Insurer offers terms or declines'},
        {'n': 4, 'lane': 'PT', 'text': 'Record response: offer or decline'},
        {'n': 5, 'lane': 'PT', 'text': 'Compare offers: select, lead, shares total 100%'},
        {'n': 6, 'lane': 'PT', 'kind': 'decision', 'text': 'Client to accept terms first?', 'to': [(7, 'Yes'), (9, 'No')]},
        {'n': 7, 'lane': 'AE', 'text': 'Send the Quotation Slip (and comparison report)'},
        {'n': 8, 'lane': 'CL', 'text': 'Client accepts the quotation'},
        {'n': 9, 'lane': 'PT', 'text': 'Placement Slip (PS-): Send to insurer(s)'},
        {'n': 10, 'lane': 'IN', 'kind': 'external', 'text': 'Each participant confirms its share or declines'},
        {'n': 11, 'lane': 'PT', 'kind': 'decision', 'text': 'All confirmed?', 'to': [(12, 'Yes'), (9, 'No: edit participants')]},
        {'n': 12, 'lane': 'SY', 'kind': 'system', 'text': 'Slip Bound'},
        {'n': 13, 'lane': 'PT', 'text': 'Issue Policy: shares, bill and journal per insurer'},
        {'n': 14, 'lane': 'PT', 'kind': 'end', 'text': 'Policy issued'},
    ]},
    # ------------------------------------------------------------------------------------------------ F03
    {'id': 'f03_endorsement_cancellation', 'lanes': ['CL', 'OP', 'PT', 'SY', 'IN'], 'steps': [
        {'n': 1, 'lane': 'OP', 'kind': 'decision', 'text': 'Change or cancellation?', 'to': [(2, 'Change'), (3, 'Cancel')]},
        {'n': 2, 'lane': 'OP', 'text': 'Endorsement Request: changes; premium re-priced', 'to': [5]},
        {'n': 3, 'lane': 'OP', 'text': 'Policy Cancellation: date, reason, method'},
        {'n': 4, 'lane': 'SY', 'kind': 'system', 'text': 'Compute return premium, taxes and commission'},
        {'n': 5, 'lane': 'OP', 'text': 'Send to the insurer: Waiting for Update'},
        {'n': 6, 'lane': 'IN', 'kind': 'external', 'text': 'Insurer issues its endorsement'},
        {'n': 7, 'lane': 'PT', 'text': 'Proceed: upload the endorsement and complete'},
        {'n': 8, 'lane': 'SY', 'kind': 'system', 'text': 'Apply to policy and client; compute again'},
        {'n': 9, 'lane': 'SY', 'kind': 'decision', 'text': 'Premium change', 'to': [(10, 'Additional'), (11, 'Return')]},
        {'n': 10, 'lane': 'SY', 'kind': 'system', 'text': 'Bill additional premium; accrue commission', 'to': [12]},
        {'n': 11, 'lane': 'SY', 'kind': 'system', 'text': 'Credit bill, refund payable, insurer refund, clawback', 'same': False},
        {'n': 12, 'lane': 'CL', 'text': 'Client notified; pays or is refunded'},
        {'n': 13, 'lane': 'CL', 'kind': 'end', 'text': 'Endorsement Completed'},
    ]},
    # ------------------------------------------------------------------------------------------------ F04
    {'id': 'f04_renewal', 'lanes': ['CL', 'OP', 'PT', 'SY'], 'steps': [
        {'n': 1, 'lane': 'SY', 'kind': 'start', 'text': 'Renewal pipeline: 90 days before expiry'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Renewal notices at 60, 30 and 15 days'},
        {'n': 3, 'lane': 'OP', 'text': 'Work Renewal Queue, At-Risk, Negotiations'},
        {'n': 4, 'lane': 'OP', 'text': 'Renew: renewal quotation re-rated'},
        {'n': 5, 'lane': 'OP', 'text': 'Request approval of the renewal terms'},
        {'n': 6, 'lane': 'PT', 'kind': 'decision', 'text': 'Terms approved?', 'to': [(7, 'Yes'), (4, 'Return')]},
        {'n': 7, 'lane': 'OP', 'text': 'Send for customer approval'},
        {'n': 8, 'lane': 'CL', 'kind': 'decision', 'text': 'Client renews?', 'to': [(9, 'Yes'), (12, 'No')]},
        {'n': 9, 'lane': 'OP', 'text': 'Issue the renewal (placement journey if set)'},
        {'n': 10, 'lane': 'SY', 'kind': 'system', 'text': 'New term, old Renewed, bill and commission'},
        {'n': 11, 'lane': 'SY', 'kind': 'end', 'text': 'Renewed'},
        {'n': 12, 'lane': 'SY', 'kind': 'system', 'text': 'Expired, then Lapsed after the grace period'},
        {'n': 13, 'lane': 'OP', 'text': 'Lapse Management: win-back campaign'},
        {'n': 14, 'lane': 'OP', 'kind': 'end', 'text': 'Won back or lost'},
    ]},
    # ------------------------------------------------------------------------------------------------ F05
    {'id': 'f05_billing_collection', 'lanes': ['CL', 'OP', 'AC', 'AM', 'SY'], 'steps': [
        {'n': 1, 'lane': 'SY', 'kind': 'start', 'text': 'Bill raised at issue, endorsement or renewal (INV-)'},
        {'n': 2, 'lane': 'AC', 'kind': 'decision', 'text': 'Instalments?', 'to': [(3, 'Yes'), (4, 'No')]},
        {'n': 3, 'lane': 'AC', 'text': 'Instalment plan; optional instalment invoices'},
        {'n': 4, 'lane': 'SY', 'kind': 'system', 'text': 'Reminders before and after due date; warranty monitor'},
        {'n': 5, 'lane': 'CL', 'text': 'Client pays: cash, cheque, transfer, online or PDC'},
        {'n': 6, 'lane': 'AC', 'kind': 'decision', 'text': 'Post-dated cheque?', 'to': [(7, 'Yes'), (8, 'No')]},
        {'n': 7, 'lane': 'AC', 'text': 'Register PDC; deposit on its date', 'to': [10]},
        {'n': 8, 'lane': 'OP', 'text': 'Record payment: Proceed to Payment (Reviewing)'},
        {'n': 9, 'lane': 'AC', 'kind': 'decision', 'text': 'Payment verified?', 'to': [(10, 'Confirm'), (8, 'Reject')]},
        {'n': 10, 'lane': 'SY', 'kind': 'system', 'text': 'Official receipt posted; bill Partial or Paid'},
        {'n': 11, 'lane': 'AM', 'text': 'Exceptions: warranty extension, credit limit'},
        {'n': 12, 'lane': 'SY', 'kind': 'end', 'text': 'Premium collected'},
    ]},
    # ------------------------------------------------------------------------------------------------ F06
    {'id': 'f06_remittance_direct_bill', 'lanes': ['AC', 'AC2', 'SY', 'IN'], 'steps': [
        {'n': 1, 'lane': 'AC', 'kind': 'start', 'text': 'Automated Processing: draft remittances (REM-)'},
        {'n': 2, 'lane': 'AC', 'text': 'Tracking: process the remittance for approval'},
        {'n': 3, 'lane': 'AC2', 'text': 'Approve within the Authority Matrix limit'},
        {'n': 4, 'lane': 'AC', 'text': 'Settlement: premium less commission and tax'},
        {'n': 5, 'lane': 'AC2', 'text': 'Approve settlement (SET-): insurer voucher raised'},
        {'n': 6, 'lane': 'AC2', 'text': 'Approve the voucher: cheque or bank file'},
        {'n': 7, 'lane': 'SY', 'kind': 'system', 'text': 'Payment journal; remittance Completed'},
        {'n': 8, 'lane': 'IN', 'kind': 'external', 'text': 'Statement of account; reconciled (ISR-)'},
        {'n': 9, 'lane': 'AC', 'text': 'Direct bill: raise commission debit note'},
        {'n': 10, 'lane': 'AC2', 'text': 'Approve debit note (DN-): printed, e-mailed'},
        {'n': 11, 'lane': 'IN', 'kind': 'external', 'text': 'Insurer pays net of EWT; issues 2307'},
        {'n': 12, 'lane': 'AC', 'text': 'Record the collection: cash and EWT'},
        {'n': 13, 'lane': 'SY', 'kind': 'end', 'text': 'Commission receivable cleared'},
    ]},
    # ------------------------------------------------------------------------------------------------ F07
    {'id': 'f07_commission_payout', 'lanes': ['CO', 'SY', 'AC', 'AC2', 'RF'], 'steps': [
        {'n': 1, 'lane': 'CO', 'kind': 'start', 'text': 'Licence Register: agent licences in force'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Policy issued: comsub line Accrued'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Premium fully collected: Eligible'},
        {'n': 4, 'lane': 'AC', 'text': 'Referrer account: WHT, bank account, lines'},
        {'n': 5, 'lane': 'SY', 'kind': 'decision', 'text': 'Licence in force?', 'to': [(6, 'Yes'), (11, 'No (block)')]},
        {'n': 6, 'lane': 'AC2', 'text': 'Approve the lines (not the maker)'},
        {'n': 7, 'lane': 'AC', 'text': 'Generate payout: draft payout voucher'},
        {'n': 8, 'lane': 'AC2', 'text': 'Approve the voucher or the bank file batch'},
        {'n': 9, 'lane': 'SY', 'kind': 'system', 'text': 'Payable, cash and WHT posted; lines Paid'},
        {'n': 10, 'lane': 'RF', 'kind': 'end', 'text': 'Paid; BIR Form 2307 each quarter'},
        {'n': 11, 'lane': 'CO', 'text': 'Held: licence renewed and recorded', 'to': [5]},
    ]},
    # ------------------------------------------------------------------------------------------------ F08
    {'id': 'f08_claims', 'lanes': ['CL', 'CM', 'CM2', 'AC', 'SY', 'IN'], 'steps': [
        {'n': 1, 'lane': 'CL', 'kind': 'start', 'text': 'Client reports a loss'},
        {'n': 2, 'lane': 'CM', 'text': 'Register claim from the policy (CLM-)'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Loss advice to insurer; checklist; due date'},
        {'n': 4, 'lane': 'CM', 'text': 'Claim Documents: receive, waive, remind; submit'},
        {'n': 5, 'lane': 'IN', 'kind': 'external', 'text': 'Insurer assigns adjuster and claim number'},
        {'n': 6, 'lane': 'CM', 'text': 'Adjuster report: claim Processing'},
        {'n': 7, 'lane': 'CM', 'kind': 'decision', 'text': 'Motor repair?', 'to': [(8, 'Yes'), (9, 'No')]},
        {'n': 8, 'lane': 'CM', 'text': 'Estimate, adjuster decision, LOA, release', 'to': [9]},
        {'n': 9, 'lane': 'CM', 'text': 'Assessment; submit settlement'},
        {'n': 10, 'lane': 'CM2', 'kind': 'decision', 'text': 'Approve settlement?', 'to': [(11, 'Approve'), (9, 'Return')]},
        {'n': 11, 'lane': 'SY', 'kind': 'system', 'text': 'Claim Settled; claimant informed'},
        {'n': 12, 'lane': 'SY', 'kind': 'decision', 'text': 'Paid through the broker?', 'to': [(13, 'Yes'), (17, 'No')]},
        {'n': 13, 'lane': 'SY', 'kind': 'system', 'text': 'Recoverable per insurer; payable to claimant'},
        {'n': 14, 'lane': 'IN', 'kind': 'external', 'text': 'Insurer remits the claim funds'},
        {'n': 15, 'lane': 'AC', 'text': 'Record funds received'},
        {'n': 16, 'lane': 'AC', 'text': 'Pay claimant (CPV-); release and quitclaim', 'to': [17]},
        {'n': 17, 'lane': 'CL', 'kind': 'end', 'text': 'Claimant paid'},
    ]},
    # ------------------------------------------------------------------------------------------------ F09
    {'id': 'f09_period_close', 'lanes': ['AC', 'AM', 'SY'], 'steps': [
        {'n': 1, 'lane': 'AC', 'kind': 'start', 'text': 'Bank statements: import, match, prepare (BRC-)'},
        {'n': 2, 'lane': 'AM', 'text': 'Approve the bank reconciliations'},
        {'n': 3, 'lane': 'AC', 'text': 'Insurer statements: import, resolve, submit (ISR-)'},
        {'n': 4, 'lane': 'AM', 'text': 'Approve insurer reconciliations'},
        {'n': 5, 'lane': 'AC', 'text': 'New close run for the period (MEC-)'},
        {'n': 6, 'lane': 'SY', 'kind': 'system', 'text': 'Accruals, recurring, deferral, FX, depreciation, checklist'},
        {'n': 7, 'lane': 'AC', 'text': 'Fix failures; sign off manual items; submit'},
        {'n': 8, 'lane': 'AM', 'kind': 'decision', 'text': 'Approve close?', 'to': [(9, 'Approve'), (7, 'Reject')]},
        {'n': 9, 'lane': 'SY', 'kind': 'system', 'text': 'Period closed'},
        {'n': 10, 'lane': 'AC', 'text': 'Year end: pre-checks; adjustments in period 13'},
        {'n': 11, 'lane': 'AM', 'text': 'Close the year'},
        {'n': 12, 'lane': 'SY', 'kind': 'system', 'text': 'Closing entries, opening balances, periods locked'},
        {'n': 13, 'lane': 'SY', 'kind': 'end', 'text': 'Next fiscal year open'},
    ]},
    # ------------------------------------------------------------------------------------------------ F10
    {'id': 'f10_bir_filing', 'lanes': ['SY', 'AC', 'TX', 'BIR'], 'steps': [
        {'n': 1, 'lane': 'SY', 'kind': 'start', 'text': 'Taxes posted by vouchers, receipts, invoices'},
        {'n': 2, 'lane': 'AC', 'text': 'Open the return: 0619-E, 1601-EQ, 2551Q or 1604-E'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Return built from the ledger; reconciliation shown'},
        {'n': 4, 'lane': 'TX', 'kind': 'decision', 'text': 'Differences explained?', 'to': [(5, 'Yes'), (2, 'No: correct')]},
        {'n': 5, 'lane': 'AC', 'text': 'Print or Excel; DAT files where needed'},
        {'n': 6, 'lane': 'BIR', 'kind': 'external', 'text': 'File and pay; confirmation received'},
        {'n': 7, 'lane': 'AC', 'text': 'Record filing: date, reference, amount'},
        {'n': 8, 'lane': 'AC', 'text': 'Quarter: 2307 certificates, SAWT, QAP, SLSP, VAT'},
        {'n': 9, 'lane': 'AC', 'text': 'Month: print the CAS loose-leaf books'},
        {'n': 10, 'lane': 'AC', 'kind': 'end', 'text': 'Period filed and documented'},
    ]},
    # ------------------------------------------------------------------------------------------------ F11
    {'id': 'f11_aml', 'lanes': ['OP', 'SY', 'CO', 'AMLC'], 'steps': [
        {'n': 1, 'lane': 'OP', 'kind': 'start', 'text': 'Onboard client: identity, owners, signatories, PEP'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Rate risk; screen client, owners, signatories'},
        {'n': 3, 'lane': 'SY', 'kind': 'decision', 'text': 'Possible match?', 'to': [(4, 'Yes'), (5, 'No')]},
        {'n': 4, 'lane': 'CO', 'text': 'Decide hit: clear, escalate or confirm'},
        {'n': 5, 'lane': 'SY', 'kind': 'decision', 'text': 'Rated High?', 'to': [(6, 'Yes'), (8, 'No')]},
        {'n': 6, 'lane': 'OP', 'text': 'Prepare and submit the EDD review'},
        {'n': 7, 'lane': 'CO', 'text': 'Approve or reject the EDD review'},
        {'n': 8, 'lane': 'SY', 'kind': 'system', 'text': 'Policy issue allowed; checks repeated at issue'},
        {'n': 9, 'lane': 'SY', 'kind': 'system', 'text': 'Daily monitoring raises alerts (AMA-)'},
        {'n': 10, 'lane': 'CO', 'text': 'Review alerts: close or open a case (AMC-)'},
        {'n': 11, 'lane': 'CO', 'text': 'STR narrative or CTR period; approve for filing'},
        {'n': 12, 'lane': 'CO', 'text': 'Generate report file (AMR-) and download'},
        {'n': 13, 'lane': 'AMLC', 'kind': 'external', 'text': 'File in the AMLC portal; acknowledgement'},
        {'n': 14, 'lane': 'CO', 'text': 'Record filing: alerts Reported, case Filed'},
        {'n': 15, 'lane': 'SY', 'kind': 'end', 'text': 'KYC refresh when due'},
    ]},
    # ------------------------------------------------------------------------------------------------ F12
    {'id': 'f12_complaints', 'lanes': ['CP', 'HD', 'CXO', 'SY', 'IC'], 'steps': [
        {'n': 1, 'lane': 'CP', 'kind': 'start', 'text': 'Complaint received'},
        {'n': 2, 'lane': 'HD', 'text': 'Log complaint (CMP-); assign'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Deadlines set; assignee notified'},
        {'n': 4, 'lane': 'HD', 'text': 'Acknowledge; acknowledgement letter'},
        {'n': 5, 'lane': 'HD', 'text': 'Investigate with insurer, claims, accounts'},
        {'n': 6, 'lane': 'SY', 'kind': 'system', 'text': 'Daily reminders; overdue escalated'},
        {'n': 7, 'lane': 'CXO', 'text': 'Review the escalation; direct the handler'},
        {'n': 8, 'lane': 'HD', 'text': 'Resolve: outcome, redress; resolution letter'},
        {'n': 9, 'lane': 'CP', 'kind': 'decision', 'text': 'Complainant satisfied?', 'to': [(11, 'Yes'), (10, 'No')]},
        {'n': 10, 'lane': 'IC', 'kind': 'external', 'text': 'Elevated to the IC: Refer to the IC; or Reopen', 'to': [11]},
        {'n': 11, 'lane': 'HD', 'text': 'Close the complaint'},
        {'n': 12, 'lane': 'CXO', 'kind': 'end', 'text': 'Regulator report for the period'},
    ]},
    # ------------------------------------------------------------------------------------------------ F13
    {'id': 'f13_data_breach', 'lanes': ['IT', 'DPO', 'SY', 'NPC', 'DS'], 'steps': [
        {'n': 1, 'lane': 'IT', 'kind': 'start', 'text': 'Incident detected and reported to the DPO'},
        {'n': 2, 'lane': 'DPO', 'text': 'Log incident (PDB-): time discovered'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': '72-hour clock; reminders at 48, 24, 6 hours'},
        {'n': 4, 'lane': 'DPO', 'kind': 'decision', 'text': 'Notifiable breach?', 'to': [(5, 'Yes'), (9, 'No')]},
        {'n': 5, 'lane': 'DPO', 'text': 'Notify the NPC; record Notify NPC'},
        {'n': 6, 'lane': 'NPC', 'kind': 'external', 'text': 'Notification received; reference'},
        {'n': 7, 'lane': 'DPO', 'text': 'Notify the data subjects, or record why not'},
        {'n': 8, 'lane': 'DS', 'kind': 'external', 'text': 'Data subjects informed'},
        {'n': 9, 'lane': 'IT', 'text': 'Contain and remediate; cause recorded'},
        {'n': 10, 'lane': 'DPO', 'text': 'Close with outcome and measures'},
        {'n': 11, 'lane': 'DPO', 'kind': 'end', 'text': 'Annual security incident report'},
    ]},
    # ------------------------------------------------------------------------------------------------ F14
    {'id': 'f14_golive_cutover', 'lanes': ['DO', 'ML', 'SA', 'AM', 'SY', 'SC'], 'steps': [
        {'n': 1, 'lane': 'SA', 'kind': 'start', 'text': 'Configuration workbook: template or current data'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Upload and validate: trial run, errors workbook'},
        {'n': 3, 'lane': 'SA', 'text': 'Fix, load; approve authority limits'},
        {'n': 4, 'lane': 'SA', 'text': 'Set golive.cutover_date'},
        {'n': 5, 'lane': 'DO', 'text': 'Extract the old system; control figures'},
        {'n': 6, 'lane': 'ML', 'text': 'Migration workbook: validate, fix, validate again'},
        {'n': 7, 'lane': 'ML', 'text': 'Load the migration workbook'},
        {'n': 8, 'lane': 'SY', 'kind': 'system', 'text': 'Reconciliation: rows, totals, TB, receivables'},
        {'n': 9, 'lane': 'AM', 'text': 'Sample checks; sign the reconciliation'},
        {'n': 10, 'lane': 'SC', 'kind': 'decision', 'text': 'Go?', 'to': [(11, 'Go'), (6, 'No go: fix and reload')]},
        {'n': 11, 'lane': 'SA', 'text': 'Switch on golive.locked; snapshot'},
        {'n': 12, 'lane': 'SA', 'text': 'Switch on schedules and e-mail'},
        {'n': 13, 'lane': 'SY', 'kind': 'end', 'text': 'Live; hypercare starts'},
    ]},
    # ------------------------------------------------------------------------------------------------ F15a
    {'id': 'f15a_promotion', 'lanes': ['DEV', 'RM', 'DV', 'SA', 'SY'], 'steps': [
        {'n': 1, 'lane': 'DEV', 'kind': 'start', 'text': 'Pull request: lint, tests, audit, build'},
        {'n': 2, 'lane': 'SY', 'kind': 'system', 'text': 'Merged: artefacts kept; deployed to Dev'},
        {'n': 3, 'lane': 'RM', 'text': 'Release candidate tag; approval for SIT or UAT'},
        {'n': 4, 'lane': 'DV', 'text': 'Deploy: backup, migrate, switch, smoke test'},
        {'n': 5, 'lane': 'DV', 'kind': 'decision', 'text': 'Smoke test passed?', 'to': [(6, 'Yes'), (14, 'No')]},
        {'n': 14, 'lane': 'SY', 'kind': 'end', 'text': 'Automatic rollback; fix and deploy again'},
        {'n': 6, 'lane': 'SA', 'text': 'Export Current data from the source environment'},
        {'n': 7, 'lane': 'SA', 'text': 'Review users and numbering; load in the target'},
        {'n': 8, 'lane': 'SA', 'text': 'On-screen items; second admin approves limits'},
        {'n': 9, 'lane': 'SA', 'text': 'Compare environments'},
        {'n': 10, 'lane': 'SY', 'kind': 'decision', 'text': 'Mirrored?', 'to': [(11, 'Yes'), (7, 'No: correct')]},
        {'n': 11, 'lane': 'RM', 'text': 'CAB approves the release tag'},
        {'n': 12, 'lane': 'DV', 'text': 'Deploy to Production after approval'},
        {'n': 13, 'lane': 'DV', 'kind': 'end', 'text': 'Release live'},
    ]},
    # ------------------------------------------------------------------------------------------------ F15b
    {'id': 'f15b_masking_refresh', 'lanes': ['RM', 'DPO', 'DV', 'SY'], 'steps': [
        {'n': 1, 'lane': 'RM', 'kind': 'start', 'text': 'Refresh request: target, reason'},
        {'n': 2, 'lane': 'DPO', 'text': 'Approve the refresh'},
        {'n': 3, 'lane': 'DV', 'text': 'Production backup; restore into the copy'},
        {'n': 4, 'lane': 'DV', 'text': 'Dry run with --remark-copy'},
        {'n': 5, 'lane': 'SY', 'kind': 'decision', 'text': 'Copy safe to mask?', 'to': [(6, 'Yes'), (13, 'No: refused')]},
        {'n': 13, 'lane': 'DV', 'kind': 'end', 'text': 'Investigate the marker; nothing changed'},
        {'n': 6, 'lane': 'DV', 'text': 'Mask: one transaction; users reset'},
        {'n': 7, 'lane': 'SY', 'kind': 'system', 'text': 'Verification: nothing left unmasked'},
        {'n': 8, 'lane': 'DV', 'text': 'Spot checks; start the API; hand over'},
        {'n': 9, 'lane': 'DV', 'text': 'Delete the restored dump; unset the salt'},
        {'n': 10, 'lane': 'DV', 'text': 'Evidence to the change record'},
        {'n': 11, 'lane': 'DPO', 'text': 'Sign off the evidence'},
        {'n': 12, 'lane': 'DPO', 'kind': 'end', 'text': 'Masked copy in use'},
    ]},
    # ------------------------------------------------------------------------------------------------ F16
    {'id': 'f16_dealer_programme', 'lanes': ['DL', 'AE', 'SY', 'AC', 'BK'], 'steps': [
        {'n': 1, 'lane': 'AE', 'kind': 'start', 'text': 'Set up the dealer programme; premium preview'},
        {'n': 2, 'lane': 'DL', 'kind': 'external', 'text': 'Dealer sends the vehicles sold'},
        {'n': 3, 'lane': 'AE', 'text': 'Upload sales on the programme'},
        {'n': 4, 'lane': 'SY', 'kind': 'system', 'text': 'Check rows; prospect and quotation per vehicle'},
        {'n': 5, 'lane': 'SY', 'kind': 'decision', 'text': 'Upload creates?', 'to': [(6, 'Policy issued'), (8, 'Quotation')]},
        {'n': 6, 'lane': 'SY', 'kind': 'system', 'text': 'Client and policy; bank mortgagee; bill per payer'},
        {'n': 7, 'lane': 'BK', 'kind': 'external', 'text': 'Bank endorsement letter received', 'to': [9]},
        {'n': 8, 'lane': 'AE', 'text': 'Complete the quotation with the buyer', 'same': True, 'to': [9]},
        {'n': 9, 'lane': 'AE', 'text': 'Correct failed rows; upload again'},
        {'n': 10, 'lane': 'AC', 'text': 'Collect from dealer, bank and buyer'},
        {'n': 11, 'lane': 'AC', 'kind': 'end', 'text': 'Dealer Production report'},
    ]},
    # ------------------------------------------------------------------------------------------------ F17
    {'id': 'f17_fleet', 'lanes': ['CL', 'OP', 'PT', 'SY'], 'steps': [
        {'n': 1, 'lane': 'OP', 'kind': 'start', 'text': 'New fleet schedule: client, insurer, rates'},
        {'n': 2, 'lane': 'OP', 'text': 'Add vehicles or upload the template'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Price each vehicle: OD, AoN, liability, CTPL, taxes'},
        {'n': 4, 'lane': 'OP', 'text': 'Issue policy (minimum vehicles)'},
        {'n': 5, 'lane': 'SY', 'kind': 'system', 'text': 'Policy, bill, journal and commission'},
        {'n': 6, 'lane': 'CL', 'text': 'Adds or removes a vehicle mid-term'},
        {'n': 7, 'lane': 'OP', 'text': 'Add vehicle by endorsement, or Delete'},
        {'n': 8, 'lane': 'SY', 'kind': 'system', 'text': 'Pro-rata premium on an endorsement'},
        {'n': 9, 'lane': 'PT', 'text': 'Complete with the insurer: bill or credit'},
        {'n': 10, 'lane': 'OP', 'kind': 'end', 'text': 'Schedule PDF and Excel'},
    ]},
    # ------------------------------------------------------------------------------------------------ F18
    {'id': 'f18_marine_open_cover', 'lanes': ['CL', 'OP', 'SY', 'AC'], 'steps': [
        {'n': 1, 'lane': 'OP', 'kind': 'start', 'text': 'New open cover: goods, voyages, rates, limits'},
        {'n': 2, 'lane': 'OP', 'text': 'Save and Activate'},
        {'n': 3, 'lane': 'SY', 'kind': 'system', 'text': 'Open policy issued without a bill'},
        {'n': 4, 'lane': 'CL', 'text': 'Ships goods; asks for a certificate or declares'},
        {'n': 5, 'lane': 'OP', 'text': 'Issue certificate, or shipment without certificate'},
        {'n': 6, 'lane': 'SY', 'kind': 'system', 'text': 'Insured value, premium, limit and period checks'},
        {'n': 7, 'lane': 'OP', 'text': 'New declaration for the period; submit'},
        {'n': 8, 'lane': 'OP', 'text': 'Bill the declaration'},
        {'n': 9, 'lane': 'SY', 'kind': 'system', 'text': 'Bill, journal, collection item, commission'},
        {'n': 10, 'lane': 'AC', 'kind': 'end', 'text': 'Collected and remitted as any bill'},
    ]},
    # ------------------------------------------------------------------------------------------------ F19
    {'id': 'f19_facultative', 'lanes': ['CD', 'PT', 'RE', 'SY', 'AC'], 'steps': [
        {'n': 1, 'lane': 'CD', 'kind': 'start', 'text': 'Cedant offers part of a risk'},
        {'n': 2, 'lane': 'PT', 'text': 'New slip: risk, 100% terms, share, commissions'},
        {'n': 3, 'lane': 'PT', 'text': 'Add reinsurers (security rating checked)'},
        {'n': 4, 'lane': 'PT', 'text': 'Send to market: slip PDF'},
        {'n': 5, 'lane': 'RE', 'kind': 'external', 'text': 'Accept a line or decline'},
        {'n': 6, 'lane': 'PT', 'kind': 'decision', 'text': 'Lines reach 100%?', 'to': [(7, 'Yes: Placed'), (3, 'No')]},
        {'n': 7, 'lane': 'PT', 'text': 'Bind the slip'},
        {'n': 8, 'lane': 'SY', 'kind': 'system', 'text': 'Due from cedant, due to reinsurers, brokerage'},
        {'n': 9, 'lane': 'PT', 'text': 'Cover note, debit note, credit notes'},
        {'n': 10, 'lane': 'CD', 'kind': 'external', 'text': 'Cedant pays the premium'},
        {'n': 11, 'lane': 'AC', 'text': 'Record premium received'},
        {'n': 12, 'lane': 'AC', 'text': 'Record payment to each reinsurer'},
        {'n': 13, 'lane': 'SY', 'kind': 'end', 'text': 'Slip settled; bordereau'},
    ]},
]
