// Audit Trail Action Types
export const GET_AUDIT_TRAIL_REQUEST = "GET_AUDIT_TRAIL_REQUEST";
export const GET_AUDIT_TRAIL_SUCCESS = "GET_AUDIT_TRAIL_SUCCESS";
export const GET_AUDIT_TRAIL_FAILURE = "GET_AUDIT_TRAIL_FAILURE";

// Claim Details Action Types
export const GET_CLAIM_DETAILS_REQUEST = "GET_CLAIM_DETAILS_REQUEST";
export const GET_CLAIM_DETAILS_SUCCESS = "GET_CLAIM_DETAILS_SUCCESS";
export const GET_CLAIM_DETAILS_FAILURE = "GET_CLAIM_DETAILS_FAILURE";
